### ISSUE TITLE
Access to repository for Jenkins

### ISSUE THREAD

**Issue by mmc46** [geneontology/go-site#100]
In our Jenkins jobs that update GO in our ontologies, we use

svn://ext.geneontology.org/trunk/ontology

as the repository URL in the job settings. 

ftp://ftp.geneontology.org/pub/go/www/GO.svn.help.shtml

This has been failing since the end of July.  Could you tell me what I should be using now please?

Thanks.

**Comment by stuartmiyasato** [comment]
Hi Marta,

Has anything changed on the machine running the Jenkins jobs that you know of?  Anything like firewall rules?  (Specifically, outbound TCP connections to port 3690.)  We haven't changed anything on the server end, and a svn checkout on my personal machine at home seems to work fine.

miyasato% svn co svn://ext.geneontology.org/trunk/ontology
A    ontology/go.obo
A    ontology/gene_ontology.obo
A    ontology/obo_format_1_0
[...]

Does your Jenkins job report any specific errors?  If so, can you forward those along?  It may help with debugging this problem.

Thanks,
-- Stuart

**Comment by mmc46** [comment]
Thanks Stuart.

Nothing changed as fas as I know. But it might be something here, as the console shows

Stopped Release process. Reason: Could not lock staging directory via lock file: /var/lib/jenkins/workspace/FBbt_SF_trunk_weekly_GO_update/oort/staging/.lock

Failures with this error happen once in a while, but are usually solved by deleting the workspace, thought this hasn’t worked so far.

**Comment by cmungall** [comment]
Not related, but I just noticed you have bookmarked HTML documentation 
that appears on our FTP site

The original location was here:
http://www.geneontology.org/GO.svn.help.shtml

Which correctly redirects to:
http://geneontology.org/page/svn-help

I don't think we can redirect ftp? But perhaps we can put something in 
the headers in svn (which will percolate to ftp)

**Comment by cmungall** [comment]
Also, maybe there is something we could do that doesn't require an svn 
checkout? Which files are you consuming aqnd on what cycle?

**Comment by mmc46** [comment]
For the GO update for FBbt, I’ve cleared the workspace again, and it is now working (it showed the lock error). That uses go-simple.obo. 

For the FBcv update I get another error. That uses go-simple.owl on

--add-imports-from-supports --extract-module -c -s $OBO/go/go-simple.owl --set-ontology-id $OBO/fbcv_go_import.owl -o fbcv_go_import.owl

with 

export OBO=http://purl.obolibrary.org/obo

ERROR (CommandRunner:3229) Could not find specified ontology http://purl.obolibrary.org/obo/go/go-simple.owl <http://purl.obolibrary.org/obo/go/go-simple.owl> for --source

First fail was on the 27th June, last success on the 20th. It’s a weekly job.

**Comment by cmungall** [comment]
I recommend only purls from here:

http://geneontology.org/page/download-ontology

Try changing go-simple for http://purl.obolibrary.org/obo/go/go-basic.obo (obo is fine here)

I'll be out the rest of this week @dosumis and @hdietze should be able to fix between them

**Comment by mmc46** [comment]
There is also an earlier reference to go-simple.obo that I’d missed

ontology-release-runner --reasoner elk $FBCV_WS_PATH/fbcv-edit.obo --allow-equivalent-pairs go-simple.obo  --no-subsets --allow-overwrite --outdir oort 

and the other

owltools $FBCV_BUILD_PATH/fbcv-non-classified.owl go-simple.owl --add-imports-from-supports --extract-module -c -s $OBO/go/go-simple.owl --set-ontology-id $OBO/fbcv_go_import.owl -o fbcv_go_import.owl

Should I change them all?

**Comment by mmc46** [comment]
Hi,

I still haven’t been able to get this to work on Jenkins. Any ideas?

export OBO=http://purl.obolibrary.org/obo
owltools $FBCV_BUILD_PATH/fbcv-non-classified.owl go-simple.owl --add-imports-from-supports --extract-module -c -s $OBO/go/go-basic.obo --set-ontology-id $OBO/fbcv_go_import.owl -o fbcv_go_import.owl 

Console:
2015-10-22 14:29:03,951 ERROR (CommandRunner:3229) Could not find specified ontology http://purl.obolibrary.org/obo/go/go-basic.obo <http://purl.obolibrary.org/obo/go/go-basic.obo> for --source
2015-10-22 14:29:03,952 INFO  (CommandRunner:3253) OBJS: 1578
Exception in thread "main" java.lang.NullPointerException
	at uk.ac.manchester.cs.owlapi.modularity.SyntacticLocalityModuleExtractor.<init>(SyntacticLocalityModuleExtractor.java:238)
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:3276)
	at owltools.cli.CommandRunner.run(CommandRunner.java:298)
	at owltools.cli.CommandRunner.run(CommandRunner.java:290)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)


Nothing as changed on Jenkins since late June, afaik, when the job started failing.

Thanks,
Marta

**Comment by dosumis** [comment]
Odd.  From the error message, it looks like it is failing to find this:
http://purl.obolibrary.org/obo/go/go-basic.obo 

But this URI resolves fine in a browser.

Have you tried running locally, with all the relevant files in the same folder?

owltools fbcv-non-classified.owl go-simple.owl --add-imports-from-supports --extract-module -c -s go-basic.obo --set-ontology-id $OBO/fbcv_go_import.owl -o fbcv_go_import.owl

**Comment by dosumis** [comment]
(will need a local copy of OWLtools, but easy to build)

**Comment by cmungall** [comment]
The error message is because the extract module command was unable to find an ontology with the IRI `$OBO/go/go-basic.obo` within the set registered by the manager. The IRI argument must match what is in the IRI of the form

Note you'll never find an ontology with an IRI that ends in .owl, even if the filename is '.obo'.

This should work, because when we public the go-basic file we reuse the main GO IRI (which is questionable)
```
owltools $FBCV_BUILD_PATH/fbcv-non-classified.owl $OBO/go/go-basic.obo --add-imports-from-supports --extract-module -c -s $OBO/go.owl --set-ontology-id $OBO/fbcv_go_import.owl -o fbcv_go_import.owl 
```

**Comment by mmc46** [comment]
Thanks, I’ll try that.

**Comment by mmc46** [comment]
That worked, thank you.

**Comment by dosumis** [comment]
Perhaps I'm misunderstanding here, but shouldn't the resolvable URI and ontology IRI always match, at least for OWL files?
