### ISSUE TITLE
GO refs need checking to make sure that they are actually frontmatter/yamldown

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1003]
Currently, while gorefs treated as if they were yamldown/frontmatter, they do not actually parse as such. There is a retroactive fix in the works (see #1001 and #1002 ), but we should add something to travis to ensure that there is not a problem on PRs. I'd naively assume that we could replicate what we do to make the gorules compliant.

**Comment by kltm** [comment]
Tagging @dougli1sqrd , let's talk about this later on.

**Comment by pgaudet** [comment]
I thought this was one of the GO rules ? (maybe not yet implemented). 


Pascale

**Comment by cmungall** [comment]
No, this is a syntax check separate from go-rules

**Comment by kltm** [comment]
Talked to @dougli1sqrd and will copy what we do for the rules checks with schema in travis.

**Comment by kltm** [comment]
Talking with @dougli1sqrd , at least for now we'd like to "generalize" sparta to be able to schema check yamldown/frontmatter on more than just gorules. This would involve pretty much just pushing the glob to the command line and adjusting the travis checks accordingly.
If I get ahead of @dougli1sqrd on this, I may try something nasty with renaming the files in the travis check that should be undone later.

**Comment by kltm** [comment]
I believe this can be closed with the merging of https://github.com/geneontology/go-site/pull/1006

**Comment by dougli1sqrd** [comment]
@cmungall @kltm,

> just extract the yaml, convert to json, and validate. 

This is exactly what the validator does in sparta. It just assumes the file names (when using a directory) are named gorule. The change in sparta would be to pass in the glob.

**Comment by kltm** [comment]
@dougli1sqrd @cmungall If https://github.com/geneontology/go-site/pull/1006 does not break anything or make matters worse, let's just go with it for now--it's currently blocking further progress on https://github.com/geneontology/go-site/issues/993 as it requires actually clean gorefs files (which are fixed in #1006 )

**Comment by kltm** [comment]
Now in place.
