### ISSUE TITLE
Bibtex for citations

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-site#101]
Or at least hyperlinks.

http://geneontology.org/page/go-citation-policy

For example I wanted to cite AmiGO: http://geneontology.org/page/go-citation-policy#AmiGO
Carbon S, Ireland A, Mungall CJ, Shu S, Marshall B, Lewis S, AmiGO Hub, Web Presence Working Group. AmiGO: online access to ontology and annotation data. Bioinformatics. Jan 2009;25(2):288-9. [abstract | full text]

but [abstract | full text] are not links.

**Comment by kltm** [comment]
Whoops--bad copy/paste there. Now fixed.
