### ISSUE TITLE
Change metadata to improve text on annotation downloads page

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1018]
Currently, a products download page is produced directly from the pipeline and left places like: http://snapshot.geneontology.org/products/pages/downloads.html
Some of the text is hard to read for intended audience.

Started by @pgaudet , see:
https://github.com/geneontology/go-site/pull/1012
https://github.com/geneontology/go-site/pull/1011

**Comment by kltm** [comment]
Assuming `submitter` should match shorthand in groups.yaml
I'm surprised that `entity_type` is uncontrolled. According to @dougli1sqrd none of these are currently used internally, so having them be labels would not be a problem. @cmungall would you know if these fields are used by others?

**Comment by cmungall** [comment]
I decree we should use biolink model types for entity type. 

E.g. https://w3id.org/biolink/vocab/ProteinIsoform

Just use the fragment, e.g. ProteinIsoform. When we get around to adding a json-ld context we will can make the base for the type field be `https://w3id.org/biolink/vocab/`

**Comment by suzialeksander** [comment]
OK, looks like i just made some changes for https://github.com/geneontology/go-site/issues/847 to change a blank entity type to 'protein', which is an existing type- I think this is an allowed entry? 

For the other downloads, the entities they include are: 

- TAIR: antisense_RNA, gene_product, lnc_RNA, miRNA, protein, pseudogene, RNA, rRNA, snoRNA, snRNA, transposable_element_gene, tRNA
- WB : gene, protein
- Zfin: protein_coding_gene pseudogene miRNA tRNA protein gene_product
- Dicty: protein snoRNA snRNA gene_product tRNA scRNA RNase_P_RNA RNase_MRP_RNA
- FB: gene_product protein rRNA ncRNA miRNA tRNA snoRNA snRNA
- CGD: gene_product protein
- ~~Ecoli: protein~~
- Pfalc: mRNA tRNA gene_product ncRNA
- Lmajor: mRNA gene_product (note: only 44x gene product)
- Tbrucei: mRNA gene_product snoRNA tRNA
- MGI: protein_coding_gene pseudogene gene_product gene_segment tRNA_gene scRNA_gene lncRNA_gene protein biological region snRNA_gene miRNA_gene ncRNA_gene snoRNA_gene lincRNA_gene sense_intronic_ncRNA_gene gene rRNA_gene RNase_P_RNA_gene telomerase_RNA_gene mRNA sense_overlap_ncRNA_gene RNase_MRP_RNA_gene SRP_RNA_gene
- Pseudo: protein, tmRNA, ncRNA
- RGD: gene, protein
- SGD: protein gene protein_complex snoRNA tRNA ncRNA rRNA snRNA telomerase_RNA 
- ~~Sjap: protein~~
- Pombe: protein, tRNA, gene_product, snoRNA, rRNA, snRNA, protein_coding_gene
- Xenbase: protein, gene

@pgaudet

**Comment by pgaudet** [comment]
@suzialeksander Let's talk about his tomorrow?

**Comment by suzialeksander** [comment]
entity type and submitter are not columns in the New Downloads Table.
