### ISSUE TITLE
Upstream gene_association.pseudocap.gz appears to contain "bad" characters/encoding

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1023]
On taking a new upstream for pseudocap (https://github.com/geneontology/go-site/pull/1019), GO pipelines started to fail on parsing the gene_association.pseudocap.gz file.
Examination seems to indicate that the file may not be encoded as expected for some readers/parsers.

The immediate expression in the pipeline is errors like:
```
'utf-8' codec can't decode byte 0xa0 in position 7878: invalid start byte
```
After some trial and error, basic fixes may be:
```bash
iconv --from-code=8859_1 --to-code=ascii//TRANSLIT gene_association.pseudocap > pseudocap.ascii
diff gene_association.pseudocap pseudocap.ascii 
2356,2357c2356,2357
< PseudoCAP	PA2950	pfm�		GO:0004318	PMID:27965638	IMP	Fproton motive force protein, PMF	proton motive force protein, PMF|pfm�|fabV|enoyl-acyl-carrier protein reductase FabV	protein	taxon:208964	20190311PseudoCAP			
< PseudoCAP	PA2950	pfm�		GO:0006633	PMID:27965638	IMP	PseudoCAP:PA2950	P	proton motive force protein, PMF	proton motive force protein, PMF|pfm�|fabV|enoyl-acyl-carrier protein reductase FabV	proteintaxon:208964	20190311	PseudoCAP			
---
> PseudoCAP	PA2950	pfm 		GO:0004318	PMID:27965638	IMP	Fproton motive force protein, PMF	proton motive force protein, PMF|pfm |fabV|enoyl-acyl-carrier protein reductase FabV	protein	taxon:208964	20190311PseudoCAP			
> PseudoCAP	PA2950	pfm 		GO:0006633	PMID:27965638	IMP	PseudoCAP:PA2950	P	proton motive force protein, PMF	proton motive force protein, PMF|pfm |fabV|enoyl-acyl-carrier protein reductase FabV	proteintaxon:208964	20190311	PseudoCAP			
```

If I had to hazard a guess, I believe that the new database dumps for this file are allowing a special character connected to "pfm", which has a different encoding to  ascii and utf-8, to get into the GAF causing issues.

Tagging @glwinsor @vanaukenk @dougli1sqrd

**Comment by kltm** [comment]
Note that current upstream reads as ISO-8859, https://github.com/geneontology/pseudomonas-genome-database/commit/aa02bfb564d552991bf491d969bce59c6bda4c57 as ascii:
```bash
file gene_association.pseudocap pseudocap.ascii
gene_association.pseudocap:       ISO-8859 text, with very long lines
pseudocap.ascii: ASCII text, with very long lines
```

**Comment by kltm** [comment]
We have created a PR for a possible fix: https://github.com/brinkmanlab/pseudomonas-genome-database/pull/1
In the interim, we will revert the upstream pseudocap file to the SVN one we had a couple of days ago.

**Comment by glwinsor** [comment]
Thanks. Let me know if there's anything we can do on our end to help.

**Comment by kltm** [comment]
@glwinsor 
To have your new data move through the pipeline, I believe the fix would be to either accept our PR (and we switch back to the new data) and/or your end would prevent the rogue character data from getting into the GAF.

**Comment by kltm** [comment]
@glwinsor Thank you, I can see that my fork is merged.
We're going to try and work through the pipeline for a run looking at another issue, and then will change your source URL back to:
https://github.com/brinkmanlab/pseudomonas-genome-database/raw/master/pseudocap-annotation-files/gene_association.pseudocap.gz

**Comment by kltm** [comment]
`master` and `snapshot` passed pseudocap.
