### ISSUE TITLE
Bad route on current.go.org- logo does not display

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-site#1029]
Logo on upper left of http://current.geneontology.org/products/pages/downloads.html is broken and does not display (this page is accessed from http://geneontology.org/docs/download-go-annotations/)

**Comment by suzialeksander** [comment]
Adding to this, most of the links in the menu bar on current are 404- have been changed/deleted in the move.  Can we remove this bar or edit it to fit the new site? I'm not sure how to edit Current.

**Comment by kltm** [comment]
Ugh, that's not supposed to be there anymore anyways.
https://github.com/geneontology/go-site/blob/master/scripts/downloads-page-template.html

**Comment by lpalbou** [comment]
@kltm this issue may also be affecting the presence of our logo in the OBO page: http://www.obofoundry.org/ontology/go.html

**Comment by kltm** [comment]
It's the old drupal static file site (http://geneontology.org/sites/default/files/go-logo-icon.mini__0.png). Templates, etc. will need to be updated with a new path.

**Comment by pgaudet** [comment]
This sounds high priority - who can do this ?

**Comment by lpalbou** [comment]
Should be solved here: https://github.com/geneontology/go-site/pull/1155

As for obofoundry, @cmungall do you know who could update the URLs ?

**Comment by cmungall** [comment]
The beauty of the obofoundry system (if I do say so myself :-) is that anyone can make a PR

Just go to
http://www.obofoundry.org/ontology/go

Click "edit" on the lower right (yes this is a bit ugly and unintuitive - PRs on the jekyll layout welcome too!!) and make a PR. Usually merged within a day.

**Comment by lpalbou** [comment]
Thanks @cmungall PR is here: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1034

**Comment by lpalbou** [comment]
Both PRs to OBO foundry and the html template have been merged. [OBO foundry](http://www.obofoundry.org/ontology/go.html) is now showing again the GO logo so the next version of the download page should be good too.

This ticket can be closed at the next release (September) if the GO logo indeed appears in http://current.geneontology.org/products/pages/downloads.html
