### ISSUE TITLE
Reactome2GO mapping file appears truncated on current and snapshot

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-site#1031]
Hi,

A Reactome user reported on their helpdesk that the Reactome2GO mapping file available for download appears to be truncated:

http://current.geneontology.org/ontology/external2go/reactome2go

The source file in go-ontology seems okay:

https://raw.githubusercontent.com/geneontology/go-ontology/master/src/ontology/external2go/reactome2go

**Comment by kltm** [comment]
Internally generated. Does anybody know where the extraction code lives?

**Comment by kltm** [comment]
From @cmungall This is in the ontology Makefile.

**Comment by balhoff** [comment]
Expected to be fixed in next snapshot by this PR merged today: https://github.com/geneontology/go-ontology/pull/16856

**Comment by kltm** [comment]
While we do not have a release out, this appears to be fixed on snapshot; moving to "Clearing"

**Comment by dougli1sqrd** [comment]
This appears to still be truncated.

**Comment by kltm** [comment]
From @balhoff : 
The truncated output comes from a small number of lowercase reactome xrefs in go-edit.obo

**Comment by kltm** [comment]
Noting that @goodb 's PR was changing the case up to "Reactome"

**Comment by kltm** [comment]
Current theory is that is should be correct in `snapshot` tomorrow.

**Comment by kltm** [comment]
This now appears to be correct on `snapshot`: http://snapshot.geneontology.org/ontology/external2go/reactome2go. This should carry to the `release`, which we may trigger over the weekend.
