### ISSUE TITLE
Add documentation on github for GO curators

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#105]
Migrated from http://wiki.geneontology.org/index.php/Manager_Call_2015-09-16

> Github: 1) Documentation on how to use github for curators, 2) how to add curator initials when a new > curator wants to make ontology changes (Paola has volunteered to bring this up in Ontology call). > UPDATE ON 2): discussed here: http://jira.geneontology.org/browse/GO-952. Last question remaining: > Chris, can editors stop editing the GO.curator_dbxref file then?

**Comment by kltm** [comment]
I assume the idea would be to make GO.curator_dbxref a read-only downstream artifact like GO.db_xrefs?
Might want to coordinate with @hdietze on this. The last merge of all resources was a little bit ago, so we'd have to do that again, and then flip it over (copying the dbxrefs.yaml).

**Comment by kltm** [comment]
@cmungall There is also GO.curator_dbxrefs.json. Do you know how this was generated (at least since FOAF/WebID was the rage)? It does not seem to update as part of any pipeline, but I haven't been able to find the update script anywhere (and it would be somewhat nicer to work with than parsing the other file, again).

**Comment by kltm** [comment]
Discussed with @cmungall, will treat org field of GO.curators_dbxrefs as string for the time being. @hdietze has provided the sources for his current instance, so will do a three-way merge with the current data.

**Comment by kltm** [comment]
Not sure if gists tag you, but here:
https://gist.github.com/kltm/198879e787c3a42470de
@cmungall @hdietze
