### ISSUE TITLE
Plan for the geneontology FTP

### ISSUE THREAD

**Issue by lpalbou** [geneontology/go-site#1050]
@kltm  comment:
> Unless new plans are made, the FTP will be shut down. These files will
either need to be placed into a new how (e.g. a GitHub repository) or
made as a product of the pipeline. If we do not have a ticket for one of
these yet, we should probably make one if this is a product we are
intending on keeping.

I use this ftp to retrieve old versions of the GO ontology and some files are to my knowledge only accessible here (e.g. recent inquiry about taxon_union_terms.obo and taxon_go_triggers.obo).

If the FTP is shutdown, it seems necessary to plan to store these files before and to communicate on those changes (e.g. through the new go site).

**Comment by pgaudet** [comment]
These two files were requested, so we should make them as part of the pipeline: 

   http://geneontology.org/quality_control/annotation_checks/taxon_checks/taxon_union_terms.obo
   and 
   http://geneontology.org/quality_control/annotation_checks/taxon_checks/taxon_go_triggers.obo

**Comment by lpalbou** [comment]
This is also possibly linked to https://github.com/geneontology/go-site/issues/483 if we use S3 for the long-term storage of those files

**Comment by kltm** [comment]
#483 is the current roadmap for how to deal with older files like this.
