### ISSUE TITLE
gorule0000001: Report cases where > 1 Reference exists 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1065]
From #1063 

The GAF parsing rules state that a single reference should exist per annotation (DB:Reference; GAF column 6). When this is not the case, it is not reported, so it's probably not being detected. 

We need to implement a check and report it in error reports. 

@dougli1sqrd 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
Is this a duplicate of #1063 ?

**Comment by pgaudet** [comment]
Possibly.
