### ISSUE TITLE
Is gorule-0000008 implemented as a filter or a report ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1068]
Hi @dougli1sqrd 

According to the error reports on snapshot, PAINT has at least 1000 errors for gorule-0000008 (http://snapshot.geneontology.org/reports/paint_other-report.html#gorule-0000008); however I find no annotations in AmiGO to GO:0005622 intracellular

For example http://amigo.geneontology.org/amigo/gene_product/UniProtKB:F6V2J7
has no annotation to  GO:0005622 intracellular in AmiGO, but it does in PAINT (PTHR10554). 

Any idea what's going on ? 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
rule 8 looks like it's implemented as a report.

**Comment by pgaudet** [comment]
It's still odd that QuickGO has  123 annotations to intracellular and there are none in AmiGO.
I'll try to investigate more. 

Thanks, Pascale

**Comment by pgaudet** [comment]
These are still not in AmiGO. I think they are being filtered out.

**Comment by dougli1sqrd** [comment]
This should be fixed now. Looks like there was a bug in ontobio that we fixed a couple weeks ago but we haven't released ontobio yet. I just released a new version of ontobio with the fix and updated go-site to pick up the new ontobio. Tomorrow (June 19) we should see this as you expect it.

**Comment by pgaudet** [comment]
OK in snapshot: annotations to GO:0005622 are found in the fb.gaf, but not in the /release file.
