### ISSUE TITLE
Missing gp2protein.fb.gz

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-site#1071]
The FlyBase  gp2protein file seems to be missing from the svn - the ftp path:
ftp://ftp.flybase.net/releases/current/precomputed_files/go/gp2protein.fb.gz
as specified in our data yaml file seems ok and our gaf  has certainly been updated. We did have an issue with our gp2protein not reaching our ftpsite few a bit, but that's been fixed for a few weeks now.

Could you have a look and see what's going on?

**Comment by hattrill** [comment]
FB yaml:
https://github.com/geneontology/go-site/blob/master/metadata/datasets/fb.yaml

**Comment by kltm** [comment]
@hattrill Apologies, I'm going to have to recreate what the intention and reality is here.

As the SVN is being deprecated, we're trying to make sure that the files we expect to be there from the SVN server and now processed through the main pipeline. I'm not sure, however, what the expectations are for gp2protein files are at this point. That said, I believe the consensus was that they were dropped as main product for the time being:

https://github.com/geneontology/go-site/issues/959#issuecomment-448809876

This is also variously touched on at:

https://github.com/geneontology/go-site/issues/939#issuecomment-474135849
https://github.com/geneontology/go-site/pull/806#issuecomment-421503811
https://github.com/geneontology/go-site/issues/400

If this is something that needs to be revisited, we should bring in @cmungall and others to look at / talk about the data flow.

**Comment by hattrill** [comment]
I knew that the svn was being killed off, but I thought it was a bit weird that our GAF had been updated on svn but the gp2protein hadn't.

So, there is no official home for gp2protein at the moment or indeed in the future?

**Comment by hattrill** [comment]
(I've been bad and updated the svn with our gp2protein file...sorry...I want to check something with a GOA error report before making any more deadend tickets.)

**Comment by kltm** [comment]
@hattrill My (possibly flawed) understanding is that there is no current home for gp2protein (subject to change) and that the successor was intended to be GPI. If these are serious blockers for you, we should reopen this discussion.

**Comment by hattrill** [comment]
No blocker - I am going to have a dig and then a chat with GOA - and if the gp2protein is not needed, I shall just kill it.
