### ISSUE TITLE
Update metadata for TAMU projects

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-site#1078]
A variety of files need to be updated and maintained for projects associated with the TAMU groups (@jimhu-tamu and @dsiegele). Following an email discussion with @vanaukenk and @kltm about whether we could do this directly via branching and pull requests is was suggested that I look at related documentation on 

http://wiki.geneontology.org/index.php/Installing_and_Using_git
http://wiki.geneontology.org/index.php/Ontology_Editors_Daily_Workflow

Based those, I am creating this Issue created to have a tracker id number for following the branch naming convention.

**Comment by jimhu-tamu** [comment]
As I suspected, I can branch on my local machine, but cannot commit a new branch to go-site
```
git push --set-upstream origin issue-1078
ERROR: Permission to geneontology/go-site.git denied to jimhu-tamu.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by kltm** [comment]
For the time being, you can also fork and then create a PR back to us from your fork.

**Comment by jimhu-tamu** [comment]
Created a pull request to test working from a fork. Doing it via the forked copy long-term is OK with me, assuming it works.

**Comment by kltm** [comment]
More documentation now here:

https://github.com/geneontology/go-site/blob/master/documentation/how-do-i-edit-metadata.md

via https://github.com/geneontology/go-site/commit/8fb6640a0f4c2d74db42a5df0ad3dbc79c591bb2

**Comment by kltm** [comment]
Is there any other metadata that you need changed?

**Comment by jimhu-tamu** [comment]
Yes, I did a minimal change to test the workflow. 

The biggest thing is probably to manage where we will provide our post-svn gpad files (as we retire making gaf) and the stuff we used to email directly to Tony.

**Comment by kltm** [comment]
@jimhu-tamu 
For the data stuff, the metadata in question for you would be located at: 
https://github.com/geneontology/go-site/blob/master/metadata/datasets/gonuts.yaml
https://github.com/geneontology/go-site/blob/master/metadata/datasets/ecocyc.yaml

We currently have GAF pickup (GPAD not quite there yet) and GPI pickup for loading into NEO (optional). If you need help setting up a place to drop files, please let us know.

**Comment by jimhu-tamu** [comment]
I was just going to provide a url to a directory on our server. 

But does that mean we should still make gaf for now?

**Comment by kltm** [comment]
@jimhu-tamu Yes, all we'd need is a URL for a GAF on a web-accessible server.
GAFs for the time being--the finalization of GPAD 2.0 is being worked out as we type, but GAF will still work as currency until there are more announcements.

**Comment by jimhu-tamu** [comment]
@kltm:  I just attempted to submit a pull for new metadata to give the location of a pickup for the gene_association.ecocyc.gz on our server.

I need to do the same for a gpad 1.1 for the CACAO annotations. Can I get some help with how to compose that? 
* Should it be a new yaml file or should it go in the gonuts.yaml? 
* Not sure what to do for the various fields.

**Comment by kltm** [comment]
@jimhu-tamu If you're talking about https://github.com/geneontology/go-site/pull/1109, it doesn't seem to contain anything except a breaking adjustment to users.yaml (as of this writing).

For ecocyc, I would assume that the adjustment that would be needed would be to the file/line here: https://github.com/geneontology/go-site/blob/master/metadata/datasets/ecocyc.yaml#L19

For CACAO, I'm actually not sure. Is that the same thing (historically) as the GONUTS annotations? If so, the change would be here: https://github.com/geneontology/go-site/blob/master/metadata/datasets/gonuts.yaml#L19 . If not, a new file just like that named `cacao.yaml` in that directory would be the preferred way forward.

**Comment by jimhu-tamu** [comment]
The pull request should have only changed the source url in ecocyc.yaml. I modeled it on what I saw in the sgd.yaml

The place to fetch the gaf is

https://ecocyc.org/gaf/gene_association.ecocyc.gz

For CACAO, it's not the same as the gonuts annotations, which really should be obsoleted.  Historically @suzialeksander would make the gpad and we would mail it to Tony Sawford. I emailed goa with the link for the downloadable copy, which is in gpad 1.1 (because we were using gpad and the gpad pickup doesn't seem to be ready). The link for that one is

https://gowiki.tamu.edu/gpad/CACAO.gpad.gz

**Comment by kltm** [comment]
@jimhu-tamu The only pull request that I see that you have open seems to have only a single breaking change in the YAML spacing: https://github.com/geneontology/go-site/pull/1109/files

We can go ahead and make the changes necessary at our end if you want.

@cmungall @vanaukenk Are we good to go ahead and have a CACAO source?

**Comment by jimhu-tamu** [comment]
> The pull request should have only changed the source url in ecocyc.yaml. I modeled it on what I saw in the sgd.yaml
> 
> The place to fetch the gaf is
> 
> https://ecocyc.org/gaf/gene_association.ecocyc.gz
> 
> For CACAO, it's not the same as the gonuts annotations, which really should be obsoleted. Historically @suzialeksander would make the gpad and we would mail it to Tony Sawford. I emailed goa with the link for the downloadable copy, which is in gpad 1.1 (because we were using gpad and the gpad pickup doesn't seem to be ready). The link for that one is
> 
> https://gowiki.tamu.edu/gpad/CACAO.gpad.gz

There was an error in the URL for the ecocyc gaf.  Should be:

https://ecoliwiki.org/gaf/gene_association.ecocyc.gz

**Comment by vanaukenk** [comment]
We discussed the fate of the gonuts.yaml entry and it will be removed from the datasets.

**Comment by kltm** [comment]
ecocyc is clear; now need to:
- [ ] remove gonuts
- [ ] add GOA CACO GAF

**Comment by pgaudet** [comment]
@kltm I think this is done? I think we not get CACAO from GOA.

**Comment by kltm** [comment]
Stale either way, so I'm okay with closing.
