### ISSUE TITLE
Refine gorule-0000033 to be a warning and the wording relaxed and ontobio impl

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#1082]
We should refine https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000033.md so that fail_mode=soft, because there is too high a chance of removing valid annotations (e.g. if a group provides a MOD ID but no PMID)

gorule 33 currently is worded very aggressively. The wording implies that we can understand which IDs are synonyms. 

We should change this to assume that different IDs *are* synonyms, and then `repair` the reference that is the DB ID by removing it, leaving only the GO_REF or PMID, etc (full list is in the current go rule).

Closing this ticket comes along with an ontobio implementation.
(See also https://github.com/geneontology/go-site/issues/1063#issuecomment-490651143)

**Comment by pgaudet** [comment]
We need to fist get the MODs to remove their publication IDs from the files they provide. 

We should focus the work on rules that are 'approved' (or incorrectly implemented). 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
The implementation of this rule will remove the Group specific ID. This is only coming up because of https://github.com/geneontology/go-site/issues/1063#issuecomment-490651143.

**Comment by pgaudet** [comment]
I changed the status to approved. 

We should notify contributing groups. Who can do that ?

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/pull/1083

**Comment by dougli1sqrd** [comment]
@pgaudet I'm not sure how that would work, what are the normal channels to do this?

**Comment by pgaudet** [comment]
Annotation calls, go-consortium email list, and go-announcements repo.

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/pull/1197

**Comment by pgaudet** [comment]
* The current proposal is to filter internal MOD reference ID for GO_REFs - ie if there are both a internal MOD reference ID  and a GO_REF, we will filter out the MOD ref ID. 
* For PMIDs also having a internal MOD reference ID, both references will be kept for now.  

@vanaukenk does that seem to reflect the decision from the Berkeley GOC meeting ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
After discussion with @ukemi and @vanaukenk 
We will deprecate this rule. Groups want to link to their internal pages for all references. 

@sabrinatoro I think ZFIN removed those already; if you want to you can add them back. Sorry about that ! 

Thanks, Pascale

**Comment by sabrinatoro** [comment]
@pgaudet, yes, we "just" did this (at the same time as the Berkeley GOC meeting).
I'll see what we want to do. Thanks!

**Comment by kltm** [comment]
@pgaudet What is the current status of this? https://github.com/geneontology/go-site/issues/1082#issuecomment-556051891 says that the way forward was deprecation, and it appears to be done (no 33).

**Comment by pgaudet** [comment]
Rule not showing up in http://snapshot.geneontology.org/reports/gorule-report.html
Good ! (as we requested to deprecate it)
