### ISSUE TITLE
Missing line in SGD output GAF file

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1086]
Hello, 

On today's QC call we noticed that this line: 

SGD	S000000892	TRP2		GO:0005950	PMID:3881257	IPI		C	Anthranilate synthase	YER090W|anthranilate synthase TRP2	gene	taxon:559292	20050126	SGD

is present in the **sgd-src-gaf** file but NOT in the **sgd_valid.gaf** file. 

One observation is that this line fails gorule-0000018 but we don't know whether there is any causal link. 

@dougli1sqrd Do you know what happened to this annotation? 

@kltm 

Thanks, Pascale

**Comment by kltm** [comment]
To reiterate, for the given GAF line in the input sgd-src.gaf:
`SGD S000000892 TRP2 GO:0005950 PMID:3881257 IPI C Anthranilate synthase YER090W|anthranilate synthase TRP2 gene taxon:559292 20050126 SGD`
It is expected that this should have a corresponding output in sgd_valid.gaf. There is confusion in that GO rule 0000018 is interpreted as a warning, so should not have filtered the rule. 

This item is meant to trace the exact "removal" of this line.

**Comment by dougli1sqrd** [comment]
I found the culprit. This is being filtered by mistake. The work will continue along this ticket: https://github.com/biolink/ontobio/issues/329. This is an easy fix, and will be corrected shortly.
