### ISSUE TITLE
Infer annotations on molecular function via has_part

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-site#109]
Background: 

Many molecular functions can be broken down into a set of simpler functions (parts), all carried out by _the same agent_.  This agent is the subject of GO annotation - a gene product or a Protein Complex. Because of this, it is safe to infer annotation to has_part children of MFs.  This argument does not apply for BPs (which have many agents) or CCs (where the subject of annotation may not be localized to the parts).  The only exception to this is if a contributes_to qualifier is used.  

Spec for extension to annotation inference pipeline:
For any annotation to a molecular function, MF-X, that does not use the contributes_to qualifier, infer annotation to all MFs that stand in a has_part relationship to MF-X.

**Comment by dosumis** [comment]
CC @cmungall

**Comment by cmungall** [comment]
Ideally we could do this at the OWL reasoning level.

E.g.

    capable_of o has_part -> capable_of

If this is too strong then we can map the implicit MF aspect relation to a more specific one

**Comment by dosumis** [comment]
Notes from meeting:

In principle this makes sense, but may suffer from inconsistent usage of contributes_to qualifier.

**Comment by pgaudet** [comment]
Added a new GO rule to describe this:  PR is here: https://github.com/geneontology/go-site/pull/1810

**Comment by pgaudet** [comment]
Note that ontobio work was done here: 
https://github.com/biolink/ontobio/issues/341#issuecomment-499292690

If I understand correctly we left this with the following tasks to be completed: 
https://github.com/geneontology/pipeline/issues/130

Thanks, Pascale

**Comment by kltm** [comment]
I think this is dupe https://github.com/geneontology/pipeline/issues/130 now?
Currently, the work for adding the limited annotation propagation is in the cleaning project in a single item. If there is more to add, we'd rescope and create a new project.

**Comment by kltm** [comment]
Reading through everything, I think this is indeed a dupe now for https://github.com/geneontology/pipeline/issues/130
