### ISSUE TITLE
Lost all annotations to NCBITaxon:425011 and NCBITaxon:510516

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1092]
Hello, 

Comparing the annotations from the latest release to that of the April release, it looks like we have lost all annotations to NCBITaxon:425011 (Aspergillus niger) and NCBITaxon:510516 (Aspergillus oryzae). 
(see https://s3.amazonaws.com/geneontology-public/go-stats.tsv) 

I suspect this is related to filtering these species out of the UniProt-all file and relying on AspDB to submit them; perhaps these taxa are not in the AspDB data ? 

@marekskrzypek 
@kltm 

Thanks, Pascale

**Comment by marekskrzypek** [comment]
Hi Pascale,
There is quite a number of annotations in AspGD for both species, but they have a different taxon ID, for some reason. A. niger is 5061 and A. oryzae is 5062.

**Comment by pgaudet** [comment]
Hi Marek, 

here are the differences between last month's release and this month's: 

**niger**
Taxon | Number annotations April | Number annotations May
-- | -- | --
NCBITaxon:425011  |  23322 | 0 
NCBITaxon:5061 | 60287 |  66621


**oryzae**
Taxon | Number annotations April | Number annotations May
-- | -- | --
NCBITaxon:510516 | 13946  |  0
NCBITaxon:5062  |  54252 |  60337



So it seems to me, overall some annotations are missing.

**Comment by dougli1sqrd** [comment]
@pgaudet your hypothesis is correct it seems. Looking at the metadata entry for aspgd NCBITaxon:425011 and NCBITaxon:510516 were added in the May release, which would mean in May annotations in goa_uniprot_all would be filtered that have those taxon IDs.

**Comment by pgaudet** [comment]
Ok - so these were the 'duplicate annotations'. 

One question for @alexsign : (with a CGD example but it's the same process): 
Q6FNQ2 (NCBITaxon:284593) has x ref to CGD:CAL0133042 (NCBITaxon:5478); should these entries have the same taxon ?  

(I guess this is not a GO issue anymore, so I'l close). 

Thanks, Pascale
