### ISSUE TITLE
Remove all OWLTools (taxon) reports from pipeline

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1095]
I also see that there are now taxon check fails in some files - but there is a problem - for e.g.: 
http://snapshot.geneontology.org/reports/aspgd-report.html

# GO_AR:0000013	Taxon-appropriate annotation check	Warning	count:	264280
260834	GO_AR:0000013	Warning	Could not retrieve a class for taxonCls: NCBITaxon:767769	AspGD	Aspbr1_0137236	Aspbr1_0137236 GO:0007165	AspGD_REF:ASPL0000166200	IEA	InterPro:IPR000198|InterPro:IPR008936	P	gene_product	taxon:767769	20190526	AspGD 

However the term is ’signal transduction’, there is no taxon constraint on this. 

Thanks, Pascale

**Comment by pgaudet** [comment]
not yet fixed

**Comment by balhoff** [comment]
I added the taxon to the slim request file: https://github.com/obophenotype/ncbitaxon/pull/17

Will see about getting a new taxon release made.

**Comment by balhoff** [comment]
An updated taxonomy should be coming out tomorrow. However I realized there are many other missing taxa reported on that page. (and I assume also in other reports?) We need to collect these more systematically and make another taxonomy update.

**Comment by pgaudet** [comment]
Will be 'handled' by removing when OWL tool report will be removed.

**Comment by kltm** [comment]
Apparently, https://github.com/geneontology/go-site/issues/1095#issue-449124035 is fixed?

From https://github.com/geneontology/go-site/issues/1095#issuecomment-553102857, the separate reports still exist, but maybe still around until all other taxon bugs are cleared? It would be fine to close this out I think, adding a new ticket to mark the final cleaning with the removal of owltools.

**Comment by pgaudet** [comment]
OK looks like the OWL tools reports are no showing up in the main report anymore. 
Thanks !
