### ISSUE TITLE
Need help with a query

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1103]
Hello, 

For the QC group work, we need to have 
*	GOID
*	LABEL
*	ASPECT
*	TOTAL DIRECT ANNOTATIONS
*	EXP DIRECT ANNOTATIONS
*	DO NOT ANNOTATE

For the following list of GO IDs: 

GOID
--
GO:0009966
GO:0045860
GO:0016197
GO:0019538
GO:0005840
GO:0005773
GO:0005774
GO:0006605
GO:0000003
GO:0000166
GO:0000278
GO:0000280
GO:0000375
GO:0000377
GO:0000398
GO:0000785
GO:0001067
GO:0001932
GO:0001934
GO:0003006
GO:0003674
GO:0003676
GO:0003824
GO:0004842
GO:0004857
GO:0005488
GO:0005575
GO:0005623
GO:0005694
GO:0005815
GO:0005975
GO:0006139
GO:0006163
GO:0006259
GO:0006260
GO:0006261
GO:0006351
GO:0006397
GO:0006402
GO:0006412
GO:0006417
GO:0006468
GO:0006629
GO:0006725
GO:0006732
GO:0006753
GO:0006793
GO:0006796
GO:0006807
GO:0006810
GO:0006811
GO:0006812
GO:0006820
GO:0006873
GO:0006875
GO:0006950
GO:0006979
GO:0007010
GO:0007018
GO:0007049
GO:0007059
GO:0007154
GO:0007346
GO:0008047
GO:0008104
GO:0008150
GO:0008219
GO:0008284
GO:0008380
GO:0008610
GO:0009123
GO:0009126
GO:0009144
GO:0009150
GO:0009161
GO:0009167
GO:0009199
GO:0009205
GO:0009259
GO:0009605
GO:0009607
GO:0009628
GO:0009636
GO:0009653
GO:0009719
GO:0009991
GO:0010033
GO:0010467
GO:0010468
GO:0010498
GO:0010556
GO:0010557
GO:0010558
GO:0010564
GO:0010604
GO:0010605
GO:0010608
GO:0010628
GO:0010629
GO:0015238
GO:0015672
GO:0015711
GO:0015849
GO:0015931
GO:0016042
GO:0016051
GO:0016052
GO:0016310
GO:0016458
GO:0016567
GO:0016569
GO:0016772
GO:0018105
GO:0018130
GO:0018193
GO:0019219
GO:0019222
GO:0019438
GO:0019439
GO:0019637
GO:0019693
GO:0019725
GO:0019787
GO:0019941
GO:0022603
GO:0022607
GO:0022804
GO:0030001
GO:0030003
GO:0030154
GO:0030162
GO:0030234
GO:0031224
GO:0031399
GO:0031400
GO:0031503
GO:0031667
GO:0031668
GO:0031669
GO:0032259
GO:0032268
GO:0032269
GO:0032270
GO:0032502
GO:0032774
GO:0032880
GO:0033044
GO:0033554
GO:0034622
GO:0034641
GO:0034645
GO:0034654
GO:0034655
GO:0034976
GO:0036211
GO:0040007
GO:0040008
GO:0040029
GO:0042127
GO:0042221
GO:0042325
GO:0042327
GO:0042493
GO:0042592
GO:0042803
GO:0042886
GO:0043085
GO:0043086
GO:0043087
GO:0043170
GO:0043412
GO:0043414
GO:0043547
GO:0043632
GO:0043933
GO:0044085
GO:0044087
GO:0044089
GO:0044092
GO:0044093
GO:0044237
GO:0044238
GO:0044248
GO:0044249
GO:0044257
GO:0044260
GO:0044265
GO:0044267
GO:0044270
GO:0044271
GO:0044281
GO:0044798
GO:0045184
GO:0045595
GO:0045597
GO:0045786
GO:0045892
GO:0045893
GO:0045934
GO:0045935
GO:0046483
GO:0046700
GO:0046942
GO:0046983
GO:0048284
GO:0048285
GO:0048583
GO:0048584
GO:0048585
GO:0048646
GO:0048856
GO:0048869
GO:0048878
GO:0050789
GO:0050790
GO:0050793
GO:0050794
GO:0050801
GO:0050896
GO:0051049
GO:0051050
GO:0051094
GO:0051128
GO:0051129
GO:0051130
GO:0051168
GO:0051171
GO:0051172
GO:0051173
GO:0051186
GO:0051234
GO:0051246
GO:0051247
GO:0051248
GO:0051252
GO:0051253
GO:0051254
GO:0051276
GO:0051338
GO:0051493
GO:0051606
GO:0051649
GO:0051716
GO:0051726
GO:0055065
GO:0055074
GO:0055080
GO:0055082
GO:0055086
GO:0055114
GO:0060255
GO:0060341
GO:0065003
GO:0065007
GO:0065008
GO:0065009
GO:0070727
GO:0070887
GO:0071310
GO:0071495
GO:0071496
GO:0071554
GO:0071702
GO:0071704
GO:0071705
GO:0071824
GO:0071840
GO:0072503
GO:0072507
GO:0072521
GO:0080090
GO:0080134
GO:0080135
GO:0090304
GO:0090305
GO:0097159
GO:0097659
GO:0098813
GO:1901135
GO:1901136
GO:1901360
GO:1901361
GO:1901362
GO:1901363
GO:1901564
GO:1901565
GO:1901575
GO:1901576
GO:1901657
GO:1901700
GO:1901701
GO:1901987
GO:1902679
GO:1902680
GO:1903046
GO:1903047
GO:1990234
GO:2000112
GO:2000113
GO:2001141
GO:0033036
GO:0032879
GO:0033043
GO:0051179
GO:0033365
GO:0051640
GO:0051641
GO:0008152
GO:0009056
GO:0009057
GO:0009894
GO:0009987
GO:0009889
GO:0009890
GO:0009891
GO:0009892
GO:0009893
GO:0031323
GO:0031324
GO:0031325
GO:0031326
GO:0031327
GO:0031328
GO:0031329
GO:0046907
GO:0051704
GO:0022402
GO:0022411
GO:0022414
GO:0044703
GO:0019953
GO:0016043
GO:0006464
GO:0009058
GO:0009059
GO:0010638
GO:0070925
GO:0006996
GO:0005215
GO:0048518
GO:0048519
GO:0048522
GO:0048523
GO:1903506
GO:1903507
GO:1903508

Thanks, Pascale

**Comment by lpalbou** [comment]
It's a simple combination of two GOLr queries:

To get ID, Label, Aspect and do not annotate:
```
http://golr-aux.geneontology.io/solr/select?fq=document_category:%22ontology_class%22&q=*:*&wt=json&fl=annotation_class,annotation_class_label,source,subset&rows=1000000&fq=annotation_class:(" + IDS + )"
```

And to get the annotations:
```
http://golr-aux.geneontology.io/solr/select?fq=document_category:%22annotation%22&q=*:*&fq=annotation_class:(" + IDS + ")&fl=annotation_class,evidence_type&rows=1000000&facet=true&facet.field=evidence_type&wt=json
```

**Comment by pgaudet** [comment]
Thanks @lpalbou !!
