### ISSUE TITLE
New proposed rule gorule-0000053 : rule 'NOT' annotation should not have extension

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1106]
See PR here: 
https://github.com/geneontology/go-site/pull/987

We have not yet decided if we want to implement this rule.

**Comment by ValWood** [comment]
we should implement this rule.

We can't use NOT to negate extensions, it would be ambiguous.

NOT always mean that the term does not happen. If  we want to negate an extension, a different mechanism is required.

Any annotations with NOT and an extension should be rejected. If the NOT applies to the term, the extension should be removed. If the NOT applies to the extension,  we can't  handle this right now.

PomBase  is "stockpiling" negated extensions until a mechanism exists  (but I think we only have 3)

**Comment by mah11** [comment]
> PomBase is "stockpiling" negated extensions until a mechanism exists (but I think we only have 3)

We have 18.

**Comment by pgaudet** [comment]
TO BE DISCUSSED @vanaukenk @ValWood

**Comment by pgaudet** [comment]
@vanaukenk @ukemi 
We are **not** going to implement this rule yet. It would be nice to have a better way to expression NOT annotations with extensions.

**Comment by RLovering** [comment]
at UCL we have not (I hope) been creating NOT annotations with extensions

**Comment by pgaudet** [comment]
As far as I can tell only MGI has them.

**Comment by pgaudet** [comment]
@mah11 has pombase removed those ?

**Comment by mah11** [comment]
We have never had annotations with the 'NOT' qualifier and an extension.

**Comment by ValWood** [comment]
We wanted to make some negative extensions (only a few), but we never did it with NOT because that would mean something different

**Comment by pgaudet** [comment]
OK thanks.
