### ISSUE TITLE
Arrow display issue on download page

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-site#111]
Little ordering arrows at http://geneontology.org/page/download-annotations seem to be missing.
![screen shot 2015-10-23 at 11 46 00](https://cloud.githubusercontent.com/assets/2214135/10690746/c2bd018e-797b-11e5-99fd-7f0fc265a825.png)

**Comment by monicacecilia** [comment]
@kltm FYI, I don't have permission to check out what's going on here.

**Comment by kltm** [comment]
@stuartmiyasato @kkarra unfortunately, I cannot seem to get access to the server at geneontology.org (to apply the fix) with ssh from any of our usual locations. Is it possible that the ssh ALLOW rules were not copied over or something? Maybe the key has changed?

**Comment by kltm** [comment]
None of my keys work from inside the Stanford VPN either.

**Comment by kltm** [comment]
@stuartmiyasato has gotten me access again (welcome back!), I'll get the updates through.

**Comment by kltm** [comment]
The fix has been applied, and the caches cleared. YMMV.
