### ISSUE TITLE
PANTHER to output a new xml-based tree files for consumption

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#112]
From https://www.ebi.ac.uk/panda/jira/browse/GO-265

These files:
- should be based on phyloXML (or similarly common format)
- ids should follow namespace:id formatting
- species/ancestors should be referred to by their NCBI taxon id where possible
- metadata, such as uniprot ids, should be within the body of the file, either at the node level (preferred) or in a self-contained map
- there should be PTN ids for internal nodes where possible
- there should be labels for internal nodes where possible

There is an additional noted item that Paul should add information in trees to indicate species tree (horizontal transfer issues).

**Comment by mugitty** [comment]
This has already been implemented.  Use the following URL:
http://paintcuration.usc.edu/webservices/family.jsp?searchType=SEARCH_TYPE_PHYLOXML&searchValue=PTHR10000

substitute bookId for parameter searchValue.

**Comment by kltm** [comment]
Thank you @mugitty ; are these included in the file drops that we get as part of the release? IIRC, that was the initial reason for the ticket--possibly to supplement or replace the *.arbre files? (Unfortunately, it has been a while.)

@cmungall , could you take a look at the above file? There seems to be some inconsistencies in the way IDs are encoded, but I'm not sure.

**Comment by mugitty** [comment]
@kltm, these are not part of the file drop.  These can be used in place of the *.attr files.

**Comment by kltm** [comment]
Likely passed by
https://github.com/geneontology/amigo/issues/532
