### ISSUE TITLE
Test IBA GAF set based on Panther 14.1

### ISSUE THREAD

**Issue by dustine32** [geneontology/go-site#1127]
Creating a test branch to test pipeline response to IBA GAFs generated from PAINT after migrating annotations from Panther 13.1 to Panther 14.1.

A separate version-specific URL will be used for this testing.

This in support of issues:
https://github.com/geneontology/pipeline/issues/78
https://github.com/geneontology/pipeline/issues/86

**Comment by kltm** [comment]
Created.
