### ISSUE TITLE
Single uniform URL for PANTHER resource

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#113]
From https://www.ebi.ac.uk/panda/jira/browse/GO-264

Two parts. The first action is to create a single uniform URL that can process both PTHR and PTN IDs for the PANTHER resource.

After this is completed, the assignee should be switched to Seth, who will update the GO.xrf_abbs accordingly.

Conversation to date:

```
Huaiyu Mi added a comment - 14-Feb-14 09:37

Here is the uniform url:

http://www.pantherdb.org/panther/lookupId.jsp?id=$id
```

```
Seth Carbon added a comment - 14-Feb-14 11:03

I was taking a look at this, and they don't seem to be resolving yet. For example, take the following working URLs:

http://www.pantherdb.org/panther/family.do?clsAccession=PTHR11455
http://pantree.org/node/annotationNode.jsp?id=PTN000161291

If I plug the identifiers into the new format, they do not seem to resolve at the moment:

http://www.pantherdb.org/panther/lookupId.jsp?id=PTHR11455
http://www.pantherdb.org/panther/lookupId.jsp?id=PTN000161291
```

```
Huaiyu Mi added a comment - 14-Feb-14 11:22

Oh, the url is just a place holder for now. It has not been implemented yet.

```

**Comment by mugitty** [comment]
This functionality has now been implemented.

**Comment by kltm** [comment]
Excellent--can confirm that the test URLs above resolve. (@cmungall, should be fine in dbxrefs then.)

As an aside, @mugitty, do you have an external PANTHER tracker so we can find out the status of various issues in progress? I'm not sure we would have known about these if we hadn't transferred these out of the old tracker.

**Comment by mugitty** [comment]
@kltm, we do not have an external PANTHER tracker.  Issues can get assigned in either JIRA or GitHub and we have been closing them as they get resolved.

**Comment by pgaudet** [comment]
Close ? @kltm

**Comment by kltm** [comment]
Why not--this was long ago. If it's still a problem, we can reopen/revisit.
