### ISSUE TITLE
Download and organize scripts to be used in the pipeline to grab all GAF sources

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#1133]
From https://github.com/geneontology/pipeline/issues/27

We will download all GAF upstream sources early on all at once in the pipeline. Not only does that enable the above issue, but it also is a dependency of https://github.com/geneontology/go-site/issues/882 using gaferencer. 

We should have a script(s) that will download all needed sources using the metadata and then another that will organize the source files in the filesystem the way that ontobio validate likes it.

**Comment by dougli1sqrd** [comment]
This has been merged and run successfully on master pipeline.

**Comment by kltm** [comment]
I believe that this is still in progress again, correct?

As an aside, it might be interesting to look at and compare the AGR solution: https://github.com/alliance-genome/agr_ferret

**Comment by kltm** [comment]
Natually, if this work has been moved elsewhere, close this and tag the upstream ticket on the new one.

**Comment by dougli1sqrd** [comment]
Yeah the current issue with the downloader I've been working from is this: https://github.com/geneontology/pipeline/issues/122

**Comment by dougli1sqrd** [comment]
The downloader is in master has been running on snapshot.
