### ISSUE TITLE
Incorrect error gorule-0000011? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1136]
Hi @dougli1sqrd 

The JCVI errors report error for gorule-0000011
http://release.geneontology.org/2019-06-09/reports/jcvi-report.html#gorule-0000011

but I dont see what is wrong with the term/evidence combination here: 
ERROR - Violates GO Rule: GORULE:0000011: ND annotations to root nodes only (GO:0008150) -- TIGR_CMR CBU_0005 CBU_0005 GO:0000004 GO_REF:nd ND P hypothetical protein protein taxon:227377 20060327 TIGR

Can you check what's going on ? 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
Should be fixed: https://github.com/biolink/ontobio/pull/385
