### ISSUE TITLE
No evidence codes in the GOA file 'goa_uniprot_all_noiea.gpad.gz' (remove owltools from main file processing)

### ISSUE THREAD

**Issue by alexsign** [geneontology/go-site#1141]
I have following message form one of the GO users. 

****
Dear Alex, 

I have just downloaded the current GOA file 'goa_uniprot_all_noiea.gpad.gz' from http://current.geneontology.org/annotations/ (the July 1 release). However the file does not contain any annotation evidence code info. The column 6 is empty. The document http://geneontology.org/docs/gene-product-association-data-gpad-format/ indicates that column 6 is required. Could you look into this? I am interested in all current annotations that are supported by experimental evidence so am hoping to use the noiea.gpad file to further narrow down to the data I need.

Thank you! 
Peifen
(my colleague Tanya Berardini suggested me to contact you) 
****
In contrast to GOA posted goa_uniprot_all.gpa.gz file which has the evidence (ECO) codes.

**Comment by kltm** [comment]
@dougli1sqrd Do you know where the GPAD generator is?

**Comment by kltm** [comment]
I don't seem to be able to find the evidence in any past release.

**Comment by kltm** [comment]
mgi does seem to have them--possibly file specific?

**Comment by kltm** [comment]
Emitter code difference seems minor (ontobio/io/assocwriter.py):
gpad:
```python
ev = assoc['evidence']
evidence = self.ecomap.coderef_to_ecoclass(ev['type'])
```
gaf:
```python
ev = assoc['evidence']
evidence = ev['type']
```
I would note that the following command returns nothing, when it should throw an error:
```python
e.coderef_to_ecoclass('NOT_A_CODE')
```
our expected domain looks like:
```bash
sjcarbon@moiraine:/tmp$:) zcat goa_uniprot_all_noiea.gaf | cut -f 7 | sort | uniq -c | sort -n
      4 IKR
    159 IC
    199 IGC
    325 ISM
    405 IGI
    460 EXP
    518 ISO
    617 NAS
    729 RCA
    754 ISA
   1393 IEP
   2845 TAS
   3151 HDA
   6698 IMP
  10635 IPI
  27082 ND
  27389 IDA
 126074 ISS
```
testing, they all give appropriate answers. Issue is not in emitter?

**Comment by kltm** [comment]
Looking at go-site/pipeline/Makefile, it looks like this is an owltools generated file?
```bash
owltools --log-error --gaf target/groups/goa/goa_uniprot_all_noiea.gaf --write-gpad -o target/groups/goa/goa_uniprot_all_noiea.gpad.tmp && mv target/groups/goa/goa_uniprot_all_noiea.gpad.tmp target/groups/goa/goa_uniprot_all_noiea.gpad
```

**Comment by kltm** [comment]
Anyways, can confirm that this does not work as desired:
```bash
sjcarbon@moiraine:~/local/src/git/owltools[master]$:) ./OWLTools-Runner/bin/owltools --log-error --gaf /tmp/goa_uniprot_all_noiea.gaf.gz --write-gpad -o /tmp/goa_uniprot_all_noiea.gpad.tmp
```
Noting that all the code is 4-6yrs old and likely some rot in there. My wild guess is that it is not properly getting/using the default eco file that's hard-coded in there. Does not seem to want it as a command line.

Anyways, the fix for this issue should be to switch over to the python.

**Comment by peifenz** [comment]
I also noticed that in file 'goa_uniprot_all_noiea.gaf.gz', there is no annotation with evidence code IBA. Not sure whether you intentionally removed all IBA annotations from this file or by accident.

**Comment by peifenz** [comment]
By the file name '*noiea* I was expecting to see all annotations other than 'IEA', which should include IBA annotations.

**Comment by dougli1sqrd** [comment]
Yes, the goa_uniprot_all file does have IBA removed as of Sept. 2018. 

That is baffling that OWLTools is not correctly outputting the evidence though. How long has this been true I wonder?

**Comment by kltm** [comment]
@dougli1sqrd As far as I can tell, since always. The code was likely Heiko's, so it would be interesting to see what tests he had. That said, the fix (as you did) is just to switch to ontobio, so we can worry about that all later on.

**Comment by dougli1sqrd** [comment]
This looks like it's working, so I will close this.
