### ISSUE TITLE
Ecocyc GAF is still lacking HAMAP and interpro2go

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#1142]
Should be assigned to @jimhu-tamu 

 * URL needs to change from SVN to HTTP
 * File needs to include ALL annotations for E coli, e.g including hamap, intepro2go (previously embedded in #969)

**Comment by jimhu-tamu** [comment]
Hope I just did the pull request correctly. I did not use the commit directly to master option. Should I have done that?

**Comment by jimhu-tamu** [comment]
Still need to work on second part. cc: @dsiegele

**Comment by cmungall** [comment]
Any update on getting the interpro2go and hamap mappings in there @dsiegele @jimhu-tamu?

Can you give an estimate? If this will take a while we'll need to inject these ourselves in the GOC pipeline

**Comment by cmungall** [comment]
Oh hold on, it looks like you have fixed this:

```
$ curl -L -s https://ecoliwiki.org/gaf/gene_association.ecocyc.gz | gzip -dc | grep P0A6T5 | grep GO:0046654
UniProtKB       P0A6T5  folE    GO:0046654      GO_REF:0000104  IEA     UniRule:UR000081104 P   GTP cyclohydrolase 1    folE|b2153|ECK2146      protein taxon:83333     20190112        UniProtKB          PR:P0A6T5
UniProtKB       P0A6T5  folE    GO:0046654      GO_REF:0000002  IEA     InterPro:IPR001474|InterPro:IPR018234   P       GTP cyclohydrolase 1    folE|b2153|ECK2146      protein taxon:83333     20190112   InterPro         PR:P0A6T5
```

hurrah, folE has annotations to tetrahydrofolate biosynthetic process at last!! Thank you!! I think this can be closed as soon as we have a new GOC release. Thank you @dsiegele @himhu-tamu!!!

**Comment by kltm** [comment]
Still getting the same output:
```
sjcarbon@moiraine:/tmp$:( curl -L -s http://current.geneontology.org/annotations/ecocyc.gaf.gz | gzip -dc | grep P0A6T5 | grep GO:0046654
UniProtKB	P0A6T5	folE		GO:0046654	GO_REF:0000104	IEA	UniRule:UR000081104	P	GTP cyclohydrolase 1	folE|b2153|ECK2146	protein	taxon:83333	20190112	UniProtKB		PR:P0A6T5
UniProtKB	P0A6T5	folE		GO:0046654	GO_REF:0000002	IEA	InterPro:IPR001474|InterPro:IPR018234	P	GTP cyclohydrolase 1	folE|b2153|ECK2146	protein	taxon:83333	20190112	InterPro		PR:P0A6T5
```
