### ISSUE TITLE
Update/Add NCBI taxa ids for paint file filter

### ISSUE THREAD

**Issue by hdietze** [geneontology/go-site#115]
While debugging a closure issue for Amigo, we found that the paint submission files for certain mods/species are incomplete and leak into the `paint_other.gaf`. We definitely see Pombase and SGD annotations in the `paint_other.gaf` file. Other mod-organisms might be affected as well
This seems to be a side effect of the NCBI Taxonomy to get rid of strain specific identifiers.

The task is to add the missing/new taxon identifiers to the filter script (`software/utilities/paint-gaf-filter.pl`)

related tickets
- geneontology/amigo#273 
- owlcollab/owltools#134

**Comment by pgaudet** [comment]
out of date
