### ISSUE TITLE
go-plus.json is not updated from July 18th, 2019 

### ISSUE THREAD

**Issue by alexsign** [geneontology/go-site#1151]
go-plus.json in snapshots looks a bit outdated. 
http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.json
just checking if everything is ok with the pipeline

**Comment by kltm** [comment]
@alexsign Thank you for checking in with it. Unfortunately, it is not feeling well at the moment, but has been doing better in recent days:

https://build.geneontology.org/job/geneontology/job/pipeline/job/snapshot/

We're hoping that it will be hale and hearty before the weekend.

**Comment by alexsign** [comment]
@kltm no worries, I was just curious why it's not updated
