### ISSUE TITLE
Dual Taxon check gorule-0000015 should split out general GP/taxon verification

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#1156]
The current GORULE:0000015 text basically outlines 2 checks: 1) A taxon should be aligned with the GP in the annotation, and 2) Dual taxons are only allowed with descendants of GO:0044419 and GO:0044215. 

It seems only point 2 is the actual *dual species check*. Point 1 should be spun out into its own rule  as it should apply to both single taxon fields *and* dual taxons.

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/pull/1157

**Comment by kltm** [comment]
We all talked (@pgaudet @kltm @dougli1sqrd ), we'll defer on the proposed actionable for checking taxon against source until later.
