### ISSUE TITLE
gorule-0000027: limit ID spaces that can be used for annotation

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#1158]
In datasets.yaml we should list the expected IDs for:

 - canonical entities (col1 in a GAF)
 - any entity (col1 or col17 prefix in a GAF)

This should avoid situations like the ongoing EcoCyc mess up

**Comment by pgaudet** [comment]
Where would these allowed ID be specified ? dbxref.yaml ?

**Comment by pgaudet** [comment]
Should be part of https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000027.md?
