### ISSUE TITLE
Get GO IDs in enrichment results

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-site#116]
Is there a way to get the GO IDs instead of labels in the enrichment results? 

Context if of interest: an attendee of the course @paolaroncaglia and I were giving today wanted to try Revigo, http://revigo.irb.hr, but the tool takes a list of GO IDs + p-values rather than labels + p-values

**Comment by kltm** [comment]
I've assigned someone from PANTHER to help triage this.

**Comment by mugitty** [comment]
The PANTHER results have been updated to include the GO IDs in parenthesis after the labels.

**Comment by kltm** [comment]
@mcourtot , if you can confirm, please close.

**Comment by mcourtot** [comment]
Thanks for including the GO IDs, but would it be possible to get them in a separate column? 

As is, if our user wants to extract only GO IDs and the corresponding values (as per his original question), he still needs to parse the file (short excerpt below):
hepoxilin biosynthetic process (GO:0051122)	5	5	.05	+	 > 5	1.37E-05
hepoxilin metabolic process (GO:0051121)	5	5	.05	+	 > 5	1.37E-05
detection of endogenous stimulus (GO:0009726)	3	3	.03	+	 > 5	2.82E-02
[...]

Ideally the return would instead look like:
GO:0051122	hepoxilin biosynthetic process	5	5	.05	+	 > 5	1.37E-05
GO:0051121	hepoxilin metabolic process 	5	5	.05	+	 > 5	1.37E-05
GO:0009726	detection of endogenous stimulus 	3	3	.03	+	 > 5	2.82E-02
[...]

**Comment by mugitty** [comment]
The output from the export functionality is similar to the output from the results page.  Adding an extra column to the results page will make the page too wide.  The user can easily parse the exported results to get the GO id.

**Comment by mcourtot** [comment]
I did ask a few of my biologist colleagues, and unfortunately they are not quite sure how to parse out the file. Could you describe how to "easily parse the exported results to get the GO ID"? I could then add this to the FAQs. Please keep in mind they don't do scripting. 

Regarding making the page too wide, I'm not sure adding a column would make it way wider, as we'd lose the need for brackets around the GO ID by using a different column. If we put that in column 1 with fixed width fitting the GO IDs length, the width gain should be minimal?

**Comment by pgaudet** [comment]
Out of date
