### ISSUE TITLE
Update pipeline for GR (Gramene) annotation source

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-site#1166]
In the interim, while the Planteome groups works out a new submission pipeline for GO annotations, update the current GO pipeline for GR (Gramene) annotations to come from UniProt-GOA.

This will allow us to import GR annotations updated/revised by GO curators using Protein2GO.

Specific steps for this TBD.

**Comment by vanaukenk** [comment]
From email with Alex:

GR (Gramene) annotations are considered 'external' in the Protein2GO database and thus cannot be edited in the tool.

I think this then forces the issue of what to do with annotations sets not maintained by the original submitting group and not also incorporated internally in the GOA database.

Import into Noctua?

**Comment by kltm** [comment]
@vanaukenk I see two paths here. The first would be a port of the GAF into, say, GitHub, where is could be edited and "released". Not terrific maybe, but very clear, public, and would fit nicely with a lot of our current workflows.
The second path is to port it into GO-CAM/Noctua. I don't believe this is quite ready yet, as it would take some pipeline plumbing to make work. For example, we do not have anything that covers the line-by-line checks that we currently have for the GAF inputs. That means either we need to add that coverage, or convert to GAF for checking.

I think that the timeline for this takeover would be informative here. If it has to be done sooner rather than later, I think it likely has to look like the former for the time being.

Also note is progress towards: #997

**Comment by vanaukenk** [comment]
Another alternative, suggested by @alexsign, is that we make the current GR annotation set "internal" to Protein2GO.

This would allow @pgaudet and me to update the annotations as required for any annotation review.

Given that this annotation set is unlikely to change dramatically in the short term, this might be the most pragmatic solution at this point.  Then, once the Planteome project works out their new pipeline, we can decide how best to handle these annotations in the future.  

Note: we'll need to look carefully at the content of the file in the GO SVN directory (the URL listed in the datasets.yaml) vs what is on the GO ftp site where Alex retrieves the gramene annotation file to make sure we know exactly what would be made 'internal' vs what might not be making it into the GOA database.  @alexsign do you have error logs for what might be not uploaded into GOA?  I suspect it could be a lot.

Thx.

**Comment by kltm** [comment]
@vanaukenk Given what I know, I would agree that that would be the best short-term pragmatic approach.

**Comment by alexsign** [comment]
@vanaukenk if everyone agreed I can implement it early next week

**Comment by alexsign** [comment]
@pgaudet I can send you full report or I can try to post it here. What I see as reference is GR_REF:8030 (about 5500 times) GR_REF:8210 (7000 times) and so on.

**Comment by alexsign** [comment]
[syntax_check.log](https://github.com/geneontology/go-site/files/3609387/syntax_check.log)
here is the full report

**Comment by pgaudet** [comment]
I had a look. 
* Most of GR_REF:8030 are InterPro2GO; are we not getting those via the GOA pipeline anyway ? 
* GR_REF:8210 are membrane proteins; again, is this not part of some automated pipeline somewhere ?

**Comment by alexsign** [comment]
@pgaudet here is the list of the refs in question:
GR_REF:11089
GR_REF:1128
GR_REF:11435
GR_REF:2696
GR_REF:6902
GR_REF:7047
GR_REF:8030
GR_REF:8210
GR_REF:IPR001092
GR_REF:IPR001789

let me know if I should remove all/some and regenerate cleaner report.

**Comment by pgaudet** [comment]
This should not be in: 
GR_REF:IPR001092
GR_REF:IPR001789

We also have these are references, these lines will need to get filtered out: 

UniProt:P93003
UniProt:Q41261
UniProt:Q9LEG5

Pascale

**Comment by alexsign** [comment]
all above is removed

**Comment by alexsign** [comment]
@pgaudet  GR_REF:7047 has 33714 records another RCA to go I guess

**Comment by pgaudet** [comment]
* GR_REF:11089 : ~1500 annotations, IC and RCA.  Looks manually reviewed, but we would probably get most of the annotations from the InterPro pipeline

* GR_REF:1128 
Single annotation, not traceable -> Remove

* GR_REF:11435 
4 ISS annotations to an uncharacterized sequence (Q94IC1) -> Remove

* GR_REF:2696
9 ISS/IC, no 'with' data. Most of the annotations are also from IBA -> Remove

* GR_REF:6902
General Gramene reference. About 20 ISS annotations, not 'with' data  -> Remove


GR_REF:7047: Subcell, by a mix of experimental (no citations), and tools for subcell detection. -> Remove


Pascale

**Comment by pgaudet** [comment]
Hello, 

Looking at all those my conclusion is that we need to remove all these annotations that fail the GOA checks. Hopefully the UniProt automated pipeline and the IBA annotations will still provide good coverage. 

Note also that we should expect significant changes in number of annotated entities for Gramene, since PAINT and gramene seem to provide different identifiers for the same protein, for eg: 
http://amigo.geneontology.org/amigo/gene_product/GR_PROTEIN:P12330
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:P12330

Thanks, Pascale

**Comment by alexsign** [comment]
yay! here the report:

Number of lines processed: 1994
Total number of annotations: 1982
Number of annotations assigned by GR: 1982
Total number of problems detected: 435
Number of annotations with error "Evidence code not valid for GO term": 7
Number of annotations with error "Obsolete GO ID": 2
Number of annotations with error "Reference not appropriate for evidence code": 7
Number of annotations with error "Restricted GO term: gocheck_do_not_annotate": 183
Number of annotations with error "Restricted GO term: gocheck_do_not_manually_annotate": 9
Number of annotations with error "Unsupported / missing reference": 126
Number of annotations with error "With/from contains one or more invalid components": 44
Number of annotations with error "With/from is mandatory for this evidence code": 57
Total number of warnings: 3
Number of annotations with warning "With/from is not allowed with this evidence code": 3
Number of annotations with no errors: 1605

**Comment by alexsign** [comment]
[syntax_check_clean.log](https://github.com/geneontology/go-site/files/3610318/syntax_check_clean.log)
and the log file

**Comment by pgaudet** [comment]
Cool ! Can you paste the full report ?

**Comment by vanaukenk** [comment]
Thank you @alexsign and @pgaudet 

Alex, let's go ahead and import the GR annotations that pass the error checks.  

I'm assuming that for any annotations that had pipe-separated references and one of those references was a PMID, that the import script allows those annotations as long as they otherwise pass the QC check.  Please correct me if that's not true.

I'll let Pankaj know of the current status of the import and point him to the log file in case they want to fix those annotations in the future and re-submit.

@alexsign @kltm @dougli1sqrd - when GOA is ready to export the GR annotations, we will need to update the source URL for Gramene annotations from Gramene to GOA in the datasets.yaml

**Comment by alexsign** [comment]
@vanaukenk yes, you are correct about pipe separated references. Another question, should I use go-quality@mailman.stanford.edu as the new contact address or leave gramene@gramene.org? It's important for the future checks.

**Comment by vanaukenk** [comment]
@alexsign 
Let's use the go-quality email for now, and if we need to update that in the future, we can.
Thx.

**Comment by alexsign** [comment]
@vanaukenk @pgaudet conversion is complete, I added permissions on GR source to both of you. Please let me know in case of any issues, or if the other people needs an access as well.

**Comment by vanaukenk** [comment]
Thank you very much @alexsign !
We'll let you know if any issues come up.

**Comment by vanaukenk** [comment]
Tagging @kltm to make sure we back-up the current Gramene file in SVN and also to make sure we remember to update the source of GR annotations in the datasets.yaml when the file is available from UniProt-GOA.

**Comment by kltm** [comment]
As we will be backing up the SVN generally, that should not be an issue. I've also squirreled it away locally, just in case.
When the time comes to switch over, the PR can reference this ticket.

**Comment by pgaudet** [comment]
Done, Gramene removed as a data source from our datasets.yaml
