### ISSUE TITLE
Update pipeline for new GOA tRNA resources to no IEA

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1168]
Recently, it was discovered that GOA tRNA IEAs were skewing the expected GO release statistics. This will need to be remedied before a release can move forward.

Tagging @vanaukenk @pgaudet

**Comment by kltm** [comment]
Change https://github.com/geneontology/go-site/blob/master/metadata/datasets/goa.yaml#L836 to non IEA variant?

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-site/pull/1170

**Comment by pgaudet** [comment]
GOA is now providing rna_noiea files. I have upated the yaml to reflect the file download location.

**Comment by pgaudet** [comment]
Yes. Cow had the largest change, but to be consistent we're removing all
IEA annotations to RNAs.

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @kltm 

I am not sure I understand the difference between the two options, but the latter sounds more correct, "change the naming and drop the old products."

Thanks, Pascale

**Comment by kltm** [comment]
Talking to @pgaudet , we'll switch to the new identities, with an associated announcement for the next release.

**Comment by pgaudet** [comment]
Announcement is here: https://github.com/geneontology/go-announcements/issues/77

**Comment by dougli1sqrd** [comment]
So we're renaming the dataset IDs in goa.yaml to be the original IDs, but point to the noiea version of the source file. We discovered additional issues in the pipeline related to the renaming of these datasets. So to make the metadata consistent, just changing the source URL and not the IDs was decided as an easier solution. PR here: https://github.com/geneontology/go-site/pull/1184

**Comment by pgaudet** [comment]
Out of date. We had changed the files were are loading from the complete file to the 'no-IEA'. 
However, more recently we have switched to the 'GOA-plus files that include all annotations for gene-centric entities, and now we do have some IEAs to RNAs (although not as many as when we were loading the complete file),
