### ISSUE TITLE
Create aggregated gorule violation report 

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#1199]
At the meeting, @alexsign suggested we produce a merged file consisting of the contents of the many GO_RULES into a single JSON file with all go rules at once. Similarly, we would do something like this for the GO_REF files as well.

I suggest we add a key to each json blob to include the text of the rule/ref:
```
[
  {
    "id": "GORULE:0000007",
    "_text": "The IPI (Inferred from Physical Interaction) evidence code is used..."
    .
    .
    .
  },
  ... etc
]
```

This would be a product in our pipeline. He requested this as a file because he uses these files in his pipeline, but it's harder to gather and parse all the files at once as they are. 

Tagging @kltm, @cmungall.  @alexsign Feel free to chime in for anything I missed.

**Comment by alexsign** [comment]
basically enhanced version of 
http://current.geneontology.org/metadata/go-refs.json
should do, or separate file. In any case I can use it for conversion of database IDs to go_refs and go_ref to eco validation

**Comment by kltm** [comment]
Is this something that we still need? There would need to be in-pipeline generation anyways. If this is something that's needed, let's talk about it on a call.

**Comment by mugitty** [comment]
This file will be generated with the assigned-by reports.

**Comment by kltm** [comment]
I'm still not clear on the end-user use case and why we want to release the same info in multiple permutations.

**Comment by mugitty** [comment]
Its a single markup aggregate file that will list out the violations for each GORULE.

**Comment by kltm** [comment]
@pgaudet @mugitty I think it would be good to verbally touch bases on the inclusion of this in the project--I'm not understanding who this is for after four years of no comment. Just because a file exists, doesn't necessarily mean that we want to expose it as a product.

**Comment by mugitty** [comment]
Discussed with @kltm about this aggregate report file. It is a markdown file as opposed to a JSON file.  It will be placed in the reports directory with the 'assigned_by' files.

**Comment by kltm** [comment]
Noting that we're kind of hijacked the original ticket to describe a new report for @pgaudet . Updating title to reflect this.
