### ISSUE TITLE
Add URL to link out to ECO

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-site#1210]
We don't currently have a URL in dbxrefs.yaml for ECO.

@kltm  Can we add one so that we can link out to the ECO website for AmiGO as well as the Noctua form?  

For example:

http://www.evidenceontology.org/term/ECO:0000314/

Thx.

**Comment by kltm** [comment]
There should be no problem adding additional information to the db-xrefs.yaml for ECO.

**Comment by vanaukenk** [comment]
https://github.com/geneontology/go-site/pull/1213
