### ISSUE TITLE
JCVI now provided by UniProt

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1217]
Hi, 

We have been getting the JCVI data from UniProt. What is the process to deal with the jcvi.yaml, just delete ? 

@kltm 
Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet Actually and simply: yes!
This can be done in the web interface--just go to a file, hit the garbage icon, and start a PR.

**Comment by pgaudet** [comment]
OK. @alexsign will send me the report of IDs he has managed to load, and when we're sure we're loading everything we can, I'll delete JCVI as a separate source.

**Comment by pgaudet** [comment]
Removed 
https://github.com/geneontology/go-site/pull/1241

**Comment by cmungall** [comment]
hmm, might be better to mark as obsolete rather than deleting?

>
