### ISSUE TITLE
Some source identifiers are not properly upgraded (e.g. FB/FLYBASE)

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1218]
While there has been some implementation, there are still some "bad" identifiers making it out to productions AmiGO, like FLYBASE.

This is to fix the implementation of gorule-0000027, originally discussed in #950 .

**Comment by pgaudet** [comment]
And also - UniProtKB should be repaired to UniProt (impacts 22k annotations)

**Comment by kltm** [comment]
To clarify, this seems to be "fixed" in col1, but in other columns like assigned_by, there is no upgrade, just a warning if not in groups.

Fixing this would either mean using db-xrefs here, or adding synonyms to groups. May want to hash this out.

**Comment by kltm** [comment]
Talking to @pgaudet , we likely want to just upgrade the same as we do in col1 and use db-xrefs.

**Comment by cmungall** [comment]
`curl -L -s "http://current.geneontology.org/annotations/mgi.gaf.gz" | gzip -dc | grep UniprotKB | wc`

46 using incorrect case

**Comment by pgaudet** [comment]
I guess this is fix during the release process? I don't see this as a Group in the release stats (http://release.geneontology.org/2022-07-01/release_stats/go-annotation-changes.tsv)


@hdrabkin Would you please fix this in the MGI data? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Hi @pgaudet 
I need a bit more instructions here. What is the problem. I have not been following this thread.

**Comment by kltm** [comment]
Rerunning Chris's `curl -L -s "http://current.geneontology.org/annotations/mgi.gaf.gz" | gzip -dc | grep UniprotKB | wc`, this is still an issue.

**Comment by pgaudet** [comment]
Need to add a test in the test GAF

**Comment by cmungall** [comment]
There are other offenders; eg UniPRotKB

**Comment by pgaudet** [comment]
Related or same as https://github.com/geneontology/go-site/issues/2063

**Comment by pgaudet** [comment]
This ticket is getting too confusing; replaced by https://github.com/geneontology/go-site/issues/2210
