### ISSUE TITLE
Connection Refused error in the Megamake pipeline

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#1222]
```
03:24:32      raise URLError(err)
03:24:32  urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
03:24:32  Makefile:119: recipe for target 'target/groups/goa/goa_uniprot_all_noiea.gpad' failed
03:24:32  make: *** [target/groups/goa/goa_uniprot_all_noiea.gpad] Error 1
```

This is happening in the makefile, when we convert goa_uniprot_all into gpad. This uses the `ontobio_parse_assocs` script. We don't pass in an ontology as it's not needed in order to perform the conversion.

However the ontobio `ontol_factory.py` still creates a default ontology from some web resource. This web resource is what is failing, above. 

The easiest solution is to pass in the `go-ontology.json` file that is there, even thought it's not needed. This will prevent the call out to the sky ontology.

**Comment by kltm** [comment]
So this has happened two times in two weeks, so that's a little unsettling.
Ideally, we'd have this patched for the next `release` run, as it sounds like a fairly easy thing to do (threading one more file through). Any thoughts on complexity?

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/pull/1223

**Comment by kltm** [comment]
If added to a project, we're now in "Clearing".

**Comment by dougli1sqrd** [comment]
I think we can close. This workaround is presently in master.
