### ISSUE TITLE
GOA annotation checks on GAFs are more stringent than Jenkins checks (should be same?)

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-site#123]
Moved from GO helpdesk:
http://jira.geneontology.org/browse/GO-819

Hello,

Val received a report on annotations filtered from the PomBase GAF by
UniProt/GOA. Some of the warnings that have to do with annotation
extensions using SO IDs are false positives, i.e. they erroneously report
that a SO ID is not in the allowed range for the relation used.

All of PomBase's coincident_with(SO:nnn) extensions should be allowed,
because the local_range is defined as "CHEBI:24431 SO:0000001", i.e. any
SO term that has an is_a path to "region" should be allowed.

There are also a few false positives involving SO IDs and other relations.
All of the SO IDs here have paths to SO:0000673 ! transcript, which is in
the local_range specifications for both has_direct_input and
has_regulation_target:

Line 32145: WARNING Annotation_extension failed validation
[[GO:0052905] [has_direct_input(SO:0000261)] [Invalid range for
has_direct_input: SO:0000261]]
32145> PomBase SPAC6B12.09 trm10 GO:0052905
PMID:24081582 IDA F tRNA m(1)G methyltransferase Trm10
protein taxon:4896 20131007 PomBase
has_direct_input(SO:0000261)
Line 35716: WARNING Annotation_extension failed validation
[[GO:1901581] [has_regulation_target(SO:0001923)] [Invalid range for
has_regulation_target: SO:0001923]]
35716> PomBase SPBC1778.02 rap1 GO:1901581
PMID:22139915 IMP P telomere binding protein Rap1
protein taxon:4896 20121106 PomBase
has_regulation_target(SO:0001923)
Line 35717: WARNING Annotation_extension failed validation
[[GO:1901581] [has_regulation_target(SO:0001925)] [Invalid range for
has_regulation_target: SO:0001925]]
35717> PomBase SPBC1778.02 rap1 GO:1901581
PMID:22139915 IMP P telomere binding protein Rap1
protein taxon:4896 20121106 PomBase
has_regulation_target(SO:0001925)
Line 35718: WARNING Annotation_extension failed validation
[[GO:1901581] [has_regulation_target(SO:0001924)] [Invalid range for
has_regulation_target: SO:0001924]]
35718> PomBase SPBC1778.02 rap1 GO:1901581
PMID:22139915 IMP P telomere binding protein Rap1
protein taxon:4896 20121106 PomBase
has_regulation_target(SO:0001924)
Line 35719: WARNING Annotation_extension failed validation
[[GO:1901581] [has_regulation_target(SO:0001926)] [Invalid range for
has_regulation_target: SO:0001926]]
35719> PomBase SPBC1778.02 rap1 GO:1901581
PMID:22139915 IMP P telomere binding protein Rap1
protein taxon:4896 20121106 PomBase
has_regulation_target(SO:0001926)
Line 35843: WARNING Annotation_extension failed validation
[[GO:0004525] [has_direct_input(SO:0000209)] [Invalid range for
has_direct_input: SO:0000209]]
35843> PomBase SPBC119.11c pac1 GO:0004525
PMID:9326493 IDA F double-strand-specific
ribonuclease Pac1 snm1|rnt1|hcs protein taxon:4896 20140117
PomBase has_direct_input(SO:0000209)
Line 36053: WARNING Annotation_extension failed validation
[[GO:0000175] [has_direct_input(SO:0001905)] [Invalid range for
has_direct_input: SO:0001905]]
36053> PomBase SPBC29A10.09c tri1 GO:0000175
PMID:24095277 IDA F triman, ribonuclease involved in
priRNA formation Tri1 protein taxon:4896 20140207
PomBase has_direct_input(SO:0001905)
Line 36056: WARNING Annotation_extension failed validation
[[GO:0003723] [has_direct_input(SO:0000646)] [Invalid range for
has_direct_input: SO:0000646]]
36056> PomBase SPCC736.11 ago1 GO:0003723
PMID:24095277 IDA F argonaute csp9 protein
taxon:4896 20140207 PomBase has_direct_input(SO:0000646)

Please let us know if we're misinterpreting these warning messages.
Otherwise, it seems that the checks need a bit of checking.

Thanks,
Midori

**Comment by tberardini** [comment]
Heiko: Hello Midori,

do you know who created the report? It is the script run by Stanford or the Jenkins checks?

**Comment by tberardini** [comment]
Valerie Wood added a comment - 27/Apr/15 11:06 AM

These annotations get through to the GO database just fine, they pass Jenkins checks They fail the GOA checks, which Tony has implemented based on the GO defined constraints:
https://github.com/geneontology/go-site/blob/master/metadata/eco-usage-constraints.yaml

GO/GOA should both be singing from the same hymn sheet so to speak. I had no idea until talking to Tony that all of these PomBase annotations were failing the GOA checks...

If they are valid checks we should aim to correct them when we submit the GAF...

Thanks,

Val

**Comment by tberardini** [comment]
Dr Midori A. Harris added a comment - 27/Apr/15 11:21 AM

Val’s correct in saying that the failed checks re neither the old perl script nor the Jenkins checks. But Tony is checking more than just the ECO constraints listed at the github link — he’s also running some checks on relations and IDs in annotation extensions, and it’s one (or some) of those that is/are giving false positive warnings. I don’t know whether the annotation extension checks are listed somewhere viewable.

Midori

**Comment by tberardini** [comment]
Rama Balakrishnan (Inactive) added a comment - 29/Apr/15 2:18 PM

I agree GO/GOA should both be singing from the same hymn sheet. So far we don't have any checks for col-16 in Mike's script or Jenkins, but we should. We have been meaning to collect all of GOA's checks and include them in GO. I will follow up on this.

Thanks for bringing this up.
Rama

**Comment by tberardini** [comment]
Valerie Wood added a comment - 29/Apr/15 2:36 PM

Great, thanks Rama.

**Comment by tberardini** [comment]
Chris Mungall added a comment - 29/Apr/15 7:45 PM

We do have syntactic and reasoner checks that use annotation extensions - in fact some MGI annotations fail due to this. We never use local ID range, but we use OWL axioms. If something is slipping through the ontology group should be notified to add the correct constraint.

**Comment by tberardini** [comment]
@cmungall @hdietze @mah11 @ValWood

**Comment by tberardini** [comment]
Also consolidating information from http://jira.geneontology.org/browse/GO-817
report more GO errors in jenkins checks



GOA implements a lot of consortium defined annotation rules which are not included int he jenkins checks.

This results in a large number of PomBase annotations being excluded from GOA (around 1000). Could these checks be included in the GAF checks?
They include things like:
"missing/empty "with" field with ISS annotation.
Unknown identifier in ISS annotation.

Some annotation I thought were OK, like the use of a GO CC complex ID as a proxy for a complex identifier with a "guilt by association" process annotation using IPI
(i.e. chromatin remodelling IPI chromatin remodelling complex)
Can anyone confirm this? We could change these to IC, which seems a shame as it is really IPI....

I thought also thought the use of CBS:TMHMM in the "with" field was allowed

And I think these extensions are valid:
Line 35718: WARNING Annotation_extension failed validation [[GO:1901581] [has_regulation_target(SO:0001924)] [Invalid range for has_regulation_target: SO:0001924]]
35718> PomBase SPBC1778.02 rap1 GO:1901581 PMID:22139915 IMP P telomere binding protein Rap1 protein taxon:4896 20121106 PomBase has_regulation_target(SO:0001924)
Line 35719: WARNING Annotation_extension failed validation [[GO:1901581] [has_regulation_target(SO:0001926)] [Invalid range for has_regulation_target: SO:0001926]]
35719> PomBase SPBC1778.02 rap1 GO:1901581 PMID:22139915 IMP P telomere binding protein Rap1 protein taxon:4896 20121106 PomBase has_regulation_target(SO:0001926)

It would be great if GO and GOA used the same consistency checks. We have users who are getting really confused because a lot get the GO annotation from GOA (particularly this using proteomics tools which support UniPROT IDs and annotation), and then can't figure out why things are different.......

Val

**Comment by tberardini** [comment]
Valerie Wood added a comment - 26/Apr/15 11:57 PM

The complete list for fission yeast is attached to this ticket on the PomBase tracker:
https://sourceforge.net/p/pombase/curation-tasks/607/

**Comment by mah11** [comment]
Note - the comment about the list for fission yeast is very out of date now. The ticket has moved (along with the rest of PomBase's trackers) to GitHub, and it's no great loss that the attachment did not come along because it, too, is out of date.

https://github.com/pombase/curation/issues/591

**Comment by kltm** [comment]
@pgaudet @cmungall @dougli1sqrd Should now be subsumed by GO Rules additions from Tony.
