### ISSUE TITLE
Add new gorule-0000055 references should only have one ID per idspace

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1233]
We will implement an additional syntactic check (thus subsumed under rule 1) such that warnings are emitted if we see >1 ID per IDSpace in one line. This can only happen if distinct publications are referenced. We cannot repair this one in a systematic way. I think this should be a warn rather than throwing out the annotation, because the annotation may still be biologically valid.

TODO: Update rule above when decided.

**Comment by dougli1sqrd** [comment]
from https://github.com/geneontology/go-site/issues/1063

**Comment by pgaudet** [comment]
EXAMPLE problematic annotation: 
PlasmoDB:PF3D7_1471100	exported protein 2		GO:0044658		GeneDB	NCBITaxon:36329	IDA			mRNA		PMID:27865834|PMID:30476118	20161123

**Comment by mugitty** [comment]
This is for column 6 of GAF.  Can only specify any namespace once, there can be multiple namespaces.  Example DOI:##
PMID:##
Agicola:##
MGI:##
TAIR:##

**Comment by mugitty** [comment]
Functionality has already been implemented.  No new changes required
