### ISSUE TITLE
New GORULE that defines that annotations should conform to existing Shape Schemas

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#1237]
We should have a GORULE that expresses the fact that Annotations and GO-CAMs should be able to be successfully validated against our battery of Shape schemas for GO-CAM data.

**Comment by pgaudet** [comment]
What is the action ? We could create a rule called 
'Annotations should conform to existing Shape Schemas' with a link to 
https://github.com/geneontology/go-shapes/blob/master/shapes/go-cam-shapes.shex
?
