### ISSUE TITLE
Update obsolete info about RDF/XML format

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/go-site#124]
The page http://geneontology.org/page/file-format-guide refers to the 1999 style rdf/xml format in the list of formats, yet this is deprecated and replaced by the OWL rdf/xml format using OboInOwl. This page should be updated to reflect the deprecated style of the old format and the maintained status of the OboInOwl version (plus that version should be linked).

Regards,
Jerven Bolleman

From http://jira.geneontology.org/browse/GO-637

**Comment by paolaroncaglia** [comment]
See also https://github.com/geneontology/go-site/issues/150 created by @mcourtot 
Mark one of the two tickets as duplicate?
