### ISSUE TITLE
Please do not release code/rules until they have been tested

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1246]
@kltm @cmungall Can we set up a process by which there is more testing before we release code/rules/anything ? 

For example: 
1. Taxon constraints are still not behaving correctly  #1245
2. Information macromolecule issue in Noctua https://github.com/geneontology/noctua/issues/638

It would be nice if we caught these things before releasing the code. 

Thanks, Pascale

**Comment by cmungall** [comment]
1 was a false positive, it works AFAICT. 2 was unfortunate but as I understand we had this up on dev for a week

**Comment by vanaukenk** [comment]
@cmungall  -  by 'dev' do you mean noctua-dev or minerva-dev?
