### ISSUE TITLE
GO Slim documentation

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/go-site#125]
The JIRA ticket no one wants to answer... :dancer: 
@cmungall,the Jira ticket says we are waiting on you to address this and guide us on updating the documentation. http://jira.geneontology.org/browse/GO-709 Thanks in advance.

What we need: 
- Clarifications to the documentation wrt: owltools method, etc. 
- Updates were necessary at least in these two pages: http://geneontology.org/page/go-slim-and-subset-guide and http://geneontology.org/faq/how-do-i-map-set-annotations-high-level-go-terms-go-slim

Original message: (sort of)
[...] I want to get more information about the map2slim. [Although] I have [learned about] the Annotation and GO slim, [in] this page"http://search.cpan.org/~cmungall/go-perl/scripts/map2slim#___top" [there] is [an example] about the "MAPPING ALGORITHM". 
Questions: 
1- I want to know How to generate this graph of map2slim.gif , and what [it means to be] left of the divider and right [of the divider]. If try to use two or more tables of database to said it , how [can] I do it?
2- If only in the database, such as sqlserver2008, can I implement the same process and function? And What should I do?
Sincerely,
olive.

**Comment by monicacecilia** [comment]
oh... and this seems to be somewhat of a dup of #17

**Comment by mcourtot** [comment]
@dosumis was planning on looking into this during SPOT documentation week.
@dosumis: if it is helpful Tony S had prepared a short summary of slimming at http://www.ebi.ac.uk/seqdb/confluence/display/GOA/GO+Slimming+-+an+executive+summary

**Comment by dosumis** [comment]
Need to keep slim vs slimming distinct:
* What is a slim and how can I develop/maintain one?
  * Need to distinguish classic meaning (manually annotated set) from more recent uses.
* What does it mean to 'slim' annotations (Tony's guide)

**Comment by paolaroncaglia** [comment]
Related… Existing GO slims are only available in basic OBO format. Therefore, axioms pointing to other ontologies are invisible to anyone wanting to use GO slims. This causes information loss that is undesirable for some. E.g. GO:0009908 ‘flower development’ has the intersection

intersection_of: GO:0048856 ! anatomical structure development
intersection_of: results_in_development_of PO:0009046 ! flower

but this is lost in the Plant GO slim available from the ’Subsets’ list on the website
http://geneontology.org/ontology/subsets/goslim_plant.obo

Hopefully this can be answered by David’s additions to the slim documentation :-)

**Comment by dosumis** [comment]
> Related… Existing GO slims are only available in basic OBO format. Therefore, axioms pointing to other ontologies are invisible to anyone wanting to use GO slims. This causes information loss that is undesirable for some. E.g. GO:0009908 ‘flower development’ has the intersection

> intersection_of: GO:0048856 ! anatomical structure development
> intersection_of: results_in_development_of PO:0009046 ! flower

> but this is lost in the Plant GO slim available from the ’Subsets’ list on the website
http://geneontology.org/ontology/subsets/goslim_plant.obo

Isn't this inevitable in classic slims in that only tagged classes are included in the slim?  If these additional relationships were included, we would still need to consider whether grouping via the relations involved  (results_in_development_of in this case) is valid.

**Comment by paolaroncaglia** [comment]
Updating group: afraid there wasn't enough time to cover GO slims and slimming during SPOT documentation week.

@dosumis , as this question in particular is quite relevant to many of our users and possibly the bit for which current documentation is unsatisfactory to most users requesting it
"(What is a slim and) how can I develop/maintain one?"
do you think we could set a timeframe for this? I know you're swamped with other tasks at the moment, so, just to avoid it disappearing through the cracks :-)
Your help with this would be hugely appreciated!

Thanks,
Paola

**Comment by pgaudet** [comment]
Out of date/not relevant given the tools GO currently provides.
