### ISSUE TITLE
gorule-0000013 misses errors

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1253]
Hello, 

there are 5 annotations to pombase + multiorganism processes - for example: 
PomBase:SPBC11B10.09	cyclin-dependent protein kinase Cdk1/Cdc2		GO:0007275		GO_Central	NCBITaxon:4896	IBA	PANTHER:PTN000623979|TAIR:locus:2099478	PANTHER:PTHR24056	protein		PMID:21873635	20170228

This is not reported in the pombase report: 
http://snapshot.geneontology.org/reports/paint_pombase-report.html#gorule-0000008

Thanks, Pascale

**Comment by balhoff** [comment]
This annotation seems to come from `paint_pombase-src.gaf`, and looks like this:

```
PomBase	SPBC11B10.09	cdc2		GO:0007275	PMID:21873635	IBA	PANTHER:PTN000623979|TAIR:locus:2099478	P	Cyclin-dependent kinase 1	UniProtKB:P04551|PTN000624043	protein	taxon:284812	20170228	GO_Central		
```

But the taxon there is `284812` (an S. pombe subclass), not `4896`. The violation appears to be caught by gaferencer. @dougli1sqrd will look into whether his code is getting confused by the taxon difference (e.g. is only the `4896` being searched in the gaferencer output).

**Comment by dougli1sqrd** [comment]
When I ran this locally I get the correct errors. I believe snapshot is just out of date.

I get as a part of the generated report:
### gorule-0000013

Taxon-appropriate annotation check

* total: 47
#### Messages
* WARNING - Violates GO Rule: GORULE:0000013: Taxon-appropriate annotation check -- `PomBase	SPBC11B10.09	cdc2		GO:0007275	PMID:21873635	IBA	PANTHER:PTN000623979|TAIR:locus:2099478	P	Cyclin-dependent kinase 1	UniProtKB:P04551|PTN000624043	protein	taxon:284812	20170228	GO_Central		
`
Which is the example above

**Comment by pgaudet** [comment]
@dougli1sqrd What do you mean 'snapshot is out of date'? 
These are not new annotations, and this taxon constraint has not recently been added. What's out of date ? 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
Oh just that since the snapshot pipeline hasn't succeeded in a few days, perhaps we're seeing slightly older data/reports. My point above was that I'd like to see snapshot run again and check the reports since locally when I replicated the paint_pombase validation, I see the expected error above - which is not present in the report you link to. This makes me thing that there's something going on more up to date than the current failing snapshot.

**Comment by pgaudet** [comment]
Hi @dougli1sqrd @balhoff 

This is still not being picked up in the latest snapshot (Jan 6 2020) - can you please check what's going on ? 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
I'll look into it again :+1:

**Comment by dougli1sqrd** [comment]
When in go-site/pipeline, make sure python is installed, gaferencer is in your path (you can also set it with `--gaferencer PATH`), and ontobio is installed. `. environment.sh` will create and install a virtual environment. It's what I used when running locally.
```
go-site/pipeline $ python ../scripts/download_source_gafs.py group paint -d ../metadata/datasets/ -T sources --type gaf -x paint_other -x paint_cgd -x paint_dictybase -x paint_ecocyc -x paint_fb -x paint_goa_chicken -x paint_goa_human -x paint_mgi -x paint_rgd -x paint_sgd -x paint_tair -x paint_wb -x paint_zfin

go-site/pipeline $ python ../scripts/download_source_gafs.py organize -d ../metadata/datasets/ -T target/groups/ -S sources/

go-site/pipeline $ python ../scripts/gaferencer-by-metadata.py group paint -d ../metadata/datasets/ -T target/groups/paint/ --contexts target/go_context.jsonld --contexts target/obo_context.jsonld --ontology target/go-gaf.owl --gafs target/groups/paint

go-site/pipeline $ validate.py produce paint -x paint_other -x paint_cgd -x paint_dictybase -x paint_ecocyc -x paint_fb -x paint_goa_chicken -x paint_goa_human -x paint_mgi -x paint_rgd -x paint_sgd -x paint_tair -x paint_wb -x paint_zfin -m ../metadata/ --gpad -t target/ -o target/go-ontology.json --skip-existing-files -I target/groups/paint/paint.gaferences.json
```

**Comment by kltm** [comment]
"Simulating" in docker:

```bash
docker run -it geneontology/dev-base:eb2f253bb0ff780e1b623adde6d5537c55c31224_2019-08-13T163314
```
 In the image:
```bash
mkdir -p /opt/go-site
cd /opt/ && git clone -b master https://github.com/geneontology/go-site.git
mkdir -p /opt/bin
mkdir -p /opt/lib
scp -r bbop@skyhook.berkeleybop.org:/home/skyhook/release/bin/* /opt/bin/
scp -r bbop@skyhook.berkeleybop.org:/home/skyhook/release/lib/* /opt/lib/
chmod +x /opt/bin/*
cd /opt/go-site/pipeline
```
[now following @dougli1sqrd from above]
```bash
make target/obo_context.jsonld target/go_context.jsonld target/go-gaf.owl target/go-ontology.json

PATH=/opt/bin:$PATH python3 ../scripts/download_source_gafs.py group paint -d ../metadata/datasets/ -T sources --type gaf -x paint_other -x paint_cgd -x paint_dictybase -x paint_ecocyc -x paint_fb -x paint_goa_chicken -x paint_goa_human -x paint_mgi -x paint_rgd -x paint_sgd -x paint_tair -x paint_wb -x paint_zfin

PATH=/opt/bin:$PATH python3 ../scripts/download_source_gafs.py organize -d ../metadata/datasets/ -T target/groups/ -S sources/

PATH=/opt/bin:$PATH python3 ../scripts/gaferencer-by-metadata.py group paint -d ../metadata/datasets/ -T target/groups/paint/ --contexts target/go_context.jsonld --contexts target/obo_context.jsonld --ontology target/go-gaf.owl --gafs target/groups/paint

validate.py produce paint -x paint_other -x paint_cgd -x paint_dictybase -x paint_ecocyc -x paint_fb -x paint_goa_chicken -x paint_goa_human -x paint_mgi -x paint_rgd -x paint_sgd -x paint_tair -x paint_wb -x paint_zfin -m ../metadata/ --gpad -t target/ -o target/go-ontology.json --skip-existing-files -I target/groups/paint/paint.gaferences.json
```

**Comment by kltm** [comment]
Closer to what Jenkins does:
```bash
RESOURCE_GROUPS="paint" DATASET_EXCLUDES="paint_other paint_cgd paint_dictybase paint_ecocyc paint_fb paint_goa_chicken paint_goa_human paint_mgi paint_rgd paint_sgd paint_tair paint_wb paint_zfin" PATH=/opt/bin:$PATH make PY_BIN=/usr/local/bin/ -e target/groups.touch
```
Found...
Again:
```bash
RESOURCE_GROUPS="paint pombase" DATASET_EXCLUDES="paint_other paint_cgd paint_dictybase paint_ecocyc paint_fb paint_goa_chicken paint_goa_human paint_mgi paint_rgd paint_sgd paint_tair paint_wb paint_zfin" PATH=/opt/bin:$PATH make --jobs 3 PY_BIN=/usr/local/bin/ -e target/groups.touch
```
Also found...

**Comment by kltm** [comment]
Trying the full Jenkins analog of the last command above on `master` pipeline.
https://build.geneontology.org/job/geneontology/job/pipeline/job/master/500/

**Comment by kltm** [comment]
Testing SOP:
- [ ] check that the rule is in gafrences
- [ ] check that it's in the *input* gaf
- [ ] check that it's in the *output* gaf
- [ ] check that it's in dataset report json
- [ ] " md
- [ ] check that it's in the gorule table

**Comment by kltm** [comment]
Noting that run no.500 did not produce the desired report:
```bash
grep "WARNING" paint_pombase.report.md | grep "taxon:284812" | grep "GO:0007275" | grep "SPBC11B10.09"
```
This means that there is a difference in our manual docker image run versus the "automated" jenkins one: we still cannot reproduce success in a "production" environment and cannot reproduce failure in a local/testing environment. I honestly forget what this means for the bet (a caffeinated beverage of choice) between @kltm and @dougli1sqrd. @dougli1sqrd to fill in later:

- [ ] @kltm won
- [ ] @dougli1sqrd won

At this point, that would seem to point to a difference in how the environmental variables are passed/interpreted and how the Makefile is executed, as I believe everything else was controlled in our docker experiments above. I suppose ontologies are still not being tightly controlled, but I doubt that path compared to the other possibilities at this point.

**Comment by dougli1sqrd** [comment]
This was my hypothesis that the master run wouldn't show the errors.

**Comment by kltm** [comment]
Random thought: alphabetically speaking, all paint_* files have a rule 13 report until paint_other, then none of them do.

I'm trying something in this vein on master now.

**Comment by kltm** [comment]
Also, paint_other has a high count...what if the next file gets into the 10k range and something goes wrong.

Both paint_ (with its history as resource and group, as well as being appended) and rule 13 (external w/odd process) are special in various ways. It's hard to untangle those.

I'll try running master without paint_other to see if we can get results for paint_pombase.

**Comment by kltm** [comment]
@dougli1sqrd Sneak preview by invading the running docker image for no.503:
```
-rw-r--r-- 1 root root 33830 Jan 14 01:36 paint_pombase.report.md
```
```
### gorule-0000013

Taxon-appropriate annotation check

* total: 45
#### Messages
* WARNING - Violates GO Rule: GORULE:0000013: Taxon-appropriate annotation check
 -- `PomBase    SPBC18E5.10     SPBC18E5.10             GO:0005747      PMID:218
73635   IBA     PANTHER:PTN000207233|UniProtKB:P25708|TAIR:locus:2159522|UniProt
KB:P49821       C       mitochondrial iron-sulfur cluster protein (predicted)   
UniProtKB:O94500|PTN000207285   protein taxon:284812    20170228        GO_Centr
```

**Comment by dougli1sqrd** [comment]
[copied from gitter]
In the master test, it looks like we have semi-duplicated the snapshot gorule 13 issue. Taking out paint_other as well as others, we have just paint_mgi, paint_pombase, paint_wb. paint_mgi has 29 gorule 13 errors, but then the other two datasets (paint_pombase, paint_mgi) have 0 errors, like in the snapshot run

**Comment by pgaudet** [comment]
Perhaps your list above was not exhaustive, but PAINT-TAIR should also have errors, for eg: 
TAIR AT1G79070 should have failed for  GO:0016079 
synaptic vesicle exocytosis. 

Pascale

**Comment by dougli1sqrd** [comment]
We have a working hypothesis PR for the fix in https://github.com/biolink/ontobio/pull/426. Testing will be imminent. 

The thought is this: so consider the groups **pombase** and **paint**. When we run the **pombase** group, we validate `pombase-src.gaf`. Since this dataset has a corresponding paint, we also validate `paint_pombase-src.gaf`. The validation of `paint_pombase-src.gaf` produces a `paint_pombase.report.md` before the validated **paint_pombase** is joined to **pombase**. 

Then, when we run **paint** we validate the dataset `paint_pombase-src.gaf`, producing a `paint_pombase.report.md`. Note that this report has the same name as from the above run of **pombase**. 

But these reports have slightly different contents in them as they are being run in slightly different validation contexts. Crucially, the merged paint gafs do not have gaferencer run on them.

In the pipeline we take all files that look like report files and stick them into the same directory. This means one of the `paint_pombase.report.md` files clobbers the other, and it so happens the wrong report file clobbers the correct one. 

To prevent this, I add a flag to the function that does the main gaf validation to say if the gaf being validated is a primary source or a source to merge in (like paint). If we are validating a source that is being merged into a primary source, (like paint_pombase into pombase) then we do not produce a report, so as to prevent a clobbering.

**Comment by kltm** [comment]
Great description.
For a mile high view: the way that ontobio lays out necessary files on the file system (same names, different directories) was not compatible with the mapping done for consumption (same directory, different name).

**Comment by dougli1sqrd** [comment]
Our test is showing success: http://skyhook.berkeleybop.org/master/reports/paint_pombase-report.html#gorule-0000013

We do have an issue with how the sanity checker should handle what it thinks are "missing" reports now. 

In a master run where we only run a subset of the groups, say just goa, then the following happens:

1) a dataset like `goa_chicken` is validated in goa.
2) the paint mix-in `paint_goa_chicken` is found.
3) `paint_goa_chicken` is processed and validated for the purposes of joining to `goa_chicken`,
but the new changes have this step _not_ produce a report so as to avoid a name collision with a potentially top level validation of `paint_goa_chicken` when the group `paint` is run.
4) the sanity checker sees there is a `paint_goa_chicken-src.gaf` and then looks for a `paint_goa_chicken.report.md`, but this doesn't exist as we just saw in number 3.
5) sanity check fails.

This only occurs if we don't run paint along with something that has a paint mix-in gaf. (like paint_goa_chicken into goa_chicken)

**Comment by kltm** [comment]
Following up on a conversation with @dougli1sqrd . While the recent PR does indeed fix the problem at hand quite nicely, there are consequences of the fix elsewhere (e.g. complicating the sanity checks) that may make it less desirable in the context of the overall data flow.
On discussion, we're likely to temporarily fix the problem by *ensuring* that the correct files are in the correct place manually (starting here https://github.com/geneontology/pipeline/blob/master/Jenkinsfile#L582) by copying the "right" files into place as a final act.

A new issue will be opened to remove this added line, as well as simplify the data flow to make sure that processing occurs once and that there is no file overlap possible. TBD.

**Comment by dougli1sqrd** [comment]
Snapshot is showing `paint_pombase` gorule-0000013 (taxon checks) errors as expected: http://snapshot.geneontology.org/reports/paint_pombase-report.html#gorule-0000013

@pgaudet is this completed?

**Comment by pgaudet** [comment]
Thanks @dougli1sqrd 


@ValWood Did you run the taxon checks somewhere else, so we can compare ?

**Comment by ValWood** [comment]
No, I just spot violations but we don't run taxon checks internally.
I do have some  terms clocked which are taxon restricted terms but I don't think that will help.

I can check for violations to specific terms. I usually check for fission yeast annotated to "multi organismal process"
which usually catches things if the check are not working.

**Comment by ValWood** [comment]
currently



  | cdc2 | cyclin-dependent protein kinase Cdk1/Cdc2 |   | multicellular organism development |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000623979TAIR:locus:2099478 | cell division protein kinase pthr24056 | protein |   | PMID:21873635 | 20170228
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | mss1 | mitochondrial tRNA wobble uridine modification GTPase Mss1 (predicted) |   | embryonic organ development |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000746268ZFIN:ZDB-GENE-050522-335 | family not named pthr42714 | protein |   | PMID:21873635 | 20170828
  | mbx1 | MADS-box transcription factor Mbx1 |   | multicellular organism development |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000235373UniProtKB:Q69TG5 more... | mads box protein pthr11945 | protein |   | PMID:21873635 | 20170829
  | mbx2 | MADS-box transcription factor Pvg4 |   | multicellular organism development |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN000235373UniProtKB:Q69TG5 more... | mads box protein pthr11945 | protein |   | PMID:21873635 | 20170829
  | ldb1 | LIM domain binding protein, transcription co-repressor |   | multicellular organism development |   | GO_Central | Schizosaccharomyces pombe | IBA | PANTHER:PTN001623859TAIR:locus:2029137 | lim domain-binding protein pthr10378 | protein |   | PMID:21873635 | 20170828

**Comment by ValWood** [comment]
Are taxon checks hard checks or soft checks? (I think they should be hard checks)

**Comment by pgaudet** [comment]
That's the next step of the implementation: 
* EXP will be warnings (check)
* non EXP annotations will be filters (hard).

Plus: 
* taxon constraints DO NOT apply to NOT annotations

https://github.com/geneontology/go-site/issues/882

Thanks, Pascale

**Comment by pgaudet** [comment]
@ValWood I assume this part is OK for you.

**Comment by ValWood** [comment]
Yes.
