### ISSUE TITLE
Remove deprecated resources from db-xrefs.yaml 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1263]
Hello 

@cmungall @kltm 

Is there a reason to keep old resources in the  db-xrefs.yaml file ? For example these links do not work anymore: 

http://www.proteome.com/ 
http://cmr.jcvi.org/ and all links within that domain: 
http://cmr.jcvi.org/cgi-bin/CMR/shared/GenePage.cgi?locus=VCA0557
http://search.jcvi.org/search?p&q=TIGR00254

etc. 

Should we remove those ? Do we want to keep this as some archive  ? 

Thanks, Pascale

**Comment by kltm** [comment]
Now that my brain is working, the general policy should be that no longer working URLs should first have an attempt to update. If no update is possible, they should be removed as they are now "bad data".

**Comment by pgaudet** [comment]
Redundant with #583
