### ISSUE TITLE
AmiGO entry in the db-xref file

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1281]
Hello, 

I am cleaning up the dbxref file and I found something odd about the AmiGO entry: 

- database: GO
  name: Gene Ontology Database
  rdf_uri_prefix: http://purl.obolibrary.org/obo/GO_
  generic_urls:
    - http://amigo.geneontology.org/
  entity_types:
    **- type_name: molecular_function**
      type_id: GO:0003674
      id_syntax: \d{7}
      url_syntax: http://amigo.geneontology.org/amigo/term/GO:[example_id]
      example_id: GO:0004352
      example_url: http://amigo.geneontology.org/amigo/term/GO:0004352
    **- type_name: biological_process**
      type_id: GO:0008150
      id_syntax: \d{7}
      url_syntax: http://amigo.geneontology.org/amigo/term/GO:[example_id]
      example_id: GO:0004352
      example_url: http://amigo.geneontology.org/amigo/term/GO:0004352
    **- type_name: cellular_component**
     type_id: GO:0005575
      id_syntax: \d{7}
      url_syntax: http://amigo.geneontology.org/amigo/term/GO:[example_id]
      example_id: GO:0004352
      example_url: http://amigo.geneontology.org/amigo/term/GO:0004352
    **- type_name: macromolecular complex**
      type_id: GO:0032991
      id_syntax: \d{7}
      url_syntax: http://amigo.geneontology.org/amigo/term/GO:[example_id]
      example_id: GO:0004352
      example_url: http://amigo.geneontology.org/amigo/term/GO:0004352

*  Do we want to distinguish these 4 GO aspects, given that they don't have any special namespaces ? 
* If that's the case, I will update the GO ID example, since it represents a MF 

@cmungall @ukemi 

Thanks, Pascale

**Comment by kltm** [comment]
The examples there are only for showing the mapping, which is uniform in this case; if you wish to switch them that's no problem.

**Comment by pgaudet** [comment]
It would make more sense to me to have a single entry if all mappings are the same. Any reason we don't do that ?

**Comment by kltm** [comment]
Three different types.

**Comment by pgaudet** [comment]
well 4 according to AmiGO ;)
