### ISSUE TITLE
Retire gp2protein files

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-site#1324]
The GOC would like to retire the gp2protein files that map gene identifiers from databases, e.g. MGI or WB, to the canonical reference protein in UniProtKB.

These files have been generated by groups contributing annotations to the GOC.

We plan to retire these files in ~ one months' time, February 15th.

We encourage anyone who may still be using these files to contact us (help@geneontology.org) to discuss alternative ways of obtaining these mappings (e.g. gene production information (gpi) files).

**Comment by pgaudet** [comment]
>On 16 Jan 2020, at 18:41, Stacia R Engel <stacia@stanford.edu> wrote:

>It seems this would be a useful work product for GOC, as a founding member, to provide for the Alliance.  Is this retirement a done deal?  If so, perhaps it’s worth a discussion about how to provide this info in a different way.  The topic of identifier mapping has come up often as a need within the Data Quartermasters working group.

>stacia

----

Hi Stacia, 

The gp2protein files were first requested by the RefGenome project, and have now been replaced by UniProt Reference Proteomes. I dont know of another use for the gp2protein file.

The files are not in our GO releases. GOA has a few of them on its ftp site: 
	chicken
	geneid
	human
	pseudocap
	refseq
	unigene
	uniprot

They are in the old GO SVN site: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gp2protein/
The only one that is recent in RGD; others date bewteen 8 months and 7 years. As far as I know, all species we have those files for are in the  UniProt Reference Proteomes set.  

Given that this is so incomplete, and nobody has notified us, it seems unlikely that these files are used. That being said if Alliance wants them it's OK, we'll just need to reactivate the pipeline for the various databases that have stopped producing the files. 

Thanks, Pascale

**Comment by pgaudet** [comment]
To revisit Alliance needs with @srengel after Jan 27th

**Comment by tberardini** [comment]
When the gp2protein files are retired, we'll need to provide a GPI to replace it, right? Otherwise, GO will only have the mapping from annotated gene products to UniProtKB. There won't be a file of all gene product identifiers, regardless of annotation status.  The complete list is only necessary for analyses that need the whole genome/proteome like enrichment. 

What action, if any, do we (the current gp2protein file suppliers) need to take?  What happens if we do nothing?

**Comment by kltm** [comment]
Noting issues:
https://github.com/geneontology/go-site/issues/400
https://github.com/geneontology/go-site/issues/1071

Functionally, as far as the GO pipeline and data releases goe, they have been "retired" for some time.

**Comment by tberardini** [comment]
> Functionally, as far as the GO pipeline and data releases goes, they have been "retired" for some time--they are not part of the current releases and are not used by use for anything during processing.

Great.  I am happy to officially retire TAIR's.

**Comment by pgaudet** [comment]
hi @alexsign @hattrill @ValWood 


The yaml file describing your datasets still contains description of gp2protein files. I will remove those. Please let me know ASAP if you expect this will case problems on you end (so I hold off). 
https://github.com/geneontology/go-site/blob/master/metadata/datasets/fb.yaml
https://github.com/geneontology/go-site/blob/master/metadata/datasets/goa.yaml
https://github.com/geneontology/go-site/blob/master/metadata/datasets/pombase.yaml

Thanks, Pascale

**Comment by ValWood** [comment]
I'm prett sure we have no dependencies but checking with @kimrutherford

**Comment by kimrutherford** [comment]
We're not using those files so no problem for us.

**Comment by alexsign** [comment]
@pgaudet for goa.yaml file can you please just update "url" value to "source" value for now. We most likely going to keep generating the g2protein files for teams which might still use them. Once "url" is updated they'll know where to find them.

**Comment by hattrill** [comment]
@pgaudet that's ok with us. We will stop making them as they are made for GOC.

For files such as this, we really don't know if anyone will miss them. 

Perhaps the depreciation of gp2protein files could be announced via some broader channel than the mailing list: Twitter or a banner announcement on the homepage, to reach a wider audience.

**Comment by pgaudet** [comment]
Checked with @alexsign by email - removing the description of gp2protein from the GOA yaml file will not affect GOA products, so I'll go ahead and do that. 

Thanks, Pascale

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-site/pull/1396
