### ISSUE TITLE
Exception to 1 year rule (gorule-0000029) for IEAs: EcoCyc

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1376]
Hello, 

EcoCyc data is exactly 1 year old. Please make that 2 years for EcoCyc only. 

Let's do that for the upcoming release, so we dont delete 50% of EcoCc data.

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet Could you add in the rule reference here?

**Comment by kltm** [comment]
@pgaudet Could you update https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000029.md ?

**Comment by kltm** [comment]
Talked to @pgaudet . Once we've added this modification to the rule, we'll open a new ticket for it's removal, as it's a know limited-term item that we do not wanted to encode in rules.

**Comment by kltm** [comment]
https://github.com/biolink/ontobio/pull/420

**Comment by kltm** [comment]
@pgaudet If the current `snapshots` are looking good to you, we can go ahead with triggering the `release`.

**Comment by pgaudet** [comment]
Well - http://snapshot.geneontology.org/annotations/ecocyc.gaf.gz does not have any IEAs, whereas the current file in http://release.geneontology.org/2020-01-01/annotations/index.html
has 32k. 

That doesn't seem right ? 

Thanks, Pascale

**Comment by kltm** [comment]
My bad: the fix went in yesterday late enough that is wasn't picked up in the run. Try again tomorrow.

**Comment by pgaudet** [comment]
OK. Should I get a notification for the release ? Or do you want me to manually check that this went through ?

**Comment by kltm** [comment]
If the `snapshot` is looking good to you, I'll go ahead and trigger the `release`.

**Comment by pgaudet** [comment]
Can you count the number of lines ? We expect about 60k annotations for E coli. 
The IEA filter was leaving only 27k.

Thanks, Pascale

**Comment by pgaudet** [comment]
The file on snapshot today has the right number of annotations. You can go ahead with the release. 

Thanks, Pascale

**Comment by kltm** [comment]
Okay, great. I've put in to start `release` tomorrow (as we want the `snapshot` results from today to isolate the taxon/gorule:0000013 bug).
