### ISSUE TITLE
Verbose mode and logging

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#1380]
Ontobio validate.py should have a "verbose" mode set with a flag.

This verbose mode will set logging to a more granular level.

The initial INFO logging we will do will pertain to tracking the bug here: https://github.com/geneontology/go-site/issues/1253

**Comment by dougli1sqrd** [comment]
https://github.com/biolink/ontobio/pull/421

**Comment by kltm** [comment]
This supports the pipeline overall.
