### ISSUE TITLE
Error report - fix to remove OWL rules

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1386]
Hello, 

The top of the rules report includes a section about OWLTools checks that looks like this for http://snapshot.geneontology.org/reports/aspgd-report.html

> GAF Validation Summary Errors are reported first.

> For rule GO_AR:0000008 (http://www.geneontology.org/GO.annotation_qc.shtml#GO_AR:0000008) No annotations should be made to uninformative high level terms, there are 12415 violations with type Warning.

> For rule GO_AR:0000013 (http://www.geneontology.org/GO.annotation_qc.shtml#GO_AR:0000013) Taxon-appropriate annotation check, there are 243419 violations with type Warning.

I think those have all been superseded by other checks and this section can be removed. 

Also the  section it refers to (containing the actual errors for GO_AR:0000008 and GO_AR:0000013) should be removed, as they are redundant (and incorrect for GO_AR:0000013). 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
http://skyhook.berkeleybop.org/issue-1386-remove-owltools-report/reports/goa_chicken-report.html

Owltools report is gone from the example pipeline run!

**Comment by pgaudet** [comment]
Great !!!! Thanks @dougli1sqrd

**Comment by dougli1sqrd** [comment]
This is in snapshot now! http://snapshot.geneontology.org/reports/fb-report.html

Closing.

**Comment by pgaudet** [comment]
Great !!
