### ISSUE TITLE
Missing upstream file: goa_pig_rna

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#1412]
The file described in goa.yaml here https://github.com/geneontology/go-site/blob/master/metadata/datasets/goa.yaml#L1043 seems to be missing.

URL is ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/PIG/goa_pig_rna_noiea.gaf.gz

This is for the goa_pig_rna file. I have sent an email to goa explaining the situation.

**Comment by kltm** [comment]
Weird to disappear when the other files are available. @pgaudet Do you know of any recent change there?

**Comment by pgaudet** [comment]
This is replaced by the files containing the IEAs: 
goa_pig_rna.gpad

Is that OK ? I guess we needed to create a ticket to let you know - sorry. 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet AFAIK at this point, we cannot take GPADs as primary pipeline inputs, only GAFs.

**Comment by pgaudet** [comment]
Oh yes ! @alexsign can you provide a GAF ?

**Comment by kltm** [comment]
@pgaudet I'm getting confused here. Are we talking about https://github.com/geneontology/go-site/commit/ef8962d521e529d893ffa107adb8a70719af5ab6#diff-277d096e4b485bfe87facac508530914 ?
If that PR is what we're talking about, then no GPADs were involved.

**Comment by pgaudet** [comment]
I think that's right - sorry about the confusion. 

Looks like this is resolved ?

**Comment by pgaudet** [comment]
Looks like snapshot now worked- can this be closed ?
