### ISSUE TITLE
Resources used by the GO Consortium

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-site#142]
[SPOT documentation week]

http://geneontology.org/page/go-consortium-contributors-list#Resources_used_by_the_GO_Consortium

I can think of a few others such as Wbbt that are being used. What's the best way to compile the list?

**Comment by cmungall** [comment]
The page is a bit confusing at the moment.

> The Gene Ontology Consortium (GOC) is a set of model organism and 
> protein databases and biological research communities actively 
> involved in the development and application of the Gene Ontology.

Does this mean the Gene Ontology Ontology, or Gene Ontology plus its 
annotations?

The list is mostly GAF contributors, which is partially redundant with 
the json-derived list here: 
http://geneontology.org/page/download-annotations

But it also mixes in groups funded as part of the GO grant - though 
misses some like USC

> Resources used by the GO Consortium

This is really ontologies imported by the GO ontology

**Comment by monicacecilia** [comment]
I updated the introductory text to: 
<code>The Gene Ontology Consortium (GOC) integrates resources from a variety of research institutions from model organism to protein databases to the biological research communities actively involved in the development and implementation of the Gene Ontology. Below is a list of our collaborators.</code>

Also updated the header for the "resources" to: 
<code>Ontologies imported by the GO Consortium</code>

@cmungall Do you have more details about USC? Are you talking about PANTHER? or something else? 

Should we add more resources? Update the header again?

**Comment by cmungall** [comment]
Mainly panther, but we could call out additional credit for the enrichment tool

**Comment by monicacecilia** [comment]
How about this?

__Name:__ Enrichment Analysis Tool

__Description:__ Users can perform enrichment analyses directly from the home page of the GOC website. This service connects to the analysis tool from the PANTHER Classification System, which is maintained up to date with GO annotations. The PANTHER classification system is explained in great detail in Mi H et al, PMID: 23868073. The list of supported gene IDs is available from the PANTHER website.

__Contact:__ <code>enter contact details/mailto link here</code>

-----
In which case I would suggest we change back the header to "Resources imported by the GO", or something similar.

**Comment by pgaudet** [comment]
@suzialeksander Can you check if this can be closed ?

**Comment by suzialeksander** [comment]
PANTHER info is loaded, and the EA has a dedicated "?" page linked from the homepage tool. Nothing more to fix on this for now.
