### ISSUE TITLE
GO Consortium Contributors List

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-site#143]
[SPOT documentation week]

http://geneontology.org/page/go-consortium-contributors-list

What's the best way to check the list is up to date/accurate? Is there a policy to retire groups?

**Comment by monicacecilia** [comment]
@mcourtot In my experience, it has been the GO-tops' task to comment on the institutions that should be included / removed here. 

FYI, I updated this page on 2016-02-22 to re-organize all institutions alphabetically (the prior order was not following any logic I could deduce), and to add funding details for MGI. I also addressed a request to add PRO.

**Comment by pgaudet** [comment]
Updated for 2018 GO website redesign
