### ISSUE TITLE
Xenbase annotations through pipeline with Noctua annotation and display / deposit

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-site#1434]
Making this ticket in Helpdesk until the block can be identified and this ticket moved to a more appropriate tracker, if needed.

XenBase has expressed interest in making use of their Noctua annotations (currently about 340 annotations). Their Noctua annotations are already available in a GPAD: http://release.geneontology.org/2020-02-26/products/annotations/noctua_xenbase.gpad.gz

Tagging @malcolmfisher103 as the contact, let me know if there's someone else at XB that should be involved.  @malcolmfisher103 can you provide any more details?

Tagging @vanaukenk and @kltm to help sort this out.

**Comment by malcolmfisher103** [comment]
Thanks for that catch, we are only building our files weekly at the moment but using the daily build is definitely what we want to be doing.

We do currently have a Xenbase GAF file on our FTP but we could easily put an empty dummy one up somewhere for testing.

**Comment by kltm** [comment]
Ah, you do have a GAF; could you drop the URL here?
What are the contents? Is that a derivation of the Noctua product, or something else?

**Comment by malcolmfisher103** [comment]
Our GAF (http://ftp.xenbase.org/pub/DataExchange/GO/xenbase.gaf.gz) is a filtered set of annotations taken from EBI's proteomes annotation set and a GOLR query and given Xenbase format IDs for their DB Object IDs, with the original uniprot IDs ascribed as column 17 Gene Product Form IDs. It is actually an aggregation of both of these sources for both the tropicalis and laevis species.

As for the InterPro2GO annotations, all of them are coming from the EBI file as far as I can see unless there are InterPro2GO derived annotations in GOLR that don't have 'InterPro' as their 'assigned by' source or a 'GO_REF:0000002' in the reference column?

**Comment by kltm** [comment]
@malcolmfisher103 Apologies for all the questions, I just want to make super sure I understand all that's going on before we look at the possibilities. What I'm trying to do is get a picture of each individual data thread so that we don't end up in a situation where one or both of us would be eating our own tail in some way.

When you're referring to GOlr, do you mean that you're pulling data from essentially AmiGO's backend, one of the GO's public endpoints?
From your description, it sounds like you GAF is from two external data locations. Could you provide more details about the API locations or download sites for your upstreams?

**Comment by malcolmfisher103** [comment]
No problem, the EBI sources are 'ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/proteomes/4099836.X_laevis_African_clawed_frog.goa'
and  'ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/proteomes/221256.X_tropicalis.goa'.

The GOlr queries are 'http://amigo-pro-golr.berkeleybop.org/solr/select?defType=edismax&qt=standard&indent=on&wt=csv&rows=1000000&start=0&fl=source,bioentity_internal_id,bioentity_label,qualifier,annotation_class,reference,evidence_type,evidence_with,aspect,bioentity_name,synonym,type,taxon,date,assigned_by,annotation_extension_class,bioentity_isoform&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&hl=true&hl.simple.pre=%3Cem%20class=%22hilite%22%3E&csv.encapsulator=&csv.separator=%09&csv.header=false&csv.mv.separator=%7C&fq=document_category:%22annotation%22&fq=taxon_subset_closure_label:%22Xenopus%20laevis%22&facet.field=aspect&facet.field=taxon_subset_closure_label&facet.field=evidence_subset_closure_label&facet.field=regulates_closure_label&facet.field=annotation_class_label&facet.field=qualifier&facet.field=annotation_extension_class_closure_label&facet.field=assigned_by&facet.field=panther_family_label&q=*:*'
and
'http://amigo-pro-golr.berkeleybop.org/solr/select?defType=edismax&qt=standard&indent=on&wt=csv&rows=1000000&start=0&fl=source,bioentity_internal_id,bioentity_label,qualifier,annotation_class,reference,evidence_type,evidence_with,aspect,bioentity_name,synonym,type,taxon,date,assigned_by,annotation_extension_class,bioentity_isoform&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&hl=true&hl.simple.pre=%3Cem%20class=%22hilite%22%3E&csv.encapsulator=&csv.separator=%09&csv.header=false&csv.mv.separator=%7C&fq=document_category:%22annotation%22&fq=taxon_subset_closure_label:%22Xenopus%20tropicalis%22&facet.field=aspect&facet.field=taxon_subset_closure_label&facet.field=evidence_subset_closure_label&facet.field=regulates_closure_label&facet.field=annotation_class_label&facet.field=qualifier&facet.field=annotation_extension_class_closure_label&facet.field=assigned_by&facet.field=panther_family_label&q=*:*'

**Comment by malcolmfisher103** [comment]
Something seems to have happened with the GOlr query URLs, the GitHub interface seems to be parsing out some of the URL.

**Comment by kltm** [comment]
@malcolmfisher103 Okay, great. No worries--I have the info I wanted.

Assuming things remain as they are now, my first comment would be to stop using amigo-pro-golr.berkeleybop.org as that is not really a supported endpoint. The only "supported" endpoint for GOlr we have at the moment is the one for releases at golr-aux.geneontology.io . But let's try and find a better way forward overall. If it's going through our system, there would be no need to prosecute us for the data ahead of time. That said, if you were to become the canonical resource for that species, it would be good to know what you needed to cover that we would start stripping out of goa_uniprot_all.

For the FTP file from GOA, do you do any cleanup on it before making available as a (combined) GAF?

**Comment by malcolmfisher103** [comment]
@kltm Thanks for that alternative endpoint, I've changed our scripts to reflect it but as you say a less piecemeal approach would be better. Most of the cleanup on the GOA FTP file is removing entries for uniprot IDs that we don't have a mapping to in our database. We also make the taxon syntax consistent.

**Comment by ukemi** [comment]
Interesting @malcolmfisher103. We have the same issue with uniprot id's that don't map to mouse genes. At the moment we tack those annotations on to the end of our exported gaf. I have discussed this with @vanaukenk and I think we will revisit this practice in the future.

**Comment by kltm** [comment]
@malcolmfisher103 Okay, that's great. I think we're getting a sense of what's going on here. I think you may be talking to @ukemi later this week about this as well.

Would it be possible for you to make a GAF file that is just your fixed GOA upstream, without the additional AmiGO/GOlr annotations?

**Comment by malcolmfisher103** [comment]
@kltm It shouldn't be hard to generate that file. If I need to put it up on the FTP it might take a little longer.

**Comment by kltm** [comment]
@malcolmfisher103 Maybe don't commit any resources until you've had a chance to talk to @ukemi a little, but if we go this way we'd want to have that file available on FTP, or some other public location.

**Comment by malcolmfisher103** [comment]
I have created a version of our gaf file using only the annotations derived from EBI, it is available at our FTP site (ftp://ftp.xenbase.org/pub/DataExchange/GO/xenbase.EBI.only.gaf.gz). There are still a number of partially overlapping sources (such as Agbase and the BHF-UCL) we are picking up from both EBI and our AMIGO query, if we only pick up the Noctua and Paint files is there somewhere to get these as well?  I can easily exclude  a specific source from the EBI derived gaf as the current SPARQL query returns more results but is that query an appropriate source for those annotations? If not is there an alternative source for annotations in GOLR that aren't Noctua or PAINT?

**Comment by kltm** [comment]
@malcolmfisher103 When added into the system, you will be the blessed gatekeeper for the two species that you listed. All of out data for those species must be derived from you, by definition, so you will no longer be able to get them from us, as we're getting them from you. The "exceptions" to this are PAINT and Noctua, as they are annotation tools hosted within the consortium.

If you want to get at the the "additional" annotations that we currently hold (as there is no current gatekeeper for these two species ATM), I would probably look at https://github.com/geneontology/go-site/blob/master/metadata/datasets/goa.yaml#L1067 . The data we have is held in one of the GAFs in one of the datasets metadata files in that directory and that is a likely candidate. You may want to see what their upstream source is and go right to that.

Once that is sorted and you are the canonical source for all things that you want for your species (delta the two GO annotation tools), we have the go ahead to start testing your data in one of the pipelines.

**Comment by malcolmfisher103** [comment]
@kltm We now have a revised EBI only gaf on our FTP site at ftp://ftp.xenbase.org/pub/DataExchange/GO/xenbase.EBI.only.gaf.gz. Can we try using that as an input for adding the Noctua/Paint annotations?

**Comment by kltm** [comment]
@malcolmfisher103 Just to confirm, you'd like to use ftp://ftp.xenbase.org/pub/DataExchange/GO/xenbase.EBI.only.gaf.gz as the file source that is used to drive the curation autocomplete in Noctua?

**Comment by malcolmfisher103** [comment]
Hi @kltm, no this is regarding adding GAF formatted annotations for Noctua and PAINT to our EBI only gaf. We have had persistent trouble converting the GPAD files into gafs and this was a suggested solution to get our Noctua annotations into the gaf format so we could then provide a full gaf making our new Noctua derived annotations available on Amigo. We wanted to test this so I could compare the product of such a process against our current combined gaf to see what we might be losing.

**Comment by kltm** [comment]
@malcolmfisher103 Okay, understood: this is for including Xenbase annotation within our normal pipeline and adding Xenbase and its species to our metadata.
Perhaps @pgaudet and @vanaukenk could take a quick look at the file (ftp://ftp.xenbase.org/pub/DataExchange/GO/xenbase.EBI.only.gaf.gz). If all looks well, we could add the file and metadata (species filter for the GOA file) to the pipeline after the September release goes out and start testing.

**Comment by kltm** [comment]
Talked to @malcolmfisher103 and @vanaukenk this morning.
We'll go ahead with an experimental pipeline to see the product of adding in the noctua and paint annotations to the xenbase upstream source GAF, producing a new "final" GAF. If it is usable, we can add into AmiGO and the standard data flow from there; if not, we will iterate on the tooling to get the necessary GPI available.
Also, once arbitrary format conversion--anything to anything--is available in ontobio (@dougli1sqrd), we'll let @malcolmfisher103 know so that they can use it in their own pipeline.

**Comment by kltm** [comment]
Will use:
https://github.com/geneontology/pipeline/tree/issue-go-site-1434-add-xenbase
https://github.com/geneontology/go-site/tree/issue-1434-add-xenbase

**Comment by malcolmfisher103** [comment]
@kltm  I was hoping that now that the EBI is providing gaf 2.2 formatted files we might revisit this. 

To recap -
We are currently producing a file, 'http://ftp.xenbase.org/pub/DataExchange/GO/xenbase.EBI.only.2.2.gaf',  of all the Xenopus annotations from the  EBI's 'goa_uniprot_all.gaf.gz' file and filtering out those with GOC and GO_CENTRAL as a source or which do not have Uniprot IDs corresponding to Xenbase IDs.  

We are hoping that you can pick up this file and append to it the Xenopus ( taxon:8355, taxon:8364) PAINT and Noctua annotations stored in GOLr in gaf 2.2. format.

**Comment by kltm** [comment]
@malcolmfisher103 I think it might be good to do a sit down with @vanaukenk to make sure that things are all lined up for attempting a switchover (and ensuring that you're filtering will cover all the edge cases).

**Comment by kltm** [comment]
Talking to @vanaukenk and @malcolmfisher103 , next steps:

- [ ] update metadata on go-site and pipeline branches (listed above)
- [ ] successfully complete xenbase pipeline run
- [ ] evaluate product on successful run

**Comment by kltm** [comment]
Ran into a little issue with working with the non-compressed upstream file. For the time being, I'm switching over to a local gzipped version for testing: http://skyhook.berkeleybop.org/xenbase.EBI.only.2.2.gaf.gz

**Comment by kltm** [comment]
@vanaukenk @malcolmfisher103 , preliminary output is available here for the moment. This may blink out as we adjust the late pipeline, but should return after the run gets sufficiently underway.
http://skyhook.berkeleybop.org/issue-go-site-1434-add-xenbase/annotations/

**Comment by malcolmfisher103** [comment]
Thanks @kltm, what should we be expecting to see added? I can't find any GO_Central or GOC sourced annotations. I've put a breakdown of the sources below.  I'm a little surprised there are only 88 Xenbase annotations, the file at 'http://current.geneontology.org/products/annotations/noctua_xenbase.gpad.gz' has around 490 annotations. 

AgBase	543
ARUK-UCL	2
BHF-UCL	203
CACAO	21
CAFA	29
DFLAT	19
Ensembl	2874
HGNC	6
HGNC-UCL	39
IntAct	216
InterPro	82928
MGI	33
ParkinsonsUK-UCL	17
Reactome	66
RHEA	4011
UniProt	152396
WB	2
Xenbase	88

**Comment by kltm** [comment]
@malcolmfisher103 What we'd be basically be expected to see is something like:
`(<your gaf file> - <go filtering>) + <xenbase noctua annotations> => http://current.geneontology.org/annotations/xenbase.gaf.gz`

Looking at the core files involved, it does seem that there is ~121 annotation added to xenbase_valid.gaf, when compared to the final product xenbase.gaf.gz. This includes lines like:
```
Xenbase	XB-GENE-17333422		acts_upstream_of_or_within	GO:0030041	PMID:32726316	IMP		P			gene_product	taxon:0	20200915	Xenbase	part_of(GO:0003231),part_of(GO:0007507),part_of(GO:0055005)	
Xenbase	XB-GENE-17333422		acts_upstream_of_or_within	GO:0055005	PMID:32726316	IMP		P			gene_product	taxon:0	20200918	Xenbase	part_of(GO:0003231),part_of(GO:0007507)	
```
```Xenbase	XB-GENE-17340943		acts_upstream_of_or_within	GO:0001702	PMID:16026968	IMP	Xenbase:XB-TRANSGENE-17329726|Xenbase:XB-TRANSGENE-17329724|Xenbase:XB-TRANSGENE-17329720|Xenbase:XB-TRANSGENE-17329722	P			gene_product	taxon:0	20181026	Xenbase		
```
```
Xenbase	XB-GENE-996950		acts_upstream_of_or_within	GO:0000380	PMID:33230114	ISO		P			gene_product	taxon:0	20210112	Xenbase	part_of(GO:0001843),occurs_in(GO:0005634),has_input(Xenbase:XB-GENE-6041676)	
```
(Also noting that https://github.com/geneontology/pipeline/issues/239 affects Xenbase. This should be fixed up as we go along.)

Given the size of noctua_gpad I would expect rather more annotations in there (~5x), although many are getting in. For this, I've opened a new issue at https://github.com/geneontology/pipeline/issues/240

**Comment by pgaudet** [comment]
@kltm is this still open?

**Comment by kltm** [comment]
Yes, it is.

**Comment by malcolmfisher103** [comment]
@kltm Would it be possible to run this again to see what the current state is like?

**Comment by kltm** [comment]
@malcolmfisher103 Rerunning pipeline `issue-go-site-1434-add-xenbase` from above.

**Comment by malcolmfisher103** [comment]
@kltm Thanks for doing that, it didn't seem to generate any products or annotation files. Am I jumping the gun and the pipeline is still in progress?

**Comment by kltm** [comment]
@malcolmfisher103 Yes, there is no product there yet.

**Comment by kltm** [comment]
@malcolmfisher103 The pipeline has gotten far enough along that there is preliminary product available. You should be able to see finalized products in a couple of hours.
 http://skyhook.berkeleybop.org/issue-go-site-1434-add-xenbase/annotations/

**Comment by kltm** [comment]
@malcolmfisher103 It has been a few months since the last run. I've updated this branch pipeline and am restarting it. The results should soon be available again at: http://skyhook.berkeleybop.org/issue-go-site-1434-add-xenbase/annotations/

**Comment by kltm** [comment]
@malcolmfisher103 @pgaudet 
Recent products are now available for viewing at http://skyhook.berkeleybop.org/issue-go-site-1434-add-xenbase/annotations/

**Comment by kltm** [comment]
@malcolmfisher103 @pgaudet Doing another run for the Xenbase files on pipeline, with some updated software metadata. This should be available w/in twelve hours, give or take: http://skyhook.berkeleybop.org/issue-go-site-1434-add-xenbase/annotations/

**Comment by kltm** [comment]
@malcolmfisher103 @pgaudet We have the latest data run available here. As well, it should include PAINT annotations (see geneontology/go-site#1889)
http://skyhook.berkeleybop.org/issue-go-site-1434-add-xenbase/annotations/xenbase.gaf.gz

**Comment by kltm** [comment]
New PANTHER release available (15.0/2022-09-26--thank you @dustine32 and PANTHER team@), metadata switched over in go-site and loader in pipeline now has xenbase added (for amigo). While we may have to iron out errors, xenbase is now "in".

**Comment by kltm** [comment]
Testing will initially happen with `snapshot`, which should start late tonight, with results in a couple of days.

**Comment by kltm** [comment]
We have released.

**Comment by kltm** [comment]
Noting to @pgaudet , with this, https://github.com/orgs/geneontology/projects/60 is empty.
