### ISSUE TITLE
gorule-0000013 description is missing IEA: It should describe that evidence to be filtered

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#1444]
Currently gorule-0000013 does not include direction on what to do on IEA codes. The intention from @pgaudet was clearly to filter IEA annotations that violate gorule-0000013, along with non-experimental evidence codes. 

This was brought up here: https://github.com/geneontology/go-site/issues/882#issuecomment-607893035 which brought us to discover that the rule does not include IEAs.

Some further discussion here: https://github.com/geneontology/go-site/pull/1388#discussion_r402462751

We will:
1) Add IEA to the rule description as a part of "non-experimental"
2) Add the ECO code (`ECO:0000501`) as non-experimental in the ontobio implementation

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/pull/1445

**Comment by dougli1sqrd** [comment]
I believe that the reports are showing we are correctly filtering IEA taxon failures: http://snapshot.geneontology.org/reports/aspgd-report.html#gorule-0000013.

**Comment by pgaudet** [comment]
Great !! Thanks @dougli1sqrd
