### ISSUE TITLE
Modify gorule-0000015 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1451]
Hello, 

gorule-0000015 needs to also include GO:0043903 regulation of symbiotic process (old label: ~regulation of interspecies interactions between organisms~), see https://github.com/geneontology/go-ontology/issues/19207#event-3197822403

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @dougli1sqrd 

Since this is a modification of an existing rule, can you do it soon ? So the rule description and its application stay in synch.

**Comment by kltm** [comment]
@pgaudet Is this cleared?

**Comment by pgaudet** [comment]
No, this is not cleared. This ticket was requesting NOT to report annotations to 'regulation of symbiotic process' - but it is incorrectly reporting errors on terms that should have been allowed (ie children of GO:0044419 interspecies interaction between organisms), for eg:

Error in the  [http://release.geneontology.org/2020-06-01/reports/goa_human-report.html#gorule-0000015](human report)
should allow GO:0002812 biosynthetic process of antibacterial peptides active against Gram-negative bacteria

**Comment by pgaudet** [comment]
Is the rule only allowing is_a parents ?

**Comment by kltm** [comment]
Noting: http://amigo.geneontology.org/visualize?format=png&term_data_type=string&term_data=GO%3A0002812&mode=amigo&inline=false
Assuming that this is only looking at `is_a`, it can be seen that there is a cut set of `part_of`s preventing the connection between GO:0002812 and GO:0044419--I suspect this is the problem here.

**Comment by pgaudet** [comment]
@dougli1sqrd Can you just try it, see if it works ?

**Comment by pgaudet** [comment]
This is still not fixed. 
GO:0001618 | virus receptor activity
should allow 2 taxa. 

I think including part_of relations would fix this.

**Comment by kltm** [comment]
From @dustine32 :

@pgaudet Upgrading to this version of ontobio should fix #1451. A few days after this is merged, you should be able to check snapshot to confirm.

**Comment by pgaudet** [comment]
I think this is now correct. We can now use dual taxa for 'GO:0001900 ' in P2GO as requested in  https://github.com/geneontology/go-ontology/issues/19207

Thanks!
