### ISSUE TITLE
Relax IEA rule gorule-0000029 - expand window and add warning

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1456]
Hello, 

gorule-0000029 states that IEAS over 1 year old are removed. However there is no notification given. The PIs have agreed to change the rule as follows: 

- IEAs < 1 year old -> valid
- IEAs 1-2 year old -> WARNING (annotations are still included, but those would be in the error reports)
- IEAs older than 2 years old -> FAIL (annotations are excluded) 

Please implement that for the upcoming (April) release, otherwise we loose 12% of TAIR annotations. 

@kltm 
@tberardini 

Thanks, Pascale

**Comment by tberardini** [comment]
Thanks, this would be a nice early warning system.

**Comment by kltm** [comment]
- [ ] Failing WIP PR https://github.com/biolink/ontobio/pull/443
- [ ] update metadata https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000029.md

**Comment by pgaudet** [comment]
- [x] Fixed gorule-0000029

PR: https://github.com/geneontology/go-site/pull/1460

@alexsign It would be good if GOA used the same rules. 

Thanks, Pascale

**Comment by alexsign** [comment]
@pgaudet not really applicable to the GOA. We drop all IEAs every week and recalculate them. The GOA database doesn't have any IEAs more than a week old. The release files always have the IEA set created the weekend before the release.

**Comment by kltm** [comment]
Looks like it's acting as expected in `snapshot`.
