### ISSUE TITLE
Newly seen in gpad files, qualifier, "NOT|", should be "NOT" 

### ISSUE THREAD

**Issue by dvklopfenstein** [geneontology/go-site#1461]
Thank you for the great gene ontology annotations.

I am seeing many qualifiers which look like this:

```NOT|```

rather than what they were in the past:

```NOT```

This is causing our gpad reader  to fail. I am going to change the gpad reader to not fail upon encountering an unnecessary divider, but the large annotation files already take 15-30 seconds to load on my machine and adding this extra check will extend that time.

It would be cleaner if when there is only one qualifier to not include the divider.

I am seeing this in the goa_human.gpad downloaded on March 17, 2020.

**Comment by kltm** [comment]
Talking to @dougli1sqrd , fix in progress.

**Comment by kltm** [comment]
@pgaudet We may want to add this to the release notes for the last release.

**Comment by kltm** [comment]
@dougli1sqrd Noting points of interest in:
/ontobio/model/association.py
/ontobio/io/assocwriter.py

**Comment by dvklopfenstein** [comment]
Just wanted to make sure that you noticed that the content of `goa_human.gpa` and `goa_human.gpad` are different.  For example:

```
$ grep NOT goa_human.gpad | sort | grep Q9ULI4
UniProtKB       Q9ULI4  NOT|    GO:0003777      GO_REF:0000024  ECO:0000250     UniProtKB:Q52KG5                20091119        UniProt
UniProtKB       Q9ULI4  NOT|    GO:0007018      GO_REF:0000024  ECO:0000250     UniProtKB:Q52KG5                20091119        UniProt
UniProtKB       Q9ULI4  NOT|    GO:0007018      PMID:21873635   ECO:0000318     PANTHER:PTN000648413|PANTHER:PTN000649056               20170228        GO_Central
UniProtKB       Q9ULI4  NOT|    GO:0016887      GO_REF:0000024  ECO:0000250     UniProtKB:Q52KG5                20091119        UniProt
UniProtKB       Q9ULI4  NOT|    GO:0016887      PMID:21873635   ECO:0000318     PANTHER:PTN000648413|PANTHER:PTN000649056               20170228        GO_Central

$ grep NOT goa_human.gpa | sort | grep Q9ULI4
UniProtKB       Q9ULI4  NOT|enables     GO:0003777      GO_REF:0000024  ECO:0000250     UniProtKB:Q52KG5                20091119        UniProt         go_evidence=ISS
UniProtKB       Q9ULI4  NOT|enables     GO:0016887      GO_REF:0000024  ECO:0000250     UniProtKB:Q52KG5                20091119        UniProt         go_evidence=ISS
UniProtKB       Q9ULI4  NOT|enables     GO:0016887      PMID:21873635   ECO:0000318     PANTHER:PTN000648413|PANTHER:PTN000649056               20170228        GO_Central              go_evidence=IBA
UniProtKB       Q9ULI4  NOT|involved_in GO:0007018      GO_REF:0000024  ECO:0000250     UniProtKB:Q52KG5                20091119        UniProt         go_evidence=ISS
UniProtKB       Q9ULI4  NOT|involved_in GO:0007018      PMID:21873635   ECO:0000318     PANTHER:PTN000648413|PANTHER:PTN000649056               20170228        GO_Central              go_evidence=IBA
```

And the count of `NOT`s seen in the files is different too:
```
$ grep NOT goa_human.gpad | wc -l
1244

$ grep NOT goa_human.gpa | wc -l
1250
```

**Comment by kltm** [comment]
@dvklopfenstein Fixes in the `snapshot` should be out tonight on the success of the pipeline. If so, we'll proceed to attempting a new `release`.

**Comment by kltm** [comment]
This appears to now be fixed in the current `snapshot`.
