### ISSUE TITLE
Annotation quality controls

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-site#147]
[SPOT documentation week]

e.g., http://geneontology.org/page/annotation-quality-control-checks#0000009 what is GO_AR:0000009 Annotation Intersection Alerts

Clean up page some "proposed" are marked as "active implementation"

**Comment by pgaudet** [comment]
We have Annotation Intersection Alerts: 
http://current.geneontology.org/reports/shared-annotation-check.html

**Comment by pgaudet** [comment]
Some documentation is here: 
https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000009.md
