### ISSUE TITLE
Migrate from persona.org to a new authentication system 

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#148]
[Critical issue, but one that has a little time to be solved.]

@hdietze / @cmungall ,

We have about a year to abandon persona.org:

https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers
https://groups.google.com/forum/#!msg/mozilla.dev.identity/mibOQrD6K0c/kt0NdMWbEQAJ

Sad to see it go, as it was the easiest independent solution. I'm hoping
that somebody will pick this up and allow the transition to a workalike,
but I'm not going to hold my breath. It's a shame that everybody wants
their own gardens, so something nice like browserid (email verification)
is unable to find a place in the sun.

If we decide that we are truly all in with GitHub (and make sure that
GitLab isn't the better one here), I'd be much much more comfortable
using that as a login service over something like google or facebook, as
any developer or curator will pretty much by definition have to have an
account already, which will hopefully cause less disruption in the long
run. Eventually, when github (or gitlab) goes the way of sourceforge, we
can lump the login transition in with the repo transition.

I don't think running our own persona server or being our own openid
provider are good solutions.

Chris, if you're still looking at breakaway projects over the next year,
this might be something that could be done fairly quickly.

**Comment by kltm** [comment]
To specify this a bit more, we're looking for a new *authentication* system, one that should return the user's email address for further authorization steps against users.yaml. This will allow for continued easy federation and expansion, as well as (hopefully) cause less churn.

It would be good for all of our services (i.e. TermGenie and Barista) to use the same centralized service for this, rather than re-implementing it for each one in a separate language. Think of it as a persona-like system backed by another provider like GitHub (or whatever).

**Comment by stuartmiyasato** [comment]
Not directly related, but our ENCODE project is running into the same issue.  Some ideas are being bounced around, like this one from our ticket where this is being discussed:

>Another option would be to implement shibboleth authentication as it is supported by most >universities: http://www.incommon.org/federation/info/all-entities.html. More info: >https://uit.stanford.edu/service/shibboleth
>
>UChicago is working on a Shibboleth/OpenID connect bridge: https://github.com/uchicago/shibboleth-oidc

I don't know if shibboleth would fit our needs, but I thought I'd bring it up anyway.  I'll keep an eye on both issues and see if there's anything to contribute between the two threads.

**Comment by kltm** [comment]
Most excellent--thank you!

It looks like it might be hard to get people incorporated who have no association with a participating academic institute, at least from what I've read so far. (I actually thought shibboleth was something else, but apparently this is a new and/or different effort).

My ideal solution is something *extremely* lightweight, preferably around something like an email address, but as minimally integrated as possible. A lot of solutions are heavy (OpenID), fractured (again, OpenID), overly integrated (Facebook, etc.), or designed to tie into things like LDAP or further authorization controls. Our setup is trying to be very loose and light--prove the person is who they say and return an identifying token (currently email address); after that, it's up to the configs and apps.

**Comment by kltm** [comment]
A fair thread on ycombinator on this news: https://news.ycombinator.com/item?id=10884893 , showing various levels of support and possibilities for migration.

**Comment by DoctorBud** [comment]
Why not adopt OrcID and their Oauth as a default? I just got an OrcID id so I could have a URI for the users.yaml file for Monarchtua. Seems like lots of the Monarch clientele are into OrcID.

- https://github.com/ORCID/ORCID-Source
- (requires login to OrcID) http://members.orcid.org/api/explore-orcid-api-google-oauth-playground

**Comment by kltm** [comment]
It's something to keep in mind, and maybe explore later on. There is still plenty of time and while I've have some good experiences with OAuth I can't say the same for what I've done with the OAuth2 flavors I've worked with. I'd like to see what develops at the light and decentralized end of the spectrum a little bit before committing.

**Comment by DoctorBud** [comment]
[OpenVivo](http://openvivo.org) seems to be a slick way to use OrcID for login. I'd be happy with copying whatever they are doing.

Another option is [Auth0](https://auth0.com/), which is a commercial entity but has a provision for free access for open source projects: https://auth0.com/pricing.

In any case, we want to abstract any login and identity mechanism so that we are bound to a particular vendor and so that our software is more easily integrated with existing auth mechanisms that a developer/deployer of our code might face.

**Comment by kltm** [comment]
More specific stuff is being held here right now: https://github.com/geneontology/noctua/issues/270
I think the Auth0 is a non-starter. I think a more general abstraction is good, but OAuth2 with identifier on return to barista is fine.

**Comment by tberardini** [comment]
Moving discussion about TG login via persona here from /noctua/270.

"...TG as it is now will be pretty much toast--it will function "fine", but no longer have a method for logging in."

@cmungall : we're gonna need TG to be functional  past 11/30/16, don't you think?

**Comment by tberardini** [comment]
Can we use ORCIDs for login/authentication for TG? (like suggested in https://github.com/geneontology/noctua/issues/270 ?)

**Comment by kltm** [comment]
Any change will require coding changes to TG, so there is no easy out.

While we were looking at ORCID, and will probably still implement it at some point, the ToS for using their API is not very good from a developer/software point of view (single client_id per user account, etc.), so we decided to punt for a bit. However, I'm only actively looking at things for Barista right now. My understanding is that TG will be twilighted in favor of the pattern templates. Again, @cmungall will have more details.

**Comment by tberardini** [comment]
"...TG will be twilighted in favor of the pattern templates"

@cmungall : Ok, so this sounds like something that would be nice to discuss during the editor's meeting :).

**Comment by kltm** [comment]
TG is EOL, so that leaves Noctua here, which already has a mentioned ticket.
