### ISSUE TITLE
Links to RGD not working

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1502]
Hi @kltm 

The URL syntax in the yaml file for RGD was incorrect (its' missing `term=`). 

I now updated it 
https://github.com/geneontology/go-site/pull/1501/commits/ed7f947187a74cb6c005bd9a4b99f88c7cdfa231

What do I need to do so that this gets updated in the code ? 

Thanks, Pascale

**Comment by lpalbou** [comment]
If you were aiming at correcting amigo links, my guess is this won't have an effect because of  https://github.com/geneontology/amigo/issues/599.

Simple fix: sync both files; better fix: remove amigo/db-xrefs.yaml and only use go-site/db-xrefs.yaml.

**Comment by kltm** [comment]
@pgaudet Updated with https://github.com/geneontology/go-site/commit/3a2f5055562c97e7a0b1e03379ff7c4532377faf#diff-20c49b5866419d3b2e72f80936960031 ; is this working for you now?

**Comment by pgaudet** [comment]
yes, thanks!
