### ISSUE TITLE
Update gorule-0000006 to exclude annotations with source = GOC

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1519]
Hello, 

As stated, gorule-0000006 is creating false positives for interontology links derived from BP. 

We would like to change the rule so that any aspect is allowed with IEP/HEP annotations when assigned by =GOC. 

Thanks, Pascale

**Comment by kltm** [comment]
Doc PR https://github.com/geneontology/go-site/pull/1520

**Comment by kltm** [comment]
To clarify, when you mean "false positive", you referring to the on line here?
http://snapshot.geneontology.org/reports/tair-report.html#gorule-0000006

**Comment by pgaudet** [comment]
For example GO:0005623 (obsolete cell ;)
yes, this should not be reported anymore.

**Comment by kltm** [comment]
@pgaudet Are there any other examples of this?

**Comment by pgaudet** [comment]
In snapshot there is still a TAIR annotation that is a false negative for this error: 

ERROR - Violates GO Rule: GORULE:0000006: IEP and HEP usage is restricted to terms from the Biological Process ontology -- TAIR locus:2092221 STP10 GO:0005623 TAIR:Publication:501768255|PMID:26893494 IEP C AT3G19940 AT3G19940|STP10|SUGAR TRANSPORT PROTEIN 10|MPN9.18 protein taxon:3702 20160301 GOC TAIR:locus:2092221

but GO:0005623 is obsolete so this is filter via the gorule-0000001 parser (I think). 

Is that what you were asking ?

**Comment by kltm** [comment]
@pgaudet Apologies, I should have brought this up today.
The question we were asking (as part of clarifying this issue): are there any examples of this *besides* the single one from TAIR.

**Comment by pgaudet** [comment]
I dont think so

**Comment by pgaudet** [comment]
The problem here is interontology kinks keep the same evidence code (AFAIK). The best solution may be to change that behavior.

**Comment by mugitty** [comment]
Modify rule definition to:
The IEP and its high throughput equivalent, HEP, evidence codes are used where process involvement is inferred from
the timing or location of expression of a gene, particularly when
comparing a gene that is not yet characterized with the timing or
location of expression of genes known to be involved in a particular
process. This type of annotation is only suitable with terms from the
Biological Process ontology, except when the annotation comes from an inter ontology link, in which case all GO aspects are allowed.

For GAF
IF Col 6 = IEP or HEP, and Assigned_by (Col 15) GOC, then - > OK 

ELSE if Aspect (Col 9) = BP -> OK  
ELSE  error = wrong GO aspect for evidence

ELSE if assigned by is NOT GOC , check Aspect (Col 9) = IF col 9 = BP -> OK  
ELSE  error = wrong GO aspect for evidence

Implement similar rule for GPAD (column 10 and get aspect from goid)

**Comment by mugitty** [comment]
@pgaudet , we can simplify
IF evidence code (col 7) = IEP or HEP, and Assigned_by (Col 15) GOC, then - > OK
ELSE IF evidence code (col 7) = IEP or HEP, and Aspect (col 9) NOT BP -> error wrong GO aspect for evidence
ELSE -> OK

**Comment by pgaudet** [comment]
Pascale to add some tests to check that there is an exception for annotations assigned by GOC.

**Comment by pgaudet** [comment]
Added 
! FAILS GORULE:0000006 - passes because uses assigned_by is GOC, even if there is an IEP with a molecular function term.
GeneDB	PF3D7_0507500	SUB1	enables	GO:0004672	PMID:12764150	IEP		F	GORULE:0000006-4 subtilisin-like	protease 1	gene	NCBITaxon:36329	20090624	GOC

Now we need to check that we dont get an error for this line

**Comment by pgaudet** [comment]
Check at the next release

**Comment by pgaudet** [comment]
I will make a new test for this
