### ISSUE TITLE
EMAPA not resolving correctly in AmiGO, issue with data in db-xrefs.yaml

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#152]
From @ukemi:

```
> The anatomy links in AmiGO2 are not resolving correctly to EMAPA. I think
> I made a mistake in the url_syntax line in the YAML file should contain
> the ŒEMAPA:'
> 
> It should be this:
> url_syntax:"http://www.informatics.jax.org/vocab/gxd/anatomy/EMAPA:[example
> _id]"
> 
> Instead of this:
> url_syntax:"http://www.informatics.jax.org/vocab/gxd/anatomy/[example_id]"
> 
> 
> Can either of you tell me if this will work and then make it happen if it
> is ok?
```

**Comment by kltm** [comment]
@ukemi Can you confirm that the data looks correct in the file? It appears that what you want is already the most current version.
https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml#L645

@stuartmiyasato Would you be able to confirm that you have the latest version of the file pulled in production? It would likely involve the "install" step to make sure that the data was refreshed.

**Comment by stuartmiyasato** [comment]
@kltm, I don't see the db-xrefs.yaml file listed anywhere.  Where would this reference be located?

**Comment by kltm** [comment]
@stuartmiyasato Sorry, I had the names wrong there--holdover from the old amigo, the old make_dblinks.pl code.
```
System: "chmod 644 /home/sjcarbon/local/src/git/amigo/perl/bin/xrefs.json"
Created GO XRefs JSON data file: "/home/sjcarbon/local/src/git/amigo/perl/bin/xrefs.json".
```
In "install" (gulp install), the remote file should be grabbed and the javascript/lib/amigo/data/xrefs.js created--the source of data for the display (the created JSON file should supply the same information to the server perl).

Unfortunately, because of these transformations, there is no direct way of comparing files. However, we have: http://amigo.geneontology.org/xrefs , which gives: http://www.informatics.jax.org/vocab/gxd/anatomy/EMAPA:16894 . So no issues there.

So an example for this issue is:
http://amigo.geneontology.org/amigo/search/annotation?q=Birc6*&fq=source:%22MGI%22&fq=annotation_extension_class_closure_label:%22anatomical%20structure%22&sfq=document_category:%22annotation%22

Ugh, it looks like that's in the annotation extension blob, which means that the issue probably traces back to the owltools loader only giving possibly part of the ID? @hdietze or @cmungall , any thought on that?

**Comment by ukemi** [comment]
Hi Seth,

Looking at what is resolving, I am pretty sure the line in the YAML file above needs to have the "EMAPA:" like this:

url_syntax: "http://www.informatics.jax.org/vocab/gxd/anatomy/EMAPA:[example_id]"

The line as it reads now is this:

url_syntax: "http://www.informatics.jax.org/vocab/gxd/anatomy/[example_id]"

**Comment by stuartmiyasato** [comment]
@kltm Sorry, I'm still unclear on this -- is there an action item for me at this point?  Thanks.

**Comment by cmungall** [comment]
@ukemi correct

As is unfortunately often the case this stems from a confusion over what 'id' means. The format predates clarification here http://wiki.geneontology.org/index.php/Identifiers

The thing is square brackets is actually the LocalID

**Comment by kltm** [comment]
@cmungall yes, sorry, I always do that when I see them out of context.

**Comment by kltm** [comment]
@ukemi The fix is now in the repo.

@stuartmiyasato Could you re-run "gulp install" (or whatever your re-installation script is) on the production machines at some point to pick up the file change?

**Comment by kltm** [comment]
BTW, confirmed that it works here:
http://nakama.berkeleybop.org/amigo/search/annotation?q=Birc6*&fq=source:%22MGI%22&fq=annotation_extension_class_closure_label:%22anatomical%20structure%22&sfq=document_category:%22annotation%22

**Comment by stuartmiyasato** [comment]
@kltm I ran "gulp install" on the production machines and that seems to have fixed the problem.  The link seems to work fine at http://amigo.geneontology.org/amigo/search/annotation?q=Birc6*&fq=source:%22MGI%22&fq=annotation_extension_class_closure_label:%22anatomical%20structure%22&sfq=document_category:%22annotation%22

**Comment by kltm** [comment]
@stuartmiyasato Great, thank you. After a couple of refreshes, I was picking up the new link. I think that closes the issue then.
