### ISSUE TITLE
Add option to suppress PAINT IBA filtering in Makefile-gaf-reprocess

### ISSUE THREAD

**Issue by dustine32** [geneontology/go-site#1531]
I noticed on snapshot that goa_uniprot_all.gaf is the only GAF file containing IBAs, and that's likely because we specifically skip running it through the new post-filter step. My current theory is that the standard GAF parser code used in the post-filter step, by default, removes all IBAs from GAFs unless an option (--paint=True) is set to disable that.

A quick test to check this, I ran `paint_mgi.gaf` through `ontobio-parse-assocs.py`:
```
ontobio-parse-assocs.py -f paint_gafs/paint_mgi.gaf -F gaf -o paint_filtered/paint_mgi.gaf -I all.gaferences.json --report-md paint_reports/report.md --report-json paint_reports/report.json convert --to gaf
```
And the output `paint_filtered/paint_mgi.gaf` file had zero annotations. Then after setting the `paint=True` option on the `AssocParserConfig` in `ontobio-parse-assocs.py` and rerunning:
```
config = assocparser.AssocParserConfig(
        valid_taxa=args.taxon,
        ontology=ont,
        class_idspaces=args.object_prefix,
        entity_idspaces=args.subject_prefix,
        filter_out_evidence=args.filter_out,
        filtered_evidence_file=filtered_evidence_file,
        annotation_inferences=gaferences,
        paint=True
    )
```
The annotation lines were in the output GAF.

To fix, we'll need to add code to both go-site (Makefile-gaf-reprocess) and ontobio (ontobio-parse-assocs.py) repos to disable automatic IBA filtering in the GAF parser.

Tagging @kltm @dougli1sqrd

**Comment by kltm** [comment]
@dustine32 @dougli1sqrd Looking at https://build.geneontology.org/job/geneontology/job/pipeline/job/master/584/execution/node/563/log/ , it seems like the IBAs are still missing (see annotations/ on skyhook)? Can it be confirmed that go-site is at the correct ontobio version and that pipeline `master` is running with the right command? If it is, wouldn't one expect to see the paint_wb files folded in there? I think that wb is not being excluded...

**Comment by dustine32** [comment]
@kltm If I'm looking at this right, pipeline `master` is currently looking at `stats-update` branch of `go-site`?
https://github.com/geneontology/pipeline/blob/c36a6a91bdb9b27ce8fe415409efa933b778d9b7/Jenkinsfile#L34

And that branch is 16 days behind go-site master and so wouldn't have the `go-site` code with the new `--allow_paint` option:
https://github.com/geneontology/go-site/blob/87b9054fc25f953b459c17a9109639760abd7325/scripts/Makefile-gaf-reprocess#L24-L26

I think to get the changes either branch `go-site/stats-update` would have to merge in the updated `master` branch, or `pipeline/master` Jenkinsfile should point to `go-site/master`.

**Comment by kltm** [comment]
@dustine32 Gah, of course.  Thank you--I'll get that back up to date with master.

**Comment by dustine32** [comment]
This looks like it's been done for a while.
