### ISSUE TITLE
E. coli GAF ready to submit

### ISSUE THREAD

**Issue by dsiegele** [geneontology/go-site#1535]
I have the E. coli GAF ready to submit, but haven't done it before. Please let me know what to do.

Thank you!

Debby

**Comment by pgaudet** [comment]
Hi @dsiegele 

According to the previous version of yaml file concerning EcoCyc data (https://github.com/geneontology/go-site/blob/master/metadata/datasets/ecocyc.yaml), we expect the GAF to be located at: https://ecoliwiki.org/gaf/gene_association.ecocyc.gz

You can change the location of the file if you want. Each time you generate a new file, you save it at the same place. We pick it up every day for the snapshot version of the release, and monthly this becomes the 'official' release. 

I hope this is clear. 

Thanks, Pascale

**Comment by dsiegele** [comment]
I need to have permissions changed so I can upload the new file. I've contacted our IT administrator about making the change. Hopefully, I will be able to upload the new file today or tomorrow. 

Debby

**Comment by kltm** [comment]
@dsiegele 
Just noting your comment here https://github.com/geneontology/go-site/commit/8713f7686fb727fa8cf2e22b8ca8f647b1baf7ef

Just to confirm, the updated annotations are now at the previous location at https://ecoliwiki.org/gaf/gene_association.ecocyc.gz ? If so, our action will be revert to previous state and we'll be able to get the update annotations.

Tagging @pgaudet ; we can go ahead and make those changes easily; do you want to wait for the next release for this?
Cross-reference with https://github.com/geneontology/go-site/issues/1426

**Comment by pgaudet** [comment]
I updated the source. I think it's OK to have the new data in the upcoming release. 

Thanks, Pascale
