### ISSUE TITLE
PAINT file missing about half of NCBITaxon:9258|Ornithorhynchus anatinus data

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1542]
Hi @kltm 

The stats for the release candidate show that PAINT provided 27531 fewer annotations for NCBITaxon:9258|Ornithorhynchus anatinus than in the previrous (=current) release (34752 compared to 62283 in the current release). 

We seem to have valid IDs missing (at least from AmiGO staging), for eg `F6Y5V1`, belonging to PTHR36983. 

Not sure if the problem is at the source or in the processing of the data; can you please check ? (It's present in PAINT)

@dustine32  @huaiyumi 

Thanks, Pascale

**Comment by dustine32** [comment]
@pgaudet  Thanks for pointing this out!
> the problem is at the source

...is what I'm seeing currently:
```
$ cut -f13 gene_association.paint_other.gaf.20200630 | grep "taxon:9258" | wc -l
   61974
$ cut -f13 gene_association.paint_other.gaf.20200729 | grep "taxon:9258" | wc -l
   34422
```

To be clear, this means the difference is on the PAINT side. Last month's release we looked at the numbers specifically for macaque (taxon:9544) and its drop ended up very closely corresponding with the dropped gene entity IDs being obsoleted at UniProt. I'll run this same analysis on taxon:9258 to see if this is the same case.

**Comment by dustine32** [comment]
Oh fun, this is platypus.

> its drop ended up very closely corresponding with the dropped gene entity IDs being obsoleted at UniProt

So this also looks to be what's going on for platypus (NCBITaxon:9258):
1. Get list of taxon:9258 UniProt IDs in previous IBA release (2020-06-30) that are not in new IBA release (2020-07-29): **6175**
2. Check how many of these dropped IDs are not in the [UniProt GPI file](ftp://ftp.ebi.ac.uk/pub/contrib/goa/uniprot_protein.gpi.gz) that [PAINT uses for filtering obsolete IDs](https://github.com/pantherdb/fullgo_paint_update/issues/46): **6166**

Meaning that all but 9 of these IDs were removed in the latest UniProt GPI. Here are those nine:
```
F6PX39
F6QKJ9
F6QME1
F6T9M7
F6V3S6
F6ZXU1
F7CT41
F7EWD3
P30805
```
And here are a few of the 6k+ UniProt IDs dropped for platypus:
```
F7DZD4
K7EAG6
K7EIB3
```
However, this does still indicate a huge drop in entities for taxon:9258 from a PAINT perspective. From 13487 IBA entities on 2020-06-30 down to 7438 on 2020-07-29. But, comparing the two versions of the UniProt GPI used in the two releases, the numbers for taxon:9258 actually increased from 28945 in June to 38110 in July.

**Comment by pgaudet** [comment]
@dustine32 

The example ID I gave in the initial comment, `F6Y5V1`, was a non-obsolete entry. 

I am not sure what your conclusion is; do you think the data is OK ? I am concerned to produce fluctuating data across various releases. 

Thanks, Pascale

**Comment by dustine32** [comment]
@pgaudet Sorry, you're right, I kinda ended my last comment abruptly without concluding. I do think the PAINT data is OK in that it's filtering correctly.

@alexsign has [said before](https://github.com/pantherdb/fullgo_paint_update/issues/46#issuecomment-632648869) that this UniProt GPI is sort of a pre-release so some obsoleted IDs may be valid on the website (e.g. `F6Y5V1`). But maybe we should check with @alexsign about whether a large ID "shift" occurred for platypus and was expected? The total count of taxon:9258 IDs increased this month but half of PAINT-used IDs are now obsolete.

**Comment by pgaudet** [comment]
OK, @alexsign confirmed that `F6Y5V1`will be obsoleted at the upcoming UniProt release. 

Thanks for checking !
