### ISSUE TITLE
Create a static landing page for SPARQL endpoint

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#1549]
I would like to have a single canonical URL for all things SPARQL endpoint in the GO. I think we should use this URL in the NAR paper.

Perfection is the enemy of the good: The first iteration of the page can be a static collection of links and (brief) high level textual summary. We can make it fancier over time.

For the URL, one possibility is to use
http://rdf.geneontology.org/

However, this is to a generic blazegraph front page. I would like to have this be more user friendly.

I don't know if there is a way to customize this, or if we could have the top level proxypass to a static page (seems awkward), or if we should just have a page on the main GO site; e.g http://geneontology.org/docs/sparql

cc @balhoff @lpalbou @kltm @goodb @dougli1sqrd

**Comment by balhoff** [comment]
It's getting redirected down to http://rdf.geneontology.org/blazegraph/, so I think it would be fine to instead go to a separate static page at http://rdf.geneontology.org/.

We may want to add a proxy directly over the SPARQL service endpoint (`http://rdf.geneontology.org/blazegraph/sparql`) in case we change away from Blazegraph at some point. Could just be `http://rdf.geneontology.org/sparql`.

**Comment by kltm** [comment]
From a conversation elsewhere: if this is considered documentation/driven from metadata, I think it probably belongs within the main site, so http://geneontology.org/docs/sparql --this would be the location then for example queries, links and info on the actual endpoint, etc. I also agree with @balhoff that we might want to paper over the blazegraph bit at rdf.go.org as well.

**Comment by kltm** [comment]
Looking at notes and touching bases with @cmungall (let me know if I got something wrong here), I think the current temporary work we want to have done to support the NAR paper is:

* have http://geneontology.org/docs/sparql contain documentation, such as short explanation, location for blazegraph (using current sub-optimal http://sparql.geneontology.org/blazegraph/#query, etc. for now), examples for the SPARQL endpoint, etc.
* temp redirect root-only requests to http://sparql.geneontology.org over to http://geneontology.org/docs/sparql 

Further work in a TBD project.

**Comment by pgaudet** [comment]
Is this already implemented ? I get a 404 error for http://geneontology.org/docs/sparql 
as well as http://geneontology.org/docs/sparql

Thanks, Pascale

**Comment by kltm** [comment]
I believe that @lpalbou will be looking after that.

**Comment by lpalbou** [comment]
@pgaudet you cited the same URL twice. For http://geneontology.org/docs/sparql, I just merged the SPARQL doc page: https://github.com/geneontology/geneontology.github.io/pull/261 . I suppose the second URL you were referring to is http://sparql.geneontology.org/ and it's working, but I will have to push another code to GO-ify the look and feel.

**Comment by lpalbou** [comment]
The documentation page was created (http://geneontology.org/docs/sparql) and here is the ticket to follow the integration/deployment of the UI page for sparql.geneontology.org: https://github.com/geneontology/geneontology.github.io/issues/267.

**Comment by lpalbou** [comment]
Close in favor of two more precise tickets:
* GO SPARQL page: https://github.com/geneontology/geneontology.github.io/issues/267
* GO SPARQL doc page: https://github.com/geneontology/geneontology.github.io/issues/269
