### ISSUE TITLE
gorule-0000057 filter lines by provided_by

### ISSUE THREAD

**Issue by dustine32** [geneontology/go-site#1553]
For the MOD imports project, one requirement is that we filter the MOD GPAD to keep only lines where the Provided_by column (aka Assigned_by) equals the MOD. So only Provided_by=MGI in `mgi.gpad` or Provided_by=WB in `wb.gpad`. Provided_by=UniProt lines would be filtered out. 
```
GOOD: MGI     MGI:1920971     enables GO:0043014      MGI:MGI:3794006|PMID:18163442   ECO:0000314                     20081211        MGI
BAD: MGI     MGI:1920971     part_of GO:0002177      MGI:MGI:3794006|PMID:18163442   ECO:0000314                     20120221        UniProt
```
We can handle this by expanding on the `filter_out` pattern currently existing in the `mgi.yaml` and `wb.yaml` dataset files by adding a separate `filter_for` or `filter_in` (maybe `required_attributes`?) section:
```
filter_for:
  provided_by:
    - MGI
```
Accepting a list of `provided_by` values will allow flexibility if we later want to start importing some other non-MOD-source lines like UniProt. I'll update the [datasets.schema.yaml](https://github.com/geneontology/go-site/blob/master/metadata/datasets.schema.yaml), [mgi.yaml](https://github.com/geneontology/go-site/blob/master/metadata/datasets/mgi.yaml) and [wb.yaml](https://github.com/geneontology/go-site/blob/master/metadata/datasets/wb.yaml) files in a test branch.

Tagging @dougli1sqrd @kltm

**Comment by dustine32** [comment]
@ukemi Yeah, upstream filtering would be a sure way of handling this. I just automatically started porting over the pre-existing filtering functionality from `gocamgen` but we can use it as needed.

**Comment by pgaudet** [comment]
I agree with the upstream filtering, otherwise we need to restrict how Rule57 is applied, that seems to just move the problem elsewhere.

**Comment by pgaudet** [comment]
Hi @dustine32 To make it easier (or even just possible) to find any references to rule, we've been rigorous about the format in tickets, please use gorule-nnnnnnn.


Thanks, Pascale

**Comment by ukemi** [comment]
OK. @dustine32, we will create a GPAD2.0 file that only contains the annotations made by MGI curators using the MGI editorial interface. We will put it out on the test site for you.

**Comment by dustine32** [comment]
Thanks @pgaudet for correcting the title!

@ukemi Yes, having the file already filtered at its upstream location would definitely do the job. I can start translating that GPAD2.0 file once we get the ontobio GPAD parser to consume 2.0 in a short while.

**Comment by pgaudet** [comment]
Hi @dustine32 

What is the stats of this? I suppose some version of this in done in the pipeline, but is not documented here: https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000057.md

**Comment by pgaudet** [comment]
I think this specifically applies to imports and should not be part of ontobio?

**Comment by pgaudet** [comment]
Hi @dustine32 

Is this specifically applying to imports, and how is this triggered? 

Thanks, Pascale

**Comment by dustine32** [comment]
@pgaudet Yep, this was proposed for the imports project but not needed. I'll close but feel free to reopen.

**Comment by pgaudet** [comment]
Thanks, we'll just make sure to remove it from the reports (not sure why it's even coming up)

**Comment by kltm** [comment]
There is a reports filter list (variable in the pipeline), if something needs to be disappeared.
