### ISSUE TITLE
GCRP files

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-site#156]
Following discussions with the GO Consortium, we are planning to make some changes to the set of species-specific annotation files that we publish.

For each of the following species, we currently publish two sets of annotations, one based on the UniProt complete proteome, and one based on the UniProt reference proteome:

human chicken cow pig dog mouse rat arabidopsis zebrafish worm yeast fly dicty

We intend to cease production of the current goa_ and goa_ref_ files, and replace them with the following four annotation sets, which we will provide in both GAF and GPAD format (note that the names of the files are as yet undecided):
1. annotations to canonical accessions from the UniProt reference proteome
2. annotations to isoforms from the UniProt reference proteome
3. annotations to complexes
4. annotations to RNAs

Note that annotations to proteins that are not part of the UniProt reference proteome for a species will still be available in the full goa_uniprot annotation set.

Note also that this change will not be implemented before the GOA release that is scheduled for the week of March 14th 2016.

Comments on this proposal should be sent to goa@ebi.ac.uk

**Comment by pgaudet** [comment]
This has been implemented a while ago.
