### ISSUE TITLE
Testing GAF 2.2 files

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-site#1562]
This ticket is being created to facilitate the first round of GAF2.2 file ingest and testing.

Source files for testing are:

**MGI**

http://www.informatics.jax.org/downloads/custom/gene_association.mgi2

**WB**

ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/annotation/go_annotations/c_elegans.canonical_bioproject.current_development.go_annotations.gaf.gz

@dougli1sqrd @kltm -- Note that the WB file above is still using CURIEs for the gp2term relations.  The corrected file that uses a text string for gp2term relations should be synced to the ftp site next week.

**Comment by kltm** [comment]
I may edit this, but a simple GAF 2.2 -> GAF 2.1 converter.

CLI:
```bash
cat new.gaf | perl -lane 'if( /^!gaf-version: 2.1/ ){ print "!gaf-version: 2.2"; }elsif( /^!/ ){ print; }else{ @col = split("\t"); $col[3] =~ s/enables|involved_in|located_in|part_of|acts_upstream_of_positive_effect|is_active_in|acts_upstream_of_negative_effect|acts_upstream_of_or_within_positive_effect|acts_upstream_of_or_within_negative_effect|acts_upstream_of_or_within|acts_upstream_of//; print join("\t", @col); }' > old.gaf
```
Perl code:
```perl
if( /^!gaf-version: 2.1/ ){
   print "!gaf-version: 2.2";
}elsif( /^!/ ){
   print;
}else{
   @col = split("\t"); $col[3] =~ s/enables|involved_in|located_in|part_of|acts_upstream_of_positive_effect|is_active_in|acts_upstream_of_negative_effect|acts_upstream_of_or_within_positive_effect|acts_upstream_of_or_within_negative_effect|acts_upstream_of_or_within|acts_upstream_of//;
   print join("\t", @col);
}
```

**Comment by kltm** [comment]
@vanaukenk Does https://gist.github.com/kltm/a0c6006df46d14f1155848fa8edc2543 look like the correct down-conversion for your file?

**Comment by pgaudet** [comment]
Where are we going to put this ? The wiki is probably the right place? Maybe also in a README of the appropriate repo?

**Comment by ukemi** [comment]
Note that this mouse file is filtered to only contain annotations that are generated by MGI curators. It is the parallel file to the one @dustine32 will use for the imports. If you'd like, we can create a complete file as well. ping @loricorbani.

**Comment by vanaukenk** [comment]
@kltm - the down-versioned file is for MGI, but I took a look, anyway :-)

I see lines like this:  

MGI	MGI:1929608	Aatf	causally_upstream_of	GO:0007155	MGI:MGI:1927250|PMID:11071758	IMP	MGI:MGI:2176283	P	apoptosis antagonizing transcription factor	4933415H02Rik|5830465M17Rik|Che-1|Trb	protein	taxon:10090	2002-07-26	MGI	occurs_in(EMAPA:16040)

that don't look right because the original gp2term relation in the source file is not allowed, i.e. perhaps this should be 'acts upstream of'?

@ukemi - what do you think?

Also, @kltm - should the header in the down-version file say gaf 2.1?

**Comment by ukemi** [comment]
That is an error on our side where a curator (me) picked the wrong qualifier. Fixed now.

**Comment by kltm** [comment]
@vanaukenk Whoops, sorry--I managed to totally not register that there were two file.

Thank you for taking a look anyways. `causally_upstream_of` is illegal even for GAF 2.2, so I'm tempted to just go with "bad data, bad results". We can make the "converter" more robust, but we should probably just build it in to ontobio at that point.
Good catch with the version, switched in example code aboe.

Okay, now that you've had the appetizer (apologies again), here's the WB GAF 2.2 down-converted to 2.1: https://gist.github.com/kltm/c5aba7c2b7729059e8e2195fb0877f83

**Comment by ukemi** [comment]
My guess is that if you are seeing these errors, they are ones that have been manually curated.

**Comment by vanaukenk** [comment]
@kltm 
The WB file won't be converted according to your code above, because the source file still has CURIES for the relations column rather than text.
Our new, corrected file is waiting to be synced to the ftp site, but that likely won't happen until next week.
Otherwise, I don't see anything wrong with the down-converted WB file.
Thx.

**Comment by ukemi** [comment]
@kltm. I gave a quick scan of the mgi file and it looks pretty good on a fast pass. I will look more in depth on Monday.

**Comment by kltm** [comment]
@ukemi The new code should fix that, so no worries there.

@vanaukenk Okay, we can take another look then. For the code though, I think it's probably enough to give developers a flavor of what they need to do, and a place to start if they want. If we want to have a full-blown tool, we should probably start have additional stuff in ontobio (I'll check with @dougli1sqrd, maybe that will be in place or already is).

**Comment by kltm** [comment]
(Talking to @dougli1sqrd , there is the ability to degrade GAF 2.2 -> 2.1)

**Comment by dougli1sqrd** [comment]
Ontobio can convert a gaf with `gaf-version: 2.2` header into 2.1 using the `ontobio-parse-assocs.py` script.

First install ontobio (ideally into a virtual environment)
```
$ python3 -m venv env
$ source env/bin/activate
(env) $ pip install ontobio
```
You should now have access to the `ontobio-parse-assocs` script.

Given a source gaf 2.2 file: `source.gaf`, and output file `parsed.gaf`
```
ontobio-parse-assocs.py -r go-ontology.json -f source.gaf -F gaf -o parsed.gaf --report-md report.md 
```
This will produce a gaf 2.1 file, `parsed.gaf`, as well as a report, `report.md`. The ontology, `go-ontology.json` is in the obo json format, but is not strictly needed (but recommended).

**Comment by kltm** [comment]
Gist from @vanaukenk for latest iteration of GAF 2.2 test
https://gist.github.com/kltm/ef785ee4ce5253d92b8720e4cd2d8906

Preview:
```
!gaf-version: 2.2
!generated-by: WormBase
!date-generated: 2020-10-29
WB	WBGene00000001	aap-1	part_of	GO:0005942	WB_REF:WBPaper00046480|PMID:21873635	IBA	MGI:MGI:109277|PANTHER:PTN000806614|RGD:3329|UniProtKB:P23727|WB:WBGene00000001	C		Y110A7A.10	gene	taxon:6239	20170228	GO_Central		
WB	WBGene00000001	aap-1	located_in	GO:0005634	WB_REF:WBPaper00005614|PMID:12393910	IDA		C		Y110A7A.10	gene	taxon:6239	20151214	WB		
WB	WBGene00000001	aap-1	colocalizes_with	GO:0005759	WB_REF:WBPaper00046480|PMID:21873635	IBA	FLYBASE:FBgn0020622|MGI:MGI:109277|MGI:MGI:1098772|MGI:MGI:97583|PANTHER:PTN000016388|RGD:3329|UniProtKB:P23727|WB:WBGene00000001	C		Y110A7A.10	gene	taxon:6239	20170228	GO_Central
WB	WBGene00000001	aap-1	involved_in	GO:0008286	WB_REF:WBPaper00005614|PMID:12393910	IGI	WB:WBGene00000090	P		Y110A7A.10	gene	taxon:6239	20151214	WB		
WB	WBGene00000001	aap-1	acts_upstream_of	GO:0008286	WB_REF:WBPaper00005614|PMID:12393910	IGI	WB:WBGene00000898	P		Y110A7A.10	gene	taxon:6239	20151214	WB		
WB	WBGene00000001	aap-1	acts_upstream_of_positive_effect	GO:0008286	WB_REF:WBPaper00005614|PMID:12393910	IMP		P		Y110A7A.10	gene	taxon:6239	20060302	WB		
WB	WBGene00000001	aap-1	acts_upstream_of_negative_effect	GO:0008340	WB_REF:WBPaper00005614|PMID:12393910	IMP		P		Y110A7A.10	gene	taxon:6239	20060302	WB				
WB	WBGene00000001	aap-1	acts_upstream_of_or_within	GO:0016310	GO_REF:0000043	IEA	UniProtKB-KW:KW-0418	P		Y110A7A.10	gene	taxon:6239	20200620	UniProt		
WB	WBGene00000001	aap-1	acts_upstream_of_or_within_positive_effect	GO:0040024	WB_REF:WBPaper00005614|PMID:12393910	IGI	WB:WBGene00000090	P		Y110A7A.10	gene	taxon:6239	20151214	WB		
WB	WBGene00000001	aap-1	acts_upstream_of_or_within_negative_effect	GO:0040024	WB_REF:WBPaper00005614|PMID:12393910	IGI	WB:WBGene00000898	P		Y110A7A.10	gene	taxon:6239	20151214	WB		
WB	WBGene00000001	aap-1	involved_in	GO:0008150	GO_REF:0000015	ND		P		Y110A7A.10	gene	taxon:6239	20060302	WB		
WB	WBGene00000002	aat-1	enables	GO:0003674	GO_REF:0000015	ND		F		F27C8.1	gene	taxon:6239	20131022	WB		
WB	WBGene00000002	aat-1	contributes_to	GO:0015179	WB_REF:WBPaper00006408|PMID:14668347	IDA		F		F27C8.1	gene	taxon:6239	20131022	WB		
WB	WBGene00000004	aat-3	is_active_in	GO:0005575	GO_REF:0000015	ND		C		F52H2.2	gene	taxon:6239	20131022	WB		
WB	WBGene00000007	aat-6	enables	GO:0022857	GO_REF:0000002	IEA	InterPro:IPR002293	F		T11F9.4	gene	taxon:6239	20200914	InterPro		
WB	WBGene00000004	aat-3	is_active_in	GO:0031012	WB_REF:WBPaper00006408|PMID:14668347	IDA		C		F52H2.2	gene	taxon:6239	20150730	WB		
```

**Comment by kltm** [comment]
@dougli1sqrd @dustine32 Would it be possible to just run this file through ontobio enough to get a report and output?

**Comment by kltm** [comment]
@dougli1sqrd @dustine32 For that matter, would it be possible to add instructions for running individual (GAF 2.2) files here so that people can test their files locally?
Re: https://github.com/geneontology/go-annotation/issues/2917#issuecomment-722985309

**Comment by dougli1sqrd** [comment]
@kltm The command to see how ontobio handles gaf 2.2 as input is in the above comment (https://github.com/geneontology/go-site/issues/1562#issuecomment-707941676). Using `ontobio-parse-assocs.py` will run a gaf 2.2 through as much of the standard ontobio run as is possible in a stand alone setting. Some rules and checks that use various metadata files in go-site will not be run as those resources won't exist in this type of run. Typically, though, those won't change between 2.1 and 2.2.

**Comment by kltm** [comment]
@dougli1sqrd Ah yeah. How would one get the report JSON out of that?

**Comment by dougli1sqrd** [comment]
if you pass in `--report-json path/to/drop/report.json` instead of, or in addition to, the `--report-md` option, it'll also write out the json version of the report

**Comment by kltm** [comment]
@vanaukenk Trying to run https://github.com/geneontology/go-site/issues/1562#issuecomment-707941676 above, using the WB test file, I get two IBA errors and the following error:

```
        "gorule-0000001": [
            {
                "level": "WARNING",
                "line": "WB\tWBGene00000001\taap-1\tacts_upstream_of_negative_effect\tGO:0008340\tWB_REF:WBPaper00005614|PMID:12393910\tIMP\t\tP\t\tY110A7A.10\tgene\ttaxon:6239\t20060302\tWB\t\t\t\t",
                "type": "Wrong number of columns in this line",
                "message": "There were more than 17 columns in this line. Proceeding by cutting off extra columns after column 17.",
                "obj": "",
                "taxon": "",
                "rule": 1
            }
        ]
```
That line does indeed seem to be too long or something.

```
On command: `sjcarbon@moiraine:/tmp$:( python3 env/bin/ontobio-parse-assocs.py -r /tmp/go.json -f /tmp/source.gaf -F gaf -o /tmp/parsed.gaf --report-md /tmp/report.md --report-json /tmp/report.json validate`

**Comment by vanaukenk** [comment]
Updated file: https://gist.github.com/vanaukenk/d293c3e85298841a423ba865dd6af31e

**Comment by vanaukenk** [comment]
```
!gaf-version: 2.2
!generated-by: WormBase
!date-generated: 2020-10-29
WB	WBGene00000001	aap-1	part_of	GO:0005942	WB_REF:WBPaper00046480|PMID:21873635	IBA	MGI:MGI:109277|PANTHER:PTN000806614|RGD:3329|UniProtKB:P23727|WB:WBGene00000001	C		Y110A7A.10	gene	taxon:6239	20170228	GO_Central  
WB	WBGene00000001	aap-1	located_in	GO:0005634	WB_REF:WBPaper00005614|PMID:12393910	IDA		C		Y110A7A.10	gene	taxon:6239	20151214	WB  
WB	WBGene00000001	aap-1	colocalizes_with	GO:0005759	WB_REF:WBPaper00046480|PMID:21873635	IBA	FLYBASE:FBgn0020622|MGI:MGI:109277|MGI:MGI:1098772|MGI:MGI:97583|PANTHER:PTN000016388|RGD:3329|UniProtKB:P23727|WB:WBGene00000001	C		Y110A7A.10	gene	taxon:6239	20170228	GO_Central  
WB	WBGene00000001	aap-1	involved_in	GO:0008286	WB_REF:WBPaper00005614|PMID:12393910	IGI	WB:WBGene00000090	P		Y110A7A.10	gene	taxon:6239	20151214	WB		
WB	WBGene00000001	aap-1	acts_upstream_of	GO:0008286	WB_REF:WBPaper00005614|PMID:12393910	IGI	WB:WBGene00000898	P		Y110A7A.10	gene	taxon:6239	20151214	WB		
WB	WBGene00000001	aap-1	acts_upstream_of_positive_effect	GO:0008286	WB_REF:WBPaper00005614|PMID:12393910	IMP		P		Y110A7A.10	gene	taxon:6239	20060302	WB		
WB	WBGene00000001	aap-1	acts_upstream_of_negative_effect	GO:0008340	WB_REF:WBPaper00005614|PMID:12393910	IMP		P		Y110A7A.10	gene	taxon:6239	20060302	WB		
WB	WBGene00000001	aap-1	acts_upstream_of_or_within	GO:0016310	GO_REF:0000043	IEA	UniProtKB-KW:KW-0418	P		Y110A7A.10	gene	taxon:6239	20200620	UniProt		
WB	WBGene00000001	aap-1	acts_upstream_of_or_within_positive_effect	GO:0040024	WB_REF:WBPaper00005614|PMID:12393910	IGI	WB:WBGene00000090	P		Y110A7A.10	gene	taxon:6239	20151214	WB		
WB	WBGene00000001	aap-1	acts_upstream_of_or_within_negative_effect	GO:0040024	WB_REF:WBPaper00005614|PMID:12393910	IGI	WB:WBGene00000898	P		Y110A7A.10	gene	taxon:6239	20151214	WB		
WB	WBGene00000001	aap-1	involved_in	GO:0008150	GO_REF:0000015	ND		P		Y110A7A.10	gene	taxon:6239	20060302	WB		
WB	WBGene00000002	aat-1	enables	GO:0003674	GO_REF:0000015	ND		F		F27C8.1	gene	taxon:6239	20131022	WB		
WB	WBGene00000002	aat-1	contributes_to	GO:0015179	WB_REF:WBPaper00006408|PMID:14668347	IDA		F		F27C8.1	gene	taxon:6239	20131022	WB		
WB	WBGene00000004	aat-3	is_active_in	GO:0005575	GO_REF:0000015	ND		C		F52H2.2	gene	taxon:6239	20131022	WB		
WB	WBGene00000007	aat-6	enables	GO:0022857	GO_REF:0000002	IEA	InterPro:IPR002293	F		T11F9.4	gene	taxon:6239	20200914	InterPro		
WB	WBGene00000004	aat-3	is_active_in	GO:0031012	WB_REF:WBPaper00006408|PMID:14668347	IDA		C		F52H2.2	gene	taxon:6239	20150730	WB		
```

**Comment by mah11** [comment]
I've created a v2.2 GAF for PomBase, in case you can test it. It should be available within ~24 hours from
https://www.pombase.org/data/annotations/Gene_ontology/gene_association_2-2.pombase.gz

**Comment by ukemi** [comment]
Here is the test file for mouse:
http://www.informatics.jax.org/downloads/custom/gene_association.mgi2

**Comment by prmani** [comment]
zfin: 
[Uploading gene_association2.2.zfin.gz…]()

**Comment by prmani** [comment]
zfin:
ftp://zfin.org/pub/transfer/GAF/gene_association2.2.zfin.gz

**Comment by hattrill** [comment]
Testing for FlyBase:
ftp://ftp.flybase.net/releases/current/precomputed_files/go/gene_association_v2.2.fb.gz

**Comment by hattrill** [comment]
@kltm @vanaukenk GAF2.2 is going to be the FlyBase default gene_association.fb file from approximately mid-Feb. Is that all ok?

**Comment by vanaukenk** [comment]
@hattrill I think that should be fine.  The current WB file is actually GAF2.2

**Comment by pgaudet** [comment]
I think this is all working as expected
