### ISSUE TITLE
change RHEA links in AmiGO

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-site#1565]
@arnaudxk has emailed our helpdesk about changing RHEA links that appear in AmiGO: 
eg, from https://www.rhea-db.org/reaction.xhtml?id=17357 to https://www.rhea-db.org/rhea/17357

>I discovered that the URL templates used in AMIGO are actually defined
in the following json file:
 => https://s3.amazonaws.com/go-public/metadata/db-xrefs.json

I'm going to try and change this in db-xrefs.yaml

**Comment by kltm** [comment]
@suzialeksander I'll take this PR as soon as it passes (it's taking a while).

@arnaudxk I would note that https://s3.amazonaws.com/go-public/metadata/db-xrefs.json is not a canonical data source and that http://current.geneontology.org/metadata/db-xrefs.json should be used instead.

Once the PR is in, the links should be updated with the next release.

**Comment by pgaudet** [comment]
Maybe we can check with @amorgat that this is the correct way to structure the URLs ? (although it looks right, I always like to confirm with the resource directly). 

Thanks, Pascale

**Comment by amorgat** [comment]
@arnaudxk is now involved in the Rhea project. ;-)
Consequently, the change he proposed is the correct one to link Rhea identifiers to the new Rhea web site.

**Comment by pgaudet** [comment]
I invited Arnaud in the repo. I will ask add him to the group contacts, 
Thanks, Pascale

**Comment by pgaudet** [comment]
I think this is done. Closing.

**Comment by arnaudxk** [comment]
Hi, I've made a pull request to also switch Rhea URLs to https if that's ok.

**Comment by kltm** [comment]
@arnaudxk If you could take a look at https://github.com/geneontology/go-site/pull/1569 to make sure I got what you wanted correct?

**Comment by arnaudxk** [comment]
@kltm Sorry, missed your comment. Yes, #1569 update looks correct to me. It is fine with me if this gets pushed into master and gets in production.
Thanks.

**Comment by pgaudet** [comment]
Looks like this is done, looking at the example above http://amigo.geneontology.org/amigo/term/GO:0016972

Thanks, Pascale
