### ISSUE TITLE
RGD links from PAINT broken

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#1570]
we noticed that our PAINT linkouts to RGD. don't work/

@kimrutherford  says

I think the url_syntax field for RGD in GO.xrf_abbs is wrong. The url_example works but we use the url_syntax for the links.

Here's what the entry looks like at the moment:

abbreviation: RGD
database: Rat Genome Database
synonym: RAD
synonym: RGDID
generic_url: https://rgd.mcw.edu/
local_id_syntax: [0-9]{4,7}
url_syntax: https://rgd.mcw.edu/rgdweb/search/search.html?[example_id]
example_id: RGD:2004
url_example: https://rgd.mcw.edu/rgdweb/search/search.html?term=2004
entity_type: SO:0000704 ! gene

It looks like it should be:

url_syntax: https://rgd.mcw.edu/rgdweb/search/search.html?term=[example_id]`

**Comment by ValWood** [comment]
@gthayman

**Comment by ValWood** [comment]
not sure who to tag for GO so randomly @kltm

**Comment by pgaudet** [comment]
@jrsjrs

**Comment by pgaudet** [comment]
Jennifer Smith confirms we should change the links: 

> Hi, Pascale, 
It's confirmed.  It should be " url_syntax: https://rgd.mcw.edu/rgdweb/search/search.html?term=[example_id] ".  Would that be something you could change?  I'm sure I could figure out how to change it but if it would be easy for you to do that I'd appreciate it!  If not, please let me know and I can do it.
Sorry for the confusion and thanks for letting us know about the problem!
Jennifer

@kltm @dustine32 Do we need to change this in other places ?

**Comment by pgaudet** [comment]
Hi @ValWood 

The link looks right in https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml
and it has been changed back in June - can you let me know where you got the bad link form ? Hopefuly this is resolved for you. 

Thanks, Pascale

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @mugitty @dustine32 

I think Val saw this problem from Pantree, for eg http://www.pantree.org/node/annotationNode.jsp?id=PTN000623091

Can you check that our link outs match https://github.com/geneontology/go-site/blob/3a2f5055562c97e7a0b1e03379ff7c4532377faf/metadata/db-xrefs.yaml ? 
And also from PAINT.

Thanks, Pascale

**Comment by kimrutherford** [comment]
> The link looks right in https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

Hi Pascale.  Thanks for following up on this.  We've been getting the xrefs from GO.xrf_abbs in the SVN repository.  I didn't notice that it wasn't being updated any more.  We'll change to use db-xrefs.yaml

**Comment by pgaudet** [comment]
OK good ! I think this can close.

**Comment by cmungall** [comment]
@kimrutherford 

I believe these are the URLs you should use. Use release products rather than github links. @kltm can confirm

 - http://current.geneontology.org/metadata/GO.xrf_abbs legacy flat file format
 - http://current.geneontology.org/metadata/db-xrefs.json json
 - http://current.geneontology.org/metadata/db-xrefs.yaml yaml

**Comment by kimrutherford** [comment]
Thanks Chris.  I've updated our pipeline.
