### ISSUE TITLE
GO refs should be updated to refer to both traditional, and ECO codes for GPAD

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#1575]
https://github.com/geneontology/go-site/blob/master/metadata/gorefs/goref-0000015.md

**Comment by pgaudet** [comment]
Is this what you wanted ? I edited all go_refs that I found that referred to ECO.

**Comment by ValWood** [comment]
yep!

**Comment by pgaudet** [comment]
@dougli1sqrd Can you regenerate the README for go_refs so those changes show up ?

**Comment by pgaudet** [comment]
Never mind @balhoff is doing it :)
