### ISSUE TITLE
Github Action to refresh goref and gorule readme on changes

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#1586]
The README.md for the metadata/gorefs and rules depends on the other markdown files inside. This requires a small script to be run when these files are changed to update the respective READMEs.

This will ensure those files are always in sync, and we no longer have to manually sync them.

**Comment by pgaudet** [comment]
You mean this will be automatic ? That'd be great !!!

**Comment by kltm** [comment]
@dougli1sqrd I think you finished this?

**Comment by dougli1sqrd** [comment]
yep yep
