### ISSUE TITLE
New gorule to fix bad GO aspect

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1588]
Hello, 

We need a new gorule to fix bad GO aspect, see issue reported by user here: https://github.com/geneontology/helpdesk/issues/288

I think this happens during interontology annotation inferences ? But in any case the aspect should be repaired. 

Thanks, Pascale

**Comment by kltm** [comment]
According to https://github.com/geneontology/helpdesk/issues/288, this is no longer an issue.
