### ISSUE TITLE
ftp site not being updated?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#1591]
It seems that the version of GO on the ftp site is not being updated. See correspondence below with Mark Schroeder at GO Tools.

Mark : 

For one thing, apparently the gene_ontology.obo that we automatically 
update is not complete or has not been getting updated recently. The 
timestamp on the remote side has been changing, though, so we didn't 
notice, and no errors were flagged. So that is one part of the problem.

It looks like the http://purl.obolibrary.org/obo/go.obo or 
http://current.geneontology.org/ontology/go.obo is more recent (or at 
least it defines that GO term). Unfortunately our slimming tool for some 
reason does not work with it right now, so I haven't been able to fully 
test it yet. I'll be looking into that more today and tomorrow.

I think we will have to verify a lot of these sources. Val, is 
ftp.pombase.org the best place for us to automatically retrieve the 
gene_association.pombase?

On 11/29/20 11:19 AM, Valerie Wood via RT wrote:
> <URL:https://gen-help.princeton.edu/Ticket/Display.html?id=39476  >
>
> Hi Marc,
>
> I see this term in the QuickGO browser though?
> https://www.ebi.ac.uk/QuickGO/search/GO:0110161
>
> Also Cut12 has a 3  BP annotations
>
> - 	GO:0000086<https://www.pombase.org/term/GO:0000086>  	
> G2/M transition of mitotic cell cycle
> <https://www.pombase.org/term/GO:0000086>
> 	EXP
> <http://wiki.geneontology.org/index.php/Inferred_from_Experiment_(EXP)>  
> MacIver FH et al. (2003)
> <https://www.pombase.org/reference/PMID:12815070>  	70
> <https://www.pombase.org/term/GO:0000086>
> - 	GO:0140480<https://www.pombase.org/term/GO:0140480>  	
> mitotic spindle pole body insertion into the nuclear envelope
> <https://www.pombase.org/term/GO:0140480>
> 	IMP
> <http://wiki.geneontology.org/index.php/Inferred_from_Mutant_Phenotype_(IMP)>  
> 	Tallada VA et al. (2009)
> <https://www.pombase.org/reference/PMID:19487457>  	4
> <https://www.pombase.org/term/GO:0140480>
> - 	GO:0110161<https://www.pombase.org/term/GO:0110161>  	
> positive regulation of mitotic spindle formation (spindle phase one)
> <https://www.pombase.org/term/GO:0110161>
> 	IMP
> <http://wiki.geneontology.org/index.php/Inferred_from_Mutant_Phenotype_(IMP)>  
> 	Bridge AJ et al. (1998)<https://www.pombase.org/reference/PMID:9531532>
>
>
>
> I now see that there are a number of genes that are not identified,
> inclluding cut12:
>
> These 29 identifiers were found to be unannotated: Systematic ID
> SPBC32H8.03 SPCC622.21 SPBC27.04 SPCC663.02 SPCC736.05 SPBC21C3.07c
> SPCC285.07c SPCC1906.04 SPCC1183.10 SPCC1281.08 SPCC663.17 SPCC970.11c
> SPCC1450.08c SPCC794.02 SPAC12G12.16c SPAC1F7.06 SPCC1620.02 SPCC1739.15
> SPBC354.08c SPAC11D3.13 SPCC162.04c SPBC649.05 SPAC144.19 SPCC548.03c
> SPBC3H7.11 SPCC1919.06c SPCC1906.03 SPBC947.09
>
> I can't figure why, because I see them in AmiGO.
>
> at least the ones I spot checked
> http://amigo.geneontology.org/amigo/gene_product/PomBase:SPCC162.04c
> http://amigo.geneontology.org/amigo/gene_product/PomBase:SPBC32H8.03
> http://amigo.geneontology.org/amigo/gene_product/PomBase:SPBC3H7.11
>
> Any ideas?
>
>
> Best,
>
> Val

**Comment by pgaudet** [comment]
To be clear - which GO ftp site are we talking about ? Maybe that was in your original exchange ?

**Comment by ValWood** [comment]
ignore. I completely misread the problem!
