### ISSUE TITLE
Add Animal QTLdb/CorrDB db-xrefs.yaml

### ISSUE THREAD

**Issue by zhilianghu** [geneontology/go-site#1600]
I made 2 additions to the db-xrefs.yaml in my forked version. Could someone advice what's the next step to bring it to the master copy?

**Comment by kltm** [comment]
@zhilianghu 
I'd describe the changes in the title, as well as a summary, and create a PR.

**Comment by zhilianghu** [comment]
I did add descriptions when commit changes... somehow now a "Create Pull Request" button appeared.  Hope now it's on its right track.

**Comment by kltm** [comment]
Associated with: https://github.com/geneontology/go-site/pull/1604

**Comment by kltm** [comment]
@zhilianghu There are some issues with the PR. You can take a look at the issues in the GH review.

More generally, what is your use case for adding this information to the GO db-xrefs.yaml?

**Comment by zhilianghu** [comment]
I have removed redundant '-'s.  I cannot see any more format difference from other entries with my naked eyes  8-)

**Comment by kltm** [comment]
Now passing; merged.

**Comment by zhilianghu** [comment]
Thank you for your patience with me!

Zhiliang

On Jan 13, 2021, at 3:08 PM, kltm <notifications@github.com<mailto:notifications@github.com>> wrote:


Now passing; merged.
