### ISSUE TITLE
Finalize new SPARQL end user page for GO

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1606]
To support the link in the published paper and end users, we want to accomplish the following steps for a new end user SPARQL page for the GO:

- [ ] ensure that it is understood that rdf.geneontology.org will be the public endpoint to run SPARQL (and retain its blazegraph interface), while sparql.geneontology.org will be the general-purpose end user "gui" interface
- [ ] (attempt to) shorten or make available http://rdf.geneontology.org/blazegraph/sparql to http://rdf.geneontology.org/sparql 
- [x] add index.html single page app to geneontology.github.io repo
- [ ] undo sparql.geneontology.org proxy server and have above single page app available at sparql.geneontology.org

From conversation with @cmungall and @lpalbou 
Also letting @balhoff know, in case he has queries pointed at sparql.geneontology.org, or knows of anybody who does

**Comment by lpalbou** [comment]
Linking to https://github.com/geneontology/geneontology.github.io/issues/267

**Comment by pgaudet** [comment]
Where do we stand with this?

**Comment by lpalbou** [comment]
For end-users, the public sparql page (http://sparql.geneontology.org) has been up and running for several months. This ticket is only about back end optimizations that do not affect end users.

1. IMO done, but doesn't really matter as it's just 2 different UIs to query the same endpoint. Jim may be the only one caring about the blazegraph UI as it provides some non-RDF features that are blazegraph specific

2. is to simplify the URL of the rdf endpoint, it's a nice to have, but nothing critical or that would affect anyone work

3. done and powering the public UI

4. nice to have, doesn't really affect end users except they get redirected to http://geneontology.org/sparql

**Comment by pgaudet** [comment]
ok thanks! 

Would it be hard to have the same footer as on other http://geneontology.org/ pages? 

Anyway I think this can close?

**Comment by cmungall** [comment]
I'm ok to close

**Comment by lpalbou** [comment]
Footer added and updated.

**Comment by pgaudet** [comment]
Thanks !!

**Comment by lpalbou** [comment]
The SPARQL page is accessible from the GO APIs Guide: https://geneontology.github.io/docs/tools-guide/#query-go-causal-activity-models-sparql-endpoint but not from the GO Tools Overview. Ideally we want to keep a clear separation between APIs: REST API, SPARQL API, GOLr; and (higher level) Tools: amigo, gocam browser, ribbon, matrix, Noctua.

But yes, the access to both the Tools & APIs is not super intuitive right now. Creating a simple top-level menu for listing & quick access would help. I have been delaying the refactoring of that section of the website as we were / are planning to work on the new GO API, Jupyter notebooks and recommendations of community tools.

**Comment by pgaudet** [comment]
Thanks for the explanation!
