### ISSUE TITLE
Question PAINT yaml file

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1612]
Hello @dustine32 @kltm 

The PAINT yaml file does not have a 'url' value: 
https://github.com/geneontology/go-site/blob/master/metadata/datasets/paint.yaml

However I *think* this is where we want anyone using GO data to get their data from; isn't it ? 

More specifically: 
* for groups with direct submissions, this should be part of the file we produce (for eg dicty PAINT data should be included in http://current.geneontology.org/annotations/dictybase.gpad.gz) ? 
* 'others' should be picked up from goa_uniprot_all_noiea.gaf.gz ? Or as a separate file? 

In any case, the 'url' field should be filled, shouldn't it ? 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet The PAINT files handling is a little special as they are internal sources. @dougli1sqrd can give you the details on handling, but the `merges_into` field is what dictates its final location.

**Comment by dougli1sqrd** [comment]
Yeah, a paint dataset gets merged into whatever is in the `merged_into` field, like @kltm said. So to pick up paint sources you'd have to go to the `merged_into` place.

And goa_uniprot_all is for everything else, true.

**Comment by pgaudet** [comment]
They may be internal sources but some groups consume them - including GOA - why not specify where people can grab those from ?
