### ISSUE TITLE
Need details about AstraZeneca, Muscle TRAIT in list of Contributing Groups

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/go-site#162]
@cmungall @selewis 
In the list found at "GO Consortium Contributors List" http://geneontology.org/page/go-consortium-contributors-list
Do we know anything about AstraZeneca and Muscle TRAIT? 
They are listed without any details. 
Are these still active contributors? 
If so, what are the details? Or who could give me this information? 
If not, may I remove them?

**Comment by cmungall** [comment]
AZ should still be acknowledged, they provided seed funding many moons 
ago.

Muscle TRAIT: @ukemi is this related to GOC:mtg_muscle?

**Comment by ukemi** [comment]
I pinged Midori, who has a far better memory than I, about this. It was the group from The University of Padua who sponsored the muscle interest meeting (GOC:mtg_muscle). See PMID:12651729. The result of the work led to this publication PMID:9178689.

**Comment by monicacecilia** [comment]
AstraZeneca has remained on the list all along.  I did not remove it so they are recognized in the list of contributors. It would be nice to have more information about their contact details and the nature of their contribution (from where, grant #, or something similar). 

@ukemi thanks for the insight. Do we know anything about the type of funding or who the contact is/was?

**Comment by ukemi** [comment]
No. Maybe we could try to get in touch with Jen. She was our main contact.

**Comment by monicacecilia** [comment]
Apologies @ukemi, which Jen?

**Comment by cmungall** [comment]
Jen Deegan (nee Clark)

Muscle project details here: http://wiki.geneontology.org/index.php/Personnel

This is inactive. I think should be sufficient to say Erika Feltrin from University of Padua. Ideally this would all be driven directly from metadata in the ontology, ORCIDs etc

**Comment by cmungall** [comment]
It's very difficult keeping pages like this up to date in the long term. Let's think of alternate strategy to this page

 - ontology dependencies are documented directly via owl:imports. This is kind of visible in amigo. Good enough for now
 - annotation contributing database: https://github.com/geneontology/go-site/tree/master/metadata/datasets
 - contributing people: users.yaml. We can also do queries over the ontology to show contributions etc
 - other: NAR paper etc
 - funding: keep this on the website

**Comment by pgaudet** [comment]
AstraZeneca is now in the 'Past contributors' list
and TRAIT in groups.yaml

**Comment by kltm** [comment]
@pgaudet Is this change (https://github.com/geneontology/go-site/commit/58f037a229825b3aa741c20630c8832d506164ea) meant to add a curating group for Noctua? If not, we might want to touch bases about the purpose of that file.

**Comment by pgaudet** [comment]
@kltm 
No, this change is a not a group in Noctua. I would love to know the scope of the different files better. The header of the groups.yaml file stated that the documentation is in the readme.md file, which states this: 

 > Groups encompasses organizations, projects, working groups, content meetings, grants, etc. We call these "groups" as these typically consist of groups of users. Some groups may be transient (e.g. projects or working groups). Others may be permanent institutions, such as Cambridge University.

So I thought that TRAIT, who was part of the muscle working group, belonged here. 

If this is for Noctua, then many groups should be moved elsewhere. 
A few examples: 
  label: EMBL-EBI
  label: 'NCATS Data Translator'
  label: UCSD
  label: University of Toronto
  label: PAMGO

Thanks, Pascale

**Comment by kltm** [comment]
Currently, functionally, groups is used as 1) the "groups" allowed by Noctua as a curation embellishment and 2) as labels for GPAD conversion. We've talked before about centralizing information into users.yaml and groups.yaml, but have not planned that fully. Under the current regime, you may find that info like TRAIT may be currently help in users.yaml (which includes a port of previous metadata files).
