### ISSUE TITLE
Delete goa_uniprot_all.gaf earlier in pipeline to free up space

### ISSUE THREAD

**Issue by dustine32** [geneontology/go-site#1624]
Delete immediately after the goa_uniprot_all_noiea.gaf file is created from it. This should hopefully allow other processes in the mega-make pipeline step to complete without running out of disk space.

**Comment by kltm** [comment]
Even if it doesn't, we want to prevent the file from existing too long because of https://github.com/geneontology/pipeline/issues/207

**Comment by kltm** [comment]
I wonder about lines like: https://github.com/geneontology/pipeline/blob/624c42671ed719e19a4f923ec243bc6e2bfd6eb6/Jenkinsfile#L566

**Comment by kltm** [comment]
Will see effect in next attempt.
