### ISSUE TITLE
Very slow response time from GO-wiki.

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/go-site#164]
Hello, 
It seems a little odd that whenever I try to access wiki.geneontology.org for the first time in a work session, the site takes a very long time to load. Usually >15 seconds. 
Once one page loads, then the other ones tend to take less time, 1 - 2 seconds. 
All anecdotal data, I don't have actual time reports and repeats.

Are others experiencing this slow down as well?
Is there a possible reason for this?

**Comment by cmungall** [comment]
Seems ok to me?

**Comment by kltm** [comment]
Fine for me.
I'll close until reproducible under a controlled environment.
