### ISSUE TITLE
gorule-00000008 example is failing, but the test example is actually correct

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#1649]
One of the gorule-00000008 examples is failing.

`UniProtKB	Q9WVH3	Foxo4		GO:0031572	PMID:12048180	IDA		P	Forkhead box protein O4	Foxo4|Afx|Afx1	protein	taxon:10090	20110425	MGI` is expected to fail, but is passing in the example test run in travis. 

But when I run it locally, gorule-00000008 is correctly triggered, giving the message: `"message": "GORULE:0000008: No annotations should be made to uninformatively high level terms"`. This is expected. 

Offending example is https://github.com/geneontology/go-site/blame/master/metadata/rules/gorule-0000008.md#L19

**Comment by kltm** [comment]
@pgaudet The issue for the failure here was that the given term for the test annotation line (https://github.com/geneontology/go-site/pull/1662/files#diff-5830fda4cd89ac90f5ef8cba844b5b14772472046e21502313b6ffc0cc6247a2R19) has been replaced (by a term that is no longer in that subset). I selected a new term from that subset, as we wanted PRs to work again, but you might prefer a real example or better term?
