### ISSUE TITLE
Travis tests are currently failing on final test

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1660]
Currently, the travis tests seem to be pretty consistently failing on:

`docker run -it -v $(pwd):/tmp/go-site -w /tmp/go-site geneontology/dev-base:latest /bin/bash -c "pip3 install -r pipeline/requirements.txt && ./scripts/rule-example-validation.sh"`

Testing locally, I also get this failure.

Issue may be:

 ```json
        {
            "rule": "gorule-0000008",
            "type": "fail",
            "format": 2,
            "input": "UniProtKB\tQ9WVH3\tFoxo4\t\tGO:0031572\tPMID:12048180\tIDA\t\tP\tForkhead box protein O4\tFoxo4|Afx|Afx1\tprotein\ttaxon:10090\t20110425\tMGI",
            "expected": false,
            "actual": true,
            "success": false,
            "reason": "Repair found `True`, but expected `False`"
        }
```

Tagging @dougli1sqrd

**Comment by dougli1sqrd** [comment]
Yeah, I documented this here as well: https://github.com/geneontology/go-site/issues/1649

**Comment by kltm** [comment]
Cleared.
