### ISSUE TITLE
Data different between db-xrefs.json and db-xrefs.yaml

### ISSUE THREAD

**Issue by alexsign** [geneontology/go-site#1670]
Hi, 
There is an issue with url_syntax link in db-xrefs.json which is correct in db-xrefs.yaml.

from: https://s3.amazonaws.com/go-public/metadata/db-xrefs.json

"url_syntax": "https://rgd.mcw.edu/rgdweb/search/search.html?[example_id]", <--- WRONG
"example_id": "RGD:2004",
"example_url": "https://rgd.mcw.edu/rgdweb/search/search.html?term=2004"

from: https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

url_syntax: https://rgd.mcw.edu/rgdweb/search/search.html?term=[example_id] <--- CORRECT
example_id: RGD:2004
example_url: https://rgd.mcw.edu/rgdweb/search/search.html?term=2004  

Thanks,
Alex

**Comment by kltm** [comment]
@alexsign 
Would you mind taking a look at http://current.geneontology.org/metadata/db-xrefs.json? It looks to me like it has the correct syntax.

The file that you list above has not been updated in a while and is not at a currently supported endpoint. I think that might have been a holdover from an earlier period. If you can help us track down that documentation I can make sure we update it.

**Comment by alexsign** [comment]
@kltm Thanks! I'll let the developers know.

**Comment by pgaudet** [comment]
Can this be closed?
