### ISSUE TITLE
Missing newline in GPI comments out first entity

### ISSUE THREAD

**Issue by dustine32** [geneontology/go-site#1681]
As spotted by @cmungall:

> there is no newline after the header line, so the first line of actual GPI is masked
>
> (btw shouldn't there be a lot more in the metadata here?) 
```
$ curl -L -s http://current.geneontology.org/annotations/mgi.gpi.gz | gzip -dc | head
!gpi-version: 2.1MGI    MGI:1918911     0610005C13Rik   RIKEN cDNA 0610005C13 gene              SO:0000704      taxon:10090                     
MGI     MGI:1923503     0610006L08Rik   RIKEN cDNA 0610006L08 gene              SO:0000704      taxon:10090                     
MGI     MGI:1925547     0610008J02Rik   RIKEN cDNA 0610008J02 gene              SO:0000704      taxon:10090
```

To fix, we need to add `\n` to the `.write` line here:
https://github.com/biolink/ontobio/blob/d4fff4a551b71d15eb3be2f8296816ee2f721ca0/ontobio/io/entitywriter.py#L95
```
    def __init__(self, file=None):
        self.file = file
        if self.file:
            self.file.write("!gpi-version: 2.1")
```

**Comment by ukemi** [comment]
I will work with things on our side.
ping @loricorbani

**Comment by dustine32** [comment]
@cmungall @dougli1sqrd @kltm About the missing metadata: we're generating these GPIs purely from the input GAF entities, right? So we wouldn't have much metadata.

Or are we actually incorporating the GPIs people submit through the metadata yamls? If yes, then we should be copying forward their headers?

**Comment by dougli1sqrd** [comment]
Yeah this is completely on our end. We create this on our end from the GAFs. Should be version 1.2 as well that we're currently producing. We could add whatever additional metadata, but technically there's never really been requirements for this gpi file. I imagine this newline bug has been around for aaages haha.
