### ISSUE TITLE
Get validate.py to run all GORULES again

### ISSUE THREAD

**Issue by dustine32** [geneontology/go-site#1689]
@pgaudet Observed in 2021-05-22 `snapshot` that most GORULES were not running. This appears due to https://github.com/biolink/ontobio/issues/564. In the short term, to bypass the wonky default, we can just explicitly add `--rule-set all` to this `validate.py` cmd:
https://github.com/geneontology/go-site/blob/0f6c248b5aa2f253cfe3a9a736cb424f7851e91c/pipeline/Makefile#L89

Tagging @kltm

**Comment by kltm** [comment]
@dustine32 To clarify, what kind of time frame are we looking at for a fix for https://github.com/biolink/ontobio/issues/564 ?

**Comment by dustine32** [comment]
@kltm Today or tomorrow for the https://github.com/biolink/ontobio/issues/564. I'll need to make an ontobio release, push to PyPI, and PR the version bump in [go-site/pipeline/requirements.txt](https://github.com/geneontology/go-site/blob/master/pipeline/requirements.txt).

**Comment by kltm** [comment]
@dustine32 Great--cheers! Given where we are in the different pipeline runs, I don't think it will make much difference at this point and would rather not cancel so we can get an ontology release out on `snaphot`.

**Comment by dustine32** [comment]
Title changed because all changes to fix this are in ontobio. With [this ontobio change](https://github.com/biolink/ontobio/pull/565), we shouldn't have to set `--rule-set all`.

**Comment by kltm** [comment]
Appears to be cleared. Re-open if not.
