### ISSUE TITLE
Remove GAF lines when DB_object_id is not found in the submitted GPI. 

### ISSUE THREAD

**Issue by sierra-moxon** [geneontology/go-site#1704]
For the ZFIN MOD import, there are 12 genes not currently in the ZFIN GPI: 
ZFIN can fix the GPI upstream, but in the meantime, should annotations be produced to objects not in the GPI file?  (the current symptom of this is that the taxon field for those 12 genes reads 'taxon:0').

**Comment by kltm** [comment]
Also see https://github.com/geneontology/pipeline/issues/239

**Comment by sierra-moxon** [comment]
These ended up being gene merges that weren't reflected in the models.  I used sed to replace the old identifier with the new identifier.
