### ISSUE TITLE
Page needs updating (documentation other menu link)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#171]
http://geneontology.org/page/other-useful-links

All references to Sourceforge on website need removing
1. SourceForge links: Useful links for the SourceForge site, including both general and GO-specific pages.
2. GO Editor Guides: A set of guides for curators editing the ontologies. (would this be better under the ontology documentation link)

If the final item  could be rehoused you could get rid of 'Other'. I only looked under here trying to find the AE documentation, but in general, I would be unlikely to ever look under a link called "Other"  except as a last resort.

**Comment by kltm** [comment]
I'd vote for doing away with the page and the menu item. It likely only exists as some form was on the old site and it was mapped over without too much consideration.

**Comment by monicacecilia** [comment]
:+1:

**Comment by kltm** [comment]
Okay, so the question is: where does the GO Editor's Guide go? As that is the only remaining item, what if that was the menu item? Or should it be housed in a more sensible spot? (I haven't kept up with how the docs are laid out.)

**Comment by monicacecilia** [comment]
I think the 'GO Editor Guides' should go "somewhere" in http://geneontology.org/page/contributing-go
That is, when I get to cleaning up this part of the yard... which is also referenced [I think] in the #161  honeydo list.

**Comment by cmungall** [comment]
> I'd vote for doing away with the page and the menu item

+1

> I think the 'GO Editor Guides' should go "somewhere" in http://geneontology.org/page/contributing-go

That seems reasonable, but if we lose the link to it from the main site in the interim, no big deal. The number of people who need to know how to find this are fairly small and know how to find it anyway. The priority for the main GO website is the wider community

**Comment by ValWood** [comment]
This ticket is probably out of date?
@suzialeksander  are you looking after the website?
can probably close this?

**Comment by pgaudet** [comment]
We fixed this in the Documentation jamboree, this page is now unpublished.
