### ISSUE TITLE
Allow existence_overlaps as valid extension relation

### ISSUE THREAD

**Issue by dustine32** [geneontology/go-site#1716]
See https://github.com/geneontology/go-annotation/issues/2677#issuecomment-882845068. Annotation extensions using `existence_overlaps` relations are being filtered out in GO rule QC.

This missing relation was just added in `ontobio` via https://github.com/biolink/ontobio/pull/580. Bumping the `ontobio` version in `requirements.txt` should bring this change into the next `snapshot` run.

Tagging @vanaukenk @kltm

**Comment by mah11** [comment]
The PomBase report is now free of gorule-0000001 errors. Thank you!
