### ISSUE TITLE
Create a top level GO-CAM page on the GO site

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#172]
This would be high level, and would not duplicate the material available on noctua.berkeleybop.org, which it should link to.

The people arriving here would be primarily interested in (a) obtaining the data and (b) browsing it. We won't be set up for (b) until future iterations of amigo, obtaining more production models. However, we can provide a to some extent via #169

**Comment by pgaudet** [comment]
Hi Chris

This was for a milestone that past one year ago. Is this still high priority ? If so, can you give an expected delivery date ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Done ? 
http://geneontology.org/docs/gocam-overview/

@lpalbou Is this OK to close ?

**Comment by lpalbou** [comment]
Chris original intent was for this to be in amigo, but as you pointed out, we have the documentation, gocams can be downloaded from the official release and models can be browsed on http://geneontology.org/gocam.

So I think we can close that ticket for now and other concerns can be revisited later.

**Comment by pgaudet** [comment]
Thanks !
