### ISSUE TITLE
obsolete terms in AmiGO

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#1742]
Should that happen?
<img width="1144" alt="Screenshot 2021-10-11 at 12 53 13" src="https://user-images.githubusercontent.com/7359272/136823068-7fec111e-39ce-45d2-8c36-20910f2a967d.png">
?

**Comment by kltm** [comment]
@ValWood I'm not sure what view this is, but the term does indeed have the label "obsolete covalent chromatin modification".
http://amigo.geneontology.org/amigo/term/GO:0016569
Why there are annotations to this term may need to be taken up upstream:
http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=regulates_closure:%22GO:0016569%22&sfq=document_category:%22annotation%22

**Comment by ValWood** [comment]
Right it probably hasn't been fixed yet, I assumed annotations to obsolete terms weren't loaded at all. Close if this is not the case.

**Comment by ValWood** [comment]
Actually, is this  really an obsolete" term  or has 'obsolete' just been added to the term name???

**Comment by pgaudet** [comment]
Interesting - when you look at the GO term page view in AmiGO, the annotations do not show up: 
http://amigo.geneontology.org/amigo/term/GO:0016569


But the filter is not working on the Annotation view - as if the data had been loaded - I expected that only the filtered data would be loaded.

**Comment by kltm** [comment]
It seems that the results have improved, or at least shifted, from what they were before. Currently, the test `~skyhook/release/annotations$ reset && zgrep GO\:0031935 *.gaf.gz` only returns results from goa_uniprot_all_noiea.gaf.gz, which is to be expected as this is not a file that we run QC on. As well, all other linked results above no longer seem to contain the previously mentioned problematic annotations.

**Comment by kltm** [comment]
Talking to @pgaudet , it looks like this has been cleared. We'll look at how to deal with these more generally.
