### ISSUE TITLE
Improve the labels on the toolbar, specifically the Tools links

### ISSUE THREAD

**Issue by helenp** [geneontology/go-site#175]
Discussion at the GO meeting. Improve GOOSE and AMIGO labels to indicate functionality rather than project component names.

**Comment by ValWood** [comment]
Landing page has been improved, I hope
http://tomodachi.berkeleybop.org/amigo/landing
and probably here, although I didn't look at this in detail
http://tomodachi.berkeleybop.org/amigo/software_list

**Comment by ValWood** [comment]
https://github.com/geneontology/amigo/issues/331

Hopefully altready omprved a bit
http://tomodachi.berkeleybop.org/amigo/landing

I'm not sure if changes filtered through to this page
http://tomodachi.berkeleybop.org/amigo/software_list

But these changes haven't yet filtered through to live site

**Comment by ValWood** [comment]
Follow on from https://github.com/geneontology/amigo/issues/303 ;)

**Comment by cmungall** [comment]
Looks like this is done, thanks!
