### ISSUE TITLE
No ontology snapshot

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#1758]
Hi, it seems there hasn't been an ontology snapshot for a few weeks?
Cheers

Val

http://snapshot.geneontology.org/summary.txt

Runtime summary.

Mon Nov 22 00:01:33 PST 2021

Release notes: https://github.com/geneontology/go-site/tree/master/releases
Branch: snapshot
Start day: Monday
Start date: 2021-11-22
Official release date: metadata/release-date.json
Official Zenodo archive DOI: metadata/release-archive-doi.json
Official Zenodo archive DOI: metadata/release-reference-doi.json
TODO: Note software versions.

**Comment by pgaudet** [comment]
Indeed, last snapshot was on Nov 22
http://snapshot.geneontology.org/metadata/release-date.json

**Comment by kltm** [comment]
This is correct. There have been no real successes since the last release for various issues, currently https://github.com/geneontology/pipeline/issues/262. We'll hopefully have something together v/soon (currently testing).

**Comment by ValWood** [comment]
close?
