### ISSUE TITLE
gorefs place to link to for descriptions

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#1762]
HI,

We would like somewhere stable to a) link to and b)  extract the text for the GO db-xrefs.

Googling I can only find ;
https://github.com/geneontology/go-site/blob/master/metadata/gorefs/goref-0000116.md

Is there anywhere on the GO site proper?

We could use this:
https://raw.githubusercontent.com/geneontology/go-site/master/metadata/gorefs/goref-0000116.md

but it done not look very constrained (embedded URLs and PMIDs etc)

We want to add this information to these pages:
https://www.pombase.org/reference/GO_REF:0000116

@kimrutherford

**Comment by kltm** [comment]
@ValWood Just to clarify, it looks like you're GO refs, not the rules or the db xrefs, correct?

The `GO_REF:0000015` CURIE expands to the URI `http://purl.obolibrary.org/obo/go/references/0000015`, which is then mapped to `https://github.com/geneontology/go-site/blob/master/metadata/gorefs/goref-0000015.md`. So, officially, the URI is what one would want.

Depending on what you're doing though, it might be easier just to either work with the data in GitHub (as it's easily handled using a yamldown lib) or take the entire thing from the aggregated README:
https://github.com/geneontology/go-site/blob/master/metadata/gorefs/README.md

That said, depending on your use, it may be the less derived from the URI source the better.

**Comment by ValWood** [comment]
It seems this should be on the GO site somewhere really. I wonder how other link to this info??

**Comment by ValWood** [comment]
main GO site

**Comment by ValWood** [comment]
Doesn't it seem a bit weird to link to a GitHub page?
I see that is what AmiGO does....

**Comment by kimrutherford** [comment]
Ideally, we'd like a single easy to parse file containing all the GO ref details.  We were hoping there would be a file a bit like this one that we use for our internal references: https://curation.pombase.org/dumps/latest_build/pombe-embl/supporting_files/PB_references.txt

But for now will parse the individual `.md` files.  Thanks for the hint about yamldown.

**Comment by ValWood** [comment]
I'm sure others could use such a file too!

**Comment by kimrutherford** [comment]
> > Ideally, we'd like a single easy to parse file containing all the GO ref details. 
>
> I'm sure others could use such a file too!

We now process the `.md` files into a single file for loading.

Here's what we loaded last night: https://curation.pombase.org/dumps/latest_build/pombe-embl/supporting_files/go_references.txt

**Comment by kltm** [comment]
With feedback from @cmungall, closing in favor of future work item: https://github.com/geneontology/go-site/issues/1764
