### ISSUE TITLE
Migrate AspGD to P2GO

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1763]
@marekskrzypek has informed the GOC that AspGD is not being maintained anymore, so the annotations will be migrated to P2GO as an internal source, ie modifications will be done there. 

Tasks: 

- [x] load data in P2GO @alexsign 
- [x] give edit permissions to @pgaudet @vanaukenk @Antonialock - who else? @marekskrzypek ? @suzialeksander ? 
- [x] delete yaml file: https://github.com/geneontology/go-site/blob/master/metadata/datasets/aspgd.yaml @kltm 
- [x] remove aspgd from any tests or test pipelines (audit) @kltm 
- [x] Remove aspergilus from downloads? http://current.geneontology.org/products/pages/downloads.html (should happen naturally, but @kltm @dustine32 to check)

Anything else? @kltm @alexsign ? 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet Added a little to your list above and added to project.

**Comment by pgaudet** [comment]
Hi @alexsign , just wondering where this ticket stands on your end?

**Comment by pgaudet** [comment]
P2GO side of things is handled.

**Comment by pgaudet** [comment]
@kltm I think this can be closed?

**Comment by kltm** [comment]
@pgaudet Just clarifying, this is finalizing the "removal" of aspgd, correct?

**Comment by pgaudet** [comment]
yes

**Comment by kltm** [comment]
One items left above; will be cleared after next release?

**Comment by kltm** [comment]
Cleared.
