### ISSUE TITLE
Datasources: Fix GeneDB data sources

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1768]
Hi, 

GeneDB has been taken down, Plasmodium falciparum 3D7 data is now on PlasmoDB. 

I have update the db-xrefs.yaml to reflect that

@kltm @dustine32 @sierra-moxon Does anything need to be updated in the pipeline or AmiGO? 

Thanks, Pascale

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-site/pull/1767/files

**Comment by kltm** [comment]
Like all of GeneDB is gone? We are still loading some file: https://github.com/geneontology/pipeline/blob/snapshot/Jenkinsfile#L134-L135
Are you saying that these need to be removed?

**Comment by kltm** [comment]
Talked to @pgaudet : will revert changes made to links; no data updates are necessary for data load.

**Comment by kltm** [comment]
Reverting with https://github.com/geneontology/go-site/pull/1770

**Comment by pgaudet** [comment]
In fact this was correct. The links in AmiGO (and QuickGO) to GeneDB should be changed to PlasmoDB.

**Comment by pgaudet** [comment]
@Achchuthan Do you generate a mappings between the genedb and plasmodb identifiers? This is for GOA (QuickGO) to be able to link out. @alexsign has an older version of the file, but if this is maintained and updated, we'd like to be able to get it from you. 

Thanks, Pascale

**Comment by pgaudet** [comment]
I'll open a new ticket for this

**Comment by kltm** [comment]
Dupe to https://github.com/geneontology/go-site/issues/1777
