### ISSUE TITLE
Create new source for PlasmoDB

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1769]
We need to update https://github.com/geneontology/go-site/blob/master/metadata/datasets/genedb.yaml
to reflect the new location of the data: 

https://plasmodb.org/common/downloads/Current_Release/Pfalciparum3D7/gaf/PlasmoDB-55_Pfalciparum3D7_GO.gaf

@kltm I think you need this as a gzip file? 

@alexsign 
@Achchuthan 

Thanks, Pascale

**Comment by uliboehme** [comment]
Hi @pgaudet , there are currently a few issues with the GAF file on VEuPathDB. @Achchuthan has been looking into this and can provide further details if necessary. 

The annotation of P. falciparum 3D7 and also any other curated VEuPathDB genomes is still done with chado Artemis at the Sanger Institute and therefore the GAF file should still be used from the Sanger FTP site: 
ftp://ftp.sanger.ac.uk/pub/genedb/releases/2022-02/Pfalciparum

Please let me know if there are any questions. 
Thanks, Uli

**Comment by Achchuthan** [comment]
Hi @pgaudet, I agree with @uliboehme. There are a lot of duplicate annotations and annotations with missing metadata in PlasmoDB. This was the issue as PlasmoDB is importing annotations (both GeneDB curated and automated annotations) from the EBI pipeline since the merger with VectorBase. Since we utilize the Sanger infrastructure for curation, it's better to import GO annotations from Sanger FTP site for P. falciparum 3D7, Trypansooma brucei TREU927 and Leishmania major.

**Comment by pgaudet** [comment]
OK, we'll get the data from Sanger for these species. 

For link outs, are the changes here ok? 
https://github.com/geneontology/go-site/commit/5d3b194a78794773b572220fc76b22f9d2f76a3e#diff-45447b7afbd5e544f7d0f1df0fccd26014d9850130abd3f020b89ff96b82079f

Thanks, Pascale

**Comment by Achchuthan** [comment]
Hi @pgaudet, Here we are referencing to PlasmoDB in the linkouts. This is fine for P. falciparum 3D7. But the other two species Trypanosoma brucei TREU927 and Leishmania major are Kinetoplastida genomes from TriTrypDB (https://tritrypdb.org/). I'm wondering whether we can represent multiple databases in the yaml file?
Thanks,
Achchuthan

**Comment by kltm** [comment]
@pgaudet Yes, compressed would be desired here.

**Comment by pgaudet** [comment]
>  I'm wondering whether we can represent multiple database linkouts in the yaml file?

Yes!

**Comment by pgaudet** [comment]
I will created another ticket, this is not quite right.

**Comment by kltm** [comment]
Dupe to #1777
