### ISSUE TITLE
User stories is an unclear / confusing concept

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-site#177]
From GO meeting via GO Help desk:

Hi,
On the homepage the title User stories doesn't really tell me what it is.
Think about rebadging the whole right hand panel as documentation. The user
stories are really quick links to documentation relevant by user type. That
is still a mouthful. But explains more clearly what a user should expect to
see.
Thanks
Alex

**Comment by kltm** [comment]
There are several identical tickets around this, will consolidate.

**Comment by kltm** [comment]
From @mcourtot:
```
http://geneontology.org/page/user-stories

The User Story Story
User stories represent a way of looking at the information that the Gene Ontology offers.

When clicking on this I expect something like http://www.ebi.ac.uk/about/jobs/career-profiles/scientific-curator - perhaps we should change the heading?
```
From Alex Bateman:
```
Please clarify what “User stories” are. Perhaps change the name so users can better understand the material contained in these sections.
```

**Comment by kltm** [comment]
These will be removed from future versions of the website.
