### ISSUE TITLE
New sources for GeneDB data, need to be added back into AmiGO

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1777]
Hello, 

I have updated the links to get GeneDB data in the Datasets yaml file for GeneDB: 

https://github.com/geneontology/go-site/blob/master/metadata/datasets/genedb.yaml

We have new source links; also, GeneDB is taking back management of Plasmodium data (NCBITaxon:5833 & NCBITaxon:36329) 

@kltm 
@dustine32 
@Achchuthan 

---

[Adding action item checklist @kltm ]

- [x] change https://github.com/geneontology/go-site/blob/master/metadata/datasets/genedb.yaml( https://github.com/geneontology/go-site/pull/1776)
- [x] update links in db-xrefs-yaml (ongoing see #1778 )
- [x] Re-add Plasmodium to AmiGO loads (TODO)

**Comment by pgaudet** [comment]
Sorry I just made a new PR with corrected links, https://github.com/geneontology/go-site/pull/1780

**Comment by kltm** [comment]
Failing PR at https://github.com/geneontology/go-site/pull/1778

**Comment by kltm** [comment]
@pgaudet There was a fair amount of churn around this. could you check that all code and metadata changes related to this are linked here?

**Comment by kltm** [comment]
@pgaudet From #1778, this inconsistent:
```
      url_syntax: http://www.genedb.org/gene/[example_id]
      example_id: PF3D7_1467300
      example_url: http://www.genedb.org/gene/PF3D7_1467300
      example_url: https://plasmodb.org/plasmo/app/record/PF3D7_1467300
      example_id: Tb927.1.630
      example_url: https://tritrypdb.org/tritrypdb/app/record/gene/Tb927.1.630
      example_id: LmjF.12.1310
      example_url: https://tritrypdb.org/tritrypdb/app/record/gene/LmjF.12.1310     
```

If the `url_syntax` is `http://www.genedb.org/gene/[example_id]`, only `http://www.genedb.org/gene/PF3D7_1467300` can be valid. If there are different URLs/structures, they need to be listed as different databases.

**Comment by kltm** [comment]
- [ ] checklist test

**Comment by pgaudet** [comment]
Right I saw that; what is the procedure un this case? Do we have two sources 'GeneDB_plasmodb' and GeneDB_tritrypdb'?

**Comment by Achchuthan** [comment]
Hi @pgaudet, @kltm 

We should be changing the "url_syntax" as well as GeneDB is taken offline. 

@uliboehme, Is it worth considering changing the data source from GeneDB to VEuPathDB?

Thanks,
Achchuthan

**Comment by uliboehme** [comment]
@Achchuthan I agree it would be better to change the data source to VEuPathDB. Hope this is possible.

**Comment by Achchuthan** [comment]
@pgaudet, If adding multiple source urls for a single source (to the same yaml file) is not possible, I would be happy with having two separate yamls for PlasmoDB (P. falciparum) and TriTrypDB (Leishmania major and Trypanosoma brucei) respectively.

**Comment by kltm** [comment]
@Achchuthan @pgaudet 
Just to clarify the issue here, in case I'm misunderstanding something, for the purposes of GO the `db-xrefs.yaml` file behaves a lot like a CURIE map: a single database (namespace) needs to expand to a single URL. A single resource to different URLs isn't something that is supported. (I.e. surjective.)
If something like that is required, there are two possible paths forward:
* the database supplies it's own internal mapping, so that while we have a single expansion they disambiguate on their end; this still leaves a single database/namespace to a single URL expansion
* the database/namespace gets broken up so that there can be multiple expansions; this requires the resource to support those

This is a slightly separate consideration to how many YAMLs are used to represent a resource (or resources) in the datasets metadata. In general, if the identifier/database id is the same, it's probably a good idea to keep them in the same YAML. For example, the previous iterations of the `genedb.yaml` file.

**Comment by pgaudet** [comment]
@kltm are we all set? 

I know that @Achchuthan still needs to look into how to allow us to make links to the 2 different sites, but hopefully we are now getting data from the new source?

**Comment by kltm** [comment]
Talking to @pgaudet , this is a separate issue from #1779 , which deals with the links. We'll go ahead with re-adding the data as this links will be in the same situation either way.

**Comment by pgaudet** [comment]
Will this be added back for the upcoming release?

**Comment by kltm** [comment]
@pgaudet Are you meaning the "Feb" release or the "March" release here? For "Feb", we can cancel and retry with the data added back in, or let this one go and re-add in "March" (a day or so).

**Comment by pgaudet** [comment]
Is there still a Feb release? My point is, if we can avoid it, we dont want to go one release with no Plasmodium EXP data - that would be a big loss of data.

**Comment by kltm** [comment]
@pgaudet Understood: I'll go ahead and cancel out this release and prep this data to go in ASAP for an early "March".

**Comment by kltm** [comment]
Now re-added genedb_pfalciparum.gaf.gz. The rest should have already been in place.

**Comment by pgaudet** [comment]
New links from @Achchuthan 

Plasmodium falciparum - ftp://ftp.sanger.ac.uk/pub/project/pathogens/as44/Pfalciparum.gaf.gz
Trypanosoma brucei - ftp://ftp.sanger.ac.uk/pub/project/pathogens/as44/Tbruceibrucei927.gaf.gz
Leishmania major - ftp://ftp.sanger.ac.uk/pub/project/pathogens/as44/Lmajor.gaf.gz 

These have the correct information in Column 1 to allow to make the correct links 

@kltm let me know if you need more information.

**Comment by kltm** [comment]
I believe, for this ticket, we are set as "clearing" until we see the results on a future `snapshot` or `release`.
