### ISSUE TITLE
New link outs to GeneDB

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1779]
Hi, 

GeneDB now links to the EuPathDB portal. I made a PR here to update the link out info: 
https://github.com/geneontology/go-site/pull/1778
but I probably did something not allowed for the yaml file. 

The data should link to one of two URLs depending on the species: 
Plasmodium: 
https://plasmodb.org/plasmo/app/record/gene/PF3D7_1467300

L. major and T. brucei
https://tritrypdb.org/tritrypdb/app/record/gene/Tb927.1.630
https://tritrypdb.org/tritrypdb/app/record/gene/LmjF.12.1310

**Comment by kltm** [comment]
@pgaudet Is this not included in #1778 and #1777 ?

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-site/pull/1778 is the PR for this ticket here (**link outs to EuPathDB**). 

https://github.com/geneontology/go-site/pull/1777 is about data **sources**.

**Comment by pgaudet** [comment]
Hi @kltm 

I was trying to keep the data sources and the link outs (xrefs.yaml) separate.

For link outs, you wrote here  https://github.com/geneontology/go-site/issues/1777#issuecomment-1030392643 
you wrote 

From #1778, this inconsistent:
```
      url_syntax: http://www.genedb.org/gene/[example_id]
      example_id: PF3D7_1467300
      example_url: http://www.genedb.org/gene/PF3D7_1467300
      example_url: https://plasmodb.org/plasmo/app/record/PF3D7_1467300
      example_id: Tb927.1.630
      example_url: https://tritrypdb.org/tritrypdb/app/record/gene/Tb927.1.630
      example_id: LmjF.12.1310
      example_url: https://tritrypdb.org/tritrypdb/app/record/gene/LmjF.12.1310     
```

If the `url_syntax` is `http://www.genedb.org/gene/[example_id]`, only `http://www.genedb.org/gene/PF3D7_1467300` can be valid. If there are different URLs/structures, they need to be listed as different databases. 


----

Is it OK if we create two entries, one for PlasmoDB and one for TriTrypDB? 

 database: PlasmoDB
  name: PlasmoDB
  rdf_uri_prefix: https://identifiers.org/plasmodb
  generic_urls:
    - https://plasmodb.org
  entity_types:
    - type_name: gene
      type_id: SO:0000704
      id_syntax: PF3D7_[0-9]{7})
      url_syntax: https://plasmodb.org/plasmo/app/record/[example_id]
      example_id: PF3D7_1467300
      example_url: https://plasmodb.org/plasmo/app/record/PF3D7_1467300
  

 database: TriTrypDB
  name: TriTrypDB
  rdf_uri_prefix: https://identifiers.org/tritrypdb
  generic_urls:
    - https://tritrypdb.org/
  entity_types:
    - type_name: gene
      type_id: SO:0000704
      id_syntax: ((LmjF|LinJ|LmxM)\.[0-9]{2}\.[0-9]{4})|(Tb[0-9]+\.[A-Za-z0-9]+\.[0-9]+)|(Tb\.[0-9]{6}\.[0-9]+)
      url_syntax: https://tritrypdb.org/tritrypdb/app/record/gene/[example_id]
      example_id: Tb927.1.630
      example_url: https://tritrypdb.org/tritrypdb/app/record/gene/Tb927.1.630
      example_id: LmjF.12.1310
      example_url: https://tritrypdb.org/tritrypdb/app/record/gene/LmjF.12.1310         

I'll make a new PR with this. 

Thanks, Pascale

**Comment by Achchuthan** [comment]
Hi Pascale,

> database: PlasmoDB name: PlasmoDB rdf_uri_prefix: https://identifiers.org/plasmodb generic_urls: - https://plasmodb.org entity_types: - type_name: gene type_id: SO:0000704 id_syntax: PF3D7_[0-9]{7}) url_syntax: [https://plasmodb.org/plasmo/app/record/[example_id]](https://plasmodb.org/plasmo/app/record/%5Bexample_id%5D) example_id: PF3D7_1467300 example_url: https://plasmodb.org/plasmo/app/record/PF3D7_1467300
> 
url_syntax should be [https://plasmodb.org/plasmo/app/record/gene/[example_id]]
example_url should be https://plasmodb.org/plasmo/app/record/gene/PF3D7_1467300

> database: TriTrypDB name: TriTrypDB rdf_uri_prefix: https://identifiers.org/tritrypdb generic_urls: - https://tritrypdb.org/ entity_types: - type_name: gene type_id: SO:0000704 id_syntax: ((LmjF|LinJ|LmxM).[0-9]{2}.[0-9]{4})|(Tb[0-9]+.[A-Za-z0-9]+.[0-9]+)|(Tb.[0-9]{6}.[0-9]+) url_syntax: [https://tritrypdb.org/tritrypdb/app/record/gene/[example_id]](https://tritrypdb.org/tritrypdb/app/record/gene/%5Bexample_id%5D) example_id: Tb927.1.630 example_url: https://tritrypdb.org/tritrypdb/app/record/gene/Tb927.1.630 example_id: LmjF.12.1310 example_url: https://tritrypdb.org/tritrypdb/app/record/gene/LmjF.12.1310
> 
We have updated Leishmania infantum (LinJ) genome with a newer assembly in TriTrypDB and the identifiers are now different. An example is LINF_330027200. So, the id_syntax for this genome should be [LINF_[0-9]{9}].  
>

Thanks,
Achchuthan

**Comment by pgaudet** [comment]
Thanks, I made the changes, let me know if that doesnt seem right.

**Comment by pgaudet** [comment]
- [ ] Add GeneDB back to dbxref while PlasmoDB and TriTryDB are being sorted (need to fix the namespaces) 
- [ ] Remove ApiDB_PlasmoDB

**Comment by pgaudet** [comment]
For linking out- exchanged with @Achchuthan 

Hi Ach,
 
One other request (hopefully we’re done after this): for the links to resolve correctly, there are 2 options:
 
You change the GAF files to have the correct prefix in Column 1: PlasmoDB/TriTryDB, rather than GeneDB.
You keep GeneDB in column 1, but then you need some redirect system on the EuPathDB website.
 
Do you think one of these 2 options can be done?
 
Thanks, Pascale


---

@Achchuthan 's response: 
Hi Pascale,


I don’t think option 1 is possible as far as the Sanger FTP files are concerned. If we are to do the change with GAF files, we need to change the location to somewhere else. Sanger FTP files are automatically generated and we don’t have any developer support from Sanger anymore. 

I don’t quite understand option 2. But, we reference GeneDB as the source in PlasmoDB/ TriTrypDB.

Best wishes,
Achchuthan

**Comment by pgaudet** [comment]
This is not yet resolved (link to GeneDB cannot be automatically built from the information in the genedb yaml file). 

Ach has left the project -  Ulrike Boehme and Beatrice Amos are now taking care of the project.

**Comment by kltm** [comment]
Closed for https://github.com/geneontology/go-site/issues/2256
