### ISSUE TITLE
Plan replacement for go-help jira instance

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#178]
We should either spin up a new instance, or consider an alternate technology (e.g. one that plugs into github like zendesk)

**Comment by monicacecilia** [comment]
https://www.zendesk.com/

**Comment by kltm** [comment]
An ideal solution would be:
* Open source
* Easily migratable and exportable
* Contain some project management with external user/issue tracking
* [Others?]

As part of this migration, I would suggest activating the domain help.geneontology.org for the Helpdesk interface and ensuring (as well as enumerating) help at geneontology.org (and other) are easily aimed at other targets.

**Comment by cmungall** [comment]
* https://github.com/rossp/django-helpdesk -- but does not appear to integrate with github
 * https://github.com/Taskulu/deskulu -- if we were sticking with drupal

Trac appears to offer github integration: https://github.com/trac-hacks/trac-github

Some open sources options in the 2nd list here: http://blog.capterra.com/the-7-best-free-help-desk-software-tools/

**Comment by kltm** [comment]
I think we want to get away from Drupal as fast as possible. Django-based apps are going to have a lot of the same issues.
More practically, we want somebody to offer hosting or to have an integrated stack.
Also note: https://devzing.com/
Also, OTRS and Apache Bloodhound (Trac derivative). It's amazing how long some of these projects have been around.

I think Trac (or derivative) may be worth looking at more seriously. It has been long enough since we tried a bunch of them out that's it's not appearing in my notes. but I don't remember any of them being particularly hard.

I would suggest though looking at not hosting ourselves. If we go that route, we need to make sure we have our own access to the backups, etc.

**Comment by tberardini** [comment]
It's Feb 1, 2016.  The current GO JIRA helpdesk instance went down a couple days ago and we resuscitated it.   How goes the plan for a replacement by March 1, 2017?

**Comment by kltm** [comment]
I think we're circling towards more robust documentation, FAQs, and community forums.

**Comment by tberardini** [comment]
Okay.  We'll plan to make a backup copy of the JIRA helpdesk data (I think in XML) so you can have that FWIW.

**Comment by kltm** [comment]
That's good--we may also want to go the route of indexing the emails and making them available as well, etc.

**Comment by monicacecilia** [comment]
@cmungall @kltm the countdown to 2017-03-01 is at t-48 hours. Are there details about progress on this front we should be aware of? Perhaps described somewhere else?

**Comment by cmungall** [comment]
Is the current plan to create a new repo, go-helpdesk, and change the website to point at this?

**Comment by kltm** [comment]
Well, this is a start. We'll want to have more information there:
 https://github.com/geneontology/helpdesk
Ideally, we'll also want to have the the helpdesk email go to an appropriate "vacation" message.

@tberardini How is the backup/archive coming along? Are you still slating the March 1st shutdown?

**Comment by kltm** [comment]
Also, we need to update the drupal site, etc. to just UI forward over to the GitHub helpdesk.

**Comment by kltm** [comment]
Also, any issues that are open probably need to be marked so they can be ported.

**Comment by tberardini** [comment]
@kltm We're planning to backup/archive on March 1st.  We can probably keep it alive a bit longer if you need it but really want to shut that instance down ASAP.  With Bob retiring very soon, the knowledge will go with him.

**Comment by kltm** [comment]
@stuartmiyasato I think we touched bases on this at the meeting a couple of weeks ago:
https://github.com/geneontology/go-site/issues/313
How hard would it be, and how long would it take, to put a "vacation" message onto the go helpdesk email addresses?
@cmungall As we are traveling on the 1st, this will be a little tricky to coordinate. AmiGO, fortunately, still goes through the wiki, so that's easy, and I can get drupal quickly as well. That leaves ~21 issues that are open in the tracker. Could you give them a quick look over and see if we can close them out before the transition? That would make it a lot easier.

**Comment by kltm** [comment]
@stuartmiyasato Okay, I've talked with @cmungall and I think we are going to go ahead with shutting down the helpdesk immediately. Thinking about our conversation, you're not allowed to have "personal" accounts for your email at Stanford, so we'll need to have a secondary email address that you'll forward to. I'll get that setup somewhere now.

**Comment by kltm** [comment]
Okay, trying to setup a "vacation" message now:
```
Thank you for contacting the GO Helpdesk

Dear GO Helpdesk User,

Thank you for contacting the GO Helpdesk.
In an effort to consolidate our efforts and better serve the community, we will be transitioning the current GO Helpdesk system to using a public GitHub tracker. We invite you to open at ticket on our tracker at:

 https://github.com/geneontology/helpdesk/issues

Once opened, you will be able to track responses to your issue and follow the process from end to end. With this transition, we hope to be able to be more open and responsive to our wonderful community.

Best wishes,

The GO Helpdesk Team
```
Everybody good with this text?

**Comment by kltm** [comment]
This (GMail) is not working as expected/desired. I'm going to try another approach, completely different.

**Comment by kltm** [comment]
Okay, new plan--vacation bounces through GMail are being agressively being rejected early on.

Taking a quick browse, it seems like the *vast* majority of tickets are coming in through the Drupal form. Really then, we do not need an email address at all--almost everybody who is contacting is through the form anyways, so forwarding email doesn't serve much point.

I will update AmiGO and Drupal with the message above; @stuartmiyasato could you go ahead and direct the gohelpdesk emails to my lbl.gov account? I'll go ahead and take care of anybody who has somehow gotten that address and is getting around the form (although @tberardini might have a better idea about that number).

**Comment by kltm** [comment]
First pass at labels: https://github.com/geneontology/helpdesk/labels

**Comment by tberardini** [comment]
@kltm : on the volume of help desk tickets through drupal vs. other sources.  99% through the website, 1% from the email address (mostly Val).

**Comment by tberardini** [comment]
more labels: (from JIRA, add those you like)

Enrichment Analysis
Website
Out of Scope for GO
Internal Discussion
GO Slim
Third Party Tools


I'd add them myself but couldn't figure out how to do it quickly.

**Comment by kltm** [comment]
Cheers!

@tberardini Since the use-vacation-message-through-gmail idea didn't work, my second idea was to just have the email to redirect directly into some other account that we control since it is mostly, as you say, the form and Val, and I can get Val to the right spot. The one hiccup I see in that plan is that the *spam* volume might be quite high. Is there any way for you to see the direct spam volume going over that email address?

**Comment by kltm** [comment]
The AmiGO wiki link and Drupal site now both direct people towards the GitHub "helpdesk".
Email issues TBD, but I believe that there really should be no new tickets coming in to JIRA.

**Comment by monicacecilia** [comment]
@kltm great! thanks for the update. Also, I could help with adding labels, but I need permissions.

**Comment by kltm** [comment]
@tberardini The email currently goes to you, correct? Another option would be to setup the responder there. That might not help with the rejects, etc.

**Comment by kltm** [comment]
@monicacecilia Yes, we should probably sit down and talk about what's best with @cmungall ; hopefully we can make it a nice tight finite set.

**Comment by kltm** [comment]
@tberardini @cmungall @monicacecilia 
Putting aside the email for a moment, the remaining outstanding issue is the dump (history) and current open issues.

**Comment by stuartmiyasato** [comment]
Very sorry @kltm -- I missed your message earlier!  go-helpdesk@geneontology.org is now pointing to your lbl.gov address.

**Comment by kltm** [comment]
@stuartmiyasato Cheers. I guess we'll see if that catches fire ;)

**Comment by tberardini** [comment]
@kltm Do you still need me to do anything with the 'local' email address we have (go dash helpdesk at arabidopsis dot org)?  Sounds to me like Stuart has redirected already.

**Comment by tberardini** [comment]
Re: open tickets

I suggest creating new github tickets for all the remaining open ones that cannot yet be closed.  However, for most of them, I suspect the users don't have github accounts so we/you'll have to keep corresponding with them through email and copying the responses to GH (either by cc'ing or copy/pasting) for tracking purposes.

**Comment by kltm** [comment]
@tberardini @stuartmiyasato I /think/ we're good. Now, that said, I have not gotten any of my test emails yet. Would you all mind trying to email that address?

**Comment by tberardini** [comment]
Sent email to go dash helpdesk at geneontology dot org

**Comment by monicacecilia** [comment]
Same here.

**Comment by kltm** [comment]
No cookies available, but both of your texts got through. Thanks!

**Comment by kltm** [comment]
@tberardini 
Well, I've tried to get people to rally around the last 13 on JIRA, but I don't know how well that will go.
As we'Il be flygin tomorrow, if you don't mind, could you close anything remaining off tomorrow with a message like:

```
GO Helpdesk User,

Our apologies that we were not able to get back to you in a timely manner. We are transitioning to a new public issue tracker for working with the community. If you are still interested in following up on your query, please feel free to sign onto GitHub and open an issue on our new tracker: https://github.com/geneontology/helpdesk .

Again, our apologies and thank you for your understanding.

Best wishes,

-The GO Helpdesk Team
```

**Comment by tberardini** [comment]
@kltm 
Will do!

**Comment by kltm** [comment]
Whoops! AmiGO's "data health" tag was still pointing at the old form. I went ahead and set the old form URL forward to GitHub in drupal.

**Comment by tberardini** [comment]
Ok. All issues closed out and message sent to the users as above.

**Comment by monicacecilia** [comment]
Thanks to all of you for moving so quickly on this. This morning I updated GO-managers & GO-directors (by extension) on progress & pointed everyone to Seth's updates on 'how to reach the GO'. 
Dang. Y'all are rockstars.

**Comment by tberardini** [comment]
GO JIRA backup/archive has been created and made accessible to Seth.

**Comment by tberardini** [comment]
I also updated the wiki.

http://wiki.geneontology.org/index.php/Gohelp

**Comment by kltm** [comment]
Cheers!

**Comment by kltm** [comment]
*please don't remove the downloasds yet*
I've poked around the files a little (items back to 2013), and it seems that "stuff" is there, but I haven't made any attempt at parsing enough to know how easy it would be to jimmy into GitHub (or something). 
*If* I said I had the files, is your intention to bin the whole thing, or is it living in archive with the rest of your data? I'm just trying to figure out how ginger I need to be with what we have at this point.
Thank you for getting us the files!

**Comment by kltm** [comment]
@cmungall I've been playing around with saxonb and an xslt to get it into something that is workable:
```
sjcarbon@moiraine:~/local/src/git/xsltjson[master]$:)  java -classpath /usr/share/java/saxonb.jar net.sf.saxon.Transform entities.xml conf/xml-to-json.xsl > /tmp/gohelp.json
```
The short of it so far is that: 1) I think that feeding this all into GitHub may be a reasonable thing to do, but 2) whether we want to use GitHub as an archive for this info is debatable (I think the continuity might be nice), and 3) I'm not sure how much of the old helpdesk data we want to preserve--it's detailed down to marking anybody even seems to have sniffed an item. That last point may be the largest potential time sink, assuming that we could piggyback on what you already tried to do with the previous ticket transfer.

**Comment by kltm** [comment]
Exploration fun:

: jq '.["entity-engine-xml"] | keys' /tmp/gohelp.json
: jq '.["entity-engine-xml"]["Issue"] | length' /tmp/gohelp.json
: jq '.["entity-engine-xml"]["Action"] | length' /tmp/gohelp.json

Accordingly, we seem to have ~4k "actions" over ~1k tickets, meaning that we'll need to stream ~5k items into GitHub (or wherever). We also have easy access to the user names for these things, so if there was a mapping from JIRA to GitHub IDs, we could even still store the credits, etc., which would be nice.  I think sprinkling the dates in there would be nice as well. It would be pretty easy to use `jq` to process this into a first pass for uploading, but it might be good to sleep on it first (long day).

We also got the attachment archive, much larger than the text archive, but I think that could go away without too much fuss.

**Comment by tberardini** [comment]
> If I said I had the files, is your intention to bin the whole thing, or is it living in archive with the rest of your data? 

Our intention is to bin the whole thing.  I can keep the archive files around but the application itself (jira.arabidopsis.org) will go dark very soon.

**Comment by kltm** [comment]
Okay, good, I think we're on the same page. When I said "bin", I meant the data, not the site (which could theoretically always be reconstituted from the data). If you could archive the files, that would be great. I currently have a copy on one server and my personal machine, but accidents happen and I want to make sure there is a backup for a bit longer.

If you are going to have an archive, I think we're good at this point to shelve the system. Ideally, if you you could flick it off for a few days before putting the disk into the wood chipper, that would be preferred just to make sure that nobody is going to have any last minute regrets. Understood though if that isn't going to work out--the offsite archive of the core 30mb is what we're most interested in right now.

**Comment by tberardini** [comment]
Say goodbye...jira.arabidopsis.org is gone.  I'll keep the archive around, though probably not in the spot where it is now.

**Comment by kltm** [comment]
Great--thank you!

**Comment by monicacecilia** [comment]
buh-bye jira...

**Comment by tberardini** [comment]
Moved files to my work Dropbox.  This will be the third location until the backup becomes unnecessary or I need to clear out space. :)

Tanya/GO JIRA files.

**Comment by kltm** [comment]
Great--thank you! (original expression of thanks, not a copy-paste from above)

**Comment by kltm** [comment]
For the time being, I've also pushed these into a private repo for both archival purposes and working out how to get them loaded into the new helpdesk repo as history.

**Comment by kltm** [comment]
@cmungall @monicacecilia 
Please take a look at: https://github.com/kltm/go-helpdesk-staging/issues/9
This is the current upload pattern I've put together. I am currently losing the time and the tags. For the former, I'd like to talk about if they are necessary and at what resolution (I'd model them using GH Milestones); for the latter, I'd create a mapping from what we have to the current list, so I'd need some feedback there (is we want to preserve tags).

**Comment by monicacecilia** [comment]
@kltm I see a date at the beginning of each issue, but I think you mean the time "when" it was created as some sort of sorting tool. 
I guess it could be useful to have them divided in some sort of chronological order, but I don't think it would be a show stopper if they are not, as long as we can browse & query the contents in some way. 
In my opinion it would be okay to split them up into milestones that cover about the same amount of time that runs between GOC meetings: half year or even full year batches? Does this address your question appropriately?

**Comment by kltm** [comment]
Paola did something weird on the first one, try this one as an example:
https://github.com/kltm/go-helpdesk-staging/issues/11

**Comment by monicacecilia** [comment]
Got it.

**Comment by kltm** [comment]
@monicacecilia Yes, by "time" I meant binning them into milestones at some resolution for reports (just catching @cmungall up on what we talked about yesterday). I don't think we'll be able to query the documents for time-as-string very well, but at least they are there in this first pass.

**Comment by monicacecilia** [comment]
Well, I think the milestones will be a 'nice to have' but not indispensable. The fact that we can even keep the messages is amazing, and if we can try to browse through the contents, it will be great. 

Ha, of course, in retrospect we are all going to wish all of GO rota had renamed a ticket every time we responded... I know I forgot to do it occasionally. :bowtie:

**Comment by kltm** [comment]
Thoughts about label/tag mapping?

**Comment by tberardini** [comment]
I *tried* to get people to rename. You can lead a horse to water...

**Comment by kltm** [comment]
@cmungall is going to run this by managers next week, so I'm putting a pin in this until then.

**Comment by kltm** [comment]
Just as a general note about the potential import of old tickets:
* I've already scrubbed out anything that looks like an email address
* I've removed all non-public activity (only responses to users are included, not internal chatter)
* GO Helpdesk usernames and questioner names still crop up, but are not linked
* Links to old trackers and systems are still present for reference
* If imported into github, they would be indistinguishable from new tickets (although obviously already closed)
* While we preserve the dates as strings, date searches would not really work; instead, we could bin them by biannual milestones 
* This would give us a continuous, unbroken, and public helpdesk history back to 2013

**Comment by kltm** [comment]
http://help.geneontology.org is not setup and running.

**Comment by kltm** [comment]
Updated everything I have access to to either point directly to the new URL or to one of the Drupal 301ed locations.

**Comment by kltm** [comment]
Well, there is some worry about having even the scrubbed helpdesk data being made public and searchable, so we are going to table the upload for the time being. I've uploaded the archive (unscrubbed) and the json for the upload script (scrubbed) into the private https://github.com/geneontology/go-internal repo, under archive/helpdesk, along with the tools written to do the uploading if we come back to it.

With that tabled, there is nothing more to do here.
