### ISSUE TITLE
Change rdf_uri_prefix from registry entry to entity entry

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1788]
Some entries in db-xrefs.yaml have the incorrect `rdf_uri_prefix` (registry identifer vs entity identifier). As an example, we want to switch these from

`  rdf_uri_prefix: https://registry.identifiers.org/registry/maizegdb.locus`

to 

`  rdf_uri_prefix: 	https://identifiers.org/maizegdb.locus`

**Comment by kltm** [comment]
Work in https://github.com/geneontology/go-site/pull/1787

**Comment by kltm** [comment]
From an email thread with @cmungall @balhoff and @pgaudet , this field is not apparently currently used and could possibly be removed altogether (not sure of the timeline there though).

**Comment by pgaudet** [comment]
Thanks!
