### ISSUE TITLE
Add ontology statistics / graphs page

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-site#179]
AI from Geneva GOC meeting

Track quarterly, in addition to cumulative stats
AI: GOC to extract this data and display annual stats on web page
discuss with GOC members
AI: GOC extract ontology stats
Also add input into ontology structure, e.g. adding/updating terms

**Comment by kltm** [comment]
It would be good to get what numbers or axes people want to see. In the end, this is likely to be bundled into AmiGO somehow, but can leave here until there is a clear work order.

**Comment by kltm** [comment]
Statistics are now included in/provided by AmiGO. Concrete action should be re-opened on the geneontology/amigo tracker.

I'm not sure where this falls, but would like to see progress or bumping it.

**Comment by mcourtot** [comment]
do you have a specific link/example? I think it would be nice to maybe bring this to a manager call and see if this address their use case for reporting, and whether there are any further desiderata.

**Comment by kltm** [comment]
http://amigo.geneontology.org/amigo/base_statistics
Maybe, but we have a lot of tickets about this, and I'd like to consolidate. Maybe to here: https://github.com/geneontology/amigo/issues/364

**Comment by kltm** [comment]
Now #842
