### ISSUE TITLE
Change fail mode to GORULE:0000016 With/From: IC annotations require a With/From GO ID

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1794]
'GORULE:0000016 With/From: IC annotations require a With/From GO ID'  is causing a large decrease in the number of ComplexPortal annotations because they use ECO:0005547, which maps to IC, but they do not provide 'with' data. 

We will change the fail mode from 'filter' to 'report', to allow annotations to pass until we figure out how to resolve the problem.

https://github.com/geneontology/go-site/pull/1793

---

[Apologies @pgaudet , hijacking top comment so we can get a checklist with a completion, @kltm ]

Metadata PR open, still need to:

- [x] check through the ontobio and update to "soft"? https://github.com/biolink/ontobio/pull/614
- [x] update any tests <br /> are there tests for this somewhere? guess we'll see if the PR passes
- [x] make a new release
- [x] update the pipeline with new ontobio release version
- [x] merge the metadata PR

Tagging @dustine32 @sierra-moxon

**Comment by kltm** [comment]
Metadata PR open, still need to:

- [ ] check through the ontobio and update to "soft"? https://github.com/biolink/ontobio/blob/34924740c19fc92403ee1dcfa3e34c6725a276ec/ontobio/io/qc.py#L346
- [ ] update any tests
- [ ] make a new release
- [ ] update the pipeline
- [ ] merge the metadata PR

Tagging @dustine32 @sierra-moxon

**Comment by kltm** [comment]
@dustine32 @sierra-moxon I believe the only thing we need here is enum "HARD" on that line to go to enom "SOFT", then a release. Is that something that one of you could help ferry through? (I'd volunteer, but it will take me more time to remember the release procedure than to get the work done.)

**Comment by kltm** [comment]
PR https://github.com/biolink/ontobio/pull/614

**Comment by kltm** [comment]
@dustine32 @sierra-moxon Apologies, we're waiting for a confirming response from @vanaukenk and @suzialeksander before proceeding (or a second confirmation from @pgaudet ).

**Comment by dustine32** [comment]
@kltm Cool, I just adjusted the tests in https://github.com/biolink/ontobio/pull/614 to get it to pass. I can merge, release, and update the pipeline reqs.txt when we get the thumbs up.

**Comment by pgaudet** [comment]
Looks good to me. 

Thanks, Pascale

**Comment by kltm** [comment]
@dustine32 Great--thank you. Now merged.

**Comment by kltm** [comment]
Merged @pgaudet 's change as well; should be good for Tuesday.

**Comment by dustine32** [comment]
@pgaudet With the latest 2022-03-02 `snapshot`, the [report](http://snapshot.geneontology.org/reports/goa_human-report.html#gorule-0000016) for goa_human (as an example) shows that GORULE:0000016 has been changed to a WARNING and the offending lines are no longer being filtered out of the final `goa_human` annotation files (e.g. [goa_human.gaf.gz](http://snapshot.geneontology.org/annotations/goa_human.gaf.gz)). Feel free to close this ticket if you think it is done now.

**Comment by kltm** [comment]
Since that's pretty objective, let's just close for now and reopen if it crops up again.
