### ISSUE TITLE
Decide location for `gorefs.yaml` file

### ISSUE THREAD

**Issue by sujaypatil96** [geneontology/go-site#1804]
After completing issue #1803, decide where within this repo the file should be stored.

Should it be stored in the `metadata/gorefs` folder of the root of this repo? Or is there some other better location to store this file?

CC: @kltm

**Comment by kltm** [comment]
Looking at where our other stuff is, /metadata/gorefs.yaml makes sense to me.

**Comment by kltm** [comment]
Done here!
