### ISSUE TITLE
Add automatic schema checker to validate `gorefs.yaml`

### ISSUE THREAD

**Issue by sujaypatil96** [geneontology/go-site#1805]
After completing both issue #1803 and #1804, we need to add a schema checker, which should be a JSON Schema file that validates any future modifications made to the gorefs.yaml file in a Github Action step.

We can break out the tasks for this issue into two steps:

- [ ] Create JSON Schema file that appropriately describes the structure of the data that should be present in the gorefs.yaml file
- [ ] Add jsonschema CLI validate command to Github Actions so it verifies the correctness of file after every modification to it

**Comment by kltm** [comment]
To fit with the current naming conventions, unless there is other mechanism needed or reason otherwise, /metadata/gorefs.schema.yaml would be fine here.

**Comment by kltm** [comment]
Closing out in preference for new worklist
