### ISSUE TITLE
All Plasmodium falciparum 3D7 annotations are missing from the 2022-02-24 release candidate

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1807]
@kltm @dustine32 

It looks like the file from GeneDB was not loaded? Can you please check?

**Comment by kltm** [comment]
@pgaudet I believe this is an ongoing dupe with https://github.com/geneontology/go-site/issues/1777.

**Comment by kltm** [comment]
Basically, there has been a lot of data churn and this has not yet been re-added.
