### ISSUE TITLE
SGN data on FTP not currently available; FTP connection not working

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1811]
@nmenda

From about 2022-03-04, we have been having trouble contacting the solgenomics FTP server. Specifically, we have been unable to download ftp://ftp.solgenomics.net/ontology/GO/gene_association.sgn.gz (in our sgn.yaml metadata file). We were wondering if this was a temporary outage, or if maybe the file/service had been moved?

Tagging @pgaudet

**Comment by nmenda** [comment]
@kltm 
our FTP files were recently moved. 
The files are now at https://solgenomics.net/ftp/ontology/GO/

**Comment by kltm** [comment]
@nmenda Great, thank you for the update.

**Comment by kltm** [comment]
Waiting to clear on `snapshot` success.
