### ISSUE TITLE
Migrate current Google Drive to new Google Shared drive

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1813]
We have had a good start on migrating to a new shared GO Google Drive and want to continue the momentum, completing the migration as quickly as possible to prevent confusion.

The process here is non-destructive, so no worries on that front. However, we want to prevent multiple copies of a file existing whenever possible to prevent document drift. As well, we want to move files, rather than copy (or download/upload them) to prevent the same document existing in multiple editable locations (and causing drift).

- [x] @cmungall to change the name of "Gene Ontology (NEW SHARED DRIVE)" to something like "FIRST DRAFT SHARED DRIVE - DO NOT USE FOR NEW WORK"
- [x] @cmungall to create a new shared Gene Ontology with a name like "Gene Ontology"; this newest shared drive is where we will move documents and where all new work should go
- [x] @cmungall to announce to go-managers that this has been done
- [x] copy _users_ from old shared drive to `go-consortium` list/group; managers should be added at top level with higher privs <br /> managed to add most, but not all, of managers--need gmail/google account
- [ ] GO managers are to move (not download and upload or otherwise copy) any files they own to the newest shared drive ("Gene Ontology"); this should be sooner rather than later to help prevent confusion (and so are can remove or otherwise mothball the previous two drives). This will preserve all of the links that we have built up. Please recreate and file hierarchy as you go. Check your name off when you've completed your move
  - [x] @suzialeksander  
  - [ ] @cmungall 
  - [x] @kltm
  - [x] @pgaudet 
  - [ ] @huaiyumi 
  - [ ] @vanaukenk 
  - [x] @ukemi 
  - [ ] @thomaspd 
  - [x] Helen
  - [x] Ruth
  - [x] Patrick Masson
  - [x] Colin
  - [x] Val
  - [ ] (ADD MORE NAMES HERE)
- [ ] Once all of the go-managers have moved their files to the newest drive, look to see what other users we can contact to move their files to the newest drive ("Gene Ontology")
- [ ] Do a file listing of the three drives and compare the results to see what still needs to be moved (@kltm or @cmungall )
- [ ] Contact remaining users to move their files
- [ ] For users that cannot be contacted or cannot be contacted in a timely way, _copy_ their files over, marking in their old files the new location or renaming the file to make it clear about the change
- [ ] Do a final file listing comparison (@kltm or @cmungall ) to ensure we have moved or copied anything we want
- [ ] Figure out the best way to rename/disable/mothball the two previous drives (explicit "hide" and "delete" options are available as well)
- [ ] Enjoy not having to think about this for a while

Please edit this checklist here as new items get added or are changed.

**Comment by kltm** [comment]
As discussed, have started copying _users_ from from old drive share settings to the `go-consortium` list/group; unfortunately, I 1) hit the daily limit halfway through and 2) accidentally was copying to a different mailing list. Will try again tomorrow.

**Comment by kltm** [comment]
Managed to move a few more users, but quickly hit the 
```
An error occurred
Failed to add members, you have exceeded your daily limit. Please try again later.
```
error again. Will try again after 5pm tomorrow.

**Comment by kltm** [comment]
Okay, I've "successfully" attempted to re-add all previous users of the shared drive to the `go-consortium` group. Many, were duplicates and got dropped. The group now has 94 members (which can certainly be trimmed down).

**Comment by kltm** [comment]
I've managed to add some, but not all, of the go-managers to the top-level "Manager" status. I believe that requires a gmail address/google account? If there are alternate address that can be used, please let me know on the next call.

**Comment by kltm** [comment]
On request from @pgaudet, I believe I've locked out all non-GO-managers users that were not already at the top-level from the previous transfer attempt ("FIRST DRAFT SHARED DRIVE - DO NOT USE FOR NEW WORK (Gene Ontology)").

**Comment by suzialeksander** [comment]
Pinging @cmungall @huaiyumi @vanaukenk @thomaspd as I think you still have unmoved files, thanks.

**Comment by vanaukenk** [comment]
@suzialeksander I'll work on moving more files today.

**Comment by kltm** [comment]
@suzialeksander My understanding from the call today is that we are in the last two steps of the original checklist.
For the two drives in question ("LEGACY Gene Ontology -use Shared Drive" and "FIRST DRAFT SHARED DRIVE - DO NOT USE FOR NEW WORK (Gene Ontology)"), only @cmungall and @kltm should have write access to these drives.
