### ISSUE TITLE
Temporarily suspend aspgd, to enable pipeline use (IEA threshold crossed)

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1820]
Recently, our frozen (https://github.com/geneontology/go-site/blob/d5edb01de7e1c641803bed994427a6ea889bb2eb/metadata/datasets/aspgd.yaml#L19) aspgd resource crossed an important IEA threshold, eliminating a lot of annotations:

```
$ grep -v -e "^\!" aspgd-src.gaf | grep 20200401 | cut -f7,14 | sort | uniq -c
425638 IEA	20200401
76744 ND	20200401
```
(from @dustine32)

Since this triggers the sanity checks, it prevents pipelines from running. To make sure we're still able to examine products while this is being looked at, the sanity check for aspgd is temporarily being relaxed.

Tagging @pgaudet

**Comment by kltm** [comment]
This can be closed once a more "permanent" solution or ruling is found for aspgd.

**Comment by pgaudet** [comment]
Please load the old file until GOA processes this data 

@alexsign

**Comment by cmungall** [comment]
@alexsign - should we produce a spearate goa_asp file?

**Comment by kltm** [comment]
From thread with @pgaudet and @cmungall , for the moment we'll:

1a) remove the aspgd.yaml file from our metadata--no longer filter those canonical species from goa_uniprot_all
1b) remove from amigo load--remainder from goa_uniprot_all_noiea will get loaded

When/if a goa_asp file is made available, we'll switch to that solution.

**Comment by kltm** [comment]
This has passed into production.
