### ISSUE TITLE
Improve the explanation for "Statistics"

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/go-site#183]
From Helen Parkinson:
Improve explanation of statistics, for example to clarify that these are available for different species.

**Comment by kltm** [comment]
I'm not quite clear in the action here. This was for the geneontology.org homepage, IIRC. As well, there was something about using a better image there so things did not look like they were "decreasing" over time.

**Comment by kltm** [comment]
Statistics are now included in/provided by AmiGO. Concrete action should be re-opened on the geneontology/amigo tracker.
