### ISSUE TITLE
Some valid rules are not being reported in /reports/gorule-report.html

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1842]
For example gorule-0000003.md (Annotations to 'binding ; GO:0005488' and 'protein binding ; GO:0005515' should be made with IPI and an interactor in the 'with' field)

Need to look at which other rules should be reported.

**Comment by kltm** [comment]
As a part of this, maybe we can review the metadata in the rules and make sure that everything is up-to-date.

**Comment by pgaudet** [comment]
In progress here: https://docs.google.com/spreadsheets/d/1rCc2UL1IDDpyqc3Lp-Wuu9onzbWCeySEBfq59o4_0KI/edit#gid=552959064

**Comment by pgaudet** [comment]
Dup of  #2039
