### ISSUE TITLE
Add .github repo

### ISSUE THREAD

**Issue by nlharris** [geneontology/go-site#1859]
Chris M suggested adding a .github repo to our GitHub orgs. I think geneontology could benefit from this. With a .github repo, you can make the org home page (in this case, https://github.com/geneontology) look nicer and more informative--for example, you can explain the overall purpose of the org, and point to some of the most relevant repos.

How-to: https://www.freecodecamp.org/news/how-to-use-the-dot-github-repository/ 
Example: https://github.com/dandi (see https://github.com/dandi/.github/tree/main/profile)

BTW, apologies if this request already exists somewhere -- searching the issues for ".github" did not yield useful results.

Also, I wasn't sure which of the many repos to post this in, since it's kind of a meta-issue. Feel free to move it somewhere more appropriate!

**Comment by nlharris** [comment]
Done - see https://github.com/geneontology/.github/blob/main/profile/README.md (and please edit as much as you want).
For some reason, it didn't offer me the option of making a PR; it would only let me commit directly.

**Comment by kltm** [comment]
thank you for taking the initiative there and helping us out, @nlharris !
