### ISSUE TITLE
PomBase metadata for GPI appears to be incorrect

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1869]
Currently the GO metadata for PomBase lists https://www.pombase.org/data/annotations/Gene_ontology/pombase.gpi.gz
 for the GPI file (https://github.com/geneontology/go-site/blob/078be2d18c779fa99e70aad0d341f38a285328a1/metadata/datasets/pombase.yaml#L35). However, this URL is currently returning a 404 error:

```
sjcarbon@moiraine:/tmp$:( wget https://www.pombase.org/data/annotations/Gene_ontology/pombase.gpi.gz
--2022-06-08 13:02:20--  https://www.pombase.org/data/annotations/Gene_ontology/pombase.gpi.gz
Resolving www.pombase.org (www.pombase.org)... 149.155.131.177
Connecting to www.pombase.org (www.pombase.org)|149.155.131.177|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-06-08 13:02:20 ERROR 404: Not Found.
```

It would appear that either this URL is temporarily not being populated or that the location has changed without an update to the metadata.

Tagging @ValWood @pgaudet

**Comment by ValWood** [comment]
@kimrutherford

**Comment by kimrutherford** [comment]
Sorry about that.  It's fixed now.

**Comment by kltm** [comment]
Great--thank you!
