### ISSUE TITLE
Add Xenbase output to PAINT upstream

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1889]
We are currently trying to add Xenbase as a regular resource to the GO pipeline and they are interested in having their PAINT annotations streamed in. In order to accomplish this we'll need to have them made available at the other current resources on the FTP:
```
ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_cgd.gaf.gz
ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_chicken.gaf.gz
ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_dictyBase.gaf.gz
ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_ecocyc.gaf.gz
ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_fb.gaf.gz
ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_human.gaf.gz
ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_mgi.gaf.gz
ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_other.gaf.gz
ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_pombase.gaf.gz
ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_rgd.gaf.gz
ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_sgd.gaf.gz
ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_tair.gaf.gz
ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_wb.gaf.gz
ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_zfin.gaf.gz
```
I'm not sure is they are currently in "_other", but at least for testing it would be good to have a gene_association.paint_xenbase.gaf.gz made available. I'm not sure if there needs to be a coordinated switch or if it's possible to stage this.

Tagging @dustine32 @malcolmfisher103 @pgaudet

**Comment by dustine32** [comment]
@kltm Yep, they are currently in `gene_association.paint_other.gaf` but it wouldn't be too difficult to setup a PAINT test location with a separate `gene_association.paint_xenbase.gaf.gz` file.

**Comment by kltm** [comment]
@dustine32 Perfect.
So how is the transition best handled? They may depend on how fast you can toggle between states.
What we were looking to do is test the final Xenbase file (upstream + PAINT + Noctua) and then lock them into their final state for release. Should we point to the mock file you make and then just let you know when we want to ramp towards the final production stance?

**Comment by dustine32** [comment]
@kltm Sure. To test I think you only need to update the `_other` and add a new entry for `_xenbase` in the `paint.yaml`. New files are there now. The test URL is:
ftp://ftp.pantherdb.org/downloads/paint/test/15.0/2022-07-29/presubmission/

I'll also bring this up with @huaiyumi and @thomaspd next week.

**Comment by kltm** [comment]
From @dustine32 , will now test with:
ftp://ftp.pantherdb.org/downloads/paint/test/15.0/2022-07-29/presubmission/gene_association.paint_other.gaf.gz
ftp://ftp.pantherdb.org/downloads/paint/test/15.0/2022-07-29/presubmission/gene_association.paint_xenbase.gaf.gz

**Comment by kltm** [comment]
Now testing in pipeline `issue-go-site-1434-add-xenbase` branch.

**Comment by kltm** [comment]
Currently, it looks like http://skyhook.berkeleybop.org/issue-go-site-1434-add-xenbase/annotations/xenbase.gaf.gz now contains IBAs--that likely means that PAINT annotations are now getting properly layered in.
Tagging @malcolmfisher103
