### ISSUE TITLE
Migrate all of GO from SVN, preserving CVS history

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#189]
# Considerations
### VCS History

We have complete history in CVS. However, CVS has been read-only for a long time, some new files may not have been mirrored in CVS.

We created the SVN repo fresh and did not bring history. Thus importing SVN will not bring across full history.

History is highly useful for the ontology, at the level of granularity of the commit message. It is also of a lot of use for the associations - some collaborators have done impactful studies on change in go looking at these. However, individual commit messages are rarely informative, and the granularity could be yearly

For other portions of content, an unbroken VCS history is of more modear
### File sizes

Git complains at 50M and GitHub has a 100M limit. 

Note that importing from SVN using the GitHub web importer, GitHub will auto-create LFS files/links.

See for example: https://github.com/cmungall/desktop-phenote (which accidentally had a 250mb jar checked it)

However, the resulting repo can take a long time to check out.

Ontology specific considerations:

Currently the obo source for GO is 36M. It would be larger if we switched from .obo to an official .owl syntax, but there is no reason for us to do that (advanced axioms go in imported files).

We may be able to work with LFS for some file types, but for certain things like ontology files, diffability is non-negotiable, which AFAICT negates LFS
### Coherency

In svn everything is in one mega-repo

For GitHub it's better to be granular. 

We have already migrated the sf tracker to https://github.com/geneontology/go-ontology. Ideally the existing ontology/ directory would go here for maximum coherency (we want to hash-mention tickets in commits etc). But note we have already started a VCS history for this repo...

We have already started moving some utilities: #85 

For GAFs, the data collection WG is coming up with a plan

Other  directories in svn can either be deprecated or are less of a concern
### Http sync

A subset of top level directories are synced with a filesystem and are browsable via http (requiring tricky redirects to avoid falling into drupal)

The most important ones are
- http://geneontology.org/ontology/
- http://geneontology.org/gene-associations/
- http://geneontology.org/xml-dtd/ (yes, lots of people complain if this doesn't work)
### GitHub vs GitLab

@kltm recommends gitlab.

Note that because we already have the go-ontology tracker on github, and we want to colocate tracker and repo,  we would either have to migrate from github, or have a hybrid approach (e.g. ontologies on github, other stuff on gitlab). See Coherency above, we would ideally not split.
# Import Tools

There are various tools like `git svn`

The GitHub importer does an excellent job, even creating LFS for large files. However, it will not handle CVS
# Approach

We will break up the existing svn into separate repos. Different approaches can be applied for each. E.g. as mentioned above we already have the go-ontology repo set up.

For go-ontology we will endeavour to preserve full history to the commit back to the beginning.

Some top level directories will be subsumed into others. E.g. external2go belongs inside go-ontology. Preserving unbroken history may be hard when moves are made. As a compromise, we can import external2go, rename it so it is clear it is an archive, and then create a fresh xrefs dir in go-ontology.

**Comment by cmungall** [comment]
Experiments (ONGOING):

 * https://github.com/cmungall/goimport-external2go/import
 * https://github.com/cmungall/goimport-ontology/import

THESE ARE EXPERIMENTS, they will soon be out of sync with svn

**Comment by cmungall** [comment]
When importing the `ontology/` directory:

<img width="805" alt="screen shot 2016-06-07 at 6 13 41 pm" src="https://cloud.githubusercontent.com/assets/50745/15879754/a661dd48-2cdb-11e6-9ad2-6a5616654f18.png">

**Comment by cmungall** [comment]
I get the same message for even just ontology/editors

**Comment by kltm** [comment]
:( @hdietze and myself already have accounts on GitLab; when I get back it might be worth testing the limits. We can also look into plonking down money for a limit increase.
Also, I seem to remember from the BioJS people that they (GitHub) might be willing to lift certain limits for scientific or non-profit groups. It might be worth cleaning any unneeded stuff out and contacting them.

**Comment by cmungall** [comment]
Closing this ticket as covered in other tickets

 * https://github.com/geneontology/go-site/issues/209 - switch from svn to cloud distribution of files
 * https://github.com/geneontology/go-ontology/issues/12211 - migrating ontology area
