### ISSUE TITLE
Metadata in json format (auto conversion from yml)

### ISSUE THREAD

**Issue by rizwan-ishtiaq** [geneontology/go-site#1898]
Team,

It will be great help for JS developers to have metadata avaiable in json format. Managing it manually will be difficult. We can put github-action in place to do this conversion for us (every time when a file change)

A sudo implementation would be following

1. New sub-directory "output-json" can be created in metadata
2. This [github action](https://github.com/marketplace/actions/yaml-json-xml-converter-action) can be used to convert yml into json 
3. Save converted file into "output-json" directory with same name and commit it into main repo an example can be seen [here](https://github.com/orgs/community/discussions/26672#discussioncomment-3252794)

**Comment by rizwan-ishtiaq** [comment]
@dougli1sqrd What do you think ?

**Comment by kltm** [comment]
@rizwan-ishtiaq Which metadata were you thinking about here? We already have some of the metadata in JSON in release _metadata/_ directories.

**Comment by kltm** [comment]
(Also noting that while @dougli1sqrd used to work on GO pipeline and releases directly, he is now concerned with other projects.)

**Comment by rizwan-ishtiaq** [comment]
Thanks @kltm for your reply. i was mainly interested in db-xrefs.json
Now i have found it on following location
https://snapshot.geneontology.org/metadata/db-xrefs.json

As @dougli1sqrd is busy, i am closing it now. But i still think it would be great idea to create github action and have json files, instead of providing on other locations
