### ISSUE TITLE
SGD links to complexes do not work 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1906]
SGD annotates complexes with SGD identifiers, for example http://amigo.geneontology.org/amigo/gene_product/SGD:S000218003
However the links we provide from AmiGO are not working 
https://www.yeastgenome.org/locus/S000218003

@suzialeksander can you please check why these links are not resolving? 

Thanks, Pascale

**Comment by suzialeksander** [comment]
So, the /locus/SGDID only works with locus pages.  For a complex, the URL is /complex/SGDID, so yeastgenome.org/complex/S000218003.  Can you split the SGDIDs by type?

**Comment by kltm** [comment]
@suzialeksander GO policy has been that CURIEs do not contain information that needs to be parsed in the internal ID section. That would be that either SGD supplies a redirect to the right location for the general case or that the ID space is split so that the namespace is used to get things to resolve correctly. There is a similar discussion centered around https://github.com/geneontology/go-site/issues/659#issuecomment-392196555 ; TAIR and WB have gone through similar questions.

**Comment by cmungall** [comment]
options:

1. create a SGD.COMPLEX namespace, analogous to what you did for pathways. bioregistry already has both:
    - https://bioregistry.io/registry/sgd.pathways
    - https://bioregistry.io/registry/sgd
    - so here would would have SGD.COMPLEX:S000218003 and this is the CURIE we would use in GO
2. have the link go to a https://www.yeastgenome.org/search?q=S000218003&is_quick=true (though the complex doesn't seem to show up in the search?)

**Comment by pgaudet** [comment]
Note that the SGD complexes ID to CPX mappings should also be in the SGD GPI file
GOA cannot parse these either.

**Comment by srengel** [comment]
we are requesting please to use the #2 option:

have the link go to a https://www.yeastgenome.org/search?q=S000218003&is_quick=true

**Comment by pgaudet** [comment]
@kltm This is still not working as expected

**Comment by kltm** [comment]
Okay, current SGD metadata is: 
https://github.com/geneontology/go-site/blob/fe5452121d10b71264c0dc58dcf07e8813843167/metadata/db-xrefs.yaml#L2372-L2415

In there, right now, there is a separate SGD_LOCUS namespace, which has the "search" link. The base SGD namespace ("SGD") uses the direct locus link.

Is the ask here that the base namespace also uses the search, or that SGD is going to start using more split namespaces. If the former, it would be as simple as adding the search link to that base namespace and doing an update.

**Comment by suzialeksander** [comment]
I think these are switched, where logically the base namespace should use the search, the LOCUS namespace should use the direct locus link.  

>adding the search link to that base namespace and doing an update.

This is what we want. It would fix the complex links correct?

**Comment by kltm** [comment]
@suzialeksander Correct.

**Comment by kltm** [comment]
@suzialeksander For example: https://github.com/geneontology/go-site/pull/2150

**Comment by pgaudet** [comment]
OK on amigo-staging

**Comment by kltm** [comment]
Will close when checked on production AmiGO

**Comment by kltm** [comment]
@pgaudet This looks like it's working using the original example. Please close if confirmed.
