### ISSUE TITLE
Xenbase upstream not currently available

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1916]
@malcolmfisher103 From early today, and recently checked, it seems that Xenbase is not up:
```
09:36:11  wget --no-check-certificate https://ftp.xenbase.org/pub/GenePageReports/xenbase.gpi.gz -O mirror/xenbase.gpi.gz.tmp && mv mirror/xenbase.gpi.gz.tmp mirror/xenbase.gpi.gz
09:36:11  --2022-10-20 09:36:11--  https://ftp.xenbase.org/pub/GenePageReports/xenbase.gpi.gz
09:36:11  Resolving ftp.xenbase.org (ftp.xenbase.org)... 136.159.155.151
09:38:32  Connecting to ftp.xenbase.org (ftp.xenbase.org)|136.159.155.151|:443... failed: Connection timed out.
09:38:32  Retrying.
```
I wanted to check in that this was a known problem or if we need to update our metadata?
Also pinging @pgaudet and @vanaukenk

**Comment by malcolmfisher103** [comment]
@kltm Sorry about that, I believe our Dev team was dong some system wide backups/upgrades and it seem the VM  for the FTP may have been down in just the wrong window.

**Comment by kltm** [comment]
No worries; working now! Closing.
