### ISSUE TITLE
Discuss with MGI what files remain and what software is being used

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1918]
- [x] Figure out date for initial discussion

Tagging @ukemi and @loricorbani

**Comment by ukemi** [comment]
MGI does the following loads that are not already from the GOC:

1. GOA load (ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/MOUSE/goa_mouse_isoform.gaf.gz **and** ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/MOUSE/goa_mouse.gaf.gz). This file contains manual annotations made by non-MGI curators in P2GO and annotations generated through X2GO mapping files such as InterPro2GO. We filter this file.
2. Human orthology load (ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human_isoform.gaf.gz **and** ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human.gaf.gz). We use MGI to identify orthologs, create mouse annotations and we also filter these annotation.
3. Rat orthology load (http://current.geneontology.org/annotations/rgd.gaf.gz). We use MGI to identify orthologs, create mouse annotations and we also filter these annotation.

**Comment by loricorbani** [comment]
David, we also do these:

4. snapshot.geneontology.org/products/annotations/mgi-prediction.gaf
5. snapshot.geneontology.org/annotations/mgi.gaf.gz

**Comment by loricorbani** [comment]
We use Python 3.7.5 scripts and rules (from David/Harold) to process the files.

**Comment by ukemi** [comment]
Right. But those are from the GOC, so presumably we won't need to load those at the GO end. Do we still do the refgen (PAINT) load? That is also from the GOC.

**Comment by loricorbani** [comment]
5. snapshot.geneontology.org/annotations/mgi.gaf.gz

This is GO/PAINT.

**Comment by ukemi** [comment]
So just to summarize and be complete, we also load several files where the annotations originate at the GOC:
1. inter-ontology inferences ---snapshot.geneontology.org/products/annotations/mgi-prediction.gaf
2. PAINT annotations --- snapshot.geneontology.org/annotations/mgi.gaf.gz
3. Noctua annotations ----snapshot.geneontology.org/products/annotations/noctua_mgi.gpad.gz

**Comment by kltm** [comment]
@ukemi @loricorbani I've seeded a document for further discussion here: https://docs.google.com/document/d/10m5ZQ6ffugaUb2L85TtBB94-5G12GwVH9b8JjO_4Y6Y

**Comment by loricorbani** [comment]
I think the best thing to do is have a meeting.  it's complicated.

**Comment by loricorbani** [comment]
According to the document above, you are taking over only 2 of the MGI/GO data streams:  GOA/Mouse and GOA/Human.
What about the others?  GO/Rat, GO/PAINT, GO/CFP, MGI/UniProtload?
Will these be addressed in a different ticket?
MGI would like all of these data streams handled by GO, so that we only have to process one NOCTUA/GPAD, if possible.

**Comment by loricorbani** [comment]
@loricorbani testing to get this to forwarded to my email.

**Comment by kltm** [comment]
@loricorbani I think we would need to sit down with @ukemi when he's back and see how these are all used. My overall understanding at this point is that GO-origin loads would stay internal to GO, orthology data (generated ISO GAFs) would be taken over by either GO or Alliance, and that GOA-origin loads would be pulled by GO directly.

**Comment by loricorbani** [comment]
Ok, I didn't understand that you were making distinctions between these.  Thanks for the clarification.  We'll talk when David gets back.  Thanks.

**Comment by loricorbani** [comment]
@ukemi 

what is the MGI/UniProt load/GO annotations considered? 
I didn't realize there were distinctions between these from the GO perspective.

gomousenoctua : GO-origin
goamouse : GO-origin
goahuman : GO-origin
gocfp : orthology data
gorefgen : orthology data
gorat : orthology data
uniprotload

**Comment by pgaudet** [comment]
Done
