### ISSUE TITLE
db-xrefs.yaml fails under some parsers

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#192]
@simonjupp found an issue with the db-xrefs.yaml when trying to parse it using snake--backslashes in regexp strings.

See if this is a kwalify or snake issue, and correct, hopefully not causing any problems for other users.

**Comment by kltm** [comment]
@simonjupp could you check this version? Close if it works; if it doesn't could you specify the first fail line?

**Comment by simonjupp** [comment]
Looks good, thanks!
