### ISSUE TITLE
Attempt to make spreadsheet comparing legacy drive and new drive

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1920]
From the managers' call today, to get a handle on what is left to transfer and who might be responsible for various files, @kltm has agreed to spend a little time on trying to make a spread sheet.

Possible methods:
1) API calls in
2) listings of simulated filesystem

Will tag @suzialeksander and @pgaudet when done, one way or another.

**Comment by kltm** [comment]
If I'm doing this right, something like 833 files remain in the legacy drive. They break down by type something like:
```
      1 
      1 874
      1 875
      1 eps
      1 m4v
      1 mov
      1 ppsx
      1 rtf
      1 zip
      2 dia
      2 doc
      2 gaf
      2 owl
      2 ppt
      2 webm
      2 xml
      3 tsv
      4 txt
      6 gpad
      6 org
      6 tex
      7 mp4
      8 html
      8 jpeg
     10 JPG
     13 CR2
     15 gz
     47 png
     63 pdf
     97 docx
    155 xlsx
    167 pptx
    195 jpg
```
Top-level folder are looking like:
```
     59 Annotation-FROZEN_ Sabrina, Kimberly, Dustin, Helen, GO, Penelope, Giulia
     55 GO-CAM-and-Noctua-FROZEN
    224 GO Pictures-FROZEN_ various owners
     12 Managers-FROZEN
    306 Meetings-FROZEN
      4 MOVED Administrative
      7 Ontology-FROZEN
      3 Ontology infrastructure-FROZEN - Melanie, David OS
      6 Outreach-FROZEN
     73 PAINT-FROZEN - Dustin, Anushya
     27 Papers and Presentations-FROZEN-issue
     12 Progress Reports-FROZEN
      1 reference proteome.docx
      4 Technical-FROZEN
      6 TempFiles
      1 Use Cases-FROZEN - Suzi L
      3 Website-FROZEN
     30 Working Groups-FROZEN
```
Which I think gives a pretty hopefully picture of next steps.

https://docs.google.com/spreadsheets/d/1jB1tCydM-g20_CYPFa7dQdTbSq7m18MSwYPIa8HVx4c/edit#gid=243309765

**Comment by kltm** [comment]
Tagging back to @suzialeksander

**Comment by kltm** [comment]
@suzialeksander Is this enough information to start with? The "ownership" didn't pop out in the way I did it, but can poke a bit more if needed.

**Comment by pgaudet** [comment]
OK on the managers call to copy all these
