### ISSUE TITLE
All remaining legacy drive files to get copied into "legacy" folder in new shared drive

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1921]
If they are otherwise sorted out and moved by previous owners, we intend on copying all files remaining in the old legacy drive into the the top-level "legacy" folder in the new drive.
This should essentially be the last act of this project, as nothing we intend on editing or looking at would remain in the old legacy drive.

**Comment by kltm** [comment]
If I'm doing this right, something like 833 files remain in the legacy drive. They break down by type something like:
```
      1 
      1 874
      1 875
      1 eps
      1 m4v
      1 mov
      1 ppsx
      1 rtf
      1 zip
      2 dia
      2 doc
      2 gaf
      2 owl
      2 ppt
      2 webm
      2 xml
      3 tsv
      4 txt
      6 gpad
      6 org
      6 tex
      7 mp4
      8 html
      8 jpeg
     10 JPG
     13 CR2
     15 gz
     47 png
     63 pdf
     97 docx
    155 xlsx
    167 pptx
    195 jpg
```
Top-level folder are looking like:
```
     59 Annotation-FROZEN_ Sabrina, Kimberly, Dustin, Helen, GO, Penelope, Giulia
     55 GO-CAM-and-Noctua-FROZEN
    224 GO Pictures-FROZEN_ various owners
     12 Managers-FROZEN
    306 Meetings-FROZEN
      4 MOVED Administrative
      7 Ontology-FROZEN
      3 Ontology infrastructure-FROZEN - Melanie, David OS
      6 Outreach-FROZEN
     73 PAINT-FROZEN - Dustin, Anushya
     27 Papers and Presentations-FROZEN-issue
     12 Progress Reports-FROZEN
      1 reference proteome.docx
      4 Technical-FROZEN
      6 TempFiles
      1 Use Cases-FROZEN - Suzi L
      3 Website-FROZEN
     30 Working Groups-FROZEN
```
Which I think gives a pretty hopefully picture of next steps.

https://docs.google.com/spreadsheets/d/1jB1tCydM-g20_CYPFa7dQdTbSq7m18MSwYPIa8HVx4c/edit#gid=243309765

**Comment by kltm** [comment]
@suzialeksander There was not much reported change in the number of files.
I've gone ahead and copied all ~1k remainder files to:
"Gene Ontology" > "OLD LEGACY DRIVE FILES -- WARNING" > "LEGACY Gene Ontology"

**Comment by kltm** [comment]
Does this wrap this (remaining) ticket?

**Comment by suzialeksander** [comment]
I hope it does. I'm happy to let you close (again).

**Comment by pgaudet** [comment]
Is the Google drive move project done then ?
