### ISSUE TITLE
Test IBA GAF set and tree files based on PANTHER 17.0

### ISSUE THREAD

**Issue by dustine32** [geneontology/go-site#1926]
Point [paint.yaml](https://github.com/geneontology/go-site/blob/master/metadata/datasets/paint.yaml) metadata to the specific IBA GAF folder for the new 17.0 [release](http://data.pantherdb.org/ftp/downloads/paint/17.0/2022-11-04/presubmission/) (`/17.0/2022-11-04/`). We can close this once the test Jenkins branch runs successfully.

**Comment by dustine32** [comment]
Noting this issue will also cover the test Jenkins branch where I'll set PANTHER version to `17.0` in order to fetch correct `tree_files.tar.gz`.

**Comment by kltm** [comment]
Test branch is `issue-1926-paint-17-test`.

**Comment by dustine32** [comment]
@pgaudet After running this test pipeline against the PANTHER 17.0 trees and IBA GAFs, here is the go-annotation-changes report:
[go-annotation-changes.tsv.txt](https://github.com/geneontology/go-site/files/10061372/go-annotation-changes.tsv.txt)
The drop in `PHYLO` annotations (-316991) roughly matches the expected drop as seen in the PAINT 17.0 [IBA GAF report](https://docs.google.com/spreadsheets/d/1ShFwfNGk67v9XKj9COVPdHGaUfqIICtMi7wY-wkFcfY/edit#gid=1051461976) (-316642).
These results should start being seen in the `snapshot` runs starting with the 2022-11-22 run and then into the December GO `release`.
