### ISSUE TITLE
Add documentation for external resources to link to GO-CAM models

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#1929]

**Comment by kltm** [comment]
@pgaudet Doesn't this just mean to point to the models' URI? (i.e. models.geneontology.org/INTERNALID)

**Comment by kltm** [comment]
@pgaudet If this isn't distinct from geneontology/web-gocam#23 and there is no other documentation we want to fix/add, then this can be closed.

**Comment by kltm** [comment]
Let's add how to link, using the above URL (i.e. models.geneontology.org/INTERNALID) to the FAQ around https://geneontology.org/docs/faq/#go-cams . This can be done now and independently of any other action, as it is the standard link.

**Comment by kltm** [comment]
@pgaudet @suzialeksander I'm not sure if this is a priority? I'll leave this open until tomorrow, then close (and we can deal with docs later in another project).

**Comment by kltm** [comment]
Actually, let's close this out; we can reopen in another project if necessary--there is no AmiGO-specific action here, as the correct link has always been model.geneontology.org/XYZ
