### ISSUE TITLE
Migrate create-annotation-summary-statistics.js to node.js

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#193]
And also move from svn into this repo

Should be a straightforward move, similar to that for query-sf-for-new-terms.js

At the moment, the ringo job is failing
https://build.berkeleybop.org/view/GAF/job/gaf-json-statistics/

**Comment by kltm** [comment]
@hdietze didn't I already commit these new scripts?

**Comment by hdietze** [comment]
Different task: @kltm you migrated the scripts for the notification e-mails.
I forgot about the json summary for the GAF downloads, that jenkins job also uses rhino (and is currently failing).

**Comment by kltm** [comment]
@cmungall I think the conversion is done, you probably want to take it for a spin.

**Comment by kltm** [comment]
```
No such file ‘gene_association.goa_uniprot.gz’.
```
@cmungall Do we want "all" and "gcrp"?

**Comment by jmcherry** [comment]
As previously noted the http://geneontology.org/page/download-annotations page needs lots of updates.

-Mike



Well for a change its not a problem I caused.  If you notice the URL used to download the >3.2 GB file with all GOA annotations is going to the old name.  More importantly its going to the old location.  <ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/gene_association.goa_uniprot.gz>

If you really want the last version of the GOA annotations with the old file name you have to go to <ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/old/UNIPROT/gene_association.goa_uniprot.155.gz>

The new file is at <ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/goa_uniprot_all.gaf.gz>

All the GOA files from the May 10th release are in the <http://geneontology.org/gene-associations/> directory.  If the user really wants the GOC “filtered" goa_uniprot file from May, last version with the old name, they can retrieve it from <http://geneontology.org/gene-associations/gene_association.goa_uniprot.gz>

That is to say all files with names like this, gene_association.goa_*.gz are the May version and will not be updated.  GOA has switched to a new naming convention.  This is an EBI specific naming convention and there is no planned migration of all the other GAF files.

It should also be noted that I don’t know how that <http://geneontology.org/page/download-annotations> page is updated.  It needs to be changed to include the files with the new names, only the old are listed.  Also it should be noted on the page, if the link continues to be to the EBI site, that the file is not like all the others — it has not had the GOC filtering.  If we want the user to download the GOC filtered version of the goa_uniprot_all file then this URL should be used:  <http://geneontology.org/gene-associations/goa_uniprot_all.gaf.gz>.  This file is not available from the EBI site.

My guess it Seth needs to update the <http://geneontology.org/page/download-annotations> page.  SVN is current with the GOA files of the new names in both the main and submission directory.  The >3 GB files are not in SVN, never have been, but are available from the <http://geneontology.org/gene-associations/*> location.

-Mike




On Jun 23, 2016, at 10:21 AM, kltm <notifications@github.com<mailto:notifications@github.com>> wrote:


No such file ‘gene_association.goa_uniprot.gz’.


@cmungall<https://github.com/cmungall> Do we want "all" and "gcrp"?

**Comment by kltm** [comment]
@jmcherry I think a lot of that is covered in #190, we should add items not yet covered to @cmungall 's checklist there.

**Comment by kltm** [comment]
The Jenkins job successfully ran with the update on the old layout, so that's good. However, I'll wait to close until we have the final final layout done (see https://github.com/geneontology/go-site/issues/190#issuecomment-228181805).

**Comment by kltm** [comment]
Stat generation running successfully again.
