### ISSUE TITLE
Add GCBR images (and links?) to main pages

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1939]
We have been recognized as a GBC Global Core Biodata Resources. Add images to assets and to main pages.

@thomaspd Is there a link that we should be using with the image?

Adding to "proactive" unless there is a rolling doc project (@pgaudet ).

**Comment by pgaudet** [comment]
Maybe add to https://github.com/geneontology/project-management/issues/27 ?

**Comment by kltm** [comment]
Initial assets added for this: https://github.com/geneontology/geneontology.github.io/commit/6a1c31ff8f079df75517c991d0b1db371c2e2052

**Comment by suzialeksander** [comment]
Some links as part of https://github.com/geneontology/geneontology.github.io/pull/392

**Comment by suzialeksander** [comment]
If we want this in the footer, the likely file is

https://github.com/geneontology/geneontology.github.io/blob/fc7e58e8f99cb158f4a321632fc18748573efaac/_includes/footer.html

Or do we want this image/link in the header, next to the Alliance logo? I'm thinking footer, as it's in line with the sites I see the most (SGD & pombase)

**Comment by kltm** [comment]
@suzialeksander I'd just go with your instinct for the moment--we can always change later.

**Comment by suzialeksander** [comment]
done!

**Comment by pgaudet** [comment]
Looks good!
