### ISSUE TITLE
Need more user friendly error reports: conversion of json to tsv (note of discussion)

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-site#1941]
I'm adding this ticket to note a discussion on the 2012-01-10 annotation call about more curator friendly error reports.

The html version of the error reports does not preserve the tab-delimited formatting, so curators were having trouble putting the content into a spreadsheet for sorting.

We checked the other error report file formats and found that the md file does preserve the tabs so it can be used, at least for now, for copying into a spreadsheet.

Note that from this discussion we also think it would be helpful to have a working group to generate requirements for useful GOC reports.

**Comment by kltm** [comment]
Noting that we've been discussing the relative ease of deriving new report products from "combined.reports.json", the current source for reports.
