### ISSUE TITLE
Create a script (and automation?) to minimally support the annotation review process for ontology group

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1946]
The current workflow for annotation reviews for the ontology group involves creating a list of terms, semi-manually populating a spreadsheet in google docs (?) with GAF-like information, then manipulating (removing items when done?) from this document.

This is obviously a labor-intensive and fiddly process. The ask here initially is to get something minimal, but a little bit more robust/automated, in place to remove the more laborious parts. A more full-bodied workflow discussion will follow.

Tagging @pgaudet @vanaukenk

**Comment by kltm** [comment]
@vanaukenk @pgaudet Where is the document with the column/order for what the reports should look like?
The out-of-bag choices are basically what pops up with the "[Custom DL (up to 100000)]" button on http://amigo.geneontology.org/amigo/search/annotation .

**Comment by kltm** [comment]
Also, the name of the report for the label--"REPORTY" is not very informative.

**Comment by pgaudet** [comment]
For the 'Report Y': 
 name of the label: "Direct annotations to list of GO terms"

**Comment by pgaudet** [comment]
New Report: 

"Annotations to a list of GO terms (including regulates)"

**Comment by pgaudet** [comment]
Columns: 
https://docs.google.com/spreadsheets/d/11hm1kHDyu4CBUG_Zxcouq-rNDMUEmqw3YoMG8vNlWuU/edit#gid=1247173434

(note that they are in the correct order)

**Comment by kltm** [comment]
@pgaudet It now works tolerably and has a more correct output. For the time being (until I can work out the workflow), only the `direct_ann_to_list_of_terms` report works. For these parameters, it should be fine to test.
I'd also note that if you edit in GH, there are some more advanced editing options that I can show you later.

**Comment by kltm** [comment]
https://github.com/geneontology/simple-report-system

**Comment by kltm** [comment]
@pgaudet I believe this is now working for both reports. I'm not sure how this scales, but it is working for the moment :)

**Comment by kltm** [comment]
We'll need to figure cleaning out at some point.

**Comment by kltm** [comment]
Using the embedded TSV editor in gitbub.dev when editing is quite keen.

**Comment by kltm** [comment]
From @pgaudet , filter all current reports for EXP.

**Comment by kltm** [comment]
@pgaudet I think both reports are now EXP.
In addition, once the reports have been created, the link to them should appear in the commit message in the issue.

**Comment by kltm** [comment]
Also noting I cleaned out the reports directory a bit.
