### ISSUE TITLE
Periodically or dynamically create or edit the taxon slim used by GO to include all annotated and annotatable species

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1955]
Currently, some species that are used, mostly in Noctua, are not represented in the taxon slim, causing issues like missing labels, etc.  See: https://github.com/geneontology/noctua-landing-page/issues/87

We would like to come up with an SOP or periodic updates or a dynamic solution.

**Comment by pgaudet** [comment]
Can we add this to a project ?

**Comment by kltm** [comment]
@pgaudet No problem, but I'm not sure where it would go. I suspect it's its own mini-project when all said and done.

**Comment by cmungall** [comment]
here are the instructions to add to taxslim https://github.com/obophenotype/ncbitaxon/blob/master/subsets/README.md

**Comment by pgaudet** [comment]
@balhoff The species should go in this file: 
https://github.com/obophenotype/ncbitaxon/blob/master/subsets/taxon-subset-ids.txt

**Comment by kltm** [comment]
geneontology/neo
`make neo.obo` uses http://ftp.ebi.ac.uk/pub/contrib/goa/uniprot_reviewed.gpi.gz
```
...@.../neo$ grep -oh "NCBITaxon:[0-9]*" neo.obo | sort | uniq | wc -l
14182
```
```
@.../neo$ grep -oh "taxon:[0-9]*" mirror/uniprot_reviewed.gpi.tmp | sort | uniq | wc -l
14216
```
@pgaudet there are currently ~6k entries in https://raw.githubusercontent.com/obophenotype/ncbitaxon/master/subsets/taxon-subset-ids.txt. Combining and de-duping these, we get 16283 entries. Does that sound right?

**Comment by kltm** [comment]
If this looks right, I can do a PR (had to fork as didn't have perms for demonstration) https://github.com/geneontology/ncbitaxon/blob/issue-go-site-1955-annotatable-species/subsets/taxon-subset-ids.txt
@pgaudet @cmungall

**Comment by pgaudet** [comment]
Looks OK 
For example Taxon 107268 has some reviewed entries: 
https://www.uniprot.org/uniprotkb/A0A8K1C0V2/entry

Could you merge this? 

Thanks, Pascale

**Comment by balhoff** [comment]
@kltm check the second to last line: https://github.com/geneontology/ncbitaxon/blob/946f1758908edd4d11a0b77030fbcd3264643f05/subsets/taxon-subset-ids.txt#L16282

**Comment by pgaudet** [comment]
Oups! Didn't read this far !

**Comment by kltm** [comment]
@balhoff Whoops, that's me--I probably introduced that with `cat`ing the files together.

**Comment by kltm** [comment]
I don't have permission to go beyond https://github.com/obophenotype/ncbitaxon/pull/74
Tagging @cmungall @pgaudet @balhoff

**Comment by balhoff** [comment]
Can you fix the conflict? Then I think I can merge.

**Comment by kltm** [comment]
@balhoff I do not have the power to fix the conflict in this repo. It seems to just be additions, so I'm not sure why it's choking...

**Comment by balhoff** [comment]
Okay, I fixed and merged it.

**Comment by kltm** [comment]
@balhoff Cheers!

@pgaudet To close out this issue, we need to be doing this periodically or dynamically. While it's tempting to spend the energy adding something automated to the NEO pipeline to do this, I get the feeling that once a year might be fine? If we can work out what frequency and how to remind ourselves, would that allow this to be closed?

**Comment by balhoff** [comment]
I agree, I think keeping it up to date as needed, and checking periodically would be fine.

**Comment by pgaudet** [comment]
I would also do this 'on request'

Will this be added in Noctua in the next Noctua update? Or can this be done separately?

**Comment by kltm** [comment]
@pgaudet (Just writing down our earlier conversation), the answer is "both".  We do this as part of the Noctua update outages every two weeks, refreshing minerva and solr with NEO. We can also do just solr v/quickly at any point, but that means that things appear as just IDs in Noctua everywhere that's not an autocomplete.

**Comment by pgaudet** [comment]
@balhoff 

Why isnt the species showing for Q9T3Q2  in http://noctua.geneontology.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A636d9ce800000575

<img width="212" alt="image" src="https://user-images.githubusercontent.com/4782928/226550544-86547661-e8ea-44c3-a1a4-9b9b8885715e.png">


Thanks, Pascale

**Comment by balhoff** [comment]
Based on discussion at GOC meeting we likely need to update the NEO build code which puts species name abbreviations into gene names.

**Comment by kltm** [comment]
Continuing here: https://github.com/geneontology/neo/issues/116
