### ISSUE TITLE
SSL Configuration on https://current.geneontology.org (and snapshot and release)

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1975]
Discussed in https://github.com/geneontology/helpdesk/discussions/402

https://current.geneontology.org/annotations/zfin.gaf.gz (and the schema/domain https://current.geneontology.org in general) give browser warnings.

Noting that this is a distant relation to https://github.com/geneontology/go-site/issues/53 here, but in this case the cert is in place for the CDN, which is apparently misbehaving.

**Comment by kltm** [comment]
Recreate on CLI:
```
~$:) http https://current.geneontology.org

http: error: SSLError: HTTPSConnectionPool(host='current.geneontology.org', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError("hostname 'current.geneontology.org' doesn't match either of 'cloudfront.net', '*.cloudfront.net'",),)) while doing GET request to URL: https://current.geneontology.org/
```
Working version:
https://kg-hub.berkeleybop.io/
I'm suspecting this will be easier to sort out once we're in full "local" control of geneontology.org (#1503 ; #stanfordhttps://github.com/geneontology/operations/issues/63)

**Comment by kltm** [comment]
- go to cloudfront distro
- Request ACM cert
- DNS validation
- create non-local cname
- wait
- add appropriate ACM cert, save
- invalidate

**Comment by kltm** [comment]
Okay, I think I've set everything up correctly.
@abessiari I've added three new entries to the Stanford Route 53 setup. If you have a porting script, could you bring those over to ours? Otherwise, I'll move them by hand, np.

**Comment by abessiari** [comment]
@kltm 
 I will take care of it.

**Comment by abessiari** [comment]
@kltm 
Done.  These 3 were added:

"Name": "_620d292a3f71bb0e39289931b1d3bba3.current.geneontology.org.",
"Name": "_eade2bae83a80820182e6437cc5d38fd.release.geneontology.org.",
 "Name": "_f99beb2aa37b5accc77a46f002943a73.snapshot.geneontology.org."

**Comment by kltm** [comment]
Great--just in time: https://github.com/geneontology/operations/issues/63#issuecomment-1472625491

**Comment by kltm** [comment]
Seems to be working. Not automatically upgraded yet, but we're getting there.
