### ISSUE TITLE
Change the name of goa_uniprot_all* files in annotations/ to clarify derived status

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#1984]
We currently have annotations/

goa_uniprot_all.gaf.gz
goa_uniprot_all_noiea.gaf.gz
goa_uniprot_all_noiea.gpad.gz
goa_uniprot_all_noiea.gpi.gz

We'd like to rename these to something more clear so as to avoid confusion with GOA files.

I'm going to suggest:

filtered_goa_uniprot_all.gaf.gz
filtered_goa_uniprot_all_noiea.gaf.gz
filtered_goa_uniprot_all_noiea.gpad.gz
filtered_goa_uniprot_all_noiea.gpi.gz

But am happy with any consistent naming

We would need to:

- [x] get the code in place
- [x] announce to community
- [x] propagate (and let finish on a release)
- [x] remove old versions (S3)
- [ ] update docs

Also see :

https://github.com/geneontology/pipeline/issues/319
https://github.com/geneontology/go-site/issues/1971

**Comment by pgaudet** [comment]
Should we be more explicit? for example 'goa_uniprot_all_no_mod' ? 

@alexsign any suggestions/preferences?

**Comment by alexsign** [comment]
@pgaudet doesn't really matter, it would be good to have README file in the folder to explain the file names

**Comment by kltm** [comment]
Testing on `master`.

If this works, we would need to announce this before propagating it (similar to path change).

**Comment by kltm** [comment]
@pgaudet This now appears to be "working" on the `master` pipeline. Next steps would be figuring out a timeline, communicating it, etc., if needed.

**Comment by pgaudet** [comment]
@suzialeksander Can you please send announcements ?

**Comment by kltm** [comment]
@pgaudet @suzialeksander Just to make sure this is clear, I have not propagated this change to `snapshot` or `release` yet. Even if I did, with `snapshot` not being able to finish recently, it may be a while before this is live. I'm not sure the best way to communicate this, but I want to be clear that when I propagate this change, it goes "live" with the next success of `snapshot` or `release`.

**Comment by kltm** [comment]
@suzialeksander Talking to @pgaudet , let's go ahead and do an announcement like we did for the changing of the product path.

**Comment by suzialeksander** [comment]
Email sent to go-friends as well as https://github.com/geneontology/go-announcements/issues/521

**Comment by kltm** [comment]
Cleared on the last `snapshot` run

**Comment by kltm** [comment]
S3 purged.

**Comment by kltm** [comment]
Still need docs.

**Comment by kltm** [comment]
See: https://github.com/geneontology/pipeline/issues/320
