### ISSUE TITLE
Source SGD GAF includes a separate line for every piece of PAINT evidence

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#2014]
for IBAs, the source sgd GAF expands every paint annotation to N lines, where N is the number of distinct extant gene product IDs used in evidence

```
curl -L -s  https://sgd-prod-upload.s3.amazonaws.com/latest/gene_association.sgd.gaf.gz | gzip -dc |  egrep 'S000000406.*GO:0042555.*IBA'  tests/integration_tests/sgd.src.2023.gaf | wc -l
      36
```

e.g

<img width="857" alt="image" src="https://github.com/geneontology/go-site/assets/50745/657da473-e458-466b-8b4d-f809625d63d0">

when we make a release file this is compacted to a single line:

```
SGD	S000000406	MCM7	part_of	GO:0042555	PMID:21873635	IBA	PANTHER:PTN000179711|FB:FBgn0017577|MGI:MGI:1298227|MGI:MGI:1918817|FB:FBgn0025815|UniProtKB:Q14566|FB:FBgn0014861|MGI:MGI:105380|PomBase:SPBC25D12.03c|SGD:S000000119|FB:FBgn0284442|SGD:S000006223|UniProtKB:P49736|PomBase:SPBC211.04c|UniProtKB:Q9UJA3|UniProtKB:P25205|SGD:S000000406|MGI:MGI:1298398|UniProtKB:I0IUP3|FB:FBgn0020633|FB:FBgn0015929|PomBase:SPBC4.04c|UniProtKB:P33992|PomBase:SPCC1682.02c|PomBase:SPCC16A11.17|UniProtKB:I0IUP4|MGI:MGI:103199|UniProtKB:Q381H2|SGD:S000000758|SGD:S000003169|UniProtKB:Q9NXL9|SGD:S000004264|UniProtKB:P33991|MGI:MGI:1913884|PomBase:SPAC1B2.05|UniProtKB:P33993	C	mini-chromosome maintenance complex protein 7	MCM7|CDC47|YBR202W	protein	taxon:559292	20230110	GO_Central

```

I think this is low priority as our pipeline correctly compacts things and we don't expose users to the source GAF; however, we should try and have MODs provide canonical form as far as possible

**Comment by suzialeksander** [comment]
I'll see what can be done on our end.

**Comment by pgaudet** [comment]
Since we filter these anontations when loading in GO, this is not an issue for us, we re-inject them correctly. 

@suzialeksander If you want to fix this for SGD users, can you please open a ticket in the SGD tracker?
