### ISSUE TITLE
NTR:  intracellular chloride channel activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-site#202]
Could I have " intracellular chloride channel activity" as a child of "GO:0005254 chloride channel activity" and a parent of "GO:0005229 intracellular calcium activated chloride channel activity"?

-GO:0005254 chloride channel activity
	-New Term: intracellular chloride channel activity
		-GO:0005229 intracellular calcium activated chloride channel activity

intracellular chloride channel activity:
“Enables the transmembrane transfer of chloride across the membrane of an intracellular compartment. Transport by a channel involves catalysis of facilitated diffusion of a solute (by an energy-independent process) involving passage through a transmembrane aqueous pore or channel, without evidence for a carrier-mediated mechanism.” PMID:23092411 

Thanks

**Comment by paolaroncaglia** [comment]
(Noticed this by chance)
Hi @hattrill , 
I presume this request should go on the go-ontology tracker
https://github.com/geneontology/go-ontology/issues?q=is%3Aopen+is%3Aissue 
Mentioning @ukemi as he's on ontology requests duty this week.
Cheers,
Paola

**Comment by hattrill** [comment]
Whoops! Thanks, good catch. Must have been having a moment (or two). I'll close this and add it to the right tracker!
