### ISSUE TITLE
Document checks in ontobio for gorule-0000013

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#2033]
The 'test error' in this file: https://github.com/geneontology/go-site/blob/master/docs/gorules_test_errors.gaf
is not being reported in the go-rules output. 

Is gorule-0000013 treated or handled differently?

**Comment by pgaudet** [comment]
The implementation is described in quite some detail in the rule: 
https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000013.md

**Comment by pgaudet** [comment]
@kltm Given that the implementation is different, is there any way we can test that this rule is working correctly?

**Comment by kltm** [comment]
I believe there is no "surface" testing here like there is for other GAF-related checks in the ontobio, as it is using a rather different path. My guess would be that any tests would be internal code tests and the like. @dustine32 may have more information, but I believe this is just as it is--the "testing" is the examination of the output.

**Comment by pgaudet** [comment]
Low priority, closing
