### ISSUE TITLE
http://geneontology.org/formats/oboInOwl no longer resolves

### ISSUE THREAD

**Issue by tgbugs** [geneontology/go-site#2037]
I'm not sure whether this is the right issue tracker, but http://geneontology.org/formats/oboInOwl no longer resolves.

This breaks the NIF-Ontology import chain since it is imported in nif_backend https://raw.githubusercontent.com/SciCrunch/NIF-Ontology/master/ttl/nif_backend.ttl.

cc @cmungall

**Comment by tgbugs** [comment]
Ah I see https://github.com/geneontology/go-site/issues/53#issuecomment-1652708070

**Comment by kltm** [comment]
@tgbugs Apologies for the confusion. This should now resolve.

**Comment by tgbugs** [comment]
Confirming fixed on my end. Thanks!
