### ISSUE TITLE
 gorule-0000003 and  gorule-0000005 dont show up in the reports

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#2039]
Hello, 

 gorule-0000003 and  gorule-0000005 dont show up in the reports - for example here: 
http://release.geneontology.org/2023-06-11/reports/gorule-report.html

<img width="737" alt="image" src="https://github.com/geneontology/go-site/assets/4782928/40590557-79a3-4d44-9bdb-454a02b6093f">

Note that these are the only 2 'legacy' rules (ie implementing owltools code); is this code not being ran anymore? 
Would it be more judicious to rewrite these rules in new framework, or should we try to troubleshoot why these are not being displayed?

**Comment by pgaudet** [comment]
gorule-0000003 is deprecated (but its status was 'legacy'), gorule-0000003 description is now fixed to indicate it is deprecated, see https://github.com/geneontology/go-site/issues/2055

**Comment by pgaudet** [comment]
gorule-0000005:  we still dont know why the error is not showing up in the reports (probably due to being ran be owl-tools)

@mugitty needs to check with @kltm

**Comment by kltm** [comment]
owltools output is largely a dead end--those rules need to be re-implemented elsewhere (there are tickets for that).
Otherwise, for non-owltools things missing, one should all check the reports' suppression tags, although that may not be this case.

**Comment by mugitty** [comment]
@kltm , According to https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000005.md, this is implemented in owltools.  Should this be implemented in ontobio?

**Comment by kltm** [comment]
As a matter of fact, there is no real owltools reporting, although rules may "exist" there. Everything that violates a rule should generate a trace, but that is not where we are at at the moment and I'm not sure this is in scope of any current project.

**Comment by pgaudet** [comment]
* gorule-0000003 is deprecated >> OK
*  gorule-0000005 should be re-implemented at some point. 
I'll create a new ticket but for a future project.

**Comment by pgaudet** [comment]
Changed status of gorule-0000005 to indicated that its is not implemented (status = approved) 
see https://github.com/geneontology/go-site/pull/2073
