### ISSUE TITLE
New GO Mediawiki setup does not support email, meaning new users cannot edit

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#2042]
This is coming in from @raymond91125 .

A little over a year ago, we transitioned from a self-maintained instance to mediawiki to a third-party service. As part of this transition, after a little discussion, we decided that we would not need email so left that out of the requirements (additional time and expense; few editing users).

As a consequence of that, it seems that we are hitting a barrier: any newly created user is kept in a read-only mode until they can "verify" their email address. @raymond91125 is now hitting this in attempting to use an account created for him fairly recently.

While I've been reading documentation, I'm not sure if there is a "manual" way to take care of this from the places I normally have access now. Ways forward, more-or-less in order:

- [ ] continue reading documentation--I may be missing something
- [ ] see if there is some control panel that I haven't seen yet that gives us enough access to change/modify this
- [ ] figure out how to flip the right switch with direct database manipulation (maybe phpadmin shell)
- [ ] create a new contract with the third-party maintainer and add email in, in addition to security updates, etc.
- [ ] Find workarouns that doesn't involve GO wiki

Tagging @abessiari to see if you have any thoughts on this.

**Comment by abessiari** [comment]
@kltm 

Did an administrator create the user? Or did the user register on his own? 

I am asking because I found this in my conversation with David from civihost. 

```
Hi David.

We need it to be as safe and secure as possible. We have struggled in
the past with spam/bots ...

1. Anonymous edits: "no"
2. Create new user with email: "no"

The only thing that should be allowed is for an admin to create a new user.
Thanks.
aes
```

**Comment by kltm** [comment]
@abessiari I'm the one who created the account. However, the base wiki permissions seem to dictate that a user can login, but not edit, until they have verified their email address. The latter is impossible in the current setup as no email goes in or our there.
So, while I was able to create a new user, I was not able to create a new user that can make edits (which should probably be included :).

**Comment by kltm** [comment]
In discussion, this is cleared with a combination of user issues.
