### ISSUE TITLE
Fix Post-to-Twitter on Create Article page for "Editor" user

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/go-site#205]
The _Post to Twitter_ tab that used to be at the bottom of the _Create Article_ pages may have been accidentally removed from view for those with editing permissions in the GO website. Possibly a Drupal update or some other hiccup. 

@kltm may I kindly ask if you could please re-enable the tab, if possible? Else let's come up with am alternate solution. 

Thank you!

**Comment by kltm** [comment]
User permissions seem fine...
Huh.

**Comment by kltm** [comment]
Pretty weird, but I believe that this is functioning again. Could @monicacecilia or @paolaroncaglia take a look at this and close if they can see the option now?

**Comment by monicacecilia** [comment]
The _Post to Twitter_ tab is again visible when trying to create a new _Article_ page. Thank you @kltm 

<img width="509" alt="screen shot 2016-08-03 at 5 10 30 pm" src="https://cloud.githubusercontent.com/assets/1714621/17386219/4dbdb178-599d-11e6-9936-4ffeaa0d644a.png">
