### ISSUE TITLE
gorule-0000001 implementation of "pipes are not allowed"

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#2064]
Pipes are not allowed 

- [ ] confirm that this is implemented
- [x] add test in the test GAF.

**Comment by pgaudet** [comment]
Hi @balhoff 
I think what I meant here was about gene names - ie gene names should not have pipes (but other ascii characters are allowed) . Is this right ? I don't see it here https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md

Do you remember when we discussed this? 

Thanks, Pascale

**Comment by balhoff** [comment]
@pgaudet if you go into the spec for [Text_Char](https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md#Text_Char) and then [Symbol_Char](https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md#Symbol_Char), pipe is not an allowed character there.

**Comment by pgaudet** [comment]
Thanks!!

**Comment by pgaudet** [comment]
Hi @mugitty 

In the Gene Symbol column (GAF Col 3, GPAD Column 2), the pipe character ("|") is not allowed, see @balhoff 's comment above. I added a test in the test GAF to check that this is caught. 

Thanks, Pascale

**Comment by mugitty** [comment]
Gene symbol is not a field in GPAD.  It is only defined in GAF.
GPAD version 1.1 (https://geneontology.org/docs/gene-product-association-data-gpad-format/) column 2 is DB object id.  There is no gene symbol in GPAD.  Proposed GPAD version 2.0 (https://geneontology.org/docs/gene-product-association-data-gpad-format-2.0/) does not have gene symbol

**Comment by pgaudet** [comment]
Good point ! Gene symbol is in the GPI file. Do you want to implement tests on the GPI as well? It seems this should be a different project.

**Comment by mugitty** [comment]
I can add the check for GPI as well. Whenever applicable I update GPAD as well. To ensure that all error cases are covered, we should have three error files: errors.gaf, errors.gpad and errors.gpi.

**Comment by pgaudet** [comment]
Correctly failing on @mugitty 's machine
