### ISSUE TITLE
The ribbon no longer works for human (HGNC) genes

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#2087]
Right now, for the ribbon, the API translates HGNC ids from alliance to UniProt ids to query Golr with via [mygene.info](http://mygene.info/)

A recent change/release at mygene means that, for the moment, the API no longer gets SWISS-PRO ids back (I have a ticket open with them - I think this will be temporary), only TrEMBL.

Is there a better (local) way to get a translation between HGNC and UniProt (SWISS-PROT) identifiers?

I believe they have this data at the Alliance.

We already do a transform (I believe) for the GO-CAM widget. I'm wondering if that might not be the quickest way.

[pulled and merged from convo w/@sierra-moxon]

**Comment by sierra-moxon** [comment]
Chunlei Wu (Exploring Agent, Service Provider)
Thanks for reaching out to us, yes, we noticed this yesterday too, a fix should be pushed out today.

**Comment by dustine32** [comment]
@sierra-moxon @kltm I don't know if it'll help in this context, but the Alliance pathways widget "converts" HGNC to UniProt by fetching `xrefs` from each gene page and filtering for `includes("UniProtKB:")`:
https://github.com/alliance-genome/agr_ui/blob/d7a20a7e5f8a68506c4084116fb4b56f670880d6/apps/main-app/src/components/pathway/pathwayWidget.js#L256
If there are ever multiple UniProts to a single HGNC, the pathway widget simply picks the first one.

**Comment by kltm** [comment]
@dustine32 Yes, that's the direction we were thinking of. Essentially, if we only have that transform in the code for Alliance, then that can be moved over to them and we can shut down that code path and remove an external dependency--the issue we had today. However, if it's in broader usage, then we may need to think of other ways forward.

**Comment by sierra-moxon** [comment]
It would be awesome if the agr_ui could call the GO API with UniProt identifiers (handling the conversion at Alliance since they already have all the info they need in the Gene Page asset) so that the Alliance gene page doesn't have to call the GO-API just to have the GO-API turn around and call and retrieve all of the information from the Gene Page endpoint at the Alliance to get the xref to UniProt.

**Comment by kltm** [comment]
Okay, IIRC this is fixed upstream. Closing.
