### ISSUE TITLE
GO annotations inferred from GO annotations which are not in the GO database

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-site#2104]
Carried over from GO HelpDesk issue:
http://jira.geneontology.org/browse/GO-1146

Most recent exchange:

@vanaukenk : On a broader level, yes, I do think we want to make the ISS and IEA annotations traceable. However, I believe we grandfathered legacy ISS annotations that didn't have an entry in the With/From column and we also say on the website documentation for ISS that there are cases (like tRNASCAN) where an entry in the With/From column is not required:

http://www.geneontology.org/page/iss-inferred-sequence-or-structural-similarity

We can review/revisit the ISS annotations and evidence code usage, but I'd like to get a sense of the scale of the issue first.

@ValWood : My concern here was that the ISS had been made to an OBJECT which, at the time I could not find in the GO database.
I have now found it
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:V5IMB3
So this implies that UniProtKB is the database authority for Neurospora crassa OR74A is that correct?

There will be occasions where ISS/ISO are made to a gene product which does not have the annotation in question, which is not such a problem if the object is annotatable and traceable.

In this case it should not be possible to submit GO data to GO which contain cross references to other GO annotations via an ID like
BROAD_NEUROSPORA:7000007580543748 which is not the "official" reference of the database authority. This should be an easy sanity check for GO to establish.

This would solve a number of problems with minimal effort.
1. It would enforce traceability of the annotatable object, but place the responsibility for this on the submitter.
2. It would force submitters to only use GO compliant data sources for inference (i.e here making IEAs from other stale IEAs and other bad practice).

**Comment by pgaudet** [comment]
Duplicate of https://github.com/geneontology/go-site/issues/287
