### ISSUE TITLE
New gorule-0000063: ISS annotations should have data in the "with" field

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#2108]
I though this was a hard check? It used to be/should be...this isn't a new rule?

dnaK | DnaK protein |   | lipoprotein biosynthetic process |   | PseudoCAP | Pseudomonas aeruginosa PAO1 | ISS |   |   | protein |   | PMID:16109938 | 20190311
  | dnaK | DnaK protein |   | DNA replication |   | PseudoCAP | Pseudomonas aeruginosa PAO1 | ISS |   |   | protein |   | PMID:6086613 | 20190311
  | dnaK | DnaK protein |   | ATPase activity |   | PseudoCAP | Pseudomonas aeruginosa PAO1 | ISS |   |   | protein |   | PMID:6314326 | 20190311

**Comment by mugitty** [comment]
@pgaudet , I added the following lines to my copy of the errors file for testing the update:
! SHOULD PASS GORULE:0000063 - TEST 1
PomBase	SPAC25B8.17	ypf1	is_active_in	GO:0005634	GO_REF:0000024	ISO	SGD:S000001583	C	GORULE_TEST:0000063-1 intramembrane aspartyl protease of the perinuclear ER membrane Ypf1 (predicted)	ppp81	protein	taxon:4896	20230427	PomBase	part_of(X:1)
! FAILS GORULE:0000063 - TEST 2
PomBase	SPAC25B8.17	ypf1	is_active_in	GO:0005634	GO_REF:0000024	ISO		C	GORULE_TEST:0000063-2 intramembrane aspartyl protease of the perinuclear ER membrane Ypf1 (predicted)	ppp81	protein	taxon:4896	20230427	PomBase	part_of(X:1)

You can use these or something else. You probably need to make an update to the Excel spread sheet to synchronize everything.

**Comment by pgaudet** [comment]
OK, I will check when this is available on snapshot

**Comment by pgaudet** [comment]
@mugitty : I edited the rule: this should be a WARNING (fail_mode: soft), not a filter. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Done, tests are working :)
