### ISSUE TITLE
All the same databases / sources should have identical prefixes

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#212]
This is from @ValWood on https://github.com/geneontology/amigo/issues/298.

Her initial comment was:

```
This is probably really a jenkins QC check issue so it could be 'wrong tracker'
Shouldn't all the sources match the database prefix in some file somewhere?
...
```

The current "bad" list is:
- WormBase and WB
- FlyBase and FLYBASE
- UniProt and UniProtKB
- AspGD and ASPGD
- GO_Central and GO_CENTRAL and GOC (?)
- ENSEMBL and Ensembl
- REFGENOME and RefGenome

Possibly useful comments:
- As we migrate the perl gaf checks to jenkins, will this reporting become more transparent?
- It looks like somebody is filtering though an old db system and then we're getting them back.

**Comment by kltm** [comment]
Noting this again, from a different context. Kind of worrying that a year has gone by on this.

Looking into this, it seems that at least some is due to upstream resources "capping" assigned_by, which we then ingest.

@cmungall

**Comment by cmungall** [comment]
We should have the new GAF pipeline report and repair, assigning @dougli1sqrd

**Comment by pgaudet** [comment]
Redundant with https://github.com/geneontology/go-site/issues/1218
