### ISSUE TITLE
gorule-0000051 - unexpected GO-checks violation for protein binding annotations

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#2124]
Some GO terms require a value in the Annotation Extension field

total: 2618

WARNING - Violates GO Rule: GORULE:0000051: Some GO terms require a value in the Annotation Extension field -- PomBase SPAC1002.06c bqt2 enables GO:0005515 PMID:16615890 IPI PomBase:SPAC6G9.13c F bouquet formation protein Bqt2 mug18|rec23 protein taxon:4896 20190711 PomBase

but GO:0005515 does not require a value in the extension field does it?
Am i missing something?

**Comment by ValWood** [comment]
Yeah with/from would make sense

**Comment by pgaudet** [comment]
@ValWood  the with/from is checked by GORULE_0000016

**Comment by pgaudet** [comment]
@mugitty We need to comment out this rule for now, guidelines are not clear about this.

**Comment by ValWood** [comment]
GO:0005515 does not require a value in the extension field that I have ever heard. If one was required we could export it, but it would.  be a bit different from other extensions because it would not be 'directional'. I think we should b e encouraged to curate activities with directional extensions.

**Comment by mugitty** [comment]
GORULE:0000051 status has been updated to proposed.  Comment out code for GORULE:0000051
