### ISSUE TITLE
Move GO_REFs over to go-site

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#214]
Currently exist in svn, rendered directly as http://www.geneontology.org/doc/GO.references

And awful: http://www.geneontology.org/cgi-bin/references.cgi

move each ref to its own md/yaml file, analogous to obofoundry. Use default github rendering, optional jekyll liquid templates later

cc @kltm @monicacecilia

**Comment by kltm** [comment]
What's the endgame here? Are these individual blobs going to be pushed somewhere to resolve outside of GH? Are we going to have something like http://references.geneontology.org/GO_REF:0000001 ?

**Comment by cmungall** [comment]
Minimally, db-xrefs.yaml can be changed to point at the github URLs. A bit ugly but no worse than currently.

There are a variety of rendering options beyond this:

 * Static site with GitHub pages + jekyll, a la OBO
 * Static site generated using jekyll but deployed independent of GH (e.g. direct copy to S3)
 * Custom rendering in amigo (could use [Text::Markdown](http://search.cpan.org/~bobtfish/Text-Markdown-1.000031/lib/Text/Markdown.pm) but not really any need for this yet as we don't have much markdown in the abstract
 * Quick pandoc pipeline run in jenkins (but quickly run into questions about what css to use etc)

**Comment by cmungall** [comment]
As for the purl, I think an obolibrary purl, e.g. $OBO/go/references/0000001

**Comment by cmungall** [comment]
The metadata is now sourced from github

Still to change existing site links

**Comment by mcourtot** [comment]
@tonysawfordebi mentioned that http://purl.obolibrary.org/obo/go/references/0000001 doesn't resolve. Should we just create a new entry under https://github.com/OBOFoundry/purl.obolibrary.org/tree/master/config? I'm a bit wary of mixing this with the OBO prefixes. @jamesaoverton?

**Comment by jamesaoverton** [comment]
Any PURL starting with `http://purl.obolibrary.org/obo/go/` can be defined in <https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/go.yml>. I think <http://purl.obolibrary.org/obo/go/references/0000001> is a perfectly good PURL to define.

**Comment by tonysawfordebi** [comment]
When the PURLs are available, the GO_REF entry in https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml should also be updated.

**Comment by cmungall** [comment]
yes, will need changed in 2 places

**Comment by mcourtot** [comment]
PR at https://github.com/OBOFoundry/purl.obolibrary.org/pull/258 - @cmungall, @jamesaoverton, sanity check of the regex please?

**Comment by mcourtot** [comment]
All done.

**Comment by kltm** [comment]
@mcourtot There seems to be an issue--the patch was applied to master and fails:
https://travis-ci.org/geneontology/go-site/builds/171352515

**Comment by mcourtot** [comment]
Wrong ticket? This was a patch for https://github.com/geneontology/go-site/issues/240#issuecomment-256892110, and I didn't noticed it failed tests, but note sure why.

**Comment by kltm** [comment]
The patch applied to master is a kwalify YAML failure. I don't think it relates to the other ticket.

**Comment by kltm** [comment]
@mcourtot https://travis-ci.org/geneontology/go-site/builds/171352515#L181

**Comment by kltm** [comment]
It looks like line 1001 is not parsing as a string, but maybe as a number? It might need quotes.

**Comment by mcourtot** [comment]
Interesting - it seems that as the other example IDs are a mix letters and digits (e.g., GO:0004352) they are parsed as string, but as this one was only digits (0000001) it got parsed as... digits. without @kltm's quotation marks. Thanks for fixing!
