### ISSUE TITLE
Reinstate daily report of terms and stats

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-site#217]
As per http://wiki.geneontology.org/index.php/Ontology_meeting_2016-08-25:

Daily report of terms and stats
See http://wiki.geneontology.org/index.php/Ontology_meeting_2016-08-18#Daily_report_of_terms_and_stats

**Comment by tberardini** [comment]
No report has materialized. Please check.

**Comment by cmungall** [comment]
@kltm the job seems correctly configured, any ideas?

**Comment by kltm** [comment]
Hm. I'd not that there are two email lists there: go-ontology@mailman.stanford.edu and go-ontology@lists.stanford.edu. The latter seems to only have periodic functionality.

Assuming the job is otherwise correct, the best way forward would be to add a know good address (to make sure that the email is being sent as intended) and to bring somebody from Stanford (possibly @stuartmiyasato ?) into the loop to see if it is getting caught over there somehow.

For debugging, I'd suggest cloning the job with a smaller workset and different (good) email addresses.

**Comment by cmungall** [comment]
@kltm - unlikely to have anything to do with that. The last successful email was sent out on July 12, which is the last time https://build.berkeleybop.org/job/release-go-deprecated/ ran

The only difference is that the old job ran on grinder, the new on satin. Shall I pin to satin?

**Comment by cmungall** [comment]
pinned to grinder (we have until midnight til this runs if you'd like to try a different strategy)

**Comment by kltm** [comment]
@cmungall The various possibilities have to be eliminated systematically. We have, several times already with this setup, had email suddenly stop going out as it started being marked as spam.

We've gone ahead and added more recipients to the list to see if any get through. If any get through, it would be more likely that there is a config/spam issue somewhere in the chain. If none get through, the mailer on the machine needs to be examined.

**Comment by kltm** [comment]
@cmungall considering that *other* jenkins emails seem to get out just fine, it seem more likely at this point that the issue has an external component.

**Comment by cmungall** [comment]
OK, now I look at this more, I think the Jenkins email configuration is a red herring.

The emails were being sent out to go-watchers, not go-ontology. It's a mystery as to how this worked in the first place, as go-watchers was not set in the jenkins config. This may be buried in the depths of the compare-obo script which Amelia wrote a while ago. Ultimately we may have to stop supporting this and switch to a non-obo based diff tool

**Comment by cmungall** [comment]
For forensic purposes, here is the last email that went out:

```

---------- Forwarded message ----------
From: BBOP-Jenkins <jenkins@mill.lbl.gov>
Date: Tue, Jun 28, 2016 at 3:39 AM
Subject: [go-watchers] release-go - Build # 1422 - Successful!
To: go-watchers@lists.stanford.edu


Hello,

there is a new daily GeneOntology release available.
For changes, please see the attached report files.

If required, you can find more details and the log file here:
http://build.berkeleybop.org/job/release-go/1422/

regards,
Jenkins
_______________________________________________
go-watchers mailing list
go-watchers@lists.stanford.edu
https://mailman.stanford.edu/mailman/listinfo/go-watchers


```

The attached files are go-def-diff.html and go-obo-diff.html, which are produced using Amelia's script triggered by the Makefile. These files seem to be made successfully but I can't find the part that sent these out.

Compare with the (functional) trigger for sending inference emails:
https://build.berkeleybop.org/job/go-new-inferences-summary-email/configure

**Comment by cmungall** [comment]
it may be to do with the workspace https://build.berkeleybop.org/job/release-go/ws/svn/ lacking the obs_terms.rss, which the archive step was expecting. I have removed this. Let's see if that works. But overall we might look into a more transparent way of controlling email notifications

**Comment by kltm** [comment]
I'm not sure what you've already dug out yourself, but the possible scripts that are in reporting in svn to that email:

- compare-obo-files.pl
- cvs-retriever.pl
- reporter.pl
- rev-check.pl
- compare-defs.pl

(seeing who used that module in the first place)

I started crossing by grepping through jenkins configurations, but became depressed after realizing at some point we either need to properly parameterized a huge number of jobs, or burn it down and start over.

**Comment by tberardini** [comment]
Two additional daily emails are missing. The emails are titled:

[go] Github Annotation Tracker Update
[go] Github Ontology Tracker Update

email sent from: jenkins@mill.lbl.gov
email sent to: 	go-consortium@lists.stanford.edu,
go-curator-tracker@lists.stanford.edu

Last set of these that I received was Oct. 11, 2016.

**Comment by tberardini** [comment]
Sample [go] Github Annotation Tracker Update

Summary for tickets from 2016-10-11T06:06:03.966Z to 2016-10-12T06:06:03.966Z
New Tickets

There have been no new tickets.
Updated Tickets


Sample [go] Github Ontology Tracker Update

Summary for tickets from 2016-10-11T06:11:03.375Z to 2016-10-12T06:11:03.375Z
New Tickets
There is one new ticket.

    12727 "GO:0034290 holin activity" AND "GO:0044660 cytolysis by virus via pore formation in host cell membrane", etc. ancestry

Updated Tickets
There are 1 updated tickets.

    12678 Query about "chromatin-templated microtubule nucleation"


There have been no updated tickets.

**Comment by cmungall** [comment]
Possibly related, but the emails sent out by go-github-ontology-requests-summary-email is not coming in

According to the log it works:

https://build.berkeleybop.org/view/GO/job/go-github-ontology-requests-summary-email/lastStableBuild/console

But the emails are not getting through.

```
---------- Forwarded message ----------
From: BBOP-Jenkins <jenkins@mill.lbl.gov>
Date: Tue, Oct 11, 2016 at 11:11 PM
Subject: [go] Github Ontology Tracker Update
To: go-consortium@lists.stanford.edu, go-curator-tracker@lists.stanford.edu


Summary for tickets from 2016-10-11T06:11:03.375Z to 2016-10-12T06:11:03.375Z
New Tickets
There is one new ticket.

    12727 "GO:0034290 holin activity" AND "GO:0044660 cytolysis by virus via pore formation in host cell membrane", etc. ancestry

Updated Tickets
There are 1 updated tickets.

    12678 Query about "chromatin-templated microtubule nucleation"
```

**Comment by monicacecilia** [comment]
@tberardini @cmungall 
FWIW, I am actually still getting the _[go] Github Ontology Tracker Update_ emails (via go-consortium and go-curators-tracker mailing lists). 

As recently as 2 days ago I received the one shown below, and then am empty one 10 hours ago. 
<img width="762" alt="screen shot 2016-10-20 at 9 19 14 am" src="https://cloud.githubusercontent.com/assets/1714621/19568496/a95ddfbc-96a6-11e6-9124-c5d0e1eb9c10.png">

**Comment by stuartmiyasato** [comment]
We've been receiving messages that emails with the subject "Github Annotation Tracker Update" and "Github Ontology Tracker Update" have been automatically discarded by the go-consortium@lists.stanford.edu mailing list.  I'm not sure what changed to cause this behavior, but I have just added jenkins@mill.lbl.gov as an approved sender for that list.

If there is a problem with the go-curator-tracker@lists.stanford.edu list, I am unaware of it as I am not set as an owner or moderator of that list.

**Comment by mcourtot** [comment]
I received both the go-annotation and the go-ontology emails this morning, but @bmeldal mentioned she only received the annotation one.

**Comment by bmeldal** [comment]
Argh, I did get the ontology one as well but deleted it with a load of spam! Sorry, I'm a bit tired this morning...

**Comment by tberardini** [comment]
I got both  go-annotation and the go-ontology emails this morning.

**Comment by kltm** [comment]
This is done then, yes?

Sound like it was marked spam (https://github.com/geneontology/go-site/issues/217#issuecomment-255161126), now corrected (https://github.com/geneontology/go-site/issues/217#issuecomment-255397466).

**Comment by tberardini** [comment]
THese emails are back:

But this one is still missing I think:

**Comment by cmungall** [comment]
Correct, the tracker updates (https://build.berkeleybop.org/view/GO/job/go-github-ontology-requests-summary-email) are functional, but the release-go emails (https://build.berkeleybop.org/job/release-go) do not go out.

**Comment by mcourtot** [comment]
@stuartmiyasato: could you check whether there is an issue with the go-watchers list and the sender jenkins@mill.lbl.gov? 
Things seem to be working now that you added jenkins@mill.lbl.gov as an approved sender to go-consortium; maybe same needs to be done for go-watchers? Nothing seems to have made it through since July 2016: https://mailman.stanford.edu/pipermail/go-watchers/

**Comment by mcourtot** [comment]
@cmungall, @kltm : looking through archives of go-watchers, there are only the release emails there. It would I think be good to consolidate notifications: should we send the GH updates and release status to go-consortium?

**Comment by stuartmiyasato** [comment]
@mcourtot I actually don't have access to go-watchers.  I'm not sure who does, although I suspect Mike Cherry does.  I'll forward your note to him and see if either he can take care of it or if he can make me an owner of the list so I'll have privileges to change the list configurations.

**Comment by mcourtot** [comment]
Daily reports are now going out, and seems complete as per https://github.com/geneontology/go-site/issues/240

Ticket to follow up for release email is at https://github.com/geneontology/go-site/issues/246
