### ISSUE TITLE
gorule-0000001: GAF and GPAD parser checks for GO Id

### ISSUE THREAD

**Issue by mugitty** [geneontology/go-site#2175]
The following line is not reported as an error.  Only as warning
! FAILS GORULE:0000001 - TEST 13 - bad GO ID syntax; bad namespace															
PomBase	SPAC25B8.19	ypf3	is_active_in	RO:0006921	GO_REF:0000024	ISO	SGD:S000001583	C	GORULE:0000001-13 intramembrane aspartyl protease of the perinuclear ER membrane Ypf1 (predicted)	ppp81	protein	taxon:4896	20150305	PomBase	

Update GAF and GPAD parser to ensure name space is 'GO' and identifier is integer > 0

**Comment by pgaudet** [comment]
Note that this test is checking the the GOID is correct: GO:#######
GORULE:0000001 - TEST 13 has RO: as the prefix. 

Not sure which rule is testing this, I had assumed gorule-0000001

**Comment by pgaudet** [comment]
This is now OK on the latest test.
