### ISSUE TITLE
EnsemblPlants xref in db-xrefs.yaml doesn't work correctly

### ISSUE THREAD

**Issue by elserj** [geneontology/go-site#220]
After realizing we had it as Ensembl_Plants instead of EnsemblPlants as in the db-xrefs.yaml file, we switched it in the gaf file and reloaded.  However, now the URL that is generated is:
http://www.ensemblgenomes.org/id/[example_ID]
when it should be:
http://www.ensemblgenomes.org/id/EMT11640 (for example)

My guess is that all the Ensembl* entries in the file are [example_ID] rather than [example_id].  I'm guessing the case matters, and so AmiGO is not replacing [example_ID] with what it should be.

**Comment by cmungall** [comment]
Looks like @austinmeier fixed this one
