### ISSUE TITLE
Change sources: Human, chicken, dog, pig, cow files

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#2214]
Hello, 

@alexsign /GOA is now producing 'combined' files for Human, chichen, dog, pig, cow files, containing all Swiss-Prot isoforms, (_not_ the TrEMBL isoforms), complexes, and RNAs. 

The links are here: 

- Chicken http://ftp.ebi.ac.uk/pub/databases/GO/goa/CHICKEN/goa_chicken_plus.gaf.gz
- Cow: http://ftp.ebi.ac.uk/pub/databases/GO/goa/COW/goa_cow_plus.gaf.gz
- Dog: http://ftp.ebi.ac.uk/pub/databases/GO/goa/DOG/goa_dog_plus.gaf.gz
- Human: http://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human_plus.gaf.gz
- Pig: http://ftp.ebi.ac.uk/pub/databases/GO/goa/PIG/goa_pig_plus.gaf.gz

We need to change where we get this data in our 'sources'

Thanks, Pascale

**Comment by kltm** [comment]
Talking to @pgaudet , we'll wait for this next release to pass and then push the change. Possible locations of frictions:

- [ ] neo
- [ ] downloads
- [ ] stats

**Comment by kltm** [comment]
@pgaudet I noticed the existence of `goa_pdb` (https://ftp.ebi.ac.uk/pub/databases/GO/goa/PDB/goa_pdb.gaf.gz) in the metadata. Is this used for anything? I think we don't use that? I don't have any reference to it, except causing problems, back to 2019.

**Comment by pgaudet** [comment]
The files in the first comment are correct. GOA produces various files for various groups; we can ignore these.

**Comment by kltm** [comment]
Initial changes have been made and we're waiting on a snapshot run to test.

**Comment by kltm** [comment]
Talking @pgaudet, the stats seem to be good.
Looking at the test downloads page (http://snapshot.geneontology.org/products/pages/downloads.html , _ignoring the links_), that seems to be good.

The final item to ensure is the NEO build. Building now.

**Comment by kltm** [comment]
NEO built:
`1734706857 golr-index-contents.tgz`
on machine:
`1738730937 golr_new.tgz`
Given how close these are, I think it's reasonable that nothing extreme happened. Allowing `snapshot` to proceed.

**Comment by pgaudet** [comment]
Single file for human, dog, cow, chicken and pig: :) 



![Image](https://github.com/geneontology/go-site/assets/4782928/41c532f7-80ef-4d19-ad11-a5aae4d4cc8d)




compared to 2024-04-24 release: 


![Image](https://github.com/geneontology/go-site/assets/4782928/53a3b4c9-4462-4ebd-a389-ca7e6efea1fd)

**Comment by suzialeksander** [comment]
I think this is complete? The only concern I see now is the entity is incorrect, currently is "protein" when it's a mix of protein, various RNAs, "gene_product", etc. But I think the requirements of this actual ticket are complete.

**Comment by pgaudet** [comment]
Right, next, we need to fix the downalods page and the documentation,
