### ISSUE TITLE
Change assigned_by for GOC OWL inferences to be able to distinguish from F-P

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#222]
See https://docs.google.com/spreadsheets/d/1yW6jUW1W6-wBRk7chrV3gGLNz4Lk9MYLXAl1AtJWd5s/edit#gid=0 for a summary of how different fields are propagated by

 * GOA F->P inference pipeline
 * GOC F->P inference pipeline
 * GOC OWL inference pipeline (aka fold based prediction)

Note the two GOC ones are combined into the same jenkins report, e.g. https://build.berkeleybop.org/view/GAF/job/gaf-check-mgi/

The proposal is to change the GOC OWL one to have assigned by GOC-OWL to allow better filtering donwstream

cc @dosumis @tonysawfordebi

**Comment by dosumis** [comment]
NOTE: Disadvantage of the Berkeley inference pipeline is that it doesn't retain the link back to the original annotation.  GOA does (in DB).  This is problematic for curators - e.g. p2G users will not be able to tell which annotations are inferred from their originals.

**Comment by tonysawfordebi** [comment]
I've implemented a first stab at a pipeline to integrate the GOC-OWL inferences into our database, and I've noticed that a significant proportion of the (currently) small number of these annotations are to terms that are part of the gocheck_do_not_annotate subset (specifically GO:0097223 sperm part and 
GO:0097458 neuron part).
