### ISSUE TITLE
Computed annotation to 'do not annotate terms'

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-site#2225]
Hi

Issue discussed at ontology call: http://wiki.geneontology.org/index.php/Ontology_meeting_2016-04-07 

I noticed that MGI has some annotations to 'sperm part' coming from the GOC pipeline. For example, Spag17 has an GOC sourced annotation to "sperm part" by IC from "axonemal central apparatus" with the annotation extension "part_of sperm"

However, the term "sperm part" is in the "Terms not to be used for direct annotation (gocheck_do_not_annotate) set.

It seems that the GOC inference pipeline should take the do not annotate subset into account.   

thanks,

-Karen

@hdietze

**Comment by pgaudet** [comment]
Out of date.
