### ISSUE TITLE
PomBase inferred GAF missing annotations

### ISSUE THREAD

**Issue by mah11** [geneontology/go-site#2226]
We've noticed this the last few times we've committed the PomBase GAF to GO: the gene_association.pombase.inf.gaf file produced by the Jenkins job has far fewer inferred annotations than the equivalent file I get when I run the owltools checks locally (most recently 342 in build 97 vs. 2355 annotations).

I haven't examined every inferred annotation in detail, but some spot-checking suggests that it's not just redundant annotations in one file but not the other; rather, there are annotations that we expect to see inferred that are missing from the Jenkins file. For example, PomBase has 19 genes annotated to GO:0005484, which is part_of GO:0061025. The local file has 16 annotations to GO:0061025 inferred, but none are in the Jenkins file.

The difference also doesn't correlate exactly with evidence codes. There are a few codes that appear only in our locally generated .inf.gaf (IEP, NAS, TAS), but for all codes that are in the Jenkins .inf.gaf there are fewer annotations than in our local file.

Is there anything else I should check for, e.g. in our owltools configuration? (We definitely think the locally produced inferred annotation set is better because it's more complete.)

This might also connected to geneontology/go-annotation#1230 

thanks
m

**Comment by pgaudet** [comment]
I am not clear how F-> P links happen. 
There are several tickets about this

**Comment by pgaudet** [comment]
We now plan to get these from GOA. This will take a few months, but there is no work on the GO side planned for this.

@kltm
