### ISSUE TITLE
Add curator ORCIDs to noctua metadata; first check for data issues

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-site#2227]
There are some curators that are displaying in Noctua by ORCiD, not name.  Changing the users.yaml to add the ORCiD as the URI should fix this, but some users have existing URIs.  Can the noctua models be grep'd to see if any of the URIs for the following have escaped into the wild:

'GOC:di' Diane Inglis
'GOC:jd' GOC:Janos Demeter
'GOC:jh' GOC:Jodi Hirschman
'GOC:ssd' GOC:Selina Dwight

@kltm

**Comment by suzialeksander** [comment]
Notes from checking:


Possible bugs, these are appearing as orcids in the contributors field and aren't searchable unless you add to filters by tapping it up from the contributors display... have a video if this becomes a new ticket.
GOC:Chandra Theesfeld -> this one has ` uri: 'https://orcid.org/0000-0002-8379-6600'` so additional bug?
GOC:Eurie Hong has   `uri: 'https://orcid.org/0000-0002-1775-4998'` 
GOC:Terry Jackson has `  uri: 'https://orcid.org/0000-0003-2387-6411'`


new users @suzialeksander will add:

GOC:Emily Camozzi -> new add
GOC:Kara Dolinski _> new add
GOC:Paul Lloyd -> new add
GOC:Rose Oughtred -> new add

No action here:

~~GOC:Anand Sethuraman~~ no ORCiD
~~GOC:Cynthia Krieger~~  no ORCiD
~~GOC:Julie Park~~  no ORCiD
~~GOC:Karen Christie~~ resolves OK
~~GOC:Maria Costanzo~~ resolves OK

**Comment by kltm** [comment]
@vanaukenk Is there a "noctua" project we could move this to?

**Comment by dustine32** [comment]
Using this command against `master` branch of `noctua-models`:
```
$ grep "GOC:abc" -r models/
```
Where "GOC:abc" is a placeholder for these:
'GOC:di'
'GOC:jd'
'GOC:jh'
'GOC:ssd'

I don't see any of these uri's above in the model files.

**Comment by kltm** [comment]
Counter-confirming that
```
sjcarbon@moiraine:~/local/src/git/noctua-models/models[master]$:( grep "GOC:sjc" -r *.ttl
```
_does_ show up.

As this stands then, updating the `uri` field should be safe as a metadata-only fix.

**Comment by suzialeksander** [comment]
I'm clear to manually change these, right?

**Comment by kltm** [comment]
I'd say "yes".
