### ISSUE TITLE
ORCIDs being filtered when not explicitly given Noctua permissions

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-site#2228]
These curators are appearing as orcids in the contributors field and aren't searchable unless you add to filters by tapping it up from the contributors display

GOC:Chandra Theesfeld -> this one has ` uri: 'https://orcid.org/0000-0002-8379-6600'` so additional bug?
GOC:Eurie Hong has   `uri: 'https://orcid.org/0000-0002-1775-4998'` 
GOC:Terry Jackson has `  uri: 'https://orcid.org/0000-0003-2387-6411'`

_Originally posted by @suzialeksander in https://github.com/geneontology/go-site/issues/2227#issuecomment-1936707290_

**Comment by suzialeksander** [comment]
@kltm 

If this is indeed the problem, let me know the min I'd need to add in the users.yaml for these curators, guessing this but not sure if allow-edit needs to be true?

>   accounts:
>     github: daniwelter
>   authorizations:
>     noctua:
>       go:
>         allow-edit: true

**Comment by kltm** [comment]
Assuming the forms are using the `/users` endpoint from barista, only people who have edit permission on this instance are returned.

**Comment by kltm** [comment]
@vanaukenk Is there a "noctua" project we could move this to?

**Comment by kltm** [comment]
@tmushayahama , would you have an answer for https://github.com/geneontology/go-site/issues/2228#issuecomment-1936730444

**Comment by vanaukenk** [comment]
@suzialeksander - on the 2024-02-15 Noctua workbenches call, we agreed to fix this display issue right now by adding noctua edit = true for each of the SGD curators who have an ORCID displayed instead of their 'nickname'.
You can update the users.yaml for this.
Please let us know if you have any questions.
@kltm @dustine32

**Comment by suzialeksander** [comment]
Noting here the yaml PR check was angry when I added the permissions without a group, if this comes up again.

My pull https://github.com/geneontology/go-site/pull/2239 is failing on four curators we don't have ORCIDs for.  I know for certain we've looked for one and she doesn't have it.  Is the best solution to remove noctua permissions and group and return to how it was? (also triple checking if SGD can supply ORCIDs). In SGD's opinion this is a minor issue although future groups might have the same issue.

Cathy Ball
Cindy Krieger
Julie Park
Anand Sethuraman

**Comment by kltm** [comment]
Noting, that the `GOC:` IDs "work" as ORCIDs. I'm assuming that since you don't have these in the import data, it wouldn't be a problem?

**Comment by suzialeksander** [comment]
I think yes- they're currently in Noctua as GOC:xx, and that would be fine for this little handful of curators as far as SGD is concerned.  Mainly just documenting this for the next imported group (Worm?) to not be shocked when this occurs.  I'll leave that PR open until I can verify we definitely don't have ORCIDs for any of them

**Comment by suzialeksander** [comment]
There's no ORCID, so no way to give these users Noctua permissions currently. 

labelling won'tfix for the remaining 4 curators.
