### ISSUE TITLE
Trigger deploy workflow of `geneontology.github.io` when `gorefs.yaml` changes

### ISSUE THREAD

**Issue by pkalita-lbl** [geneontology/go-site#2235]
To be done after https://github.com/geneontology/geneontology.github.io/issues/507

- [ ] Add a new workflow to this repo which is triggered on changes to `metadata/gorefs.yaml` in the `master` branch. The workflow should use the [GitHub CLI](https://cli.github.com/manual/) to trigger the build and deploy workflow (created as part of https://github.com/geneontology/geneontology.github.io/issues/507) in the `geneontology.github.io` repo (something along the lines of `gh workflow run -R ...`). We'll need a repo administrator to add a GitHub token with permission to run that workflow as a secret in this repo. We'll also need to take care to coordinate this with the QC workflow and ensure that this workflow only runs if QC succeeded.

**Comment by kltm** [comment]
@pgaudet @suzialeksander When we reach this point, it would be good to review the changes (minimal to none at your end) and think about how (if?) to link this from the main geneontology.org pages.

**Comment by pgaudet** [comment]
It may be a good idea to deploy these on the GO website, unless the layout we have improves; right now it's a bit weird to send users to the GH markdown page (for eg https://github.com/geneontology/go-site/blob/master/metadata/gorefs/goref-0000001.md) - if I were a user I would not be sure whether I landed there on purpose.

**Comment by kltm** [comment]
@pgaudet To clarify, have these built in to the main site is the point of those section. I'm trying to specify how you want to specifically present it.

**Comment by pgaudet** [comment]
You comment " think about **how (if?)** to link this from the main geneontology.org pages." 

sounded like we were considering moving the GOREFs to the website, not that it was decided. Thanks for the clarification.

**Comment by pkalita-lbl** [comment]
Yes, just reiterating that the plan is to deprecate and [remove](https://github.com/geneontology/go-site/issues/2237) the Markdown files. There will be pages instead of geneontology.org. The format of those pages isn't fully specified. As part of https://github.com/geneontology/geneontology.github.io/issues/506 I imagine I will make a prototype of those pages and get feedback before finalizing it.

**Comment by pkalita-lbl** [comment]
This is now done with https://github.com/geneontology/go-site/pull/2294 and related PRs.

As an example, the merge of [this PR](https://github.com/geneontology/go-site/pull/2297) into `master` trigger this workflow run: https://github.com/geneontology/go-site/actions/runs/8669326165. That workflow run in turn triggered this workflow run in the `geneontology.github.io` repo: https://github.com/geneontology/geneontology.github.io/actions/runs/8669329419.
