### ISSUE TITLE
Create a GPAD2.0 test file 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#2241]
Based on the GAF1.2 test file, which is here: https://github.com/geneontology/go-site/blob/master/docs/gorules_test_errors.gaf

Working Google spreadsheet: https://docs.google.com/spreadsheets/d/1Sa2gWpx_wFAHWf36mHM1W9_FJuUg77zBrsVAplbAEak/edit#gid=1312805589

Note that this excludes all checks for gorule-0000001 for now (need to check in the GAF1.2 test before going ahead with the conversion)

**Comment by LiNiMGI** [comment]
done.

**Comment by pgaudet** [comment]
Thanks !!

**Comment by pgaudet** [comment]
Need to add checks for gorule-0000001 (when these are done)

**Comment by LiNiMGI** [comment]
@pgaudet yes, please add them to the google spreadsheet when ready for the convert, thanks, Li

**Comment by pgaudet** [comment]
Updated  tests for gorule-0000005, gorule-0000022, gorule-0000063, and gorule-0000064

**Comment by pgaudet** [comment]
Missing tests for GORULE-0000001 (since the format of the GPAD is different, some rules need to be different)
