### ISSUE TITLE
gorule-0000057 is not implemented but showing up in reports

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#2243]
Hi @mugitty 

According to @dustine32 , gorule-0000057 was never implemented (see https://github.com/geneontology/go-site/issues/1553), but it's showing up in reports, see 

http://current.geneontology.org/reports/assigned-by-gorule-report.html

Can you please remove it from the pipeline? 

Thanks, Pascale

**Comment by mugitty** [comment]
@kltm, If the rule is valid, then we need to ensure it is implemented correctly and @pgaudet will add tests. When I discussed with @dustine32, he indicated that the rule was no longer necessary and I was going to remove

**Comment by dustine32** [comment]
@mugitty As @kltm mentioned, there is a list of GoRules here:
https://github.com/biolink/ontobio/blob/57adf9c2bcdc9385c45116b58535e446f6b30bd0/ontobio/io/qc.py#L950
You can try removing GoRule57 from this list and running the validation to see if the rule row is removed from the `assigned-by-gorule-report.html`.

**Comment by dustine32** [comment]
@kltm Is this `GORULE_TAGS_TO_SUPPRESS` the rule filter variable you were referring to?
https://github.com/geneontology/pipeline/blob/5990c634683d2e5fc51f6c1baa4db8e8cc67b96b/Jenkinsfile#L135C4-L135C27

**Comment by mugitty** [comment]
I know how to remove the rule so that it does not appear in the reports.
@pgaudet has deprecated the rule, however @kltm may want to keep it. I am not sure how to proceed.  There are config parameters that can be passed to filter out the annotations.

**Comment by kltm** [comment]
@mugitty If the rule is deprecated, I would consider excising unnecessary code and commenting as such in the rule implementation notes in the rule metadata itself.

**Comment by mugitty** [comment]
#https://github.com/biolink/ontobio/pull/667

**Comment by pgaudet** [comment]
Not shown in go-rules reports, so this is OK for me - 

@kltm Do you want a 'cleaner' solution to this?

**Comment by kltm** [comment]
@pgaudet I'm okay with whatever is practical, but I just wanted to make sure we're all on the same page about expectations.

**Comment by pgaudet** [comment]
Working as needed for curators. We can revisit the system if needed.
