### ISSUE TITLE
RNAC RNA types are getting mangled by the pipeline (tested by gorule-0000001) 

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#2246]
Source:

```
✗ curl -L -s https://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human_rna.gaf.gz | gzip -dc | grep URS000075D95B_9606 | cut -f2,3,9-12
URS00004176D4_9606	URS00004176D4_9606	F	Homo sapiens (human) hsa-miR-185-5p		miRNA
URS000075D95B_9606	URS000075D95B_9606	F	Homo sapiens (human) X inactive specific transcript (XIST)		lncRNA
URS000075D95B_9606	URS000075D95B_9606	F	Homo sapiens (human) X inactive specific transcript (XIST)		lncRNA
URS000075D95B_9606	URS000075D95B_9606	F	Homo sapiens (human) X inactive specific transcript (XIST)		lncRNA
URS000075D95B_9606	URS000075D95B_9606	P	Homo sapiens (human) X inactive specific transcript (XIST)		lncRNA
URS000075D95B_9606	URS000075D95B_9606	P	Homo sapiens (human) X inactive specific transcript (XIST)		lncRNA
URS000075D95B_9606	URS000075D95B_9606	P	Homo sapiens (human) X inactive specific transcript (XIST)		lncRNA
URS000075D95B_9606	URS000075D95B_9606	P	Homo sapiens (human) X inactive specific transcript (XIST)		lncRNA
URS000075D95B_9606	URS000075D95B_9606	P	Homo sapiens (human) X inactive specific transcript (XIST)		lncRNA
URS000075D95B_9606	URS000075D95B_9606	C	Homo sapiens (human) X inactive specific transcript (XIST)		lncRNA
URS000075D95B_9606	URS000075D95B_9606	C	Homo sapiens (human) X inactive specific transcript (XIST)		lncRNA
URS000075D95B_9606	URS000075D95B_9606	C	Homo sapiens (human) X inactive specific transcript (XIST)		lncRNA
```

what we end up publishing:

```
✗ curl -L -s http://current.geneontology.org/annotations/goa_human_rna.gaf.gz | gzip -dc | grep URS000075D95B_9606 | cut -f2,3,9-12
URS00004176D4_9606	URS00004176D4_9606	F	Homo sapiens (human) hsa-miR-185-5p		miRNA
URS000075D95B_9606	URS000075D95B_9606	F	Homo sapiens (human) X inactive specific transcript (XIST)		gene_product
URS000075D95B_9606	URS000075D95B_9606	F	Homo sapiens (human) X inactive specific transcript (XIST)		gene_product
URS000075D95B_9606	URS000075D95B_9606	P	Homo sapiens (human) X inactive specific transcript (XIST)		gene_product
URS000075D95B_9606	URS000075D95B_9606	P	Homo sapiens (human) X inactive specific transcript (XIST)		gene_product
URS000075D95B_9606	URS000075D95B_9606	P	Homo sapiens (human) X inactive specific transcript (XIST)		gene_product
URS000075D95B_9606	URS000075D95B_9606	P	Homo sapiens (human) X inactive specific transcript (XIST)		gene_product
URS000075D95B_9606	URS000075D95B_9606	P	Homo sapiens (human) X inactive specific transcript (XIST)		gene_product
URS000075D95B_9606	URS000075D95B_9606	C	Homo sapiens (human) X inactive specific transcript (XIST)		gene_product
URS000075D95B_9606	URS000075D95B_9606	C	Homo sapiens (human) X inactive specific transcript (XIST)		gene_product
URS000075D95B_9606	URS000075D95B_9606	C	Homo sapiens (human) X inactive specific transcript (XIST)		gene_product
```

1. The RNA type should be preserved
2. We should have a specific QC check on RNCA that anything with an RNCA ID *must* be an RNA subtype

Aside for @alexsign should probably be it's own ticket:

Why don't we get gene symbols for RNA types? This one (Xist) clearly has one https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:12810 - why don't we just propagate across from HGNC?

And not to overstuff this issue but there are issues with general RNCA/HGNC propagation on AGR. Recall AGR uses HGNCs:
https://www.alliancegenome.org/gene/HGNC:12810
no GO annotatuion

Even though this gene obviously has a known function:
https://amigo.geneontology.org/amigo/gene_product/RNAcentral:URS000075D95B_9606

**Comment by mugitty** [comment]
Thanks @pgaudet , I will update to use this list and output a warning, if defaulting to gene_product.

**Comment by kltm** [comment]
As part of the "gaf tests", it would be good to add something to make sure that the synonyms are mapping back to the proper ID (i.e. `lnc_RNA` -> `lncRNA`).

**Comment by mugitty** [comment]
@kltm,
@pgaudet's wants to only use the terms in the attachment.  All others will default to gene_product with gorule-0000001 warning. Based on the number of warnings, the list may be updated

**Comment by kltm** [comment]
@pgaudet Clarifying that you're removing `lncRNA` (SO:0001877) in favor of SO child `lincRNA` (SO:0001463)?

**Comment by mugitty** [comment]
@pgaudet , I noticed a test for MGI that was failing with the proposed code update.  For example, if there is a GAF line as follows:
    gaf = ["MGI", "MGI:1923503", "0610006L08Rik", "enables", "GO:0003674", "MGI:MGI:2156816|GO_REF:0000015", "ND", "",
           "F", "RIKEN cDNA 0610006L08 gene", "", "gene", "taxon:10090", "20120430", "MGI", "", ""]

 "gene" will be converted to "gene_product". Is this expected?

**Comment by pgaudet** [comment]
Hi @mugitty 
Can you check in this directory in all the files *-src.gaf.gz: 
http://snapshot.geneontology.org/products/upstream_and_raw_data/index.html

whether entity types OTHER than the following are present: 

protein_coding_gene	SO:0001217
protein	PR:000000001
gene_product	CHEBI:33695
snRNA	SO:0000274
ncRNA	SO:0000655
rRNA	SO:0000252
mRNA	SO:0000234
lincRNA	SO:0001463
tRNA	SO:0000253
snoRNA	SO:0000275
miRNA	SO:0000276
scRNA	SO:0000013
piRNA	SO:0001035
tmRNA	SO:0000584
SRP_RNA	SO:0000590
ribozyme	SO:0000374
telomerase_RNA	SO:0000390
RNase_P_RNA	SO:0000386
antisense_RNA	SO:0000644
RNase_MRP_RNA	SO:0000385
guide_RNA	SO:0000602
hammerhead_ribozyme	SO:0000380
pseudogene	SO:0000336
protein_complex	GO:0032991
antisense_lncRNA	SO:0001904
gene_segment	SO:3000000
genetic_marker	SO:0001645
biological region	SO:0001411
transposable_element_gene	SO:0000111


and spit out any entity type that doesn't match these, on a file-by-file basis.

**Comment by pgaudet** [comment]
Alternatively - or in addition, could you give me a count of these different types: 

protein_coding_gene	SO:0001217
protein	PR:000000001
gene_product	CHEBI:33695
snRNA	SO:0000274
ncRNA	SO:0000655
rRNA	SO:0000252
mRNA	SO:0000234
lincRNA	SO:0001463
tRNA	SO:0000253
snoRNA	SO:0000275
miRNA	SO:0000276
scRNA	SO:0000013
piRNA	SO:0001035
tmRNA	SO:0000584
SRP_RNA	SO:0000590
ribozyme	SO:0000374
telomerase_RNA	SO:0000390
RNase_P_RNA	SO:0000386
antisense_RNA	SO:0000644
RNase_MRP_RNA	SO:0000385
guide_RNA	SO:0000602
hammerhead_ribozyme	SO:0000380
pseudogene	SO:0000336
protein_complex	GO:0032991
antisense_lncRNA	SO:0001904
gene_segment	SO:3000000
genetic_marker	SO:0001645
biological region	SO:0001411
transposable_element_gene	SO:0000111
gene	SO:0000704
lincRNA_gene	SO:0001641
lncRNA_gene	SO:0002127
miRNA_gene	SO:0001265
mRNA	SO:0000234
ncRNA_gene	SO:0001263
primary_transcript	SO:0000185
RNA	SO:0000356
RNase_MRP_RNA_gene	SO:0001640
RNase_P_RNA_gene	SO:0001639
rRNA_gene	SO:0001637
scRNA_gene	SO:0001266
sense_intronic_ncRNA_gene	SO:0002184
sense_overlap_ncRNA_gene	SO:0002183
snoRNA_gene	SO:0001267
snRNA_gene	SO:0001268
SRP_RNA_gene	SO:0001269
telomerase_RNA_gene	SO:0001643
transcript	SO:0000673
tRNA_gene	SO:0001272
+ any unmatching

Thanks, Pascale

**Comment by kltm** [comment]
@mugitty @pgaudet I'm running job to get numbers on col12.

**Comment by kltm** [comment]
```
    570 antisense_lncRNA
      1 antisense_lncRNA_gene
   6262 antisense_RNA
    188 autocatalytically_spliced_intron
 543618 gene
 362496 gene_product
    170 gene_segment
      4 guide_RNA
   2562 hammerhead_ribozyme
      2 lincRNA
 132472 lncRNA
     23 lnc_RNA
     18 lncRNA_gene
  32965 miRNA
      2 miRNA_gene
1719451 misc_RNA
  47234 mRNA
 201054 ncRNA
   8172 other
    464 piRNA
   2923 precursor_RNA
 147790 pre_miRNA
1357853612 protein
 406877 protein_coding_gene
  22567 protein_complex
   1005 pseudogene
     72 pseudogenic_transcript
      1 reactome-src.gaf.gz:date-generated: 2023-12-01
      1 reactome-src.gaf.gz:generated-by: Reactome
      1 reactome-src.gaf.gz:Project-release: Version 87
   3606 ribozyme
    434 RNA
   5547 RNase_MRP_RNA
 306437 RNase_P_RNA
12871329 rRNA
    192 scaRNA
    268 scRNA
      1 scRNA_gene
     15 siRNA
      1 sncRNA
 362852 snoRNA
 871408 snRNA
 170884 sRNA
 195433 SRP_RNA
   1053 telomerase_RNA
 103559 tmRNA
      2 transposable_element_gene
10232300 tRNA
      9 tRNA_gene
      2 uORF
      8 vault_RNA
      6 Y_RNA
      1 zfin-src.gaf.gz:0.001!date-generated: 2024-03-14
```

**Comment by kltm** [comment]
(Noting that reactome and zfin need to [obviously] fix their GAF.)

**Comment by mugitty** [comment]
@pgaudet, do you still want me to output the types for each file or is @kltm 's output good enough for now?

**Comment by pgaudet** [comment]
> (Noting that reactome and zfin need to [obviously] fix their GAF.)

Isn't this gorule-0000001 ? 
It seems it should be a hard error.

**Comment by pgaudet** [comment]
@mugitty 

Yes @kltm 's output is fine to get started.

**Comment by pgaudet** [comment]
For reference - these are the types that GOA loads from RNA central

rRNA    12894606
tRNA    10330538
misc_RNA    1720365
snRNA    833596
snoRNA    350816
RNase_P_RNA    307952
ncRNA    199135
SRP_RNA    194578
sRNA    167541
pre_miRNA    138520
lncRNA    114530
tmRNA    104453
miRNA    24008
other    7295
antisense_RNA    6196
RNase_MRP_RNA    5464
ribozyme    3603
precursor_RNA    2893
hammerhead_ribozyme    2556
telomerase_RNA    885
piRNA    445
scRNA    262
scaRNA    195
autocatalytically_spliced_intron    189
siRNA    15
vault_RNA    8
Y_RNA    6
guide_RNA    2

**Comment by pgaudet** [comment]
@kltm should I make a new GO rule for entity types?

**Comment by kltm** [comment]
@pgaudet That would be great.

**Comment by pgaudet** [comment]
Hi @mugitty 

Here are repairs we  should implement: 

- lnc_RNA should be repaired to lncRNA (should also be replaced in the code in the list of CURIES)
- lncRNA is SO:0001877


These have to be added to the GO list of CURIEs: 
-  pre_miRNA is SO:0001244
- antisense_lncRNA_gene is SO:0002182
- pre_miRNA is SO:0001244
- scaRNA is SO:0002095
- pseudogenic_transcript is SO:0000516
- siRNA is SO:0000646
- autocatalytically_spliced_intron  SO:0000588
- vault_RNA  SO:0000404
- Y_RNA  SO:0000405

That should take care of many issues. 

However, these types are not in SO: 

- misc_RNA
- other
- precursor_RNA
- sncRNA
- sRNA
- uORF

@mugitty and I propose to continue to change them to 'gene product' and output a warning. 

Thanks, Pascale

**Comment by pgaudet** [comment]
I need to add tests for the entity types ; can we first check snapshot to see if disallowed types are being reported?

**Comment by pgaudet** [comment]
This problem is fixed: 



![Image](https://github.com/user-attachments/assets/4b22839d-49b0-48b5-abfa-60daa63c80ff)

**Comment by pgaudet** [comment]
lncRNA amiGO: 



![Image](https://github.com/user-attachments/assets/b479350a-8027-4519-9977-697ac8c95004)




lncRNA staging 



![Image](https://github.com/user-attachments/assets/fd57a2e3-f7e3-4454-bd02-ac617c07945c)

**Comment by pgaudet** [comment]
Correctly fails test 

WARNING - Invalid subject type:defaulting to 'gene_product'--`UniProtKB A1B2F4 aztD acts upstream of GO:0097696 PMID:26468286 IDA F GORULE_TEST:0000001-28 misc_RNA taxon:318586 20230427 GO_Central `
