### ISSUE TITLE
Shex violations report for SGD load

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-site#2252]
@dustine32 is working on pulling the ShEx errors for the SGD annotations loaded from P2GO.  Spot checking of models revealed some relations that were incorrect in P2GO, eg `complex` `part_of` `biological_process` some  If there are widespread issues, @vanaukenk and I will talk about if they can be manually fixed or needs to be fixed in batches.

**Comment by suzialeksander** [comment]
also tagging @thomaspd

**Comment by dustine32** [comment]
@suzialeksander @vanaukenk Here is the ShEx validation report for the 7075 SGD import models (from this [PR](https://github.com/geneontology/sgd-go-cams/pull/4)):
[main_report.txt](https://github.com/geneontology/go-site/files/14437988/main_report.txt)
The relevant columns here are `shex_valid` and `OWL_consistent`:
* `shex_valid` - 290 models are false
* `OWL_consistent` - 13 models are false

**Comment by vanaukenk** [comment]
Thanks @dustine32 
@suzialeksander - I popped the report into a [spreadsheet](https://docs.google.com/spreadsheets/d/1ieNlAAzqCBKwt98pzNXn2GUG82Tm7Uy-uoFEp3KQYNU/edit#gid=0) for easier viewing.
It looks like some of the ShEx violations are similar to what we saw last week, but you should check some more of them.
Perhaps we can do some kind of systematic relations update.  We'd need to discuss further with the software team.

**Comment by kltm** [comment]
@vanaukenk @suzialeksander @pgaudet I just want to clarify (or prioritize the question of) whether the changes being reviewed are potentially blocking for a `release`, or if they are things that can be followed up on separately? We're currently trying to grind out a `release`, but could use the machine capacity elsewhere if that's not on the table for the moment.

**Comment by vanaukenk** [comment]
@kltm @suzialeksander @pgaudet @dustine32

Yes, @suzialeksander is right: wrt the ShEx violations, these are coming from Protein2GO and are currently visible with the annotations in SGD, AmiGO, and QuickGO (but not the Alliance where AEs aren't yet displayed).

So, it doesn't appear that we'd be putting newly created bad data out there for this specific issue.

**Comment by thomaspd** [comment]
So just to clarify, does that mean this issue is resolved, and we can go forward with the release?

**Comment by suzialeksander** [comment]
Yes, we can go ahead with the release; while there are unresolved issues with these annotations it doesn't seem necessary to hold up the release.

**Comment by suzialeksander** [comment]
Shex violations are available for SGD curators to check.
