### ISSUE TITLE
Get feedback on current new go_refs page

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#2255]
As the new page assembly gets put together, we want to make sure that it is acceptable to users.

**Comment by kltm** [comment]
Will need @pgaudet feedback.

**Comment by pkalita-lbl** [comment]
Some screenshots from my development branch that can be reviewed

**Top of page**
![image](https://github.com/geneontology/go-site/assets/102547565/693870e9-174b-4d74-ab36-c43d0fa30faf)

**Linked to a specific GO REF** (somewhere in the middle of the page)
![image](https://github.com/geneontology/go-site/assets/102547565/cb495174-7d84-49bd-ab8c-4acb0d4b5a9d)

**End of page**
![image](https://github.com/geneontology/go-site/assets/102547565/e573a2db-0478-4a19-87af-eec36d978aeb)

**Comment by kltm** [comment]
Talked to @pgaudet. @pgaudet will reach out to some other users and see what they prefer.

**Comment by kltm** [comment]
@pgaudet also floated ToC pager, and then linking to individual pages.

**Comment by pgaudet** [comment]
Decision: individual pages + ToC page

**Comment by kltm** [comment]
Also, there needs to be a link tot SoT (somewhere), so users that want to search through everything can do so. @pgaudet , can you define whether to do this on each page, or just on the ToC.
As well, can you define what you want to see on the ToC? I'm assuming just titles?

**Comment by pgaudet** [comment]
The source of truth (SoT) yaml file is an internal documentation, I propose to put a link in the wiki under the Annotation group documentation. OK ?

**Comment by pgaudet** [comment]
- [ ] Added a link to the goref.yaml file in the Annotation documentation: https://wiki.geneontology.org/Annotation_guidelines#General_Annotation_Documentation
@vanaukenk can you please add this to the list of discussion topics for the next annotation call ?

**Comment by kltm** [comment]
@pgaudet @vanaukenk Noting that this is not yet the SoT and will not be until Patrick's go-ref project is completed. He will do a final sync to re-match things before switching over, but we aware that the old SOP is in place until that happens.

**Comment by pkalita-lbl** [comment]
Here's a prototype of a basic ToC page:
![image](https://github.com/geneontology/go-site/assets/102547565/0cb65598-7ac2-44e5-ae50-29f8e7ce8813)

And an individual GO REF page:
![image](https://github.com/geneontology/go-site/assets/102547565/a9fddea0-e08e-45b5-a7a7-916ff2719e5b)

The "All GO REFs" on the individual GO REF page links back to the ToC page. Let me know if you'd like the ToC page linked from anywhere else, e.g. the header menu. Any other feedback is certainly welcome.

**Comment by kltm** [comment]
Looks good to me. @pgaudet, do you have any feedback here?

**Comment by pgaudet** [comment]
Looks good. 

I have one feature request : to have OBSOLETE refs in a separate section at the bottom. 

But if that's complicated we can drop it. Not a requirement for this work. 

Thanks, Pascale

**Comment by pkalita-lbl** [comment]
No that's not complicated at all, will do.

**Comment by pgaudet** [comment]
This seems to be all done? Can this ticket be closed?
