### ISSUE TITLE
ZFIN GAF contains uncommented metadata

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#2266]
Found during a scan for https://github.com/geneontology/go-site/issues/2246, the following ZFIN metadata is in error:

```
0.001!date-generated: 2024-03-14
```

**Comment by kltm** [comment]
Tagging @pgaudet

**Comment by pgaudet** [comment]
Not yet fixed 2024-04-24 snapshot

**Comment by rtaylorzfin** [comment]
Hi @pgaudet and @sramachand ,

I wanted to let you know that we fixed the header on that file. Thanks for letting us know!

https://zfin.org/downloads/gene_association2.2.zfin.gz

-Ryan

**Comment by pgaudet** [comment]
Header on snapshot is 

> !gaf-version: 2.2
!Version: 0.001
!date-generated: 2024-05-30
!generated-by: ZFIN 

Thanks @rtaylorzfin !
