### ISSUE TITLE
Reactome GAF contains uncommented metadata

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#2267]
Found during a scan for https://github.com/geneontology/go-site/issues/2246, the following Reactome metadata is uncommented:

```
date-generated: 2023-12-01
generated-by: Reactome
Project-release: Version 87
```

**Comment by kltm** [comment]
Tagging @pgaudet

**Comment by pgaudet** [comment]
Is this in the upstream GAF ? or in the file GOC produces?

**Comment by kltm** [comment]
This is the Reactome upstream.

**Comment by pgaudet** [comment]
Hi @deustp01 
Can you please see that the Reactome GAF header is fixed to add comments in the lines shown above (it needs "!" character) 

Thanks, Pascale

**Comment by deustp01** [comment]
Remedial tutorial needed here, sorry.

Are you saying that the only problem in the file is that the 2nd, 3rd, and 4th lines should have an "!" as their first charactr, just as the 1st one does now, and then the whole problem is fixed?

<img width="613" alt="Screenshot 2024-03-26 at 2 41 54 PM" src="https://github.com/geneontology/go-site/assets/12737623/5647cd7d-2307-4d8d-afa5-3f628c912c24">

If so, that should be easy - we will generate a correctly formatted GAF in connection with our next release in about a week.

**Comment by kltm** [comment]
@deustp01 Yes, that is exactly it!

**Comment by deustp01** [comment]
The new Reactome release is now live, and with it a correctly formatted GAF (anyway, a GAF with correctly escaped header content), accessible as usual from [our download page](https://reactome.org/download-data) (or wherever you get it automatically). Let us know if there are any persisting errors or we've created new ones.

**Comment by pgaudet** [comment]
Most recent header looks good

> !gaf-version: 2.2
!generated-by: Reactome
!date-generated: 2024-03-15
!Project-release: Version 88
