### ISSUE TITLE
Proposed  new gorule-0000064 TreeGrafter IEAs should be filtered for GO reference species

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#2273]
Proposed text:

If an annotation is an IEA to GO_REF:0000118 and the taxon is not in the GO reference species list (i.e 143 species for which we get IBAs), then filter out.

Ideally this would be implemented upstream at EBI-GOA

We have a goref for tree grafter #2130 : [GO_REF:0000118](https://github.com/geneontology/go-site/blob/master/metadata/gorefs/goref-0000118.md)

**Comment by pgaudet** [comment]
Test errors are correctly being picked up.

**Comment by pgaudet** [comment]
Working as expected.

**Comment by pgaudet** [comment]
Hi @mugitty 

Tests are not failing - or not being reported in error reports.

**Comment by mugitty** [comment]
@pgaudet, tests are failing for gorule 64 in snapshot:
http://snapshot.geneontology.org/reports/assigned-by-TreeGrafter-report.html#gorule-0000064
...
gorule-0000064

TreeGrafter IEAs should be filtered for GO reference species

    total: 10050

messages

    ERROR - Violates GO Rule:GORULE:0000064: TreeGrafter ('GO_REF:0000118') IEAs should be filtered for GO reference species--`SGD S000005513 YOL153C involved_in GO:0051603 GO_REF:0000118 IEA PANTHER:PTN000110795 P Blocked reading frame, contains two in-frame stops in translation YOL153C protein taxon:559292 20240610 TreeGrafter UniProtKB:P0C155 `
    ERROR - Violates GO Rule:GORULE:0000064: TreeGrafter ('GO_REF:0000118') IEAs should be filtered for GO reference species--`SGD S000005513 YOL153C located_in GO:0000328 GO_REF:0000118 IEA PANTHER:PTN000110795 C Blocked reading frame, contains two in-frame stops in translation YOL153C protein taxon:559292 20240610 TreeGrafter UniProtKB:P0C155 `
...

In the errors.gaf file processing, we have the following:
! FAILS GORULE:0000064 - TEST 1 - human protein
UniProtKB	A0A140VJL9	A0A140VJL9	involved_in	GO:0006783	GO_REF:0000118	IEA	PANTHER:PTHR11458:SF0	P	GORULE_TEST:0000064-1		protein	taxon:9606	20240201	TreeGrafter	
! FAILS GORULE:0000064 - TEST 2 - Drosophila protein
UniProtKB	Q8IH53	Hmbs	involved_in	GO:0006783	GO_REF:0000118	IEA	PANTHER:PTHR11557:SF0	P	GORULE_TEST:0000064-2		protein	taxon:7227	20240201	TreeGrafter		


Both test cases are reported as failing in 'GORULE violations assigned by TreeGrafter'
GORULE violations assigned by TreeGrafter

...


MESSAGES
gorule-0000064

TreeGrafter IEAs should be filtered for GO reference species

    total: 2

messages

    ERROR - Violates GO Rule:GORULE:0000064: TreeGrafter ('GO_REF:0000118') IEAs should be filtered for GO reference species--`UniProtKB A0A140VJL9 A0A140VJL9 involved_in GO:0006783 GO_REF:0000118 IEA PANTHER:PTHR11458:SF0 P GORULE_TEST:0000064-1 protein taxon:9606 20240201 TreeGrafter `
    ERROR - Violates GO Rule:GORULE:0000064: TreeGrafter ('GO_REF:0000118') IEAs should be filtered for GO reference species--`UniProtKB Q8IH53 Hmbs involved_in GO:0006783 GO_REF:0000118 IEA PANTHER:PTHR11557:SF0 P GORULE_TEST:0000064-2 protein taxon:7227 20240201 TreeGrafter `
....


Am I missing something?

**Comment by pgaudet** [comment]
Working
