### ISSUE TITLE
Start using GPAD / GPI 2.0 compatible ontobio ASAP

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#2286]
The new version of ontobio that @sierra-moxon has been working on is almnost completely compatible with what we currently use, but defaults to 2.0. We would like to not do everything at once and start using @sierra-moxon 's version ASAP, so we can have the new stuff and run with it for a bit.

To do this, we just want to make sure there is an easy switch or env control on the version, then update the pipelines to use that.

**Comment by kltm** [comment]
Talking to @sierra-moxon , she'll put in explicit variable code to the pipeline/Makefile, and make the default explicit, so the current branched code can be folded in and we have the ability to "play" with the "1.2" and 2.0 at the same time.

**Comment by kltm** [comment]
And just a heads-up to @dustine32 , similar changes will be made in scripts/Makefile-gaf-reprocess

**Comment by sierra-moxon** [comment]
This is a bit larger than estimated because we only support GPI 1.2 at the moment, and instead of converting that to only supporting 2.0 (in my branch), I'm now adding a bit of switch code to support both.

**Comment by kltm** [comment]
Currently using this in pre-snapshot.
