### ISSUE TITLE
Wind down support of MySQL db

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#229]
Options are:
1. Transition to the java code in owltools I started which would allow simple dumping of mysqldumps
2. Reduce cycle, e.g. every 6 months

**Comment by mcourtot** [comment]
Hi @cmungall - why is MySQL becoming unsupported? Is it not being used, or being used too sparsely to justify resources?

**Comment by kltm** [comment]
The main use of the MySQL dumps at this point is to support GOOSE. It used to be that the AmiGO stack was based around the MySQL, but that hasn't been true for years now. With the more complicated modeling coming down the pipe, along with the graph backend that can support queries and a GOOSE-like environment, there will not be the resources to support something that is both legacy and cannot be changed (without great effort) to support the new data.

**Comment by mcourtot** [comment]
Thanks Seth, this is helpful.

**Comment by kltm** [comment]
Oooold
