### ISSUE TITLE
dbxref file: update UBERON:0001062 label from 'metazoan anatomical entity' to 'anatomical entity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#2293]
Updated UBERON:0001062 label from 'metazoan anatomical entity' to 'anatomical entity' in the [dbxref file](https://github.com/geneontology/go-site/blob/842184393e7b1dfbef4f85bf5402ff147836dbcf/metadata/db-xrefs.yaml), to align with changes in UBERON. 

Impacts WB and FB entries (but it's just a change in label, so this should not matter?) 

@vanaukenk @hattrill 

PR is here: https://github.com/geneontology/go-site/pull/2292

**Comment by hattrill** [comment]
@pgaudet This is ok for us.
