### ISSUE TITLE
Provide GPAD/GPI 2.0 examples for public use

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#2300]
Closing this ticket means that @pgaudet has been provided a sufficiently final version of any example file(s) for GPAD / GPI 2.0, so that she can:

- let downstreams know that we are changing files and what format to expect
- to use for public documentation

**Comment by pgaudet** [comment]
Would you please assign this ticket ?

**Comment by pgaudet** [comment]
(this is blocker to go ahead with the announcement, and to roll out GPAD/GPI 2.0)

**Comment by kltm** [comment]
@pgaudet Whoops? Was this not a blocker? (Or maybe this was "Done" (as is current state), but not closed?)

**Comment by pgaudet** [comment]
Announcement sent yesterday: 

> GO Friends,

> We are planning on changing the GPAD/GPI format to 2.0, starting with 
the next release, expected towards the end of July. This change only 
affects files with the extensions ".gpad" and ".gpi"; files with ".gaf" 
will remain unchanged. In the lead-up to this version change, snapshots 
will switch to the GPAD/GPI 2.0 format starting with the next snapshot.

> The technical specifications for this change can be found at: 
https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md 
. This document also includes the list of differences between GPAD/GPI 
1.1 and 2.0..

> Once the release has been made, the default GPAD/GPI documentation links 
on the website will be updated to point to the 2.0 version 
(https://geneontology.org/docs/gene-product-association-data-gpad-format-2.0/), 
updating from the current 1.2.

> If you have any questions or concerns, please contact the GO Helpdesk at 
[help@geneontology.org](mailto:help@geneontology.org) or use the helpdesk tracker at 
https://github.com/geneontology/helpdesk/issues .

> Best,

> -Seth
