### ISSUE TITLE
Move curator_group_contacts.tsv to yaml in go-site

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#231]
We have two parallel redundant activities going on

@dosumis is doing this for the ontology group:
https://github.com/geneontology/go-ontology/blob/master/curator_group_contacts.tsv

meanwhile there is the ongoing activity by @kltm to organize group information for Noctua purposes: https://github.com/geneontology/noctua/issues/350

all metadata should go in go-site in yaml

**Comment by kltm** [comment]
I'd just go ahead and use this as a seed for the next step in completing geneontology/noctua#350 ; does that sound about right?

**Comment by kltm** [comment]
We could just close this out at point to it there. It should be completed shortly, and up until the final step, I'll seed from the TSV.

**Comment by kltm** [comment]
Really, #106, besides the fact that we have the groups.yaml, #106 is really just things like this.

**Comment by dosumis** [comment]
Any progress on this?  (Discussed on Ed call)

**Comment by kltm** [comment]
@dosumis Well, if there are no more changes to this information for now, you could go ahead and help merge the TSV with the users.yaml--my information can be used as a model, and there is the users.schema.yaml file if there are any questions. It would be good to fix any inconsistent naming in there. We'll probably also want to move to just using the groups list in the future and deprecate the organization field (which means we'll also want to fill in the groups.yaml file).

**Comment by kltm** [comment]
This should be completed with https://github.com/geneontology/go-site/pull/415

**Comment by kltm** [comment]
I'm leaving the removal in go-ontology to @dosumis or others.

**Comment by cmungall** [comment]
To summarize:

 * the tsv now lives in go-site/metadata as a csv https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv
 * we are retaining fields from original (name, github). No email. No reqt so far
 * other metadata about groups lives in groups.yaml

This seemed easier than having a complex nested structure in groups.yaml
