### ISSUE TITLE
We need a status page showing uptime of various GO services

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#232]
e.g. cachet

Can be used by go-help and software team for diagnosis of problems

**Comment by cmungall** [comment]
Done, thanks @kltm !

http://status.geneontology.org/

**Comment by kltm** [comment]
@stuartmiyasato got us the CNAME right fast!

At some point we'll want to replace this with something more usable and robust that we can tightly integrate with nagios and system logging (and I am indeed thinking cachet.io here), but this is a good place to start, and should help clarify what is going on with users.
