### ISSUE TITLE
Incorporate MaizeDB GAF into GO pipeline

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#233]
The completion of this ticket would incorporate the successful inclusion of the one-off MaizeDB GAF data into the standard GO pipeline.

Add steps as needed:
- [ ] data into svn
- [ ] jenkins job
- [ ] add to AmiGO configs (separate "hotfix" ticket)
- [ ] confirm

**Comment by cmungall** [comment]
@elserj will do this, as discussed with @jaiswalp 

@elserj should we file a ticket with a planteome tracker?

**Comment by cmungall** [comment]
@elserj you'll want to tidy up the file (should be a few lines of perl) and run mike's script to check it will be filtered into GO. We'll have a call to discuss this, and Planteome adopting the GO metadata schema

**Comment by elserj** [comment]
I think I missed whatever conversation this happened in.  Where is the gaf file?  Where is Mike's script?  Are we talking about this on the planteome call tomorrow?

**Comment by cmungall** [comment]
@jaiswalp can fill you in. I'll miss the call tomorrow.

**Comment by pgaudet** [comment]
Out of date ? @kltm

**Comment by kltm** [comment]
I'm going to assume out-of-date. Can be reopened.
