### ISSUE TITLE
New link for TAIR data

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#2331]
From @tberardini 

The new link is https://www.arabidopsis.org/download/file?path=GO_and_PO_Annotations/Gene_Ontology_Annotations/gene_association.tair.gz

**Comment by kltm** [comment]
Hm. I was sure we had a list of these in another ticket. Having trouble finding that...

**Comment by kltm** [comment]
The given link:
https://www.arabidopsis.org/download/file?path=GO_and_PO_Annotations/Gene_Ontology_Annotations/gene_association.tair.gz
is not a direct link to the file, but some kind of js/redirect? We need an actual direct link to the file.

**Comment by tberardini** [comment]
Will pass on to our tech team. I'm not quite sure how it all works.

**Comment by kltm** [comment]
@tberardini Cheers!

To hint this a little, the headers we get back have no forwarding info and the body is:
```html
<div id="app"></div><script src="/js/chunk-vendors.46e89868.js"></script><script src="/js/app.e3cca05f.js"></script>
```

**Comment by tberardini** [comment]
Hi all - try this:

**Comment by kltm** [comment]
@tberardini Unfortunately, we're still having trouble here; for example:
```
sjcarbon@moiraine:/tmp$:) http 'https://www.arabidopsis.org/api/download-files/download?filePath=GO_and_PO_Annotations/Gene_Ontology_Annotations/gene_association.tair.gz'
HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 118
Content-Type: text/html
Date: Wed, 19 Jun 2024 18:53:16 GMT
Server: awselb/2.0

<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>
```
From my web browser, this seems to work; not so much from the CLI. Perhaps the AWS load balancer is being aggressive towards certain agent strings?

**Comment by tberardini** [comment]
Passing on the comment. Stay tuned.

**Comment by tberardini** [comment]
One more try please. I'm hopeful the latest attempt to tweak the access rules has worked. I've tested with wget and at least that is not running into horrible errors. Fingers crossed.
```

Tanyas-MacBook-Pro-2:NCBI Col-CC Run tanyaberardini$ wget https://www.arabidopsis.org/api/download-files/download?filePath=GO_and_PO_Annotations/Gene_Ontology_Annotations/gene_association.tair.gz
--2024-06-28 09:00:30--  https://www.arabidopsis.org/api/download-files/download?filePath=GO_and_PO_Annotations/Gene_Ontology_Annotations/gene_association.tair.gz
Resolving www.arabidopsis.org... 76.223.67.159, 15.197.242.219
Connecting to www.arabidopsis.org|76.223.67.159|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [binary/octet-stream]
Saving to: ‘download?filePath=GO_and_PO_Annotations%2FGene_Ontology_Annotations%2Fgene_association.tair.gz’

download?filePath=GO_and_PO_Annotations%2FGene_Ontology_Annot     [   <=>                                                                                                                                         ]   8.13M  20.3MB/s    in 0.4s    

2024-06-28 09:00:32 (20.3 MB/s) - ‘download?filePath=GO_and_PO_Annotations%2FGene_Ontology_Annotations%2Fgene_association.tair.gz’ saved [8524024]
```

**Comment by kltm** [comment]
@tberardini It seems to test well this time; I've folded it in. If it goes well, this would be available in the `snapshot` next week.

**Comment by pgaudet** [comment]
This seems to be fixed - thanks @tberardini !

**Comment by tberardini** [comment]
Thanks for the confirmation. @pgaudet
