### ISSUE TITLE
EcoCyc now has a GPI file

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#2344]
https://www.ai.sri.com/~kr/go/latest/ecocyc.gpi

**Comment by pgaudet** [comment]
@kltm I think you need a compressed version?

**Comment by kltm** [comment]
@pgaudet Hm. While I'm not sure there is a requirement for it, I would note that _all_ resources do so and there could be a quiet requirement. As a matter of consistency and keeping sizes down, it would be nice if there was a gzipped version.

**Comment by kltm** [comment]
Actually, it seems that there is one: https://www.ai.sri.com/~kr/go/latest/ecocyc.gpi.gz

Is the intention here to use this for NEO?

**Comment by kltm** [comment]
This should now be added.
