### ISSUE TITLE
Only add GAF col 17 output (isoform) when necessary

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#2350]
In the GAF 2.2 output, now that we've switched over to the new code, column 17 is being filled when not necessary (which is a little confusing and against the spec).

@pgaudet Would you have any good examples of this for reference?

**Comment by pgaudet** [comment]
June 2024 GO release file has no col 17 information: 

> !gaf-version: 2.2
!
!generated-by: GOC
!
!date-generated: 2024-06-19T02:24
!
UniProtKB	A0A024RBG1	NUDT4B	enables	GO:0003723	GO_REF:0000043	IEA	UniProtKB-KW:KW-0694	F	Diphosphoinositol polyphosphate phosphohydrolase NUDT4B	NUDT4B	protein	taxon:9606	20240408	UniProt		
UniProtKB	A0A024RBG1	NUDT4B	enables	GO:0046872	GO_REF:0000043	IEA	UniProtKB-KW:KW-0479	F	Diphosphoinositol polyphosphate phosphohydrolase NUDT4B	NUDT4B	protein	taxon:9606	20240408	UniProt		
UniProtKB	A0A024RBG1	NUDT4B	located_in	GO:0005829	GO_REF:0000052	IDA		C	Diphosphoinositol polyphosphate phosphohydrolase NUDT4B	NUDT4B	protein	taxon:9606	20230619	HPA		
UniProtKB	A0A075B6H7	IGKV3-7	involved_in	GO:0002250	GO_REF:0000043	IEA	UniProtKB-KW:KW-1064	P	Probable non-functional immunoglobulin kappa variable 3-7	IGKV3-7	protein	taxon:9606	20240408	UniProt	


While the files on snapshots do: 
> !gaf-version: 2.2
!
!generated-by: GOC
!
!date-generated: 2024-07-15T21:54
!
!Header from source association file:
!=================================
!
!generated-by: GOC
!
!date-generated: 2024-07-14T14:58
!=================================
!
!Documentation about this header can be found here: https://github.com/geneontology/go-site/blob/master/docs/gaf_validation.md
!
UniProtKB	A0A024RBG1	NUDT4B	enables	GO:0003723	GO_REF:0000043	IEA	UniProtKB-KW:KW-0694	F	Diphosphoinositol polyphosphate phosphohydrolase NUDT4B	NUDT4B	protein	taxon:9606	20240610	UniProt		UniProtKB:A0A024RBG1
UniProtKB	A0A024RBG1	NUDT4B	enables	GO:0005515	PMID:33961781	IPI	UniProtKB:Q8NFP7	F	Diphosphoinositol polyphosphate phosphohydrolase NUDT4B	NUDT4B	protein	taxon:9606	20240608	IntAct		UniProtKB:A0A024RBG1

**Comment by pgaudet** [comment]
Oh ! I didn't see that yesterday. Looks like the GOA source file has data in Col 17 everywhere: 

> !gaf-version: 2.2
!
!date-generated: 2024-06-20 12:51
!generated-by: UniProt
!go-version: http://purl.obolibrary.org/obo/go/releases/2024-06-19/extensions/go-plus.owl
!
UniProtKB	A0A024RBG1	NUDT4B	enables	GO:0000298	GO_REF:0000033	IBA	PANTHER:PTN000290327|RGD:1310183|SGD:S000005689|UniProtKB:O95989	F	Diphosphoinositol polyphosphate phosphohydrolase NUDT4B	NUDT4B	protein	taxon:9606	20231108	GO_Central		UniProtKB:A0A024RBG1
UniProtKB	A0A024RBG1	NUDT4B	enables	GO:0003723	GO_REF:0000043	IEA	UniProtKB-KW:KW-0694	F	Diphosphoinositol polyphosphate phosphohydrolase NUDT4B	NUDT4B	protein	taxon:9606	20240610	UniProt		UniProtKB:A0A024RBG1
UniProtKB	A0A024RBG1	NUDT4B	enables	GO:0005515	PMID:33961781	IPI	UniProtKB:Q8NFP7	F	Diphosphoinositol polyphosphate phosphohydrolase NUDT4B	NUDT4B	protein	taxon:9606	20240608	IntAct		UniProtKB:A0A024RBG1
UniProtKB	A0A024RBG1	NUDT4B	enables	GO:0008486	GO_REF:0000033	IBA	FB:FBgn0036111|MGI:MGI:1930957|MGI:MGI:2147931|PANTHER:PTN000290327|SGD:S000005689|UniProtKB:O95989|UniProtKB:Q9NZJ9	F	Diphosphoinositol polyphosphate phosphohydrolase NUDT4B	NUDT4B	protein	taxon:9606	20230110	GO_Central		UniProtKB:A0A024RBG1



Maybe we need to leave it for now - I need to check with Alex next week (he's back from vacation on Monday)

Thanks, Pascale

**Comment by sierra-moxon** [comment]
@pgaudet - is this something (column 17 annotation from GOA) that I need to remove during processing?

**Comment by kltm** [comment]
@sierra-moxon I believe the idea here is to not fill the field when it is duplicative--there is no real use (and some confusion) with "UniProtKB A0A024RBG1" in cols 1 and 2 and then "UniProtKB:A0A024RBG1" in 17.

**Comment by pgaudet** [comment]
Discussing with Alex. This is not very critical, we can leave the same data as in col 1/2.
