### ISSUE TITLE
URL required for load no longer working

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#239]
AmiGO loads now seem to fail due to the following URL returning a 404:
 http://geneontology.org/ontology/extensions/go_inferences.owl
@cmungall Has something changed here?

**Comment by cmungall** [comment]
Fixed w r36507. Should be public in 30 mins (assuming sync working)

Odd this wasn't spotted before, the import has been there for months.

The catalog maps it to the editors folder, so I assume loading was previously using the catalog. Anyway, we don't want to be dependent on the catalog.
