### ISSUE TITLE
Github Ontology Tracker Update - incomplete

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-site#240]
From last week's editors call:

"Jenkins github new tickets reports
From Melanie: Birgit mentioned that "For the last few weeks my daily Jenkins updates have no new notifications and very occasionally updates." I usually check the tracker directly and delete those, can someone have a look?

[Paola] I confirm I haven't seen those reports at all lately - and there HAVE been new GH ontology tickets, as well as updates.

Chris will look into this. Tanya has sent him an example of the weekly emails she has been receiving. Adding the issue to the ticket on the go-site tracker."

(http://wiki.geneontology.org/index.php/Ontology_meeting_2016-10-20#Jenkins_github_new_tickets_reports)

Today, Melanie reported:

"I still think we are missing some notifications - Paola and I did some editing eysterday and commented/closed GH tickets. For example, I closed https://github.com/geneontology/go-ontology/issues/12752 and https://github.com/geneontology/go-ontology/issues/12184, and updated https://github.com/geneontology/go-ontology/issues/12723

They do show up as having been touched in the last 18-20h on GH: https://github.com/geneontology/go-ontology/issues?q=is%3Aissue+assignee%3Amcourtot+sort%3Aupdated-desc, so I would have expected them to show up in the notifications. The ones that show below are the 2 most recent updates (5 and 8h hours ago), see https://github.com/geneontology/go-ontology/issues?utf8=✓&q=is%3Aissue%20sort%3Aupdated-desc%20, but nothing shows up for others. Checking yesterday's email, same issue: it only contains a notification for 12761 erroneous links involving spindle pole body terms."

**Comment by mcourtot** [comment]
See also https://github.com/geneontology/go-site/issues/217: there reports are getting out, but are incomplete.

**Comment by cmungall** [comment]
Looks like a GitHub issue. This is the query we use:

https://api.github.com/search/issues?q=repo:geneontology/go-ontology+updated:=%3E2016-10-25&type=Issues&per_page=100

doesn't include #12723

**Comment by mcourtot** [comment]
Even on that query: it shows 7 tickets (12746, 12740, 12671, 12387, 12211, 11982, 9617) and only 12211 and 9617 are mentioned in the email.

**Comment by cmungall** [comment]
> Even on that query: it shows 8 tickets (12746, 12740, 12671, 12487, 12387, 12211, 11982, 9617) and only 12211 and 9617 are mentioned in the email.

right, because we're running it now, and not then

> 12723 shows up on the previous day (but not in the email): https://api.github.com/search/issues?q=repo:geneontology/go-ontology+updated:=%3E2016-10-24&type=Issues&per_page=100

Yep, and the closing of the ticket definitely happened on the 25th

**Comment by mcourtot** [comment]
Looking at code at https://github.com/geneontology/go-site/blob/master/scripts/jenkins/query-github-for-new-tickets.js#L157

    var url = 'https://api.github.com/search/issues?q=repo:'+username+'/'+projectname+'+'+type+range+'&type=Issues&per_page=100';

something seems odd with the repeated type (there is already a type=Issues later in the URL) which is also not separated from the range parameter? Created PR at https://github.com/geneontology/go-site/pull/242

**Comment by mcourtot** [comment]
I *think* the URL date syntax is off. Compare the updated parameter syntax:

`https://api.github.com/search/issues?q=repo:geneontology/go-ontology+updated:2016-10-27&type=Issues&per_page=100`
and 
`https://api.github.com/search/issues?q=repo:geneontology/go-ontology+updated:=>2016-10-27&type=Issues&per_page=100`


In the first case, as of right now, I retrieve 10 tickets. In the second case, I retrieve only 3. PR at https://github.com/geneontology/go-site/pull/244 - though it doesn't pas the checks and I don't have time to check why now :(

**Comment by mcourtot** [comment]
Interestingly I get different results using : (syntax for a specific day, 9 tickets, not sure why one disappeared...), :=> (current syntax in the file, 13 tickets) and :>= (recommended syntax as per https://help.github.com/articles/search-syntax/, 11 tickets)

Finally, using the official syntax https://api.github.com/search/issues?q=repo:geneontology/go-ontology+updated:>=2016-10-27&type=Issues&per_page=100 returns 11 tickets using the script, but 13 tickets using the API, so there seem to be another issue there.

**Comment by mcourtot** [comment]
Looks like it's bringing back correct results.

Compare
https://api.github.com/search/issues?q=repo:geneontology/go-ontology+created:2016-11-07&type=Issues&per_page=100 (new syntax, returns 2 new tickets created)
vs
https://api.github.com/search/issues?q=repo:geneontology/go-ontology+created:=%3E2016-11-07&type=Issues&per_page=100 (old syntax, returns 1 ticket created)

Tentatively closing this ticket.
