### ISSUE TITLE
XenBase curator wishes to start using Noctua

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-site#241]
I am working getting a XenBase curator to use the Noctua tool.
However, there are no Xenopus genes currently in the tool.
He has created a gpi file that could be used to populate, and I was
wondering if we could send it to one of you to see if it passes
muster.?

He'll also be at the GOC meeting, and we are hoping that if he uses
Noctua, perhaps we can get GOA to pick these up to get them into Amigo
eventually.
But, since XenBase does not have any annotation tools at the moment,
Noctua seemed to be something he could start with.
We haven't discussed protein2go with him at the moment, but that could
be another option we could discus with someone at the GOC meeting.

**Comment by hdrabkin** [comment]
I am adding the file he generated now, compressed with izip, since I can't upload a gz file.
[Xenbase.gpi.zip](https://github.com/geneontology/go-site/files/558717/Xenbase.gpi.zip)

**Comment by kltm** [comment]
@cmungall This is apparently blocked on getting the Xenopus GPI into neo.
Malcolm was going to try and get the dataset meta together and then ping you.

**Comment by cmungall** [comment]
```
$ unzip Xenbase.gpi.zip 
Archive:  Xenbase.gpi.zip
   skipping: Xenbase.gpi             need PK compat. v4.6 (can do v2.1)
```

 * we use gzip for all compression
 * can we distribute it from either the xenbase site; failing that we can just check into the submission dir for now

**Comment by hdrabkin** [comment]
Yes but I was not allowed to attach gz file to the github ticket.
Should I just upload this for him into gpad-gpi/submission??
--
Harold J Drabkin, Ph.D.
Senior Scientific Curator
Mouse Genome Informatics
The Jackson Laboratory
600 Main Street
Bar Harbor, ME 04609
voice:207-288-6650
fax: 207-288-6830
Email: harold.drabkin@jax.org

**Comment by cmungall** [comment]
yeh that'll be easiest first of all. xenbase.gpi.gz

**Comment by malcolmfisher103** [comment]
It will take a few days to get anything up on a public facing site from Xenbase, we seem to be having problems with our FTP site this weekend. One question I had was since we have gene product information for both X. laevis and X. tropicalis should I split them into distinct GPI files or can they be combined? The different species orthologs will still be distinguishable based on their taxon IDs and gene IDs.

**Comment by hdrabkin** [comment]
Malcolm; I'll now upload your latest gpi into the proper submission directory in svn to get things started.
--
Harold J Drabkin, Ph.D.
Senior Scientific Curator
Mouse Genome Informatics
The Jackson Laboratory
600 Main Street
Bar Harbor, ME 04609
voice:207-288-6650
fax: 207-288-6830
Email: harold.drabkin@jax.org

**Comment by selewis** [comment]
It shouldn't be necessary to split the two species into separate files.
Like you say there is all the information needed to differentiate these can
be pulled from within the annotation.

**Comment by hdrabkin** [comment]
I put it in the svn gpad-gpi/submission directory
@cmungall      IN order for Malcolm to do any Noctua annotations tomorrow: in the Noctua workshop,  I don’t know
how big a deal it would be to get his genes loaded from the gpi file
(can u use a script to just load his or do you have to do an entire
pipeline)
--
Harold

**Comment by cmungall** [comment]
I believe this is done @malcolmfisher103 reopen if not the case
