### ISSUE TITLE
Add email addresses for Jenkins releases notifications

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-site#246]
The latest release-go failed but no email was received. Console at http://build.berkeleybop.org/job/release-go/131/console shows:
```
Email was triggered for: Failure - Any
Sending email for trigger: Failure - Any
Failed to send e-mail to tberardi because no e-mail address is known, and no default e-mail domain is configured
Failed to send e-mail to termgenie because no e-mail address is known, and no default e-mail domain is configured
Failed to send e-mail to jenkins because no e-mail address is known, and no default e-mail domain is configured
An attempt to send an e-mail to empty list of recipients, ignored.
```

Should we send a default email to go-ontology?

**Comment by kltm** [comment]
What email address should be used?

**Comment by kltm** [comment]
Any admin/user should be able to add these.

**Comment by mcourtot** [comment]
I was thinking the editors list (go-ontology@mailman.stanford.edu) but happy to hear other suggestions.
If you can point me to the right place I'm happy to add. Thanks!

**Comment by kltm** [comment]
That email address already appears to be in the system.

**Comment by kltm** [comment]
No idea where it's getting those names from for that matter.

**Comment by mcourtot** [comment]
@cmungall, @kltm : it seems the release emails are not sent, see https://build.berkeleybop.org/job/release-go/138/console, which reads 'No emails were triggered.' How could one check the configuration for those scripts?

**Comment by kltm** [comment]
That seems to be correct. As it stands right now, the job is configured to only send email when there is a failure. In the case of the failure, a list called "Developers" is pinged (likely where the recipients in https://github.com/geneontology/go-site/issues/246#issue-187028191 came from).

It might be easier at this point to defined what the complete behaviour *should_ be, rather than try and fix the current one.

**Comment by mcourtot** [comment]
I don't know what the 'developers' list is, but as per the first comment above it doesn't find any email address to notify them.

An email to go-watchers used to be triggered in cases of success and failure, see https://mailman.stanford.edu/pipermail/go-watchers/2016-July/thread.html

Would it be possible to restore this behaviour? I was suggesting to use the go-ontology list instead of go-watchers as it seems go-watchers was used only for release notifications and could probably be retired.

**Comment by kltm** [comment]
Okay. So, after every run (success and failure), we should contact the go-ontology@mailman.stanford.edu list.
Let's see if we can convince the plugin to do that...

**Comment by kltm** [comment]
Okay, I believe I've done this, way down in the trigger advanced settings.
There should now be a daily email to the list, but let's see...

**Comment by mcourtot** [comment]
Looks like it worked, I received:
From: BBOP-Jenkins <jenkins@mill.lbl.gov>
Date: November 12, 2016 at 2:02:12 PM GMT
To: go-ontology@mailman.stanford.edu
Subject: [go-ontology] release-go - Build # 141 - Successful!

release-go - Build # 141 - Successful: Check console output at http://build.berkeleybop.org/job/release-go/141/ to view the results.

Thanks @kltm!
