### ISSUE TITLE
New goa_FOO.gaf files are empty

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#248]
http://geneontology.org/gene-associations/

goa_FOO.gaf.gz files are devoid of content. Issue in filtering.

Next step:

check software/utilities/filter-gene-association.pl

**Comment by kltm** [comment]
No longer appear to be empty.

**Comment by mcourtot** [comment]
Thanks - answered the users on helpdesk as well.
http://jira.geneontology.org/browse/GO-1388
http://jira.geneontology.org/browse/GO-1393
