### ISSUE TITLE
The Drupal site at geneontology.org has reverted to a previous state

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#249]
Something very strange is going on on the main GO site.

It appears that the site has reverted to a previous version. Which is super odd. I'm not really sure how to even go about figuring out what happened. Compare the current site to the one in the wayback machine:

![screenshot_2016-11-04_14-05-59](https://cloud.githubusercontent.com/assets/2687900/20022473/fbc31dec-a297-11e6-940b-71a1a5e54053.png)

https://web.archive.org/web/20161031140437/http://geneontology.org/

My only theory right now is that somehow an older version was used when the machines were restarted for a recent Dirty COW fix. Any thought @stuartmiyasato ?

I'm going to dig in a little and see what I can find...

**Comment by kltm** [comment]
There is apparently an edit gap between 11/03/2016 and 7/01/2015
@rachhuntley You have the only new edits. In case we have to roll back or forward, could you make sure that you save your updates locally?

**Comment by kltm** [comment]
@stuartmiyasato Possibly an old image of the site from July? Do you have a pre-Dirty COW revert image?

**Comment by stuartmiyasato** [comment]
Wow, even though I built a brand new snapshot/AMI on 11/1, it looks like I accidentally booted the new instance off an AMI from 2015.  Yikes.  Well, if there were any changes to the site since 11/1, we will now lose them.  I'm not going to worry about that now.  I'm going to boot the new instance immediately.  Hold on...

**Comment by kltm** [comment]
No worries! There are only two changes on 11/3 from @rachhuntley (sorry, your changes are going to be thrown under the bus, I'll try and grab them quickly.)

**Comment by kltm** [comment]
@rachhuntley I think I got them, but I didn't diff. If they're important and you want me to re-apply them, let me know,

**Comment by stuartmiyasato** [comment]
*sigh*  I was having problems booting the new AMI back on 11/1 and now I'm having the same problem.  Should I just revert back to the original old site for now and try to fix the Dirty COW problem from scratch?

**Comment by kltm** [comment]
A fun day all around ;)
We're having a meeting, so I'm thinking that people are going to be going to the documentation there, but I know that you're also oversubscribed.
Since we know what the issue is, and that there is a way forward (paging @thomaspd , who initially caught this), I think the most efficient way for you is probably fine.

**Comment by stuartmiyasato** [comment]
Okay, I've reverted www.geneontology.org to the instance that was running prior to 11/1.  I'll work on getting an instance up with the kernel patch.

**Comment by kltm** [comment]
Cheers!

**Comment by stuartmiyasato** [comment]
ec2-35-161-231-32.us-west-2.compute.amazonaws.com is the new instance that now has the patched kernel.  Can someone take a look at it and see if it looks okay as the new production server?  If so, I will "promote" it to production status (by switching the production Elastic IP address over to this instance).  (I hate making these sort of changes on a Friday afternoon, but I don't think we have a choice when fixing a security issue.)

**Comment by kltm** [comment]
@stuartmiyasato The site looks right, but...
I do not seem to be able to login to any of my accounts. I can't _prove_ username password combos are right, but I'm copy-pasting directly from my password file.
That said, I don't know what could cause that. Can you login?

**Comment by stuartmiyasato** [comment]
Are you talking about a shell login into the instance or logging into Drupal/the database?  The SSH keys appear to be the same, and I don't think the database permissions changed...  (Although that's a possibility since the MySQL accounts are tied to hosts, and since the server changed...)

**Comment by kltm** [comment]
Ah--the latter might be it. It's like the database is not allowing authentication.

**Comment by stuartmiyasato** [comment]
@kltm I will look into it, but I may need help testing -- I don't recall that I have an login for the website!

**Comment by stuartmiyasato** [comment]
@kltm I figured out the database root password, which helps.  :)  Looking at raw SQL, it looks like your account information is the same between the current www server and the new one.  Are you still able to log into the current www?

**Comment by kltm** [comment]
I can login fine on the "current" geneontology.org, but not on the proposed AWS one.

If you need you passwords, if you haven't changed them, I have a couple here in my pass file.

**Comment by kltm** [comment]
@stuartmiyasato Just checking in--is this still in the queue, or is it ready to retry?

**Comment by stuartmiyasato** [comment]
@kltm Sorry, it's still in the queue.  We had a massive meltdown over the weekend where we suffered disk corruption for all the VMs on one of our hosting servers.  (amigo2b ws included in that mess.)  I'm not sure if we're completely recovered from that, despite my putting in 23 hours of work over the weekend.  Lots of stuff on my plate is getting pushed back as a result.

**Comment by kltm** [comment]
No problem--be well.
I'll just try and keep people from updating until the fix is in.

**Comment by stuartmiyasato** [comment]
I have no idea what is going on with this instance.  I tried manipulating the database directly and I still can't get a login.  I'm going to start over from scratch -- take a snapshot of the currently running site and see if I can get a cloned instance to work properly.

**Comment by kltm** [comment]
Weird.
Don't stress too much about it. I turned off editing on the current public one, and let people who edited that their changes may be reverted and that they should save/note them down.

**Comment by rachhuntley** [comment]
Hi, Sorry it took me a while to get to this. You mentioned me pretty early in the thread, so I don't know if what's happened since has negated what you first said. Whatever edits I had I don't remember as they were so long ago, how do I see what they are?

**Comment by stuartmiyasato** [comment]
@kltm I might have had a breakthrough.  The blocked logins may have been a result of `$cookie_domain` being set in sites/default/settings.php, since we weren't accessing this test site through a geneontology.org URL.  I commented that out for now and it seems to work.  See if you can log into the test site at http://ec2-35-161-245-170.us-west-2.compute.amazonaws.com .

For the record, I ran "apt-get dist-upgrade" on this test instance which pulled down the latest packages for the 14.04 LTS release including the patched kernel.

**Comment by kltm** [comment]
@rachhuntley It was likely a small edit. If you haven't done anything recently, I don't think it's worth worrying too much about.

**Comment by kltm** [comment]
@stuartmiyasato Great! That's a quirk to file for later.
It looks fairly recent (and even has an edit from the sixth!) and I can login, so I don't see a problem with that going live.

**Comment by stuartmiyasato** [comment]
Okay, I just promoted the new instance to production.  I changed the value of `$cookie_domain` back to '.geneontology.org' and it still seems to work.  As before, I am keeping the old instance around in case we need to revert for some strange reason.

Yes, the image was created last night (11/9), so it's current.  I did shut down the instance to get a clean snapshot.  Downtime was only about 10 minutes, and it didn't seem to be in use when I shut the instance down, so hopefully it didn't impact anyone.

Anyway, as before, please let me know if you see any issues with the server.  I didn't want to make this change on a Friday, so I just went ahead with the change!

**Comment by kltm** [comment]
Looks great--thank you!
