### ISSUE TITLE
Proposed improvements to help page

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#25]
There is no obvious "help" entry in the menu, but you can select "contact us"
http://geneontology.org/form/contact-go

For access to go-help.

I think we should have a page prominently labeled "help" and it should go to something like this:
https://help.openshift.com/hc/en-us

In particular
- link to developer community (biostars)
- contact us
- link to FAQ (I like the split into FAQ and Knowledgebase)
- twitter?
- mailing lists

I like the clear layout

I don't think we can offer a silver plan however...

**Comment by paolaroncaglia** [comment]
Yes please! +1 for renaming "Contact us" as "Help" and adding a drop-down list of options beneath.

**Comment by suzialeksander** [comment]
I think this is done: http://help.geneontology.org/ 

(now links to GH not Biostars)
