### ISSUE TITLE
AmiGO down?

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-site#261]
As per http://jira.geneontology.org/browse/GO-1398

http://amigo.geneontology.org doesn't load for me as of 9.00 GMT.

**Comment by mcourtot** [comment]
Thanks for the note @kltm.  The Jira helpdesk ticket was open almost 20h ago, so not sure whether this is a separate issue or not (the Jira was not very clear, just says 'I can't get the site to provide any annotations. Is it actually working now?')
Hopefully @stuartmiyasato can shed some light on this :)

**Comment by stuartmiyasato** [comment]
@mcourtot I have restarted the production servers and AmiGO looks better now.  It was never actually down, but just *very* slow responding which made browsers time out.  Thanks for dealing with the user reports.  :)

**Comment by mcourtot** [comment]
Fantastic, thanks @stuartmiyasato!
