### ISSUE TITLE
Pfam db-xrefs.yaml entry needs to be updated

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#262]
From @ValWood:
```
The Pfam links still go to https://pfam.sanger.ac.uk/family
These should now go to http://xfam.org/ or something under here...
```

@ValWood
If you could get us the correct URL or example page, we could probably update that pretty quickly.

**Comment by kltm** [comment]
For upstream geneontology/amigo#404.

**Comment by ValWood** [comment]
appears to be
http://pfam.xfam.org/family/
i.e/
http://pfam.xfam.org/family/PF00069
