### ISSUE TITLE
Swiss-Prot should no longer exist in GO annotations

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#263]
Originally from @ValWood:
```
So, Swiss-Prot should not be allowed in the "with" field.
These should all be changed to UniProtKB? Then these links will work.
Seesm to be annotations coming in from TIGR and JCVI
```

The question here then is, what should be done about these annotations? Do we need sources to update these? Any ideas @cmungall ?

**Comment by kltm** [comment]
For downstream geneontology/amigo#404.

**Comment by mcourtot** [comment]
In Geneva we discussed removing those stale datasets.
Se
https://docs.google.com/document/d/12CDf4s8YsylPMNHM3UuPis9NyVQ9WFpBpNYTFYAH7kc/edit#heading=h.s4bsdd7osahv
and https://github.com/geneontology/go-annotation/issues/1387

**Comment by pgaudet** [comment]
Done.
