### ISSUE TITLE
How to handle goa_uniprot annotation files in goa.yaml?

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-site#264]
I've updated the source location for all of the species-specific annotation sets in goa.yaml, but there are, as yet, no entries for the full goa_uniprot sets (goa_uniprot_all and goa_uniprot_gcrp).

These sets are massively multi-species, so it's not practical to list the species codes and taxa that they cover. Can the species_code and taxa attributes be omitted, or are there wildcard values that can be used? Or are these datasets going to be treated as a special case, as they are at present?

**Comment by cmungall** [comment]
I agree it doesn't make sense to do this.

We may want to have the option of allowing a superclass, e.g. all-bacterial. But in your case it is all-all. So I think here we just make it optional. We could also have an explicit flag on top of this, e.g is_multispecies: true

sound ok?

**Comment by tonysawfordebi** [comment]
Thanks, @cmungall - that sounds good to me.

**Comment by pgaudet** [comment]
Out of date
