### ISSUE TITLE
Ontology builds currently failing in pipeline

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#280]
Originall from @mcourtot 
```
Seems to be an SVN issue. Same error on previous build, so may not be temporary thus ticket.

    SVN_SSH='ssh -l jenkins -i /home/jenkins-slave/.ssh/id_rsa.go-commit -o "StrictHostKeyChecking no"'
    svn commit '-mupdate go-plus.owl' go-plus.owl go-plus.obo
    Sending go-plus.obo
    Sending go-plus.owl
    Transmitting file data .svn: E000013: Commit failed (details follow):
    svn: E000013: Unable to create pristine install stream
    svn: E000013: Can't create temporary file from template '/home/jenkins-slave/workspace/release-go/svn/.svn/tmp/svn-XXXXXX': Permission denied
    Build step 'Execute shell' marked build as failure
```

**Comment by kltm** [comment]
@mcourtot Could you give me a link to the failing job?

**Comment by ukemi** [comment]
http://build.berkeleybop.org/job/build-go/
and 
http://build.berkeleybop.org/job/release-go/

**Comment by mcourtot** [comment]
Thanks @ukemi!

**Comment by kltm** [comment]
@cmungall It looks like grinder--the machine that ran into the full disk last week. My working guess is that operations attempted while the disk was nearly full left the .svn directory in an unusable state. I'm going to purge the workspaces and let them re-run.

**Comment by cmungall** [comment]
seems fine but remember we were also going to do a svn cleanup for each svn job

**Comment by kltm** [comment]
Disk overflow leading to corruption (a "unique" event) will be generally separate from the cleanup issues.

**Comment by kltm** [comment]
build-go seems to be cleared, so I think it was full corruption.
Please reopen if release similarly fails tonight.

**Comment by cmungall** [comment]
got it, thanks

**Comment by mcourtot** [comment]
Seems the release-go (164) is still failing. Or is it a timing issue and next one will go through?
