### ISSUE TITLE
Add Mouse slim to the documentation

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-site#292]
We need to add the mouse slim to the list here:

http://www.geneontology.org/page/go-slim-and-subset-guide

once it shows up in the subsets here:

http://www.geneontology.org/ontology/subsets/

The description should read 

"Mouse slim developed by Mary Dolan and the Mouse Genome Informatics group"

with the appropriate link to MGI.

**Comment by ukemi** [comment]
This file is still not showing up on the web.
@mdolanme

**Comment by pgaudet** [comment]
Done http://snapshot.geneontology.org/ontology/subsets/
