### ISSUE TITLE
stats page omissions/feedback

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#293]
http://amigo.geneontology.org/amigo/base_statistics

 - [ ]  first graph EXP by species has no cerevisiae?
 - [ ]  second graph  (EXP by assigner) is difficult to use because dwarfed  by automated GO central assignments from F-P links
- [ ]  Annotations by aspect/species by evidence is missing cerevisiae
- [ ] I think the numbers in EXP annotations by publication are incorrect. For pombe  you have 21,000 but we have curated <3000 publications, the number for SGD (91,000) exceeds the number of GO annotations. Flybase has 2 entries (FlyBase/FLYBASE)

**Comment by kltm** [comment]
I'm going to say this is probably a rider on https://github.com/geneontology/amigo/issues/364
