### ISSUE TITLE
GO Tools Registry needs to either go away or be explained further

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/go-site#30]
Why do we still have this page? 
http://geneontology.org/page/go-tools-registry

I think we should either do away with the presence of the GO Tools Registry (since it is no longer supported), or add more text to the explanation of why we no longer support a Tool Registry. The current page is quite silly.

**Comment by kltm** [comment]
I added a little explanation and removed the item from the main nav menu. This will allow old links to work, but prevent people from stumbling onto it.
