### ISSUE TITLE
Panther  enrichment queries and issues

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#314]
Hello,
I'm logging this issue here because I wanted to be able to upload screenshots easily, and I don't know where the Panther tracker is (I asked on the helpdesk recently but I did not get a reply from Panther yet...)

I was trying to use panther for enrichment (over-representation). It turns out the list I was using had no enrichment but I spotted a couple of possible problems.

1. 
My results are  summarized as "unclassified 2408"
What doe the 2408 refer to ? I can't reconcile this number with anything related to pombe process, I could not find it explained and the link does not retrieve anything

![unclassified 2408](https://cloud.githubusercontent.com/assets/7359272/23094923/7db28e14-f5f9-11e6-9219-405e08511ece.jpg)

2.
When I viewed the full results I saw:

![vitamin transport](https://cloud.githubusercontent.com/assets/7359272/23094932/9b54574a-f5f9-11e6-9e7d-21c18bf6235b.jpg)

Check out the bottom list "vitamin transport 6"

PomBAse only has 5 genes annotated to "vitamin transport"
	SPCC576.17c
	SPCC965.13
	bsu1
	thi9
        vht1

This list of 6 is
![list of 6](https://cloud.githubusercontent.com/assets/7359272/23094954/f12bef7a-f5f9-11e6-8f11-6bc3ec062e91.jpg)

SPCC285.04
SPBC725.10
SPCC1223.09
SPBC2G2.01c (is pantathoate transproter)
do not appear to have a role in vitamin transport (or even transport in some cases)

SPAC1B3.15c has  a NOT annotation to vitamin transport

vht1 appears to be the only gene product offically annotated to "vitamin transport" in the Panther list.

**Comment by ValWood** [comment]
I should add that I don't think that the 2408 has anything to do with "unannotated" because pombe has 5396 annotated objects (for a long time), not  the 5140 reported? 
Of these, 4499 have a none root none BP annotation.

**Comment by ValWood** [comment]
@thomaspd

**Comment by paolaroncaglia** [comment]
@ValWood 
The tracker you're looking for is https://github.com/geneontology/panther-enrichment

**Comment by ValWood** [comment]
Hi,

I can't supply the list I used as it is a collaborators list. However any list would do.
I just tried with this list of ALL genes annotated to vitamin metabolism
systematic_id
SPAC5H10.09c
SPBC409.13
SPBC725.03
SPAC23H4.10c
SPAP27G11.09c
SPCC18B5.05c
SPAC17A5.13
SPAC1002.19
SPCC4B3.18
SPBP4H10.05c
SPCC1223.02
SPBC428.03c
SPBC839.16
SPBC1734.03
SPCC1235.02
SPBC1711.04
SPAC222.08c
SPCC4G3.16
SPBP8B7.18c
SPBP8B7.29
SPBC21C3.10c
SPCC1281.04
SPCC18.16c
SPAC1952.08c
SPAC5H10.08c
SPAC6F12.05c
SPBP8B7.17c
SPBC23E6.06c
SPAC1486.10
SPAC9E9.11
SPAC1093.02
SPBC19G7.02
SPBC12C2.07c
SPAC29B12.04
SPBC2G2.08
SPBC26H8.01
SPBPB2B2.09c
SPCC1450.13c
SPAC8F11.09c
SPAC144.04c


If I use the enrichment on the front page of the GO site, I get the correct results (although they are not ordered by significance, and so are difficult to interpret, but you can see clearly that 
39/40 genes are annotated to vitamin metabolism (the off by 1 error could be a version issue, so we can ignore that)


![go site](https://cloud.githubusercontent.com/assets/7359272/23254596/7c0e1a50-f9b0-11e6-94de-769a7fc96e0a.jpg)



However, if I go through to the panther site to take advantage of other options like background set, I get totally different results:

![panther_site](https://cloud.githubusercontent.com/assets/7359272/23254648/a6717616-f9b0-11e6-8ae3-124bd7903901.jpg)


Only 25 gene products in this list are annotated to vitamin metabolism. It is as if the Panther site is running enrichment from a totally different annotation set?

**Comment by ValWood** [comment]
further to this,  I just found another not I made while trying to use, might be helpful:

Panther class information is very out of fate.
This link provides  "transcription, DNA-dependent"
http://www.pantherdb.org/panther/category.do?categoryAcc=GO:0006351

but this term was renamed to  	"transcription, DNA-templated"  on 2013-11-24
?

**Comment by thomaspd** [comment]
Thanks Val, I see the problem.  You're using the PANTHER GO-slim, rather than the full GO results, and yes, most of those annotations come from PAINT only (with some legacy annotations from older versions of PANTHER and our GO-slim), which will be removed/corrected with our release of version 13 late this year, so annotation and GO-slim ontology issues will be fixed then).  Note that you can change the reference list at any time, even from the enrichment results page.  The information table at the top has a "change" button next to the reference set item.  You can change the annotation set as well, by selecting from the drop-down menu next to that item.

**Comment by ValWood** [comment]
Paul,

This is all very misleading.
I go here http://www.geneontology.org/
I cannot perform an enrichment from here because a background set cannot be provided. It does not make sense to perform an enrichment without using the appropriate background for  your experiment.
So I need to go to Panther.

If I perform an enrichment or slim at Panther, I should be using the full GO annotations.
I don't understand what you mean by "Panther GO slim". A GO slim is a set of terms, not a set of annotations. Do you mean that I am using the Panther inferred annotations? 

The Panther GO slim should give exactly the same results as any other GO slim based on GO annotation, and represent the totals that are currently in the GO database. Surely?
Especially since the Panther site is the one  which is recommended to use for GO enrichment.

I wanted to repeat the procedure,  but the panther site appears to be unavailable right now?

This all seems a little crazy to me. If anyone does  an enrichment  they  should be presented with  the best available dataset, which is the annotated dataset from the GO database. This should always be the default?

**Comment by ValWood** [comment]
I really don't get this at all. Why on earth would you want to do an enrichment on a slim dataset ;(

**Comment by cmungall** [comment]
This issue was moved to geneontology/panther-enrichment#6
