### ISSUE TITLE
Is AmiGO down?

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-site#322]
Hi,

I'm currently having trouble getting to term pages in AmiGO.
The connection times out or I get a 404 error message.

Thx.
--Kimberly

**Comment by stuartmiyasato** [comment]
Hi Kimberly,

One of the production servers was getting hammered.  I'm restarting all the server processes and it looks better now.  Sorry for the inconvenience...

(Thanks for the note, @cmungall !)

-- Stuart

**Comment by vanaukenk** [comment]
Thanks @cmungall and @stuartmiyasato !
