### ISSUE TITLE
Include goa_uniprot_all (full and no IEA) versions

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#323]
the new pipeline is working except for the inclusion of the goa_uniprot_all file

These are in the legacy pipeline as can be seen here
http://www.geneontology.org/gene-associations/

Note that this is quite a large file, so we want to treat it differently. We want to fully incorporate goa_uniprot_all_noiea into the database (but we don't want to run the full owltools checks on this). For the full file, we want to do just a direct passthrough to S3

The source is here:

ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/
ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/goa_uniprot_all.gaf.gz

@tonysawfordebi - for the noiea version have we always produced this ourselves in GO Central (by basically grepping out IEAs)?

**Comment by dougli1sqrd** [comment]
I have this: https://github.com/geneontology/go-site/pull/326 that maybe does this. The change is in the Makefile generator python script.

**Comment by dougli1sqrd** [comment]
I'm closing this as the above PR was merged.

**Comment by cmungall** [comment]
Reopening until the new awk-based pipeline is fully validated

**Comment by cmungall** [comment]
Still to do

 - exclude human, dog and other species already covered in GOA files - see https://github.com/geneontology/go-site/pull/495
 - make goa uniprot all noiea 'first class' (can be punted post 1.0 of pipeline)

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/pull/501
https://github.com/geneontology/go-site/pull/495
https://github.com/geneontology/go-site/pull/502
