### ISSUE TITLE
Link to dbxref set needs to be updated

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/go-site#336]
In the GO Database Schema page in the GO site http://geneontology.org/page/lead-database-schema#go-general.table.dbxref
the link to the dbxref set is still http://www.geneontology.org/cgi-bin/xrefs.cgi which is no longer correct. 

Incidentally, where do xrefs live now?

**Comment by monicacecilia** [comment]
Fixed.

**Comment by kltm** [comment]
Ummm...depends?
http://amigo.geneontology.org/xrefs
https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml
https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.md

**Comment by monicacecilia** [comment]
In the table "Table: go_general.dbxref", the URL was  http://www.geneontology.org/cgi-bin/xrefs.cgi

I found the data here: https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

I guess either of the other two would be informative as well. I would rather use http://amigo.geneontology.org/xrefs

@kltm do you have an opinion? I'll update the page with your suggestion (if different from the yaml file on GH).

**Comment by kltm** [comment]
Well, the xrefs.cgi is toast, so that's a non-starter.

I suspect that Chris could theoretically go for a GitHub-as-CMS version that we then parse, but no such thing currently exists for that file, so we have the YAML and AmiGO.

On the upside for documentation, `go_general.dbxref` will soon be gone.

**Comment by monicacecilia** [comment]
teehee... well, it *is* a starter. it's what started this ticket. :bowtie:

**Comment by cmungall** [comment]
> I suspect that Chris could theoretically go for a GitHub-as-CMS version that we then parse, but no such thing currently exists for that file, so we have the YAML and AmiGO

No, not for these. They are not like rules which are documentation-centric.

Ultimately we want all metadata to be shown in amigo as then you can see things in context. E.g. how many annotations for an xref, how many annotations for a rule, how many annotations/ontology terms for a group/person etc
