### ISSUE TITLE
Add search box to all documentation pages on main site

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#34]
This is a common request from users.

However, the Bootstrap theme we're using, last time I checked, was very primitive in the regard and unable to have a sane looking search box in any of the header areas, meaning that we'd have to add the second column to all pages to support it.

The solution I've been waiting for is either an improved base BS3 theme that we can upgrade to or somebody writing a custom theme for us that takes care of this.

**Comment by pgaudet** [comment]
Out of date
