### ISSUE TITLE
Ensure GAF filtering is working as intended in new pipeline

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#342]
For the new pipeline, it was more convenient to replace the old filter-gene-associations script.

There is a placeholder perl script, but the filtering should be done using https://github.com/biolink/ontobio/blob/master/ontobio/io/gafparser.py

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/pull/352

**Comment by cmungall** [comment]
Still to do: noiea
