### ISSUE TITLE
Add external accession for GO_REF:0000104 

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/go-site#354]
Could you please add : 
ZFIN:ZDB-PUB-170525-1 as an external accession for GO_REF:0000104.

Alternatively: I can also add it myself if someone tells me where this information should be added.

Thank you
Sabrina

**Comment by kltm** [comment]
@sabrinatoro The location, and instructions, for the GO_REFs can be found here:
https://github.com/geneontology/go-site/tree/master/metadata/gorefs

**Comment by sabrinatoro** [comment]
Thank you @kltm !

**Comment by kltm** [comment]
Looked good to me.
