### ISSUE TITLE
GAF-version in gene_association.zfin.gz available in GO is incorrect

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/go-site#355]
The version of the ZFIN GAF file is 2.1 as shown in our GAF file headers:
!gaf_version: 2.1
!Version: 1.473
!Date: 2017/05/07
!From: ZFIN (zfin.org) 

It looks like the ZFIN GAF available at GO, shows version 2.0 instead of 2.1. See header below: 
!gaf-version: 2.0
!Project_name: The Zebrafish Information Network
!URL: http://www.zfin.org/
!Contact Email: zfinadmin@zfin.org
!Funding: NIH (P41 HG002659)
!gaf_version: 2.1
!Version: 1.473
!Date: 2017/05/07

The version # in the gene_association.zfin.gz file available at GO should probably be updated. 
Thank you.

**Comment by kltm** [comment]
@cmungall Any ideas about this? Is the rewriter missing that?

**Comment by kltm** [comment]
Closing in favor of #535
