### ISSUE TITLE
Ontobio chokes on a malformed "class expression" in the gaf release snapshot jenkins job

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#376]
https://build.berkeleybop.org/job/go-gaf-release-snapshot/87/console

This currently is failing on goa_uniprot_gcrp gaf parsing.

**Comment by pgaudet** [comment]
@dougli1sqrd Is this still relevant ?

**Comment by dougli1sqrd** [comment]
Extremely unlikely. For one thing we don't even process that dataset. The code that was merged in the PR referenced above has been running for 3 years now haha. We can probably call this done.
