### ISSUE TITLE
external2go and gp2protein files

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-site#400]
We currently submit a number of external2go and gp2protein files via SVN. Is the intention that these files should be included in our goa.yaml file in the datasets directory, or do those yaml files just drive the collection of GPAD/GPI/GAF files?

**Comment by cmungall** [comment]
external2go - I'd like to move the source of these into the go-ontology repo. They would then be built as part of the main ontology release (published to S3, rather than using the VCS as the publishing mechanism as we have in the past).

However, this could cause issues for the ones you auto-update. We'll be protecting master, so you'd have to auto-commit these to a branch and make a PR... all possible with gh api but more work. So I think a better solution is either

 - a separate repo for external2go
 - OR you just publish on your ftp site or wherever and we slurp. I think I favor this

gp2protein - we should fold this in to the same mechanism as the GAFs, include an entry in datasets/foo.yaml

**Comment by tonysawfordebi** [comment]
Concur on both points :)

The external2go files are already published at ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/external2go/ as part of the weekly update cycle, so the only change I would need to make is to turn off the cron job that does the svn commit.

I'll update the goa.yaml file to include the gp2protein files that we create - is an extension to the syntax required in order to support this?

**Comment by cmungall** [comment]
On 21 Jul 2017, at 7:06, Tony Sawford wrote:

> I'll update the goa.yaml file to include the gp2protein files that we 
> create - is an extension to the syntax required in order to support 
> this?

I don't think so - give it a go on a pull request, worst that can happen 
is travis will complain

**Comment by tonysawfordebi** [comment]
OK - I'll give it a whirl some time next week.

**Comment by tonysawfordebi** [comment]
I've added entries to goa.yaml for the various external2go and gp2protein files that we submit, and the pull request and subsequent merge went through without errors.

I've made a couple of assumptions - mainly about the values of the file type attribute - so those may need to be changed at some point.

When are you planning to turn out the lights on the current SVN submission mechanism?

**Comment by kltm** [comment]
@tonysawfordebi I think we are hopefully that we can do that this week--almost there.

**Comment by cmungall** [comment]
Heads up @kltm and @dougli1sqrd

**Comment by kltm** [comment]
@cmungall Could you clarify that a bit?

**Comment by cmungall** [comment]
Was just letting you know but you were already on it (my comment came in via email hence out of sync)

**Comment by kltm** [comment]
Note https://github.com/geneontology/go-site/issues/688 and https://github.com/geneontology/go-site/issues/996

**Comment by kltm** [comment]
Noting that the metadata still includes gp2protein information and final downstream `url` locations that do not work (e.g., see goa.yaml and check any gp2protein entry). This is a little misleading. We should either get rid of this metadata or make a product.

Tagging @cmungall @pgaudet

**Comment by pgaudet** [comment]
Hi @kltm 
If we have decided to get rid of gp2protein files, should we send out an announcement ? 
We should also 

- [ ] remove it from yaml files 
- [ ] remove references to it from documentation (for eg: http://wiki.geneontology.org/index.php/Gp2protein). 

Right ? 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet As they may end up getting used elsewhere, I'm not sure about removing them as metadata. Perhaps @cmungall could comment when he's back.

As far as an announcement goes, the deed was done over a year ago, so I'm not sure is an announcement at this point is particularly clarifying.

**Comment by pgaudet** [comment]
Just spoke to @vanaukenk . We'll announce it on the next annotation call. 
I am leaning towards removing those from the yaml files. If anyone is using it, we are not aware of it. 

Thanks, Pascale
