### ISSUE TITLE
AmiGO2 is not able to retrieve terms

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-site#402]
Browsing the ontology with AmiGO2 and clicking on a term in the search results is resulting in a 404 error.

'AmiGO 2 was unable to find the term GO:0008101 through normal channels--it may not be in our data set or it may go under a different identifier. Please try your term (GO:0008101) through the landing page general search interface using synonyms or alternate identifiers.

If you feel that this message was received in error, please contact the GO Helpdesk.'

I've tried several terms unsuccessfully from both the ontology search and from the general landing page.

**Comment by ukemi** [comment]
Seems to be fixed this morning.

**Comment by kltm** [comment]
@ukemi Sorry about that; likely a temporary outage. We're still in the process of migrating, we'll hopefully have the systems migrated soon.
