### ISSUE TITLE
Fix submission source for gramene

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#409]
gramene:
https://github.com/geneontology/go-site/blob/master/metadata/datasets/gramene.yaml

We currently get this from go svn

 1. The submission file seems to lack key genes like sub1, which is present on planteome: http://browser.planteome.org/amigo/gene_product/GR_gene:GR:0060943
 2. we need to move off svn anyway - get this from planteome or gramene directly

cc @jaiswalp

**Comment by pgaudet** [comment]
Now managed by P2GO
