### ISSUE TITLE
Create stable taxon server

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#41]
Currently we're using toaster:9999. Needs to be manually restarted every time toaster goes down. Instructions here:

http://wiki.geneontology.org/index.php/Ontology_Web_Services#Taxon_Checks

Note that the 'taxon server' is just an owltools server that is initiated with a particular set of ontologies
1. <strike>Make a supervisor job on toaster that keeps the server up and running</strike>
2. Create a stable URL that allows us to swap the physical machine. Suggested:
   - <strike>owlservices.berkeleybop.org</strike>
   - owlservices.geneontology.org (later)
3. Eject from toaster to the cloud, use ansible for setup?
4. Rewrite service layer to use dropwizard (as per owlsim-v3) or jersey (as per minerva), make into a more extensible set of owl services. @hdietze

**Comment by kltm** [comment]
I think the time for this, at least in this form, has passed.
