### ISSUE TITLE
Error message when trying to access InterPro2GO mappings file

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-site#411]
Hi,

I'm getting an error message after clicking on the txt link for the InterPro2GO mapping file from this page:

http://geneontology.org/page/download-mappings#map

When I get here:

http://geneontology.org/external2go/interpro2go

I see:

ERROR:
ORA-00257: archiver error. Connect internal only, until freed.

Links to other mapping files seem to be working.

Thanks.

**Comment by kltm** [comment]
That seems to be some kind of Oracle DB error...
https://community.oracle.com/thread/2301711
Where do we even use ODB? Is this just a redirect?

**Comment by kltm** [comment]
Apache proxying something then maybe?
```http
HTTP/1.1 200 OK
Accept-Ranges: bytes
Connection: Keep-Alive
Content-Encoding: gzip
Content-Length: 92
Content-Type: text/plain; charset=UTF-8
Date: Tue, 18 Jul 2017 21:44:31 GMT
ETag: "3b1453-48-55476dc3927d3-gzip"
Keep-Alive: timeout=5, max=100
Last-Modified: Sun, 16 Jul 2017 22:32:41 GMT
Server: Apache
Vary: Accept-Encoding
```

**Comment by kltm** [comment]
As well, the following also fail:
`pfam2go pirsf2go prints2go prodom2go prosite2go smart2go`
I don't know what the mechanism is for generating these is. @cmungall ?

**Comment by tonysawfordebi** [comment]
@vanaukenk @kltm It looks like the problem is at our end - the mapping files were not generated correctly. I'll re-make & re-submit them,

**Comment by tonysawfordebi** [comment]
Updated files now submitted to GOC SVN.

**Comment by kltm** [comment]
Thank @tonysawfordebi , everything I've tried works for me now!

**Comment by cmungall** [comment]
Tony - we'd like to switch the source to github - will this cause any 
issues for you? Do you auto-update these or do a manual commit?

**Comment by vanaukenk** [comment]
Thanks @tonysawfordebi and @kltm !

**Comment by tonysawfordebi** [comment]
@cmungall We have one weekly cron job that creates new versions of the files, and a second one that submits them to the GOC SVN repository.

I raised an issue - [https://github.com/geneontology/go-site/issues/400] - a couple of weeks ago to ask about how external2go (and other) files were going to be treated in the new metadata-driven world.
