### ISSUE TITLE
Fix syncing from gh to svn

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#414]
https://build.berkeleybop.org/job/sync-go-editors-from-github

This job originally took the src file from gh and performed the full release pipeline. Now the release is controlled entirely from gh and new jenkins. This job should be modified purely to mirror

**Comment by cmungall** [comment]
```
$ svn commit -m 'retiring catalog' catalog-v001.xml 
Sending        catalog-v001.xml
Transmitting file data .
Committed revision 43380.
```

the catalog is now empty so things will be fetched from their purls

**Comment by kltm** [comment]
Closing as SVN no longer syncs
