### ISSUE TITLE
Fix UM-BBD

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#42]
Need to fix UM-BBD. See:

> As a matter of facts, on July 1, 2014, the domain has permanently moved to eawag-bbd.ethz.ch.
> All rights of UM-BBD/PPS were transferred to Eawag then, see http://eawag-bbd.ethz.ch/whatsnew.html.
> Therefore we would actually ask you to use the .ethz.ch URLs.

**Comment by kltm** [comment]
There's a fair number of BBD entries. Does this mean all of them have to be changed, or just the explanation URLs? It's always a bit of a hit or miss editing other peoples' resources...

**Comment by suzialeksander** [comment]
I'm encountering this on download-mappings.md, part of #789.

**Comment by kltm** [comment]
If this is needed for release (as in it is currently working and we would be breaking something with the release), go ahead and add it to the super. If not, we can have it as a website goal for this (or some other) release.

**Comment by pgaudet** [comment]
http://geneontology.org/docs/download-mappings/

**Comment by suzialeksander** [comment]
OK, the yaml file is ok, as well as the hard links to the EAWAG-BBD site.  The txt links in the download table (http://geneontology.org/external2go/um-bbd_enzymeid2go etc) don't use the domain, so those work too.  Closing.
