### ISSUE TITLE
Is the metadata-driven submission process in place yet...

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-site#423]
... or should I continue to submit our files via SVN?

We have another GOA release scheduled for next week, so it would be good to know whether I need to continue submitting the many & varied GAF / GPAD / GPI, etc files using SVN, or whether they will be picked up automatically by a Jenkins job.

**Comment by kltm** [comment]
@tonysawfordebi Well, yes and yes.

While we have the new metadata-driven pipeline in place and operating in parallel, there are some practical consequences of switching over to the new pipeline that we have not fully ironed out (e.g. history, numerous exotic hard-coded URLs, etc.) and we are currently looking at a couple of transition options.
