### ISSUE TITLE
GO-CAM to gaf/gpad should collate by MOD and only include production models; also need SynGO solution

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#431]
https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/

has individual files per model, we should collate these by the MOD

@balhoff has a smarter way to do this but as a stopgap we can have a quick script that collates by col1.

**Comment by cmungall** [comment]
This is high priority for @tonysawfordebi

**Comment by vanaukenk** [comment]
@cmungall 
Do we want to collate by col1 or by taxon id?

**Comment by cmungall** [comment]
I assume col1.

**Comment by vanaukenk** [comment]
As a first pass, we will use col 1, since taxon is not in gpad.

**Comment by cmungall** [comment]
https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/

**Comment by cmungall** [comment]
TODO: production models only

**Comment by cmungall** [comment]
Will require a change to https://github.com/geneontology/minerva/blob/master/minerva-converter/src/main/resources/org/geneontology/minerva/legacy/sparql/gpad-with-evidence.rq

I can do this but if you know how to do it quickly @dougli1sqrd or @balhoff

**Comment by ukemi** [comment]
Once we have this filtered for production models only, I will request a test-load into MGI.

**Comment by ukemi** [comment]
There is something strange in the output files.  In https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/mgi.gpad/*view*/
This annotation exists:

MGI | MGI:1925503 | enables | GO:0046577 | r1 | ECO:0006017 | w1 |   | 20170926 | GO_Noctua |   | noctua-model-id=gomodel:59c8885900000227\|contributor=http://orcid.org/0000-0001-5501-853X
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
MGI | MGI:1925503 | involved_in | GO:0044108 | r2 | ECO:0000501 | w2 |   | 20180126 | GO_Noctua |   | contributor=http://orcid.org/0000-0001-5501-853X\|noctua-model-id=gomodel:5a5fc23a00000069

They are not in the model.

**Comment by balhoff** [comment]
@ukemi, looking at the first line, I don't see that annotation in the MGI file or in the [model GPAD](https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/gpad/59c8885900000227.gpad/*view*/). Am I missing the problem?

**Comment by ukemi** [comment]
Hi @balhoff, can I plead jet-lag? I don't see it now either.

**Comment by dougli1sqrd** [comment]
What graphstore is this query running against?

**Comment by dougli1sqrd** [comment]
So we could (I imagine) pretty easily filter the results of the query in only production models. Production models can be found with the triple pattern:
`?model <http://geneontology.org/lego/modelstate> "production"^^xsd:string .`
But I'm unsure how this triplestore is organized. I'll probably need @balhoff's help.

The other way we could do this, and probably the way forward more in the future, is to put this in the Pipeline. We already have some infrastructure to run reasoned sparql queries against a blazegraph. This is part of the process of producing our production triple store. At that point in the pipeline it would be pretty easy using Jim's blazegraph-runner tool to also run these queries to create gpad.

**Comment by cmungall** [comment]
@dougli1sqrd I believe this is the query you would edit:

https://github.com/geneontology/minerva/blob/master/minerva-converter/src/main/resources/org/geneontology/minerva/legacy/sparql/gpad-with-evidence.rq

**Comment by balhoff** [comment]
The problem with editing the Minerva SPARQL is that it will affect the GPAD you can make from the Noctua UI. I can't work on this right now but I'll try to get to it soon.

**Comment by cmungall** [comment]
ahh I see.

OK how about instead we just insert the model status in as a property of the annotation in the GPAD, then post-hoc filtering is easy

**Comment by balhoff** [comment]
Yes, that sounds good.

**Comment by balhoff** [comment]
Production status within GPAD is merged into Minerva now.

**Comment by ukemi** [comment]
So will we filter this before releasing the files that the MODs pick up, or do we expect the MODs to filter the annotations at their sites?

**Comment by ukemi** [comment]
Once we think the GPAD is in a consumable state, I will open a ticket here so that we can test load them into MGI with all the new qualifiers etc.

**Comment by kltm** [comment]
@cmungall Where should the expected output be?

**Comment by cmungall** [comment]
https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/ - as soon as the job completes

**Comment by kltm** [comment]
Should moving these over to their "forever home" and getting them into the main pipeline be part of closure here?

**Comment by cmungall** [comment]
Reopened because we need to figure out how this works with SynGO.

Our currently strategy is

 1. Collate production models by col1 (eg FB, MGI, UniProt) and deposit here
 2. Have each responsible group in charge of importing the annotations into their database

Note that this means that if SynGO annotations are annotated to UniProtKB IDs, it is UniProtKB's job to bring the prod GPADs and spit them out as GAFs as part of their normal database export.

We can see the the uniprot export is heavily dominated by SynGO:

https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/uniprotkb.gpad/*view*/

(4987 prod assocs)

First: @tonysawfordebi - what is UniProtKB's plans for importing these?

We *could* sub-collate in some way so that for example we split groups based on contributor, but this gets very complex.

Alternatively, we can just inject them directly in to the release GAFs as we do for PAINT.

**Comment by cmungall** [comment]
Note: All collated GPADs are now production only:

https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/

![image](https://user-images.githubusercontent.com/50745/37439783-fd89261c-27b6-11e8-8356-f1ea692b05df.png)

As can be seen this is dominated by uniprotkb, which is dominated by SynGO-VU...

**Comment by cmungall** [comment]
from @tonysawfordebi : we need a gpad header line

**Comment by kltm** [comment]
Talking to @cmungall , we wanted to check the status on this item.
Thinking about porting this over to the new pipeline (with the related decreased frequency), would we even need this if we are injecting the Noctua models into our GAF/GPI/GPAD products?

**Comment by kltm** [comment]
Note that geneontology/pipeline#65 is now active, so any changes or progress here should either be done in both places or within the new pipeline.

**Comment by kltm** [comment]
Current output from #65 seems to be production-only and by mod (using @cmungall 's script):
http://skyhook.berkeleybop.org/master/products/annotations/
I'll close this ticket--we can start a new ticket for new work or other changes that need to be made.
