### ISSUE TITLE
db-xrefs.yaml needs adjustment for obsolete databases 

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-site#46]
I've stumbled across another issue relating to the switch from GO.xrf_abbs to db-xrefs.yaml, namely that a number of GAFs are now being filtered out of existence during the transfer from the submission directory to the main gene-associations directory. This is because they refer to an obsolete database in column 1, and the new, derived-from-db-xrefs, GO.xrf_abbs does not contain entries for obsolete databases.

The affected files that I've identified so far are:

```
ftp://ftp.geneontology.org/pub/go/gene-associations/gene_association.GeneDB_Lmajor.gz  (refers to GeneDB_Lmajor, should be GeneDB)

ftp://ftp.geneontology.org/pub/go/gene-associations/gene_association.GeneDB_Pfalciparum.gz  (refers to GeneDB_Pfalciparum, should be GeneDB)

ftp://ftp.geneontology.org/pub/go/gene-associations/gene_association.GeneDB_Tbrucei.gz  (refers to GeneDB_Tbrucei, should be GeneDB)

ftp://ftp.geneontology.org/pub/go/gene-associations/gene_association.GeneDB_tsetse.gz  (refers to GeneDB_Gmorsitans, should be GeneDB)

ftp://ftp.geneontology.org/pub/go/gene-associations/gene_association.PAMGO_Atumefaciens.gz  (refers to NCBI_NP, should be RefSeq)
```

It seems to me that the correct way to fix this is to get the files corrected at source (assuming that they are all being actively maintained), rather than polluting db-xrefs.yaml with entries for obsolete databases.

However, having said that, I think it makes sense to extend db-xrefs.schema.yaml to allow an optional is_obsolete attribute, so that databases can be obsoleted in the future.

**Comment by tonysawfordebi** [comment]
One more affected file:
ftp://ftp.geneontology.org/pub/go/gene-associations/gene_association.GeneDB_Tbrucei.gz

**Comment by tonysawfordebi** [comment]
One more affected file:
ftp://ftp.geneontology.org/pub/go/gene-associations/gene_association.GeneDB_Tbrucei.gz

**Comment by tonysawfordebi** [comment]
One more affected file:
ftp://ftp.geneontology.org/pub/go/gene-associations/gene_association.GeneDB_Tbrucei.gz

**Comment by tonysawfordebi** [comment]
One more affected file:
ftp://ftp.geneontology.org/pub/go/gene-associations/gene_association.GeneDB_Tbrucei.gz

**Comment by pgaudet** [comment]
Out of date
