### ISSUE TITLE
PAINT annotations should be merged into group GAFs as part of release pipeline

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#461]
High priority

**Comment by cmungall** [comment]
The paint metadata is here:

https://github.com/geneontology/go-site/blob/master/metadata/datasets/paint.yaml

Two things need to be done

 1. [ ] include individual paint_GROUP GAFs as part of release
 2. [ ] merge into paint_GROUP GAF into main GROUP.gaf (see merges_into in yaml)

The first will happen automatically as soon as pipeline is live.

The second requires an additional piece of processing but this should be straightforward - it is the union of the two sets of annotations

**Comment by pgaudet** [comment]
Hi @cmungall 
When you write that this will happen when the pipeline is done, does this correspond to https://github.com/geneontology/go-site/issues/313? 

Thanks, Pascale

**Comment by cmungall** [comment]
@pgaudet - we're using this to track the v1 pipeline release

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/pull/500
