### ISSUE TITLE
db-xrefs.yaml  breaking  python3 yaml parser

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#464]
_From @TomConlin on November 25, 2017 22:19_

minimal example 
```
import requests
import yaml
response = requests.get('http://current.geneontology.org/metadata/db-xrefs.yaml')
result = yaml.load(response.text)
```
yields :  

```
    ...  snip cruft

ParserError: while parsing a block mapping
  in "<unicode string>", line 1424, column 7:
        - type_name: gene
          ^
expected <block end>, but found '['
  in "<unicode string>", line 1426, column 23:
          id_syntax: [A-Z][A-Za-z0-9_]+(\.[0-9])?
```

Maybe a goose chase but   
I do notice variation  enclosing the ```id_syntax``` regular expressions in single quotes     
but this one on line 1424 is the second instance  of adjacent character classes 
 ```...][...```
without enclosing tics not the first.

_Copied from original issue: geneontology/amigo#457_

**Comment by kltm** [comment]
@TomConlin 
Apologies, we just found this issue on another path. It should now be fixed:
https://github.com/geneontology/go-site/commit/368e30c90cb20b0ee26971689b388b18b737c59f

**Comment by TomConlin** [comment]
@kltm 
Since I may not reopen this, please leave issues open until the problem is addressed 
so I will get a notice when the file at: 
http://current.geneontology.org/metadata/db-xrefs.yaml 
stops breaking Python's yaml parser and I can make necessary changes in
my code. 

thanks

**Comment by kltm** [comment]
http://current.geneontology.org/metadata/db-xrefs.yaml is a monthly build and will likely not be fixed in place (although there should be a new version out in less than a week. You may want to use http://snapshot.geneontology.org/metadata/db-xrefs.yaml in the meantime.

**Comment by TomConlin** [comment]
I have been using 
https://raw.githubusercontent.com/geneontology/go-site/master/metadata/db-xrefs.yaml  
in the meanwhile but GitHub does not set "Last-Modified:"  headers which irks me.

**Comment by kltm** [comment]
Yeah, that URL will work too, but will eventually be blinked out as the old pipeline is slowly shut down over the indeterminate future as it is not an "officially" supported URL. Likely safe for a while though.

I understand your frustration here, but as far as our workflows go with this tracker, an issue is a unit of work in code that has been completed.  In the Noctua tracker we'll often keep items open until they hit the public as the development cycle is so fast. In this tracker though, in all likelihood, if I reopened this ticket it may not get closed for some time as the work has been completed and the tracker does not have a separate triage process.
