### ISSUE TITLE
Generate ttl versions of users.yaml and groups.yaml

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-site#469]
A JSON-LD context is available for translating `users.yaml` and `groups.yaml` into RDF Turtle:

https://github.com/geneontology/go-site/blob/master/metadata/users-groups-context.yaml

Somehow, the GO pipeline needs to use the context to convert those to files to RDF, and make the RDF versions available online. Some general steps are required:

- Convert all 3 files from YAML to JSON.
- Use a JSON-LD processor to convert those to RDF using that context. 
  - Not all JSON-LD processors provide a way to specify an out-of-band context to be used in the translation. Thus, a preprocessing step may be needed to insert the context in the right place within the files. E.g. this might be needed for Jena `riot`.
  - I provided example Ruby code in #442 which can do the translation direct from the YAML files, but this adds dependencies to the pipeline.
- Publish the RDF files somewhere.

Data from these files is needed for use in Noctua/Minerva, e.g. https://github.com/geneontology/noctua/issues/502

**Comment by balhoff** [comment]
A couple of notes if we want to do this with Jena `riot`:

- The `@nest` directive doesn't seem to be supported yet (it's not in the standard yet anyway)
  - It's not needed for the immediate use case, so that line could be commented out in the context.
- The data files have JSON arrays at the root, rather than objects. The root needs to be an object (`{...}`) in order to have a `@context` key. The data array can be put as the value for a `@graph` key.

The files can be processed to look like this:
```json
{
"@context": {
  "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
  "xsd": "http://www.w3.org/2001/XMLSchema#",
  etc.
  },
"@graph": [  existing contents  ]
}
```

A file like this with extension `.jsonld` can be opened directly by Jena tools.

**Comment by kltm** [comment]
@balhoff @cmungall I assume the easiest way forward for the application of this would be to add the YAML->RDF to the metadata step of the build and then aim invocations at skyhook. This assumes that nobody else should be interested in our metadata as RDF, except incidentally in our downstream data products.

**Comment by balhoff** [comment]
@kltm does the pipeline environment already have a command-line way to convert YAML to JSON?

**Comment by kltm** [comment]
Um, yes. If you are plotting out how to do this, you can just assume that as a given.
Technically, it would work something like:
```
sjcarbon@moiraine:~/local/src/git/go-site[master]$:) ./node_modules/.bin/yaml2json --help
usage: yaml2json [-h] [-v] [-p] [-i INDENTATION] [-s] [-r] [-w] input

Positional arguments:
  input                 YAML file or directory containing YAML files or - to 
                        read YAML from stdin.

Optional arguments:
  -h, --help            Show this help message and exit.
  -v, --version         Show program's version number and exit.
  -p, --pretty          Output pretty (indented) JSON.
  -i INDENTATION, --indentation INDENTATION
                        Number of space characters used to indent code (use 
                        with --pretty, default: 2).
  -s, --save            Save output inside JSON file(s) with the same name.
  -r, --recursive       If the input is a directory, also find YAML files in 
                        sub-directories recursively.
  -w, --watch           Watch for changes.

```

**Comment by balhoff** [comment]
Perfect, thanks.

**Comment by kltm** [comment]
I believe that this is already part of the pipeline: 
http://current.geneontology.org/metadata/groups.ttl
http://current.geneontology.org/metadata/users.ttl
