### ISSUE TITLE
Synchronizing db-xrefs.yaml with identifiers.org

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#47]
REST here:
http://www.ebi.ac.uk/miriamws/main/rest/

But the RDF dump would suit us better:
http://www.ebi.ac.uk/miriam/main/export/

We would review this and see if it's feasible to convert this to and use directly vs having some kind of semi-automated synchronization mechanism.

**Comment by cmungall** [comment]
First draft at mapping. this would be better done ina JSON-LD context. gox is a fake prefix here for our json tags:

 * idot:namespace = lc(gox:database)
 * dcterms:alternative = gox:synonyms
 * dcat:title = gox:name
 * dcat:description = gox:description
 * void:exampleResource = gox:example_id
 * idot:idRegexPattern = '"^" . gox:entity_types.id_syntax ."$"
 * dcat:accessURL = gox:entity_types.url_syntax

But the devil is in the details. There may be semantic differences. We capture id regexes at the level of object types (with each resource having 1 or more entity types). Can't say I love this kind of assumption of datatype by ID pattern but this is a requirement for Tony.

Another difference is that GO forces all entities to be Prefix-LocalID pairs. See http://wiki.geneontology.org/index.php/Identifiers

Formally they are CURIEs

This could be an issue if GO wanted to include say CHEMBL, which in idot is currently

```
      idot:idRegexPattern "^CHEMBL\\d+$"^^<http://www.w3.org/2001/XMLSchema#string> ;
      idot:namespace "chembl.target"^^<http://www.w3.org/2001/XMLSchema#string> ;
      void:exampleResource
              "CHEMBL3467"^^<http://www.w3.org/2001/XMLSchema#string> ;
```

We would force all identifiers in GO to be CURIES, so we would need a prefix. Our prefix can't have a dot, do the idot:namespace above wouldn't work. The natural choice would be CHEMBL as prefix, so would the CURIE be CHEMBL:nnnn or CHEMBL:CHEMBLnnnnn (echoes of MGI:MGI horror)

**Comment by kltm** [comment]
Tagging @pgaudet : from our discussion Thursday.
