### ISSUE TITLE
Set up jenkins job for CHEBI

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#48]
Check disjoints

Is this the right tracker for this?

**Comment by hdietze** [comment]
@dosumis mentioned a daily build for ChEBI. URL?
Ideally we could use this and run the job daily, avoiding/circumvent triggers via FTP changes.

**Comment by kltm** [comment]
@cmungall I feel like we're overloading this tracker--there are no artifacts in the repo for jenkins.
If we go this we'll need to add labels for all the catch-all project so we can sort them out.

**Comment by dosumis** [comment]
Nightly build is here http://www.ebi.ac.uk/~biobabel/chebiOntology/

**Comment by dosumis** [comment]
Disjointness axioms are here:

ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi-disjoints.owl

We should get them to change the import statement to point to the nightly build.  Is it also worth asking them to move this to GitHub?

**Comment by hdietze** [comment]
For now, I'm going to use a catalog xml file to redirect it to the nightly build.

**Comment by hdietze** [comment]
Job is available here: http://build.berkeleybop.org/job/check-chebi-disjoints/
But there seems to be no unsatisfiable classes at the moment. Is the check not strong enough or did they already fix it?

**Comment by cmungall** [comment]
Odd. @davidos, are you able to replicate this?

**Comment by dosumis** [comment]
Looks like they've been fixed already.  They're in the last monthly build (from Feb 2nd).  Spot checked a few to look at solutions chosen.  Looked like reasonable fixes.

**Comment by hdietze** [comment]
Seems to work as expected since February.
