### ISSUE TITLE
SVN down?

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-site#485]
Hope this is the right place to put this...

Was attempting to upload gafs, etc. to svn; 

ssvn: E210002: Commit failed (details follow):
svn: E210002: Unable to connect to a repository at URL 'svn+ssh://hjd@ext.geneontology.org/share/go/svn/trunk/gene-associations/submission'
svn: E210002: Network connection closed unexpectedly
svn: E210002: Your commit message was left in a temporary file:
svn: E210002:    '/Users/hjd/trunk/gene-associations/submission/svn-commit.tmp'
~/trunk/gene-associations/submission $

**Comment by kltm** [comment]
@hdrabkin Unfortunately, I have no power the SVN repo. We can loop in Stuart if we cannot take care of this. That said, I just did an `svn update` on the genenontology repo and things seemed to work fine. Could you confirm that this is still an issue?

**Comment by hdrabkin** [comment]
not working for me; tried to do an 'svn update ontology' from trunk and it just sits; So you think this is a problem on my end? Git stuff works fine.

svn: E210002: Unable to connect to a repository at URL 'svn+ssh://hjd@ext.geneontology.org/share/go/svn/trunk'
svn: E210002: Network connection closed unexpectedly

**Comment by hdrabkin** [comment]
@stuartmiyasato 
Any ideas;? this was working fine on Monday.

**Comment by kltm** [comment]
@hdrabkin 

This currently works for me from my work locations:

```
sjcarbon@moiraine:~/local/src/svn/geneontology.org/trunk$:) svn update ontology
Updating 'ontology':
U    ontology/extensions/po_import.obo
U    ontology/extensions/cl_import.owl
U    ontology/extensions/ro_import.obo
...
```

This might suggest a problem local to your end. Have you tried this at other sites or locations?

**Comment by hdrabkin** [comment]
No; I suppose I can try from home when I take my laptop. It won't be going through jax for that. 
Like I said, I can use the git repos no with no problem. I guess I'll wait till I get home and try. 
I also added Stuart, but it seels like you have no problem; what you show is what I usually get. 
Won't be able to submit gafs until I can fix this. 8-(
Thanks

**Comment by stuartmiyasato** [comment]
@hdrabkin I'm not seeing any issues on our end, and interestingly I'm not seeing any authentication errors in the logs for your account, which makes me wonder if the server is even seeing your request at all.

Can we try backing up a step to see if SVN is even related to this issue?  Can you try running the following command:

`ssh hjd@ext.geneontology.org date`

and report back with any output from that command?  If all is well, that should just return the server's timestamp.  That will tell whether the SSH part is even succeeding or failing, possibly prior to any SVN command being run on the server, and will help pinpoint where debugging efforts should be directed.  Thanks.

**Comment by hdrabkin** [comment]
This  command hangs and I get 
ssh: connect to host ext.geneontology.org port 22: Operation timed out
Trying from trunk
ssh: connect to host ext.geneontology.org port 22: Operation timed out

**Comment by stuartmiyasato** [comment]
That definitely sounds like a network issue between your machine and the server.  Out of curiousity, can you access http://viewvc.geneontology.org/viewvc ?  This site is hosted on the same machine as the SVN repo itself.  If you can't access that site, that would certainly point to a network issue.  If you *can*, then things get even more mysterious.  :)

**Comment by kltm** [comment]
@hdrabkin 
My wild guess, from also looking at the issue on the internets is that this may be port related and at your end. I'd be curious if this works off-site for MGI and if there was a change in policy there recently.

**Comment by hdrabkin** [comment]
You know, I was going to try that as I often look at the achives. So the link you suggest, as well as the link I usually use http://viewvc.geneontology.org/viewvc/GO-SVN/ both just site there.
This explains a lot; I can call my IT department and see.

**Comment by hdrabkin** [comment]
Even IT cannot each the url target; They suggest I try from home but to their knowledge no changes that would be port-related were made.

**Comment by kltm** [comment]
That's pretty wacky. Looks like you can let them take care of it though.
If you need to get the file through, you can maybe ping another MOD's curation team to get it through.

**Comment by hdrabkin** [comment]
Thanks; it can hold until next week.

**Comment by hdrabkin** [comment]
From home now; I can reach link no problem

**Comment by kltm** [comment]
Good luck to you, but it looks like you're on your own ;)
