### ISSUE TITLE
ftp site is not responding

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-site#487]
ftp://ftp.geneontology.org times out.
We get files for our gaf loads from the site

**Comment by stuartmiyasato** [comment]
@hdrabkin This may be related to the SVN problem you were having last week.  I can access the FTP server fine from my home computer.  I'm currently downloading the huge 5GB goa_uniprot_all.gaf.gz file and not running into any problems.  The FTP server is the same physical machine as the SVN server.

If you are still having problems accessing the SVN server, I'd suspect this is the same issue.  You might want to contact your IT group again to confirm, though.

-- Stuart

**Comment by kltm** [comment]
@hdrabkin It works for me as well.

**Comment by hdrabkin** [comment]
Yes, I will close this now; our IT department did switch our connection over to a different server and the problem went away. There WAS maintenance on early Friday morning that I think is responsible for this difficulty.
