### ISSUE TITLE
Deploy new GAF download page for S3/Cloudfront downloads

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#491]
Goal is to replace http://geneontology.org/page/download-annotations

 * [x] fix http://skyhook.berkeleybop.org/release/reports/downloads.html to not be empty
 *  [x] Needs coordinated rollout with YAML files as it uses that metadata to point to go-ified products.
 * [ ] add redirect from drupal to cloudfront

**Comment by kltm** [comment]
See #492

**Comment by kltm** [comment]
Talking with @cmungall and @dougli1sqrd : The above items can be handled separately as nobody is really using the `url` tag currently in the YAMLs.

**Comment by kltm** [comment]
Proper final would be: http://current.geneontology.org/products/pages/downloads.html

**Comment by kltm** [comment]
This will go out with the new site.

**Comment by pgaudet** [comment]
I'll try adding my comment here: 

Species: Can we change the names in parenthesis to be more easy to understand ?
Databases: Can we link the name of the database instead of having it twice ?
(for eg: "dictyBase (dictybase, Ddis)" would become
dictyBase, Dictyostelium discoideum

Thanks, Pascale

**Comment by pgaudet** [comment]
Is this already implemented in http://current.geneontology.org/products/pages/downloads.html ? 

I'd like to have a look before we can say it's closed, to make sure what was requested was correctly implemented. 

Thanks, Pascale
