### ISSUE TITLE
Correct non-usable URL entries in db-xrefs.yaml (re: Reactome links in AmiGO)

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-site#497]
If you navigate to an annotation from Reactome and click on the reference link, the link is broken. The example I used was annotations for the BCL2 gene.

**Comment by kltm** [comment]
@ukemi Sorry, could you give be a reference page to start from for repeating the bug?

**Comment by ukemi** [comment]
Sorry @kltm Try this one:

http://amigo.geneontology.org/amigo/gene_product/www.reactome.org/content/detail/R-HSA-114352

**Comment by kltm** [comment]
@ukemi Thank you. Where are you getting that link from though?

**Comment by ukemi** [comment]
The reference link in the table here:
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:P10415

Filter on contributor 'Reactome' to narrow the results.

**Comment by kltm** [comment]
@ukemi Cheers--that is an exciting!

**Comment by kltm** [comment]
@tonysawfordebi It looks like the last update for reactome removed the `http://` portion of the URL syntax. I'm going to re-add those and add some additional schema checks.

@elserj When I started adding new schema checks, I noticed that CO_125 was not really structured in a usable way (https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml#L399). If it is not actively being used, can we remove that entry? It is now failing the new checks that I'll be adding.

**Comment by kltm** [comment]
@elserj As well, the "grape"? entry is problematic with `name`, `example_id`, and `example_url`: https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml#L483

**Comment by kltm** [comment]
@elserj Finally, `OBO_SF2_PO` and `OBO_SF2_PECO` are problematic with their `generic_urls` not being URLs.
https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml#L1922
https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml#L1932

**Comment by elserj** [comment]
Made a PR to fix these issues.
https://github.com/geneontology/go-site/pull/499
Let me know if I missed anything.

**Comment by kltm** [comment]
@elserj Cheers! 
Line 408 for `CO_125` has:
```yaml
      example_url: url_example
```
I believe that is the final issue currently.

**Comment by kltm** [comment]
@elserj Whoops--I already added the schema checks. To just get it through, I added: 
```yaml
      example_url: http://www.cropontology.org/ontology/CO_125:0000000
```
which is likely no worse. Please change that if not appropriate.
If that is okay, we are good now.

**Comment by elserj** [comment]
I think that is okay.  I don't think their site is working properly as nothing useful comes up with that link, but I'll look into it.  Link format looks fine, I think problem is on their end.  Will let you know if it needs to be changed.

**Comment by kltm** [comment]
Thank you for looking!

**Comment by kltm** [comment]
@ukemi 
This should be resolved on the next AmiGO reload as it was just a metadata issue.
