### ISSUE TITLE
PANTHER as a service sometimes gives different results in different formats for same URL

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#50]
url = "http://pantherdb.org/webservices/go/overrep.jsp?ontology=biological_process&input=P31946%0AP62258%0AQ04917%0AP61981%0AP31947%0Abaxter%0AP27348%0AP63104%0AQ96QU6%0AQ8NCW5&species=HUMAN&correction=bonferroni&format=html"

About 5%-10% of the time, a couple of people (and several bots) have gotten different results when serially contacting the same URL. In these results there has been:

* the correct html page
* a different incorrect html page (that seems to have little to do with the query)
* an xml result that seems to be the right data
* an incorrect xml result

This has been an issue dealt with on email, but hopefully we can catch-up with the description here.

**Comment by kltm** [comment]
@mugitty pinging on Anushya.

**Comment by kltm** [comment]
@mugitty I was wondering if there was any update on this. A few days ago I tried and did not get error results after twenty tries, but today the amigo unit test dealing with PANTHER is failing (two of three tries) and using https://github.com/geneontology/go-site/blob/master/tests/panther-hammer.py gave almost immediate error results.

**Comment by mugitty** [comment]
Resloved
