### ISSUE TITLE
stats graph UniProt and UniProtKB

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#504]
I thought UniProt was purged in favour os UniPRotKB ages ago but it is still the main contributor here: (not BOTH are present)

![uniprot](https://user-images.githubusercontent.com/7359272/34833745-0d7f0d98-f6e8-11e7-86a3-eff4b4ff739c.jpg)

**Comment by kltm** [comment]
@ValWood In this case, the stats graph is just reflecting what is actually loaded into AmiGO (check 'Contributors' at http://amigo.geneontology.org/amigo/search/annotation).
Is this a question about UniProt vs UniProtKB in our data sources or about the stat graph itself.

**Comment by ValWood** [comment]
Hmm yes its really a submitter issue.

As far as I recall we were told that the correct prefix for UniProt was UniProtKB
so we use this in all prefixes and in the file which tells us how to refer to databases.

The correct usage seems to  come from  
MGI
Zfin
E. coli and Tair
possibly because they write out the assignee in the column correctly.

Oddly UniprotKB uses UniProt?

I'll open an issue on the annotation tracker
