### ISSUE TITLE
The PAINT GAF file has an inappropriate taxon ID--spaces added

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#51]
The current version of:

http://www.geneontology.org/gene-associations/submission/paint/pre-submission/gene_association.paint_other.gaf

Contains taxon IDs that contain spaces. When loading GOlr, the error looks like:

```
2015-03-13 09:39:31,979 INFO  (GafSolrDocumentLoader:92) Iteratively loading: /home/bbop/jenkins/workspace/load-golr-tomodachi/golr/http:/www.geneontology.org/gene-associations/submission/paint/pre-submission/gene_association.paint_other.gaf
Mar 13, 2015 9:39:31 AM org.obolibrary.obo2owl.OWLAPIObo2Owl oboIdToIRI
SEVERE: id contains space: "NCBITaxon:E   10116"
Exception in thread "main" org.semanticweb.owlapi.io.OWLParserException: spaces not allowed: 'NCBITaxon:E   10116'
```

Downloading the file and running the command:

```bash
grep "10116" gene_association.paint_other.gaf  | less
```

Shows lines like:

```
RGD	1308322	Myf5		GO:0003705	PAINT_REF:11534	IBA	PANTHER:PTN000164853	F	myogenic factor 5	PTN000164922	protein	taxon:E   10116	20141217	GO Central		
```

Where something has clearly gone wrong. A first pass analysis by @selewis would point to an error in a script in the old GO SVN repo:

 svn/geneontology.org/trunk/software/utilities/filter-paint-associations.pl

**Comment by kltm** [comment]
@selewis Could you close if this has been fixed?

**Comment by selewis** [comment]
Error in parsing UniProt taxon files - now fixed
