### ISSUE TITLE
Proposal: Consider a one-time change from UniProtKB to UniProt ubiquitously

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#515]
It should be stated from the outset: this proposal would be costly to implement and would cause a lot of churn

In fact the mere fact of _stating_ this proposal may cause confusion and churn.

In the history of GO, pre-@tonysawfordebi someone had the idea of changing the universally accepted "UniProt" to "UniProtKB" as an identifier prefix, for reasons that in retrospect are dubious. This was implemented at some cost within GO.

However, the rest of the world still uses "UniProt". Even the EBI's own identifier prefix database MIRIAN recognizes this (or at least the lowercase form; it downcases all prefixes) as canonical:

http://identifiers.org/UniProt

But this gives a 404
http://identifiers.org/UniProtKB

Also the prefixcommons project recognizes uniprot (but has uniprotkb as a synonym(
https://prefixcommons.org/?q=uniprot

This has some moderate cost for ingress and egress to and from GO. It should be stated that most of these costs are likely now paid and thus little incentive to change further.

However, the case must be made for a one-time change that would harmonize GO with the rest of the world. OK, now shoot me down...

Also it should be stated that this is about the identifier prefix, and the change would manifest in col1 and with/from of the GAF. It does not concern the group/assigned_by field. However, we have  a _convention_ that these match, when the group is also an identifier provider as well as an annotation provider. See https://github.com/geneontology/go-annotation/issues/1772 for a discussion on this. That ticket should be used for group/id harmonization issues.

This ticket here is strictly about my possibly doomed proposal to change the identifier prefix.

**Comment by tonysawfordebi** [comment]
Replacing all references to "UniProtKB" with "UniProt" would require an **enormous** amount of work on our part, for, IMHO, minimal gain.

**Comment by cmungall** [comment]
@hdrabkin - no need, even if hypothetically this ticket were to be implemented, this would be planned carefully over a long period.

@tonysawfordebi - ok fair enough. I will close this ticket as I don't want to generate busy work when we all have enough to do.
