### ISSUE TITLE
Current zip/compression used in pipeline leaves some oddities

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#534]
The new (python) gzip tools used during the compression step of the pipline reveals too much about the origin file, possibly to the point of causing confusion for some tools.

For example, using the standard `file-roller` tool, when opening dictybase.gaf.gz, I am presented with the singular option to extract "dictybase_merged.gaf". For somebody who is not familiar with the original of this file would regard that as a problem. This is a "surface" issue for now, but I worry that this could manifest as a "real" issue with some tools (such as file-roller) down the line.

Looking at the actual file, is seems that this information is stored in the header or index section of the gz. I would bet it's related to caching of the info related to the (-N) flag: https://www.gnu.org/software/gzip/manual/gzip.html#Overview . This would also depend on the use of zlib something else for the python.

A fix would be to suppress/remove historical/origin information in the create `.gz` files.

**Comment by kltm** [comment]
To note, if this can be "proved harmless" (e.g. the `-N` use above), please note and just close.

**Comment by kltm** [comment]
looping in @cmungall

**Comment by cmungall** [comment]
@dougli1sqrd what's the status?

**Comment by kltm** [comment]
@dougli1sqrd , correct me if I'm wrong, but I believe that the status here is "positively proven to not be harmful, but maybe a little confusing"? As it stands at the moment, if I download the FB GAF I get `fb.gaf-2` in some tools when decompressing, but CLI tools completely ignore it.
The question is: is the possible confusion worth doing a name juggle before compression (or should we use a compression tool where we can better control the metadata that gets in)?

**Comment by dougli1sqrd** [comment]
@kltm, yes that's true, not considered harmful. Also though, I remember writing code that corrected this. I'm trying to see if that got in.

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/pull/540

**Comment by kltm** [comment]
I take it back, currently this seems fine--I had a cached file.
