### ISSUE TITLE
Informative headers must be preserved / generated for GAFs in the pipeline

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#535]
Currently, the only headers produced/retained from the GO pipeline processing of the GAFs is apparently:

```
!gaf-version: 2.1
```

Some original headers, additional injected information (e.g. time), etc. is expected to be at the top of the file.

Any solution here should also fix any issues with #355.

**Comment by kltm** [comment]
looping in @cmungall

**Comment by dougli1sqrd** [comment]
https://github.com/biolink/ontobio/pull/144

**Comment by cmungall** [comment]
is this done?
