### ISSUE TITLE
when merging PAINT gafs, the header is inserted in between annotation lines

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#550]
in the current public release:

```
$ gzip -dc ~/Downloads/goa_human.gaf.gz  | grep -n '^\!'
1:!gaf-version: 2.1
2:!
3:!The set of protein accessions included in this file is based on UniProt reference proteomes, which provide one protein per gene.
4:!They include the protein sequences annotated in Swiss-Prot or the longest TrEMBL transcript if there is no Swiss-Prot record.
5:!If a particular protein accession is not annotated with GO, then it will not appear in this file.
6:!
7:!Note that the annotation set in this file is filtered in order to reduce redundancy; the full, unfiltered set can be found in
8:!ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/UNIPROT/goa_uniprot_all.gz
9:!
10:!Generated: 2018-02-26 09:16
11:!GO-version: http://purl.obolibrary.org/obo/go/releases/2018-02-20/extensions/go-plus.owl
12:!
448469:!gaf-version: 2.0
448470:!Created on Fri Feb 23 17:18:24 2018.
448471:!PANTHER version: v11.1.
448472:!GO version: 2017-08-27.
```

The header should be in the header..

I suggest that when merging, the header of the merged file is incorporated into the header of the primary file

 - remove gaf-version, as that must appear only once.
 - Other lines could perhaps be prefixed, e.g with "merged_from_paint_human"

@huaiyumi it looks like PAINT is using an old version of GO?

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/pull/557

**Comment by kltm** [comment]
I have a little concern that PAINT headers are often a different version than the original file itself--2.0 vs 2.1. That strikes me as wrong, but maybe this is the way things have been done?

**Comment by pgaudet** [comment]
Is this a question for @huaiyumi ?

**Comment by huaiyumi** [comment]
The header was copied from the earlier paint gaf by Suzi. Not sure about gaf version so it was left as 2.0. Others were updated accordingly. If this is a a problem, let me know exactly how you want the header to be and we can update it.

**Comment by cmungall** [comment]
The ontology version should be the ontology version you are using - is 
this really from summer 2017?

**Comment by kltm** [comment]
Okay, for the header, practically speaking from the OWLTools GAFParser code, we are indeed technically mixing two different file versions into one, which is technically bad. That said, we've been doing this for a while apparently and it does not seem to cause any *practical" problems at the moment.

What I'd like to do is close this ticket and open one in the PAINT tracker: eneontology/paint#49
