### ISSUE TITLE
Specify GAF 2.1.1

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#553]
See http://wiki.geneontology.org/index.php/Manager_Call_2018-03-01#Expanded_Set_of_Relations

We want a minor increment in GAF to make it explicit that expanded relations can go in the qualifier column. We will need documentation with examples etc.

GPAD already supports this, but we can provide specific examples in the GPAD.

potential people: @vanaukenk @dougli1sqrd @pgaudet

**Comment by vanaukenk** [comment]
I've started pages on the Annotation section of the wiki for detailed documentation of the expanded set of BP relations:

http://wiki.geneontology.org/index.php/Biological_Process

@pgaudet @ukemi and myself will work on the content of these pages next week.

**Comment by cmungall** [comment]
Should we have all GP->Term relations on one page to make it easier to find them?

Or perhaps it's fine if they all go into a category more specific than Relations. I'm a big fan of categories over manually listing links

**Comment by cmungall** [comment]
I went ahead and created a category
http://wiki.geneontology.org/index.php/Category:Gene_Product_to_Term_Relations

I also added links to exemplar models for some, e.g
http://wiki.geneontology.org/index.php/Acts_upstream_of_or_within#Examples_of_Usage

The idea here is to have the simplest possible model that demonstrates how the GPAD relation is derived from a GO-CAM

**Comment by cmungall** [comment]
We should make it explicit what combinations are possible, e.g. NOT

**Comment by pgaudet** [comment]
Abandonned for GAF2.2
