### ISSUE TITLE
Mapping MOD-specific references to GO_REFs

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-site#562]
We have been using http://www.geneontology.org/doc/GO.references as the source of mappings from MOD-specific references to GO_REFs.

As that file is no longer maintained, what's the best way to obtain these mappings? https://github.com/geneontology/go-site/tree/master/metadata/gorefs is not easily parsable...

**Comment by cmungall** [comment]
for now you can use https://pypi.python.org/pypi/yamldown/

but we should do this as part of the pipeline release and make a combined json product

**Comment by tonysawfordebi** [comment]
Thanks, Chris.
