### ISSUE TITLE
GO Tools Registry page

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/go-site#57]
Looking through old messages, I found a suggestion from Becky. 

"When I was looking at the GO tools options, the GO website (http://geneontology.org/page/go-tools-registry) just lists that the GO tools registry is no longer supported. Could it link to other tools instead…. e.g. AmiGO2? - Thanks, - Rebecca"

**Comment by monicacecilia** [comment]
Suggestions and updates on other plans currently underway to update this are also welcomed.

**Comment by kltm** [comment]
Dupe of #30.

**Comment by monicacecilia** [comment]
boy, am I repetitive. 
thanks!
