### ISSUE TITLE
How long should it take for changes to propagate through the system?

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-site#571]
I made changes to both the PAINT_REF and IntAct entries in https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml last Wednesday / Thursday, but the derived JSON file (https://s3.amazonaws.com/go-public/metadata/db-xrefs.json) has not yet caught up.

**Comment by kltm** [comment]
@tonysawfordebi Sorry for the trouble. It looks like these jobs had been paused to deal with some trouble and had not been turned back on. They are on now and should run tonight.

Also, here is a ticket to track getting the metadata into a proper final location as part of the new pipeline:
https://github.com/geneontology/pipeline/issues/33
