### ISSUE TITLE
F-P GAF has redundant annotations

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#576]
There is  a lot of redundancy with existing annotation in the inferred GAF

Here are some examples:

1.
thi1. 2 redundant annotations:

ii) redundant and identical (we made this annotation from this paper)
GO:0045944 | positive regulation of transcription by RNA polymerase II | IMP | Tang CS et al. (1994)

ii) redundant and less specific

GO:0006366 | transcription by RNA polymerase II | IMP | Tang CS et al. (1994)

![this1 2 repeats](https://user-images.githubusercontent.com/7359272/37775909-15e4c272-2ddc-11e8-9a07-6a2e79fdf685.jpg)

2.
vht1, lots of redundant less specific 

![vht1 3 redundant parents](https://user-images.githubusercontent.com/7359272/37781486-b4ace432-2de8-11e8-8347-fdb44bb0b2aa.jpg)

GO:0042886 | amide transport | IMP | Stolz J (2003)
GO:1905039 | carboxylic acid transmembrane transport | IMP | Stolz J (2003) | 
GO:0015718 | monocarboxylic acid transport | IMP | Stolz J (2003)

3. crm1 exact duplicate

GO:0006611 | protein export from nucleus  IMP | Takeda K et al. (2010)

![crm1 exact dupe](https://user-images.githubusercontent.com/7359272/37781744-37e00dd4-2de9-11e8-86f1-f1fc1936f6cd.jpg)

so can we filter 
i)  exact duplicates
ii) annotations less specific  than the existing annotations

For the non experimental annotations they are filtered by our pipeline, but we  have a rule not to filter any experimental annotation.

Having duplicated annotation isn't a show stopper, but it isn't useful and it looks sloppy/confusing  to users

**Comment by pgaudet** [comment]
Are they duplicate because they were assigned by different sources ?

**Comment by ValWood** [comment]
Well yes. PomBase made them from the paper, and the inference pipeline assigned the duplicates from our annotation ! 

@rachhuntley  made the same point about a  slightly different type of redundancy from the inference pipeline  here:

https://github.com/geneontology/go-annotation/issues/1487
3.
An inferred annotation is created even when there is a pre-existing manual annotation from the same paper with better evidence (See UniProtKB:P46153 GO:0010666 PMID:25950484). With other automated pipelines, duplicated annotations are suppressed. 

Although I do not understand this comment about the source of the annotation:

The annotation that is created in this instance is odd; it states that P46153 is inferred to be involved in
"positive regulation of cardiac muscle cell apoptotic process" with evidence from the annotation to "negative regulation of pri-miRNA transcription from RNA polymerase II promoter”, there is no indication that the evidence is actually coming from the extension statement associated with the annotation that the regulation of transcription is positively regulating apoptosis.

**Comment by ValWood** [comment]
If I understood correctly,
this ticket  is blocked by
https://github.com/geneontology/go-site/issues/576

**Comment by ValWood** [comment]
If I understood correctly,
this ticket  is blocked by
https://github.com/geneontology/go-annotation/issues/1427

**Comment by ValWood** [comment]
Another example with the redundancy

Lots of annotations to "cell" when we have more specific annotations (over occurs_at links)
(Maybe we should block the term "cell" for direct annotation anyway?  @pgaudet)

**Comment by cmungall** [comment]
We just need a single example of where this is not behaving as expectedly. Here just a gene ID and an inferred term ID.

@yy20716 will investigate this

Let me try an restate

The pombase source has a direct annotations of ste11 to  GO:0045944

```
$curl -L http://geneontology.org/gene-associations/submission/gene_association.pombase.gz | gzip -dc | grep GO:0045944 | grep SPBC32C12.02
PomBase SPBC32C12.02    ste11           GO:0045944      PMID:8196631    IMP             P       transcription factor Ste11      stex|aff1       protein taxon:4896      20120208        PomBase  has_regulation_target(PomBase:SPAPB8E5.05)      
PomBase SPBC32C12.02    ste11           GO:0045944      PMID:8196631    IMP             P       transcription factor Ste11      stex|aff1       protein taxon:4896      20120208        PomBase  has_regulation_target(PomBase:SPAC513.03)       
...
```

The prediction file includes an inference of the same gene to this term:

```
 curl -L http://snapshot.geneontology.org/products/annotations/pombase-prediction.gaf | grep GO:0045944 | grep SPBC32C12.02
PomBase SPBC32C12.02    ste11           GO:0045944      PMID:10908327   IDA             P       transcription factor Ste11      stex|aff1       protein taxon:4896      20150519        GOC      
```

in this case it does not matter where the inference comes from. If we are intending to filter out redundant annotations, this is a bug. If we are leaving it to the consumer to filter these out this needs documented.

See my comments here on where this should be documented: https://github.com/geneontology/go-annotation/issues/1336#issuecomment-375419789

**Comment by ValWood** [comment]
Here is a single example:

vht1
SPAC1B3.16c

We made the following process annotations from this paper:

vht1 | GO:1905135 | biotin import across plasma membrane | IMP | 
vht1 | GO:1905136 | dethiobiotin import across plasma membrane | IMP | 


the we get the following less specific inferences:


- | GO:0042886 | amide transport | IMP | Stolz J (2003) 
- | GO:1905039 | carboxylic acid transmembrane transport | IMP | Stolz J (2003) 
- | GO:0015718 | monocarboxylic acid transport | IMP | Stolz J (2003)

**Comment by ValWood** [comment]
They are quite annoying when we make great efforts to present non-redundant annotation  ;)

We filter redundant non experimental from any source, but these show up because they are experimental. I guess we could change so that we filter duplicates from GOC assigner, but I think it would be better generally  for everyone not to generate more duplicate annotations.

**Comment by ValWood** [comment]
Your example for ste11 is slightly different than the ones I am using. It is from 2 independent sources, and it's a different evidence code.
I think there is a strong case to filter these too, but I am  more concerned about the ones which come from an identical source.

**Comment by rachhuntley** [comment]
Responding to Val's comment:
"Although I do not understand this comment about the source of the annotation:

The annotation that is created in this instance is odd; it states that P46153 is inferred to be involved in
"positive regulation of cardiac muscle cell apoptotic process" with evidence from the annotation to "negative regulation of pri-miRNA transcription from RNA polymerase II promoter”, there is no indication that the evidence is actually coming from the extension statement associated with the annotation that the regulation of transcription is positively regulating apoptosis.""

It looks like this inference is no longer made.

**Comment by ValWood** [comment]
closed duplicate
https://github.com/geneontology/go-annotation/issues/1682

has more examples...

**Comment by ValWood** [comment]
@cmungall  you can probably close this one?

**Comment by pgaudet** [comment]
We will develop guidelines: https://github.com/geneontology/go-annotation/issues/2060
