### ISSUE TITLE
standard GO syntax checks  required on inferred GAF (contributes to and aspect)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#578]
PomBase	SPAC1002.15c	med6	contributes_to	GO:0006357	PMID:10625684	IC	GO:0030295	F mediator complex subunit Med6	pmc5	protein	taxon:4896	20160908	GOC-OWL has_direct_input(PomBase:SPBC19F8.07),part_of(GO:0006357)

- [ ] The aspect is incorrectly reported
This annotation has the aspect "F"
But it is a process term GO:0006357 regulation of transcription by RNA polymerase II

- [ ] contributes_to is not valid with a process term

**Comment by ValWood** [comment]
another example, called by @kimrutherford
here https://github.com/geneontology/go-site/issues/524#issuecomment-375125097

 the Aspect column has "C" in a lot of cases where the term isn't a component term. Lke:

PomBase  SPAC1006.07  tif1  GO:0006412  PMID:10462529  IMP  C  translation initiati...
GO:0006412 is a process term.

**Comment by ValWood** [comment]
The major one so far is that it contains many IC annotations to process terms with an F in the aspect column.
Also from
https://github.com/geneontology/go-site/issues/524


see for example
PomBase	SPBC2F12.13	klp5	GO:1990758	PMID:21664573	IC	GO:0005515	F	kinesin-8 family plus-end microtubule motor Klp5	sot1	protein	taxon:4896	20161018	GOC-OWL part_of(GO:1990758)

(there are many more)

**Comment by ValWood** [comment]
Rachel had another example here
https://github.com/geneontology/go-annotation/issues/1487#issuecomment-375402861

2. a couple of annotations have been created that use the contributes_to qualifier with a GO:CC term (UniProtKB:P21524 and UniProtKB:P38291).~

I can't tell if this is fixed  because  P21524 is not finding anything in Amigo and I presume GOA are filtering incorrect qualifiers

**Comment by kimrutherford** [comment]
> This annotation has the aspect "F"
> But it is a process term GO:0006357

For some GO:0006357 annotations the aspect is "P".

It looks like only IC annotations have the aspect wrong, and only sometimes.  For the IC annotations I looked at, the aspect matched the term in the "with" column:

    ... GO:0006357   PMID:10625684   IC   GO:0030295   F ...
    ... GO:0006357   PMID:28903048   IC   GO:0097198   P ...

**Comment by ValWood** [comment]
yep, I made a ticket about this:
https://github.com/geneontology/go-site/issues/578

**Comment by ValWood** [comment]
durr... this one

**Comment by cmungall** [comment]
I won't get a chance to look at this til monday, on a review panel tomorrow.

@yy20716 can you check why the aspect does not match the term.

part of the general problem here is that we did not do a great job of properly specifying what the actual behavior of these rules should be, see https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000023.md. They also interact in ways that need to be checked - for example, some propagations may result in things that violate other rules about what evidence codes or qualifiers can be used with different terms. Can we make a start on a google doc that lays this out it may be the best way to proceed.

**Comment by yy20716** [comment]
I was tracking the generation process of each entry in pombase-prediction.gaf. It seems that the problematic entry (`PomBase SPAC1002.15c med6 ...`) indeed comes from the codes that check for `occurs_in` and `part_of` in the class `FoldBasedPredictor`. Specifically, this entry is generated in [the loop that iterates superClassesExpressions in the method predictForBioEntities](https://github.com/owlcollab/owltools/blob/e637b4ccfd700b050880cc80a642ce2ad737e7f7/OWLTools-Annotation/src/main/java/owltools/gaf/inference/FoldBasedPredictor.java#L238). One thing strange part is that this class has not been changed for a year. Anyway, I will continue checking this issue tomorrow if you don't mind. Thanks.

**Comment by ValWood** [comment]
Original tickets date back to over a year, was reported by @rachhuntley back here https://github.com/geneontology/go-annotation/issues/1487 and by us at various times since.

 The aspect issue does not affect PomBase internally  (and probably others), because we get the aspect from the term (I think).

**Comment by yy20716** [comment]
From my observation, the problematic entry 

> PomBase SPAC1002.15c med6 contributes_to GO:0006357 PMID:10625684 IC GO:0030295 F mediator complex subunit Med6 pmc5 protein taxon:4896 20160908 GOC-OWL has_direct_input(PomBase:SPBC19F8.07),part_of(GO:0006357)

was built based on the entry 

> PomBase SPAC1002.15c  med6 contributes_to  GO:0030295  PMID:10625684 IDA F mediator complex subunit Med6  pmc5  protein taxon:4896  20160908  PomBase has_direct_input(PomBase:SPBC19F8.07),part_of(GO:0006357)

which is from [the source GAF for pombase](http://geneontology.org/gene-associations/submission/gene_association.pombase.gz) (See line 37121). 

As pointed out earlier, this entry is generated in class `FoldBasedPredictor`, which replaces fields in the second entry with direct super classes including default properties such as `part_of` and `occurs_in` (In this example entry, the derived super class was `GO:0006357`). Other fields such as aspect (in this case, `F`) are just [copied into the inferred/predicted entry](https://github.com/owlcollab/owltools/blob/e637b4ccfd700b050880cc80a642ce2ad737e7f7/OWLTools-Annotation/src/main/java/owltools/gaf/inference/FoldBasedPredictor.java#L258), but I guess this should not happen. As @cmungall suggested, we would need some validations before producing the predicted entries and GO Rules can be used for that purpose, but I wonder we have any existing codes that implement GO Rules. 

@cmungall, as you suggested, I created [the google docs](https://docs.google.com/document/d/1KYvcoqbyQwDC2__wk5wUPGrK_oj3G5jVNCYqEimGBEc/edit?usp=sharing) in the tempfile folder of gene ontology group. Could you please advise how to proceed? Thank you.

**Comment by ValWood** [comment]
Hi 

@yy20716 
( I'm Val at PomBase and I'll be bugging you a lot)

1.
GO:0006357  regulation of transcription by RNA polymerase II
the annotation being generated is a "biological process" term. but the aspect is MF
You need to ensure that any term created  the aspect matches the term aspect

2. 
contibutes_to  should not be transferred from MF to BP annotations. contributes_to  is a qualifier that  is only valid  for use with MF annotations

**Comment by yy20716** [comment]
Thank you for your clarification. I believe we may need additional filtering/vadlidation during fold-based prediction process, as Chris suggested. I will first discuss this issue with Chris on Monday. I greatly appreciate your patience and understanding.

**Comment by ValWood** [comment]
Can these checks be brought into the standard GO checks.

The Aspect should always  be correct for the term.
The very first annotation in this file
http://build.berkeleybop.org/view/GAF/job/gaf-check-pombase/lastSuccessfulBuild/artifact/gene_association.pombase.inf.gaf/*view*/

 has the incorrect aspect

PomBase	SPAC1002.15c	med6	contributes_to	GO:0006357	PMID:10625684	IC	GO:0030295	F	mediator complex subunit Med6	pmc5	protein	taxon:4896	20160908	GOC-OWL	has_direct_input(PomBase:SPBC19F8.07),part_of(GO:0006357)	

GO:0006357  regulation of transcription by RNA polymerase II
is a BIOLOGICAL PROCESS term


Also this should not have the "contributes_to" qualifier. I think there is a check for this already, so I don't know why it "passes"

**Comment by pgaudet** [comment]
Hi @ValWood 
This looks like it's not in the current predictions anymore (http://release.geneontology.org/2018-08-09/products/annotations/paint_pombase-prediction.gaf and http://build.berkeleybop.org/view/GAF/job/gaf-check-pombase/lastSuccessfulBuild/artifact/gaf-prediction-report.txt


@yy20716 was the process changed ? 

Thanks, Pascale

**Comment by ValWood** [comment]
This  fileisn't the gaf. It is in the inferred gaf (I don't know what it is!)

The annotation is the the F-P inferences, Inferred FROM  paint.
See the inferred directory in here:
http://build.berkeleybop.org/view/GAF/job/gaf-check-pombase/

**Comment by pgaudet** [comment]
Is this this the GAF ? http://release.geneontology.org/2018-08-09/products/annotations/paint_pombase-prediction.gaf

**Comment by ValWood** [comment]
No, here (another place)
http://build.berkeleybop.org/view/GAF/job/gaf-check-pombase/
gene_association.pombase.inf

(as far as I'm aware this is where we were told the  current files live)

**Comment by pgaudet** [comment]
This server is out of date (@kltm please correct if this is wrong)

**Comment by ValWood** [comment]
@mah11  is this what we use? or have we been told at some point to look elsewhere?

It is certainly what I have bookmarked and I'm sure I would have updated this if there had been a notification?

**Comment by mah11** [comment]
> http://build.berkeleybop.org/view/GAF/job/gaf-check-pombase/
> @mah11 is this what we use? or have we been told at some point to look elsewhere?

There have been a number of comments in the past several weeks indicating that this location is superseded, deprecated, etc. But all have been buried in various comments on tickets, not even all on the same tracker. I don't recall seeing an announcement on the go-announcements tracker or any mailing list.

The current sites, release.geneontology.org and snapshot.geneontology.org, look like they could do with some improvements to their organization and presentation ...

**Comment by ValWood** [comment]
OK maybe I forgot . I think it isn't clear to me which parts of the old poipeline are superceded. I thought we were still waiting for the problems with the  GO checks to iron out before we switched.

Why not flag all the pages we should no longer be using as out of date. Or get rid of them and add forwarding links to the new pages......

**Comment by ValWood** [comment]
So I should never use Jenkins now?

**Comment by ValWood** [comment]
OK I have this 
http://current.geneontology.org/
is this official?
It doesn't look ready for consumption!

**Comment by mah11** [comment]
> http://current.geneontology.org/
> ...
> It doesn't look ready for consumption!

I quite agree

**Comment by ValWood** [comment]
Where are the gaf files?
Where is the inferred gaf? (function process)

**Comment by ValWood** [comment]
There is only one gaf......
This will be really difficult  for checking.

**Comment by ValWood** [comment]
I'm a bit confused not how we use the gaf file data since it is no longer in separate files.

Can we have separate files??

**Comment by cmungall** [comment]
I presented this at the GO meeting, GOC members providing GAFs use this URL for docs: http://wiki.geneontology.org/index.php/Release_Pipeline

**Comment by ValWood** [comment]
OK but I think the confusion is exactly where we are in the procedure  wrt timing. When did we actually finally move from one location to the other and should I  ever use Jenkins now?

I knew that GO was going to inject all of the annotation, but I assumed we would still be able to pick up the separate files for the different sources.

Maybe I am out of the loop because I don't do the Gaf submission, but I still look at the files a lot...

**Comment by ValWood** [comment]
This makes it much more difficult  to  check data from other sources. 
I can't grep -v PomBase because PomBase is used in other fields.....

numbers look a bit weird anyway:

  25 GOC
12642 GO_Central
1144 InterPro
37651 PomBase
2330 UniProt

GOC is "assigned_by" for the F-P links right? Did these disappear? Only 25 seems odd?  But perhaps you now remove the redundant ones? 
(separate files would help us to sanity check these just based on size)


So @pgaudet  the offending annotation may have done away OR all of the annotations may have gone away.

**Comment by cmungall** [comment]
@dougli1sqrd - this is a bug. Should be in one location and stale copies removed

**Comment by ValWood** [comment]
Could you send an announcement to the main  GO list at some point, telling us precisely which locations we should use for 
a) consuming the F_P links and the PAINT data and b) the violations problems

Also, please ensure that the violations  for PomBAse only report the violations derived from the PomBase annotation. The PomBase files I was looking at earlier had all violations (GO_Central and GOC). Although, I would also like to be able to see the other violations so I can assess if the issues I know about are flagged as problems.

 Sorry if this was already communicated and I missed it, but it does not seem that the files are in  the same place as reported in our long ticket on the PomBase tracker. I can no longer find the slides in the google drive if the information is in there. 

Also unexplained is why the current file (If I understood the locations correctly), has only 25 GOC annotations?

**Comment by ValWood** [comment]
I only found out about "current" and "release" today. Previously we were using 
http://snapshot.geneontology.org/annotations/pombase-prediction.gaf
maybe we should migrate to "release"
but the URL for this includes a date so presumably there is a data agnostic location?

**Comment by ValWood** [comment]
ANother old link hanging around that I have been using. I don't even know where I got this from.....

http://build.berkeleybop.org/view/GAF/job/gaf-check-pombase/lastSuccessfulBuild/artifact/gene_association.pombase.inf.gaf/*view*/

but I now see it is 2 months old....

**Comment by pgaudet** [comment]
@ValWood , @kltm has now added messages on the parent pages that 'the job is no longer valid', see 
https://build.berkeleybop.org/view/GAF/job/gaf-check-pombase/

<img width="915" alt="image" src="https://user-images.githubusercontent.com/4782928/44140741-4cccb102-a07b-11e8-8c5e-f6dfe1823137.png">


@kltm would it be possible to remove all the files ? It seems likely people have scripts that download the data; would they notice nothing has changed ?

Thanks, Pascale

**Comment by ValWood** [comment]
OK, I was thinking about this some more. The last place I think we were pointed for  the inference file was 
http://snapshot.geneontology.org/annotations/pombase-prediction.gaf
what is the current location for this file?

We need these files to load into our individual MODs. It doesn't matter  to us if everything ends up in  a single file, but ideally we would still be able to see the inference file somewhere, and we would be able to pick up the most recent version of this file for loading.
Should I open a new ticket for this? or does  a ticket already exist that I can follow?

This ticket was  (originally) about whether the  incorrect annotation to  med6 still exists in the PomBAse gaf (It doesn't). However, I have been unable to establish  whether this is because all of the GOC annotation is not making  it through into the final gaf. I would expect to see more than 25  annotations from the GOC function process inference pipeline. One possibility is that the annotation is still created, but something is broken and the annotations are not making it through to the gaf file. Other explanations could be that this annotation is recognised as being a violation by some rule and discarded (if so this problem still needs to be fixed), OR that the redundant annotation is no longer produced (but even in this case the reported problem would still need to be fixed). 

However,  even if the disappearance of the med6 annotation is due to  any of these explantaiton  I  would still *expect* to see more than 25 annotations in the final gaf. I'd really like to confirm that this is the case. The best way to start would seem to be to find the current  location of the inferred gaf  (@kimrutherford  will also need this file to load into PomBase).

**Comment by ValWood** [comment]
I think the annotation and or the ontology for med6 has changed since the issue was reported.
This does not mean that the underlying problem is fixed. This was just an illustrative example that I selected from many with the same problem.
If you point me to the correct file I can start again with clearer extant examples.

This is a ticket I created in MArch in order to tease out specific issues in the inferred gaf with precise examples, based on an original ticket fron January 2017.
geneontology/go-annotation#1487 (comment)

I am happy to repeat this *If* the issue will be corrected when I report it.

**Comment by pgaudet** [comment]
> http://snapshot.geneontology.org/annotations/pombase-prediction.gaf
what is the current location for this file?

http://snapshot.geneontology.org/products/annotations/paint_pombase-prediction.gaf
(I dont know when it moved).

**Comment by ValWood** [comment]
This is PAINT. I wanted the GO inference pipeline file?

**Comment by pgaudet** [comment]
skype?

**Comment by ValWood** [comment]
OK got it.

http://snapshot.geneontology.org/products/annotations/pombase-prediction.gaf

But I don't see the paint_pombase-prediction.gaf one when I go to the parent directory

**Comment by ValWood** [comment]
OK, you can close this ticket.I see.

I will make sure @kimrutherford Kim is using 
http://snapshot.geneontology.org/products/annotations/pombase-prediction.gaf
and open tickets for any annotation problems.

**Comment by pgaudet** [comment]
OK

I am still unsure that snapshot is the version to use - at least for display on pombase. Yes, its' the most recent, but it's not a stable (citable) version. It sorts of defeats the purpose of having a 'stable monthly release', doesn't it ? 
Also, you'll have different data than AmiGO (but that's probably not a big issue). 

Pascale

**Comment by kimrutherford** [comment]
> I will make sure @kimrutherford Kim is using
> http://snapshot.geneontology.org/products/annotations/pombase-prediction.gaf
> and open tickets for any annotation problems.

Yep, that's the URL we use.

**Comment by ValWood** [comment]
OK but the version we  were pointed to before was not updated since Feb.
Will wait for Chris to point us to the correct location.

Different data from Amigo is an issue, but since we are not consuming PAINT right now  it's a negligible difference to be using an  slightly different version of this file. 
Ideally we would use the stable monthly release for loading.
