### ISSUE TITLE
Access denied message for individual evidence code pages

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-site#582]
From go-ontology:

on the Guide to GO Evidence Codes page, if I click on one of the evidence codes, I get an access denied page.

@sandyl27
Yes, I can replicate this error. I'm going to move this ticket to the go-site tracker, though, since the issue is not related to the ontology.
Thanks for reporting this.

**Comment by vanaukenk** [comment]
@pgaudet 
Perhaps this is related to re-directing the evidence code pages to the wiki?

**Comment by kltm** [comment]
Could I get some example URLs for this?

**Comment by vanaukenk** [comment]
The problem evidence codes seem to be restricted to the top six on the list here:
http://geneontology.org/page/guide-go-evidence-codes

For example:
http://geneontology.org/page/imp-inferred-mutant-phenotype 
http://geneontology.org/page/iep-inferred-expression-pattern

**Comment by kltm** [comment]
Hilarious
Lemme see...

**Comment by kltm** [comment]
Using http://geneontology.org/page/exp-inferred-experiment as the example, it is not `published`. Looking at the Internet archive, it was in the past:
https://web.archive.org/web/20170822175856/http://www.geneontology.org:80/page/exp-inferred-experiment
The only edit since 2013 was @pgaudet a few days ago; I think it was likely unpublished then.

**Comment by kltm** [comment]
Has anybody been trying to apply redirects to these?

**Comment by kltm** [comment]
No redirects show up within the system. I'll go ahead and republish these pages for the time being.

**Comment by kltm** [comment]
All of the recent unpublishing (updates) events within the last couple of months occurred between 03/23/2018 - 02:30 and 03/23/2018 - 05:23, including two pages that are not direct evcode pages: With/From Column Usage and Automatically-assigned Evidence Codes. I'm reverting all changes until we figure out what the procedure is here.

**Comment by kltm** [comment]
Pages can again be accessed. Closing.

**Comment by pgaudet** [comment]
@kltm 
I changed all the links to point to the wiki. Looks like I had not done the top of the page - I'll fix that and re-unpublish the pages on the website.

Next time can you give me at least 24h just to make sure it wasn't an accident ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@kltm 
>  I'm republishing all articles until we figure out what the procedure is here.

I thought the procedure was that Kimberly, David and I were maintaining the site. 

If there is a way to list broken links (so we can fix that) that would be more helpful than re-publishing obsolete pages. Let me know :) 

Thanks ! 

Pascale

**Comment by pgaudet** [comment]
But good idea about the redirect, I'll add that.

**Comment by kltm** [comment]
@pgaudet I was not going rogue here--this was after a discussion about what to do about broken links that were apparently affecting downstream users. ;)
It would be good to understand the changes necessary in this case and to document changes so that we can plan the removal/re-routing of links.

**Comment by mah11** [comment]
Hi,

Will redirects be set up, or should we change links at our end to point to the wiki pages for GO evidence documentation?

@kimrutherford will want to know ...

thanx

**Comment by kltm** [comment]
Also pinging @suzialeksander 
I'm not sure what the roadmap for the evidence code pages looks like.

**Comment by suzialeksander** [comment]
@kltm Thanks for the notice. I was under the impression that EC details would stay on the wiki, so that would seem safest to link to for now, at least until the plan for the new site is solidified, right?

Is there a way we can see how many external sites link to certain URLs through Google analytics or something? If so that may also help me determine which pages to "keep" (a bit off-topic).

**Comment by kltm** [comment]
@suzialeksander If that's what was Decided, that's all good. (I would note that for people trying to link in to it, a "monolithic" page can be useful as it allows people to generate links programmatically (e.g. wiki.go.org/evidence#IEA or wiki.go.org/evidence#ECO:0000123), but I'm generally not as worried about that personally as we are a little more ECO-centric).

For the analytics, they need to be more consolidated. Currently, you should see if you have access to the www.geneontology.org stuff under analytics.google.com; it's under the yeastgenome.org ID.

**Comment by selewis** [comment]
For the ribbon code we're linking here: "http://www.evidenceontology.org/term/XXX"
(where XXX is the ECO id)
Would that be appropriate here?

**Comment by pgaudet** [comment]
@kltm The ECO documentation is up to date: 

on the go website we have a simple page giving an overview: 
http://geneontology.org/page/guide-go-evidence-codes

and each evidence code goes to the full documentation on the wiki. 

Please keep as-is. 

@selewis link to the wiki: (the links can be found in the webpage: http://geneontology.org/page/guide-go-evidence-codes) 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet Not making any changes, just pointing our the uses and use cases for references and how we might want to structure things in the future at some level.

**Comment by pgaudet** [comment]
Fine, sounds good! I just wanted to add the Kimberly, David and I reviewed these pages and decided that we left the appropriate level of information for 'general users', but of course happy to revisit this if you have other suggestions.

**Comment by kltm** [comment]
@pgaudet If these are for "general users", is the eventual idea to migrate these back out to main GO site, away from the wiki, at some point?

**Comment by pgaudet** [comment]
Sorry if that wasn't clear. As its is now is how we thought it should be: 

1. on the go website we have a simple page giving an overview (we do need *some* mention of evidence codes in the general documentation):
http://geneontology.org/page/guide-go-evidence-codes

2- Each code links to the detailed information on the wiki. 
OK for you ? 

Pascale

**Comment by kltm** [comment]
@pgaudet 

Technical hat: whatever works for you here, good as good; at some future point is might be nice to consider ways of making these easily addressable for remote resources that still use three-letter codes and want a link to easy info (although those should hopefully be fewer as time goes on)

Documentation hat: I'm leery of mixing "public" documentation and "internal" documentation, especially without an explicit message that the wiki can get weird and may not be trustable; synchronization issues will be a likely constant issue, something we were hoping to fix with the static "public" documents
For example, at http://geneontology.org/page/guide-go-evidence-codes , I click on http://wiki.geneontology.org/index.php/Inferred_from_Biological_aspect_of_Ancestor_(IBA) ; this page presents me with:
1) a link further into the internal wiki (http://wiki.geneontology.org/index.php/Phylogenetic_annotation_overview); is that and all of its children all "public" documentation that needs to be treated as such?
2) a link to go "Back to: Guide to GO Evidence Codes", which actually goes back to a *different* guide page in the wiki (http://wiki.geneontology.org/index.php/Guide_to_GO_Evidence_Codes). I'm assuming that's a mistake, but it highlights how easy it is to have things fall out of phase if we allow links in to our "internal" flexible wiki documentation.
3) the general wiki links are also available, with no indication that the user should not go further

There may be no easy answers here. In my ideal world, the "public" pages would be relatively few in number and generally geared towards new users and getting novices up to a starting speed to be able to ask good questions. After that, pointing people into the wiki with caveats may be the right choice, but cross-linking presents problems.

**Comment by pgaudet** [comment]
@kltm I am not clear exactly what you are asking: 

- would like you the website NOT to link to the wiki at all (ideally?) ? 
- it also sounds like you want to minimize the internal links (as you as in point 1) 
> is that and all of its children all "public" documentation that needs to be treated as such?

No, we link to the wiki, so that's internal. 

I feel I am missing the big picture here- we have been implemented what we understood to be the decision at the Docathon. Perhaps the best is to discuss this in LA in a couple of weeks ? 

Thanks, Pascale

**Comment by vanaukenk** [comment]
@mah11 - does PomBase link out to evidence code documentation mainly for guidance for your community curators, or more as a general service to any user who is interested?

**Comment by mah11** [comment]
re @vanaukenk 

> does PomBase link out to evidence code documentation mainly for guidance for your community curators, or more as a general service to any user who is interested?

Both, although it's likely that those of our users who do the community curation thing are more interested and read such documentation more than those who don't. Even for non-curating users, we want to link our displayed evidence codes to some explanation of what they mean.

Although we're still using the three-letter evidence codes for GO at present, I'm not so fussed about whether the documentation, and linking to it, is based on the three-letter codes or ECO IDs. We would appreciate having specific links for the different codes/ECO terms, rather than one generic link.

We do use ECO more directly for some annotation types, and have mappings between other evidence sets (e.g. our phenotype evidence) and ECO.

**Comment by pgaudet** [comment]
@cmungall That may meet some use cases; but we do want GO-centric documentation describing how we use the evidence codes.

**Comment by vanaukenk** [comment]
@mah11  Thanks for the feedback. 

@cmungall The evidence code pages on each of our GO wiki pages alread contains a link out to the corresponding ECO page.  Should this be more prominent, i.e. on geneontology.org ?

As @pgaudet says, we have different use cases here - the biologist or bioinformatician that may just want a birds-eye view of evidence codes and the gory details for curators on how to apply them for annotation.

**Comment by pgaudet** [comment]
@kltm How do I apply redirects in Drupal ? 
I can redirect to that page; I dont know how to redirect a specific page elsewhere. 

Thanks, Pascale

**Comment by kltm** [comment]
Can you describe the the exact redirect that you're wanting?

**Comment by pgaudet** [comment]
Redirect the GO website pages for individual ECOs 
-> the corresponding wiki pages.

**Comment by kltm** [comment]
Is this as a bandaid on the current site, or intended as a longer solution. I believe we do not want the general public going to the wiki. For example: https://github.com/geneontology/go-site/issues/582#issuecomment-413321542

**Comment by pgaudet** [comment]
We do want the wiki to be accessible for the public. What we wanted was general, simple documentation on the website, and if users want additional details, they are directed to the wiki. 
This is how @vanaukenk @ukemi and I have been writing up the documentation. 

Is this not possible? 

Thanks, Pascale

**Comment by kltm** [comment]
We can do anything; if you give me a list of exact redirects, we can start putting those in to the old site.
I want to confirm that the inconsistencies in the wiki (enumerated in my comment above) are really worrying from the perspective of users coming in. I just want to make sure that we are okay with exposing what we currently have there.

**Comment by pgaudet** [comment]
@kltm We added links back to the GO website (ECO overview page) on all the individual wiki pages for each ECO. 

**Redirects needed:** 

http://geneontology.org/page/automatically-assigned-evidence-codes -> http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)
http://geneontology.org/page/ic-inferred-curator -> http://wiki.geneontology.org/index.php/Inferred_by_Curator_(IC)
http://geneontology.org/page/nas-non-traceable-author-statement -> http://wiki.geneontology.org/index.php/Non-traceable_Author_Statement_(NAS)
http://geneontology.org/page/tas-traceable-author-statement -> http://wiki.geneontology.org/index.php/Traceable_Author_Statement_(TAS)
http://geneontology.org/page/ird-inferred-rapid-divergence -> http://wiki.geneontology.org/index.php/Inferred_from_Rapid_Divergence(IRD)
http://geneontology.org/page/rca-inferred-reviewed-computational-analysis -> http://wiki.geneontology.org/index.php/Inferred_from_Reviewed_Computational_Analysis_(RCA)
http://geneontology.org/page/ikr-inferred-key-residues -> http://wiki.geneontology.org/index.php/Inferred_from_Key_Residues_(IKR)
http://geneontology.org/page/ibd-inferred-biological-aspect-descendent -> http://wiki.geneontology.org/index.php/Inferred_from_Biological_aspect_of_Descendant_(IBD)
http://geneontology.org/page/iba-inferred-biological-aspect-ancestor -> http://wiki.geneontology.org/index.php/Inferred_from_Biological_aspect_of_Ancestor_(IBA)
http://geneontology.org/page/igc-inferred-genomic-context -> http://wiki.geneontology.org/index.php/Inferred_from_Genomic_Context_(IGC)
http://geneontology.org/page/ism-inferred-sequence-model -> http://wiki.geneontology.org/index.php/Inferred_from_Sequence_Model_(ISM)
http://geneontology.org/page/isa-inferred-sequence-alignment -> http://wiki.geneontology.org/index.php/Inferred_from_Sequence_Alignment_(ISA) 
http://geneontology.org/page/iso-inferred-sequence-orthology -> http://wiki.geneontology.org/index.php/Inferred_from_Sequence_Orthology_(ISO)
http://geneontology.org/page/iss-inferred-sequence-or-structural-similarity -> http://wiki.geneontology.org/index.php/Inferred_from_Sequence_or_structural_Similarity_(ISS)
http://geneontology.org/page/iep-inferred-expression-pattern -> http://wiki.geneontology.org/index.php/Inferred_from_Expression_Pattern_(IEP)
http://geneontology.org/page/igi-inferred-genetic-interaction -> http://wiki.geneontology.org/index.php/Inferred_from_Genetic_Interaction_(IGI)
http://geneontology.org/page/imp-inferred-mutant-phenotype -> http://wiki.geneontology.org/index.php/Inferred_from_Mutant_Phenotype_(IMP)
http://geneontology.org/page/ida-inferred-direct-assay -> http://wiki.geneontology.org/index.php/Inferred_from_Direct_Assay_(IDA)
http://geneontology.org/page/ipi-inferred-physical-interaction -> http://wiki.geneontology.org/index.php/Inferred_from_Physical_Interaction_(IPI)
http://geneontology.org/page/exp-inferred-experiment -> http://wiki.geneontology.org/index.php/Inferred_from_Experiment_(EXP)

**Comment by kltm** [comment]
Bleh. We'll need redo this as (preferably) redirect pages in the new site as well.
Doing as 302s for now.

**Comment by kltm** [comment]
I think I got them all; there should be a cache refresh for these pages 6hrs from now.

**Comment by pgaudet** [comment]
Looks ok to me.
