### ISSUE TITLE
Clean up no longer active entries in db-xrefs.yaml

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#583]
Looks like PAMGO_MGG is dead

https://github.com/geneontology/go-site/blob/63d6a860146faedaa864a87ff5650628ecf51ba3/metadata/db-xrefs.yaml#L2000-L2010

The URLs don't work. I propose we keep the metadata but add is_obsolete: true

We could have a simple periodic check where we test all example URLs

As an aside I notice that we have a second database for the same organism

https://github.com/geneontology/go-site/blob/63d6a860146faedaa864a87ff5650628ecf51ba3/metadata/db-xrefs.yaml#L212-L222

This one is marginally better. The URL redirects to a generic database page, not to the object.

I bet @tonysawfordebi has done his own QC here, would be good to coordinate.

**Comment by pgaudet** [comment]
Removed 
- [x] BIOSIS
- [x] Broad Institute
- [x] Broad_MGG
- [x] Broad_NEUROSPORA
- [x] ecogene (offline, see https://bio.tools/ecogene) 
- [x] GDB (see #619;  (annotations now hosted at EBI)) 
- [x] GRIMS
- [x] ISRR
- [x] JCVI
- [x] JCVI_CMR
- [x] JCVI_EGAD
- [x] JCVI_GenProp
- [x] JCVI_Medtr
- [x] JCVI_REF
- [x] TIGR (except for TIGR_FAM, for which I updated the URLs)
- [x] TIGR_CMR
- [x] MENGO (annotations now hosted at EBI)
- [x] MTBBASE  (annotations now hosted at EBI (last updated 2012)
- [x] NMPDR: Redirects to https://www.patricbrc.org/
- [x] PAMGO
- [x] PAMGO_GAT
- [x] PAMGO_MGG 
- [x]  PAMGO_VMD
- [x]  PINC
- [x]  Roslin_Institute
- [x]  SFLD: "SFLD is offline, please visit http://sfld.rbvi.ucsf.edu for the static archive version" 
- [x] SPTR
- [x] SUBTILIST
- [x] SUBTILISTG
- [x] SWALL
- [x] Swiss-Prot (add as a synonym of UniProt)
- [x] TrEMBL (add as a synonym of UniProt)
- [x] UniGene
- [x] VBRC
- [x] VEGA

- Pascale

**Comment by pgaudet** [comment]
- [ ] http://bioinformatics.ustc.edu.cn/locsvmpsi/locsvmpsi.php  -> not maintained, see https://omictools.com/locsvmpsi-tool
 - [ ] ProDom (not maintained for several years; not in InterPro anymore) 
 - [ ] https://www.ebi.ac.uk/IPI

**Comment by pgaudet** [comment]
- [x]  IMP http://imp.princeton.edu/ -> access forbidden

**Comment by pgaudet** [comment]
PR https://github.com/geneontology/go-site/pull/1322

- [x] OBO_REL: Duplicate of RO
- [x] UniMOD: restricted access
