### ISSUE TITLE
Pipeline should only load IBAs (PAINT) annotations that come from GO_Central

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#587]
(I'm moving out some of the items from #581)

The valid source for PAINT annotations are the URLs in the paint.yaml file. Currently we have annotations that have been ingested into the MODs. We don't want to bring these in to GO Central.

The procedure for eliminating these is to check the reference column for GAFs that come from PAINT (`PAINT_REF:`). These should be removed (unless this is an actual paint_<xx> file being merged in).

**Comment by cmungall** [comment]
It may be more complex, as some MODs may change the ID when they bring in from PAINT

Can group representatives confirm below what they use?

 * [ ] SGD: SGD_REF:S000185201 @suzialeksander

**Comment by vanaukenk** [comment]
@cmungall 
Our PAINT pipeline looks like this:
PAINT -> Protein2GO -> WB -> GOC
I checked older gpad files that we get from Protein2GO and at some point in mid-March (unfortunately I am missing one week, so I can't tell you the exact dates) the reference for PAINT annotations switched from GO_REF:0000033 to PAINT_REF:nnnnn.
Unfortunately, this happened right after I'd just done a file upload for our next WB build.
I was planning to change our parsing script to use the PAINT_REF for our next upload in mid-May.
Is this the desired way to deal with this?

**Comment by pgaudet** [comment]
Shouldn't we have 
PAINT -> GOC? (like Paul was proposing for InterPro?) and then filtering can occur at individual databases as needed? 

Thanks, Pascale

**Comment by cmungall** [comment]
We do merge paint annotations in at goc. This ticket is about the other path the annotations take through MODs. We are trying to block this when we bring in MOD data. Do you want to make a separate ticket about having the MODs pull from GOC rather than PAINT?

**Comment by cmungall** [comment]
@vanaukenk for now I'd like to just collect all possible references used to indicate a PAINT annotation so we can be sure we are filtering everything

**Comment by cmungall** [comment]
@pgaudet - that's much simpler, I like it!

It's actually a stronger filter, in that if a group goes rogue and starts making their own IBAs, we will filter these out. I assume we regard this as a feature and not a bug, since we want to rigorously control how propagated annotations come into GO Central.

@dougli1sqrd - over to you now

Aside: it is quite interesting how everyone ended up representing imported PAINT annotations so differently

**Comment by nathandunn** [comment]
@cmungall   This will help with these? https://github.com/geneontology/amigo/issues/485#issuecomment-382225499

**Comment by cmungall** [comment]
@nathandunn - I'm unsure of the relevance of that ticket to this one

**Comment by nathandunn** [comment]
@cmungall  If you remove everything that has `PAINT_REF:`  as a reference it might fix the problems we are having with IDs not showing up at all.

**Comment by cmungall** [comment]
We are not getting rid of PAINT_REF. We are getting rid of redundant PAINT annotations that have been ingested into the MODs

**Comment by nathandunn** [comment]
K.  Unlikely that the removed refs will be the same as the bad refs.

**Comment by cmungall** [comment]
@pgaudet @dougli1sqrd it strikes me we should have a formal codified rule about this?

**Comment by vanaukenk** [comment]
Hi,
I am gearing up to parse a new C. elegans annotation file from GOA for our next WB data upload, and want to make extra certain about what will happen with the PAINT annotations.
Our current gpad file from GOA includes PAINT annotations with PAINT_REFs that use the IBA evidence code.  I am planning to include these in the WB upload (otherwise we will not get the annotations in WB, at least for now), but my understanding is that once these annotations make their way to GO, the IBA and IDB annotations will be filtered out and instead replaced by the latest PAINT annotations from the PAINT/Panther database.  Is that correct?

**Comment by hattrill** [comment]
Our load from GOA just dropped all the IBAs because of the new PAINT_REF.

Could GO please make sure that MODs are tagged when we need to do something? We also have several mailing lists that can be used.

We need to figure out how to handle these - it's not trivial.

**Comment by pgaudet** [comment]
I thought this change had been made long before. 

@cmungall should we revert for now and give people some notification so they adapt their parsers ? 

Thanks, Pascale

**Comment by tonysawfordebi** [comment]
To be fair, this is not totally a PAINT thing...

What used to happen was that our import pipeline used to transform the PAINT_REFs that it found in the PAINT annotations to GO_REF:0000033 (not entirely sure why - before my time, I think), but I discovered - purely by chance - a few weeks ago that GO_REF:0000033 is now obsolete, so I modified our pipeline to pass through the PAINT_REFs unchanged.

**Comment by cmungall** [comment]
@pgaudet
> I thought this change had been made long before.

correct, as Tony explained this only surfaced recently as the GOA step in the dataflow stopped transforming these.

> should we revert for now and give people some notification so they adapt their parsers ?

I think the answer is no, since @hattrill / FlyBase do not currently pick up PAINT annotations from GO Central anyway.

Overall we need to simplify the overall dataflow, there are too many exchanges with too many things that happen along the way. We will discuss at the NYC meeting.

My current best attempt to document the overall consortium dataflow:

https://raw.githubusercontent.com/geneontology/go-site/master/docs/go-consortium-dataflow.png

**Comment by cmungall** [comment]
@dougl1sqrd where are we with this? cc @kltm

**Comment by pgaudet** [comment]
@cmungall Can we bump up the priority on this ? I would be tempted to say 'blocker'. Can this be done for the June release ?

**Comment by cmungall** [comment]
Just to be absolutely clear about what the specific requirement is, here it is:

IF the evidence code is IBA
AND the file is NOT a paint_xxx file
THEN remove the annotation

Note that IBD is not relevant here as no source other than PAINT should have IBDs.

**Comment by suzialeksander** [comment]
I also second Sabrina's apologies, I'm trying to catch up on GH tickets this week. Not sure if this matters at this point:

I've asked about the PAINT annotations we load, and we don't change any information from the gpad. Is that what the question was?

**Comment by cmungall** [comment]
@sabrinatoro @suzialeksander it's OK. The original idea was to remove the stale PAINT annotations based on the reference field. This required collecting details from everyone on what ID they used. We then thought it would be simpler if we just bake in the assumption that if it's an IBA it's "owned" by PAINT, and we just filter based on this criteria.

So there is no longer any need for curators to do anything now, Eric is working on the changed code today.

(nevertheless I find it's useful to hear the details of everyone's pipeline, this is something we need to do a better job of documenting in GO Central)

**Comment by pgaudet** [comment]
One more point: we need to deal with IKR the same way. 
(IRD should not be propagated so they shouldn't appear in the files). 

Pascale

**Comment by selewis** [comment]
But there shouldn't be any more IKR lefts should there? Or do you think
some of the MODs still have this ancient ECO? Can't hurt I suppose.

**Comment by cmungall** [comment]
You can check annotations to IKR in AmiGO

![image](https://user-images.githubusercontent.com/50745/40566659-c7194d84-603f-11e8-8d91-7efe8f309f13.png)

Unfortunately the situation is complicated here.

I do not think that all of these originated in PAINT, hence it may be problematic to filter them.

For example, this paper was curated by pombase curators, and involved asserting an IKR
http://amigo.geneontology.org/amigo/reference/PMID:14643670
(@ValWood can you confirm? This is the only IKR in your database)

The evidence documentation suggests that this can be used by non-PAINTers:
http://wiki.geneontology.org/index.php/Inferred_from_Key_Residues_(IKR)

If we do want to filter the majority of these, then we have to go back to the strategy of doing this by reference field, which means we have to go back to collating how everyone rewrites the original PAINT reference so we can reliably filter.

Here is what we will do: for this forthcoming release, we will only filter non-PAINT IBAs, as I specified above.

```
IF the evidence code is IBA
AND the file is NOT a paint_xxx file
THEN remove the annotation
```

This is because we have a long weekend and we need to get a fix out that addresses the stale IBAs, which are the main issues.

Then immediately after we will create a more robust solution that will likely have to make use of a mix of reference IDs rather than baking in assumptions about who uses which evidence code.

**Comment by cmungall** [comment]
We should also document in this page that IBA is reserved for PAINTers: http://wiki.geneontology.org/index.php/Inferred_from_Biological_aspect_of_Ancestor_(IBA)

**Comment by dougli1sqrd** [comment]
https://github.com/biolink/ontobio/pull/181

**Comment by ValWood** [comment]
IKR predates PAINT.

I'd be happy to change this  annotation if it helps.... (it's a NOT annotation, based on sequence similarity the authors infer that the enzyme is an adenine deaminase not an  adenosine deaminase.
if we want to  block it for  manual annotation I can make this TAS...

**Comment by cmungall** [comment]
FlyBase also use this code directly, for example to annotate 50 NOTs on this sequence analysis paper:

http://amigo.geneontology.org/amigo/reference/PMID:12568721

Or this paper that demonstrates how AIF lost the residues required for DNA binding in Dmel:

http://amigo.geneontology.org/amigo/reference/PMID:18309327

Also other valid non-PAINT IKRs for other species.

So we should not handle IKRs the same way we handle IBAs

**Comment by selewis** [comment]
Some are PAINT annotations, as this was the original impetus, but Key
Residues is useful more generally. In PAINT it's used to specify the reason
for a loss of function in evolution. Curators examine the MSA and see that
the an active site is missing (for example). The other rationale for a
negation in paint is branch length, but I can't remember the evidence code
used for that. I can look it up.

**Comment by pgaudet** [comment]
Right - I know that some people have annotated it as an experimental code, and I agree that's useful; however in PAINT (and in ECO), it is under 'phylogenetic evidence': "phylogenetic determination of loss of key residues evidence used in manual assertion"
https://www.ebi.ac.uk/ols/ontologies/eco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FECO_0000320

So I think it should be limited to the annotations derived from PAINT. We could create a new evidence code for the other types of evidence like inferred from sequence dissimilarity (?), although NOT by IDA or by ISS seems acceptable as well. 

Is this too strict ? 
Pascale

**Comment by hattrill** [comment]
This is the current GOC doc for IKR:
http://wiki.geneontology.org/index.php/Inferred_from_Key_Residues_(IKR)

ECO definition seems quite vague. One instance divergent from the rest of tree or divergence of whole branch?

**Comment by kltm** [comment]
Talked to @dougli1sqrd , apparently closed https://github.com/biolink/ontobio/issues/195
