### ISSUE TITLE
Roll out GAF2.1.1 to end-users

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#589]
At first GAF2.1.1 will be rolled out within GOC. Relations will be submitted to GOC via GAF (or GPAD). At first we will mask these in the output GAF, to avoid breaking pipelines.

After sufficient lead time we will release main GAFs in 2.1.1

**Comment by tonysawfordebi** [comment]
GAF2.1.1? What's that all about, then?

**Comment by tonysawfordebi** [comment]
OK - so do we yet know what the allowable additional relations will be, and what rules will govern their usage?

**Comment by cmungall** [comment]
#553

**Comment by pgaudet** [comment]
Abandonned for GAF2.2
