### ISSUE TITLE
Deprecate or fix 'other file downloads'

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#59]
http://geneontology.org/page/other-file-downloads

This is very misleading. See: 
http://jira.geneontology.org/browse/GO-797

This page needs to be deleted or either severely refactored.

We want anything related to the ontology to be on this page
http://geneontology.org/page/download-ontology

**Comment by rbalakri** [comment]
Hi,
looks like the files related to obsolete IDs, alt_ids are not created routinely. I am going to get rid of them from this page.

Rama

**Comment by rbalakri** [comment]
Done. I removed links to those files.

Rama

**Comment by cmungall** [comment]
I updated the link to ECO
