### ISSUE TITLE
GPAD version header incorrect in files generated from Noctua models

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-site#593]
The GPAD files in https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/ have the header "!gpa-version: 1.2"; this should be "!gpa-version: 1.1"

**Comment by kltm** [comment]
@balhoff 
Would this be something that you could take a look at?

**Comment by balhoff** [comment]
I think this is @cmungall's collator script. If I find the right spot I'll try to fix.

**Comment by balhoff** [comment]
Oh I see this is in both that script and also the Minerva output. I must have copied this from the previous Minerva code.

**Comment by balhoff** [comment]
Okay, updated in Minerva now, and also in a [noctua-models PR](https://github.com/geneontology/noctua-models/pull/83). @kltm will need to coordinate merge with Minerva backup.

**Comment by kltm** [comment]
@balhoff @tonysawfordebi 
I've merged these and I believe that this should be cleared on the next run.
