### ISSUE TITLE
Twitter feed on front page is repeating the same tweets

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#60]
May be happening when something is retweeted multiple times, as is currently the case with Andrew Su's tweet about DAVID

**Comment by kltm** [comment]
For the record, http://geneontology.org, twitter widget in the lower right.

Yup--retweets all the way down. With the blessed widget, the search is for "#geneontology OR @news4go", with no other filtering possible.

However, I've turned on "Only show top Tweets", which seems to have cut down on a lot of the noise, but at a mysterious cost.
