### ISSUE TITLE
Example link for VEGA does not resolve in AmiGO

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#61]
The example link for VEGA does not resolve in AmiGO. This is from GO Helpdesk issue:

 http://jira.geneontology.org/browse/GO-836

The response Harold got from a direct VEGA request:

```
The best URL to use would be:
http://vega.sanger.ac.uk/id/*your id*

eg
http://vega.sanger.ac.uk/id/OTTMUSP00000061838
This will jump you to the relevant page for that kind of ID, whatever ID type
it happens to be.
```

**Comment by kltm** [comment]
* db-xrefs.yaml needs to be updated
* amigo needs to have its metadata refreshed

**Comment by kltm** [comment]
Looks good at: http://amigo2.berkeleybop.org/amigo/search/annotation?q=*:*&fq=annotation_extension_class_closure_label:%22receptor%20cell%22&sfq=document_category:%22annotation%22

**Comment by kltm** [comment]
@kkarra It looks like the metadata has been fixed for this. All production should need to get this is rerunning the install job on the frontends, e.g.:
```shell
make install
```
It should be considered fixed if the VEGA links resolve on pages like:
http://amigo.geneontology.org/amigo/search/annotation?q=*:*&fq=annotation_extension_class_closure_label:%22receptor%20cell%22&sfq=document_category:%22annotation%22

**Comment by kkarra** [comment]
Fix in production
