### ISSUE TITLE
GAF check failure

### ISSUE THREAD

**Issue by mah11** [geneontology/go-site#610]
The latest PomBase GAF submission has failed Jenkins checks, apparently for lack of space.

http://build.berkeleybop.org/job/gaf-check-pombase/139/consoleFull includes this gem:

    ERROR: Failed to check out svn+ssh://ext.geneontology.org/share/go/svn/trunk/gene-associations
    org.tmatesoft.svn.core.SVNException: svn: E204899: No space left on device

so it seems to be out of our hands.

**Comment by kltm** [comment]
@mah11 This should be fine now and should run as normal next time around.

Note to self: `svn cleanup`
