### ISSUE TITLE
Issues with GPADs generated from Noctua models

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-site#613]
I've just grabbed the latest batch of Noctua-generated GPADs from https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/ and run them through our syntax checker.

The resulting log file is attached to this ticket.

[syntax_check.log](https://github.com/geneontology/go-site/files/1920122/syntax_check.log)

**Comment by vanaukenk** [comment]
Thanks @tonysawfordebi 

@ukemi and I will take a look with @balhoff to work on addressing these issues in the GPAD output.

**Comment by vanaukenk** [comment]
Note that there is more to the syntax check than just rules for the GPAD output.  
If needed, I will make tickets elsewhere to address other issues.

**Comment by vanaukenk** [comment]
@tonysawfordebi 
Thanks again for sharing the syntax check for the Noctua GPAD files.

David, Jim, and I went over the report and will work on implementing additional checks to catch some of these errors.

Wrt the 'unsupported qualifier', the list of new qualifiers that will be allowed will be:

acts upstream of or within (RO:0002264)
acts upstream of or within, positive effect (RO:0004032)
acts upstream of or within, negative effect (RO:0004033)
acts upstream of (RO:0002263)
acts upstream of, positive effect (RO:0004034)
acts upstream of, negative effect (RO:0004035)

One thought we had when discussing the new qualifiers was whether it might actually be better to use RO identifiers in Column 3 (and also in annotation extensions), rather than the term label.  Annotation extensions would also require using some GOREL ids, as well.  We thought this might potentially avoid having strings like this in Column 3:

acts_upstream_of_or_within,_positive_effect

Any thoughts on that proposal?

Tagging @cmungall here, too, to get his thoughts.

Thx.

**Comment by tonysawfordebi** [comment]
Kinda makes sense - we use GO & ECO IDs rather than labels, so it would at least be consistent with those. It wouldn't, however, be consistent with how annotation extensions are formulated.

Also, would you then have things like "NOT|RO:nnnn"?

**Comment by ukemi** [comment]
We were also wondering if these were not allowed because of the underscores or if they were not incorporated into the rules yet. In MGI we take them exactly as they are output in the GPAD file. I simple added them as allowed values with a little tweak for the inclusion of the comma.

**Comment by vanaukenk** [comment]
Yes, we also thought it was more consistent with using GO and ECO IDs.

If we did this for extensions then, yes, they would go from:

happens_during(WBls:0000109),occurs_in(WBbt:0005190)

to:

RO:0002092(WBls:0000109),BFO:0000066(WBbt:0005190)

and yes, wrt Column 3 we might then have things like:

"NOT|RO:nnnn"

unless @cmungall has another thought about that.

**Comment by cmungall** [comment]
In GPAD the relations are already strings. We could increment the version?

To a developer, `acts_upstream_of_or_within,_positive_effect` looks a bit odd, we have the underscores to make it more tokenizable friendly but then we add a `,`...

**Comment by ukemi** [comment]
I've already given our software group that the commas may be going. So as long as I give them the heads-up, we are ok with it.

**Comment by vanaukenk** [comment]
+1 for incrementing the gpad version and using a numerical relation ID wherever possible

**Comment by tonysawfordebi** [comment]
If we're going to go down the numerical ID route (which I think is probably A Good Thing, at least as far as the files are concerned), how does this fit with [553](https://github.com/geneontology/go-site/issues/553)? Should we abandon the minor-minor-version increment and introduce gaf-version: 2.2 alongside gpa-version: 1.2 to indicate that a) additional relations are now valid in the qualifier column, and b) all relations are now identified by IDs rather than labels?

Should we add discussion of this to the agenda for the NY meeting?

Tagging @alexsign so that he's aware of this thread...

**Comment by tonysawfordebi** [comment]
@ukemi - (assuming that [your comment](https://github.com/geneontology/go-site/issues/613#issuecomment-383954223) was directed at me...) the reason that our parser throws the "unsupported qualifier" error is simply because it hasn't yet been updated to recognise the extended set of valid gene product-to-GO term relations.

We've been holding off doing anything until we had an agreed and approved list (and the rules that govern their usage), but it looks like we're pretty much at that stage now, so we can plough on with updating our parser & everything else that this affects.

**Comment by ukemi** [comment]
If we are going to go down the numerical route, I will need to let our software group know ASAP. We have already almost implemented the loads using the current specs with the term strings. I suspect this change will require a bit of work for us translating the numerical identifiers to meaningful strings to display on our web pages, especially for annotation extensions.

**Comment by tonysawfordebi** [comment]
Absolutely, @ukemi - it will cause **MAHOOSIVE** upheaval for us, and is not something that we'd be able to roll out quickly, **but** I do think that it's probably worth doing.

**Comment by tonysawfordebi** [comment]
Based on what has been said above, plus earlier discussions somewhere else (can't remember where), I reckon that this is the set of relations that we might expect to see in the qualifier column in future (GO Class is the class of GO terms with which the relation is valid):

ID|Label|GO Class
--|-----|--------
RO:0002327|enables|GO:0003674
RO:0002331|involved_in|GO:0008150
BFO:0000050|part_of|GO:0005575
RO:0002325|colocalizes_with|GO:0005575
RO:0002326|contributes_to|GO:0003674
RO:0002263|acts_upstream_of|GO:0008150
RO:0004034|acts_upstream_of_positive_effect|GO:0008150
RO:0004035|acts_upstream_of_negative_effect|GO:0008150
RO:0002264|acts_upstream_of_or_within|GO:0008150
RO:0004032|acts_upstream_of_or_within_positive_effect|GO:0008150
RO:0004033|acts_upstream_of_or_within_negative_effect|GO:0008150
RO:0002428|involved_in_regulation_of|GO:0008150
RO:0002429|involved_in_positive_regulation_of|GO:0008150
RO:0002430|involved_in_negative_regulation_of|GO:0008150
RO:0002431|involved_in_or_involved_in_regulation_of|GO:0008150

How does that all look? Any glaring errors or omissions? And, more to the point, is there anything in that list that now shouldn't be?

**Comment by ukemi** [comment]
Yes. I believe that is correct.

**Comment by tonysawfordebi** [comment]
Thanks, @vanaukenk

**Comment by tonysawfordebi** [comment]
I just grabbed the latest set of GPADs and ran them through our checker, and there still seem to be quite a few issues; see the attached log file for details.

[syntax_check_noctua_all.log](https://github.com/geneontology/go-site/files/2097699/syntax_check_noctua_all.log)

**Comment by balhoff** [comment]
@tonysawfordebi how are the valid ranges determined? For example the second error is about a `tissue development` that `has output` a `white adipose tissue`. That sounds good to me.

**Comment by vanaukenk** [comment]
@balhoff - in gorel there are property values that specify domain and range.  For example, has_output has these property values:

property_value: local_domain BFO:0000015 xsd:string
property_value: local_range "CHEBI:24431 GO:0032991 MI:0315 PR:000000001 SO:0000673 SO:0000704 CHEBI:33697" xsd:string

So UBERON or CL terms are not included in the local_range for has_output.

These are checks that I think we should be trying to catch upstream of Tony retrieving the file, either within Noctua or as part of the QA/QC on the overall annotation file pipeline.

**Comment by vanaukenk** [comment]
Perhaps in some of these cases, the correct relation to use would be 'results in development of'.
@ukemi would need to take a look at these models again to see if that's the intended meaning.

**Comment by tonysawfordebi** [comment]
@vanaukenk is there any "how to use this relation" documentation for the new set of qualifier relations? I'd like to include some documentation links in P2G, but all I've found so far is the purls (e.g., http://purl.obolibrary.org/obo/RO_0004034) which lead to the formal definitions of the relations, but aren't exactly curator-friendly...

**Comment by vanaukenk** [comment]
@tonysawfordebi 
I think the safest place to link right now for documentation is this category page on the GO wiki:
http://wiki.geneontology.org/index.php/Category:Gene_Product_to_Term_Relations

**Comment by tonysawfordebi** [comment]
Thanks @vanaukenk

**Comment by tonysawfordebi** [comment]
Has something change in the past few days regarding the way that GPADs are exported from Noctua? For example, uniprotkb.gpad has shrunk from around 4MB to about 300K, and the number of annotations attributed to SynGO has plummeted from c. 15000 to c. 1000.

**Comment by cmungall** [comment]
Jul 18 https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/634/artifact/legacy/

![image](https://user-images.githubusercontent.com/50745/43089026-80d23196-8e58-11e8-8b27-2cfb27141571.png)

Jul 20 https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/643/artifact/legacy/

![image](https://user-images.githubusercontent.com/50745/43089080-a37dbb20-8e58-11e8-8eb5-900bdfc17b9d.png)

This is consistent with changes @dustine32 made to map SynGO mouse to MGI IDs. MGI has gone up considerably (cc @ukemi), reflecting the fact that mouse syngo annotations go here. Similar for RGD.

Side note: we need to coordinate with RGD to have these RGD annotations picked up

**Comment by dustine32** [comment]
Thanks @cmungall !

**Comment by ukemi** [comment]
@hdrabkin noticed that there are annotations coming through in gafs that have the new qualifiers. I am tagging him here to explain their source etc.

**Comment by hdrabkin** [comment]
So we load gafs fro GOA (GOA mouse or GOA-human); any annotations with the new qualifiers are being rejected, as they are NOT expected in the gafs at this time. At the moment all of them are SynGO annotations. 
Our mgi.gpad we get from Noctua has not gone up, but I see that we haven't had a new load file since  2018-07-19 (thursday).

**Comment by tonysawfordebi** [comment]
@hdrabkin I've now fixed the issue regarding the rogue qualifiers and generated a new set of species-specific files, which are all available from the GOA ftp site (ftp://ftp.ebi.ac.uk/pub/databases/GO/goa)

**Comment by ukemi** [comment]
@tonysawfordebi and @hdrabkin, If you aren't consuming the MGI GPAD already, I'm not sure you need to change your pipeline. If I understand correctly, the murine SynGO annotations that are coming through GO-CAM models are being added to the MGI GPAD file, which we pick up and load at MGI. Those annotations will be exported in our gaf. The thing that @hdrabkin needs to check is that the attributions are coming through correctly.

**Comment by tonysawfordebi** [comment]
The thing is, @ukemi, because of the way that our pipelines (and database) work, when we load the MGI file, we only process annotations that are attributed to MGI. I've also subsequently discovered that there are SynGO annotations in the RGD, FB, and WB Noctua GPADs, so pretty much the easiest thing all round is to slurp up all of the Noctua GPADs and extract all the SynGO goodness from all of them.

BTW, I haven't yet switched to using the MGI GPAD rather than the GAF, because we see fewer errors (and hence end up with more annotations) from the GAF than the GPAD. Would you be interested in seeing the reports from our checker for both files?

**Comment by ukemi** [comment]
I'd be particularly interested in seeing what annotations are in the gaf that are being filtered out of the gpad file. Based on the way we created our gpad, the files should be basically the same unless there is a systematic error we missed.

**Comment by tonysawfordebi** [comment]
OK - give me a few minutes and I'll generate some reports

**Comment by tonysawfordebi** [comment]
I'm having problems running the checker over the GAF at the moment, but in the meantime here's the log file from the GPAD check:
[syntax_check-GPAD.log](https://github.com/geneontology/go-site/files/2223807/syntax_check-GPAD.log)

**Comment by hdrabkin** [comment]
Thanks Tony
Now I wonder if the syngo that are now appearing in our Noctua GPAD are duplicated in your gaf?
We will see on the next GOA gaf loads this weekend.

Harold

**Comment by tonysawfordebi** [comment]
OK, the (EBI load balancer-related) problems have been resolved, which means I've been able to run the MGI GAF through our checker. Here's what it had to say:
[syntax_check-GAF.log](https://github.com/geneontology/go-site/files/2223957/syntax_check-GAF.log)

**Comment by ukemi** [comment]
@hdrabkin, we need to identify which annotations are failing the checker in GPAD that are not failing in GAF and why.

**Comment by hdrabkin** [comment]
I don't think we need to worry about the NDs that give 'unmapped identifiers' ; These have no UniProt mappings at MGI either; mostly refseqs. 
annotations using secondary ids will usually go away on the next GO load, unless they are in a qualifier, which we have (??) a check for.

**Comment by tonysawfordebi** [comment]
I'll have a crack at working out which annotations we load from the GAF but not from the GPAD, but it's not going to be a 5-minute job. I'll probably try loading the GPAD into our test database and then do a comparison with what's in our production db (which is still populated from the GAF). Will take a while to set up, so probably won't get round to it until tomorrow.

@hdrabkin I'm not concerned about unmapped identifier errors - it's more about why is a GAF-format annotation OK, and its GPAD counterpart not?

**Comment by hdrabkin** [comment]
In fact, so far I can't find any of these 
eg, GO:0005605; not in our system as used in the annotation or in inferred_from field.
What we don't have a trigger for is if it's in an extension; these need to be hunted down
example GO:0005605 in two genes somewhere;

**Comment by tonysawfordebi** [comment]
(btw: the GAF we consume is this one: http://www.geneontology.org/gene-associations/gene_association.mgi.gz)

**Comment by hdrabkin** [comment]
Found them: they are coming in through our GOA mouse load as an occurs_in extension.
These need to be fixed at GOA_IntAct or we keep re-loading

**Comment by hdrabkin** [comment]
I just verified that the SynGO annotations are now in our Noctua gpad; we now have 4800+ annotations to 600 genes via Noctua

**Comment by tonysawfordebi** [comment]
I haven't done the comparison of the annotation sets that we load from the GAF and GPAD files, but I believe I've unearthed the reason why we're rejecting more annotations from the GPAD than from the GAF...

I spotted a small error in my script that analyses the errors found by the check & creates the "Analysis" section at the end of the log file, namely that it wasn't handling the "unsupported qualifier" error reports correctly. When I fixed that, it immediately became apparent that there is a problem with the way the qualifier column is being set in the GPAD.

I've attached an updated log file to this comment, but this is the relevant section:

Number of annotations with an unknown or unsupported qualifier: 2560
	acts_upstream_of_or_within|NOT: 191
	enables|NOT: 120
	enables|colocalizes_with: 1
	enables|contributes_to: 859
	part_of|NOT: 102
	part_of|colocalizes_with: 1287

[syntax_check-GPAD.log](https://github.com/geneontology/go-site/files/2227238/syntax_check-GPAD.log)

**Comment by ukemi** [comment]
Thanks Tony! So it seems that we are identifying the piped qualifier-values. I'm not sure why we would ever have enables|colocalizes_with, but the others seem ok. I think the NOT annotations should be allowed. I am less certain about the others. In the case of enables|contributes_to, perhaps contributes_to should win. In the case of part_of|colocalizes_with maybe it should be allowed. I think colocalizes_with has been used very inconsistently.  @vanaukenk

**Comment by tonysawfordebi** [comment]
At a guess, what I think is happening is that when you're writing out the GPAD you're always outputting the default relation for the GO aspect, regardless of whether there was already a qualifier (contributes_to, colocalizes_with, or NOT), and this is leading to the double qualifiers.

If a qualifier is NOTted, "NOT|" should precede it.

In pseudocode, what we do when ouptutting GPAD is:

IF qualifier IS unset THEN
   gpad_qualifier := default_relation_for_aspect
ELSIF qualifier = 'NOT' THEN
   gpad_qualifier := 'NOT|' + default_relation_for_aspect
ELSE
   gpad_qualifier := qualifier
ENDIF

**Comment by ukemi** [comment]
Yup. I can have that fixed pretty easily, my mistake interpreting the file specs. What about the contributes_to and colocalizes_with? Are they just not allowed at all?

**Comment by tonysawfordebi** [comment]
No, they're fine. They should just get passed through untouched (that's the "ELSE" bit of the pseudocode above).

**Comment by tonysawfordebi** [comment]
(As should "NOT|contributes_to" and "NOT|colocalizes_with")

**Comment by suzialeksander** [comment]
@pascale
I've saved most of the pages I think we're keeping on GH. Please edit the GH page, or if this documentation isn't in that repo, go ahead and edit as usual then let me know what the URL was- I can move/save it after you're done.

Thanks!

**Comment by suzialeksander** [comment]
@balhoff or @kltm   Since the new GPAD spec is reasonably done and is almost-live, this ticket might be closable immediately (?)

**Comment by kltm** [comment]
This is quite stale and I think covered elsewhere now.
