### ISSUE TITLE
PAINT merge is losing information from WITH column

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#614]
`curl -L http://release.geneontology.org/2018-04-02/annotations/wb.gaf.gz | gzip -dc | egrep '\tIBA\t'`

You can see that the WITH field for tree derived annotations is single-valued

e.g

```
WB      WBGene00044618  bus-2           GO:0016020      PAINT_REF:11214 IBA     PANTHER:PTN000879966    C       Hexosyltransferase      UniProtKB:H2L0F4|PTN000880197   protein taxon:6239       20170427        GO_Central
```

compare with

`curl -L ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_wb.gaf.gz`

e.g.

```
WB      WBGene00044618  bus-2           GO:0016020      PAINT_REF:11214 IBA     PANTHER:PTN000879966|MGI:MGI:1349403|UniProtKB:Q96L58   C       Hexosyltransferase      UniProtKB:H2L0F4|PTN000880197    protein taxon:6239      20180402        GO_Central      
```

**Comment by dougli1sqrd** [comment]
I found the same annotation in the parsed paint_wb from http://release.geneontology.org/2018-04-02/products/annotations/paint_wb.gaf.gz
```
WB	WBGene00044618	bus-2		GO:0016020	PAINT_REF:11214	IBA	PANTHER:PTN000879966	C	Hexosyltransferase	UniProtKB:H2L0F4|PTN000880197	protein	taxon:6239	20170427	GO_Central
```
This at least rules out that ontobio parsing is wrong. Is this a new issue?

**Comment by cmungall** [comment]
It turns out this was an upstream problem with the PAINT annotations coming from Panther. We can see this if we look at the version of paint_wb used on the last release:

`curl -L http://release.geneontology.org/2018-04-02/products/annotations/paint_wb-src.gaf.gz | gzip -dc | egrep '\tIBA\t'`

Missing species-level GPs in the WITH field.

This is now fixed in PANTHER, the fix has percolated to snapshot:

`curl -L http://snapshot.geneontology.org/annotations/wb.gaf.gz | gzip -dc | egrep '\tIBA\t'`

And will be visible the next GOC release

**Comment by nathandunn** [comment]
@cmungall   when do you think the next GOC will be?
