### ISSUE TITLE
Change information about Cross References (location and AmiGO pointer)

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#62]
http://amigo.geneontology.org/xrefs
points to

http://geneontology.org/doc/GO.xrf_abbs_spec
which documents the legacy format.

3 tasks

 1. Fully document https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml - me
 2. Add a link to this in GO.xrf_abbs_spec - me
 3. Point to 1 directly from amigo - do this last

**Comment by kltm** [comment]
When you've made the changes elsewhere, open a ticket for AmiGO and we should be able to get it into a patch release for 2.2.x.
