### ISSUE TITLE
fix wb links

### ISSUE THREAD

**Issue by nathandunn** [geneontology/go-site#628]

**Comment by pgaudet** [comment]
@nathandunn Is this done ? Can this ticket be closed ?

**Comment by nathandunn** [comment]
@pgaudet  Please discuss with @kltm  / @cmungall  

I think the fix in the PR #629 attempts to resolve the problem when we have a link to a transgene or variant and not having it go to a Gene page, though I am having difficulty finding an example where we have a transgene link show up in amigo.   sorry for my poor documentation this issue.

**Comment by pgaudet** [comment]
@vanaukenk Can you check if this fixed the wormbase URLs ? PR is here: 

https://github.com/geneontology/go-site/pull/629/commits/9280bf295bc3ddac8e7e05b7e14cb3f90ddee05b

Thanks, Pascale

**Comment by nathandunn** [comment]
@kltm  I leave it to you then.    Not sure how the original links were breaking or how #629 would break things (looks like it simply provides more precise linkages), but if we don't know how to re-create this, maybe we should close it for now?

**Comment by vanaukenk** [comment]
@pgaudet @kltm @nathandunn 

Some time ago, Seth, Sibyl, and I worked on the WB dbxrefs to make sure that we had the syntax correct for all of them.
That seemed to fix any issues with link outs to WB.

Just to be certain, I've double-checked links outs to genes, variations, RNAi experiments, and papers/references and are all working as expected in AmiGO,  although I cannot find reference to a WB transgene in our annotations to specifically test that.  I note, though, that the example URL for a transgene in the WB dbxrefs yaml entry works correctly.

**Comment by kltm** [comment]
Okay, great--let's go ahead and close this out for now.
