### ISSUE TITLE
Upstream ontology synchronization errors causing downstream owltools problems in AmiGO / GOlr loading

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#63]
Upstream ontology synchronization errors causing downstream owltools problems.

For example, can cause GOlr loader to fail with overuse of memory.

While @hdietze could give a better description, it's not necessary here--this ticket is meant to coordinate the fix and getting the AmiGO data out again.

```
Stuart,

Okay. Good news and bad news.

I just talked to Heiko and he believes that the likely culprit here is
(long story short) a data synchronization upstream from us causing the
smarts of the loader to explode. Because this is a data issue, likely in
go-plus.owl, one thing that could be done until the upstream is fixed is
to change the go-plus.owl load file to a working version from last week,
e.g.:

 http://purl.obolibrary.org/obo/go/releases/2015-05-10/extensions/go-plus.owl

The upstream data fix is unlikely to happen until next week sometime, so
we'll have to make due for now.

If you have an undamaged index from after the problems last Friday, we
can use that for now and stop trying to load until there are fixes
upstream. Otherwise, depending on the time involved, it might be good to
load with the previous data. What's the state of play at your end?

Cheers,

-Seth


On 05/15/2015 03:51 PM, Seth Carbon wrote:
> Stuart(/Heiko/Chris),
>
> For us, the loads on the 9th and 10th appear okay, not so for the 13th
> and 14th (memory related fails). When did you start having problems over
> there?
>
> Cheers,
>
> -Seth
>
>

```
@kkarra @cmungall

**Comment by kltm** [comment]
And a welcome to @stuartmiyasato .

**Comment by cmungall** [comment]
Explanation at the OWL level:

We validate every go-plus release, but the issue is that the amigo universe is larger than go-plus, and we have no checks against incoherency in the larger set. Incoherency is more frequent than we'd like due to the fact that external ontologies include subsets of GO in their dependencies, and these are often stale w.r.t. the head GO. Essentially fixes in disjointness axioms percolate slowly.

We need a better release management system for OWL, OWL-maven or similar. In the interim solutions include building go-amigo as part of the ontology release process, and distributing it as an isolated package, e.g. uisng owlzip

**Comment by kltm** [comment]
A fix seems to have been implemented in owltools by @hdietze .

**Comment by stuartmiyasato** [comment]
Should upgrading owltools sufficient be sufficient for loading or does anything in the GOlr code (or anything else) need to be changed as well?  I just upgraded owltools and got a bunch of errors of this form:

2015-05-18 13:46:04,936 ERROR (GafCommandRunner:964) Unsatisfiable: GO:0060558 'regulation of calcidiol 1-monooxygenase activity'
2015-05-18 13:46:04,936 ERROR (GafCommandRunner:964) Unsatisfiable: GO:0060559 'positive regulation of calcidiol 1-monooxygenase activity'
2015-05-18 13:46:04,936 ERROR (GafCommandRunner:964) Unsatisfiable: GO:0051100 'negative regulation of binding'
2015-05-18 13:46:04,936 ERROR (GafCommandRunner:964) Unsatisfiable: GO:0060550 'positive regulation of fructose 1,6-bisphosphate 1-phosphatase activity'

Any suggestions?

**Comment by hdietze** [comment]
Quick summary on the current state:
* The upstream problem with the ontologies still persists
* The updated owltools code fails fast, meaning: it will exit with a non-zero exit code after printing the list of unsatisfiable classes.

That mean: currently the Golr load is failing by design.

**Comment by stuartmiyasato** [comment]
Thanks Heiko!  I'll wait for further word about changes to the ontology file(s).

**Comment by kltm** [comment]
@stuartmiyasato I didn't mean my comment to trigger you into action. There is another command line flag to add to the command to see if it will fail, which means that it can be tested before getting to the loader (and dropping). While this is useful for our flow, since you load on a separate machine, the current fix is probably sufficient for you.

**Comment by stuartmiyasato** [comment]
@kltm Sorry for jumping the gun.  :-)  At least I got owltools upgraded which probably isn't a bad thing.  I'll wait for further word before trying another load.

**Comment by kltm** [comment]
@stuartmiyasato No, I think you're good--as long as your pipeline stops on the fail (non-zero), from now on when the data gets out of sync, you'll fail without any resource usage and the bad data will never start towards the user-facing servers.

In our case, we update in-place, so we need the extra command line tool to double check for good data before dropping the index and rebuilding.

That said, we still don't have the data fix, so I'm going to leave the bug open for now, until I've applied the fix to the labs servers and have good data in there again.

**Comment by kltm** [comment]
Okay, I've applied this to our (labs) servers and it seems to work (fail before attempting to load). I've added another item to my list to get the labs stuff back to a working version; then we just for the upstream fix, but no more action for production sites.

**Comment by kltm** [comment]
Going ahead after raft of fixes to reload our data from Heiko's cleaned bundle. Will put Jenkins labs loads on pause until upstream is fixed.

**Comment by hdietze** [comment]
Status update: Tracked down the underlying issue to a problem with gorel. We seem to have insufficient checks in place for the full gorel and go-plus load.
This has to be discussed with @cmungall .

**Comment by kltm** [comment]
Okay, we have our 2.2.x build looking good again, so I think we're ready to start looking at turning production amigo loads back on for @stuartmiyasato and @kkarra :

http://build.berkeleybop.org/view/GOlr/job/load-golr-nakama/

While the ontology fixes should have all taken place upstream, I would go ahead and update owltools so that you have the mechanisms that will bail out on a load attempt early if the ontologies do not agree with each other (unsatisfiable).

**Comment by stuartmiyasato** [comment]
Unless any owltools code has changed in the past week, I think we're good on that front -- I updated our owltools when @hdietze added the "fail fast" functionality.  I am currently running a manual load -- meaning the loading script is running, but not the script that copies the indexes over to the production AmiGO servers.  I will do that by hand so I can keep an eye on the servers when it happens.  I will also keep a copy of the old indexes to simplify a rollback in case that is needed.

**Comment by stuartmiyasato** [comment]
The manual load did not throw any errors.  I ran a full loading job that copied the data to the AmiGO servers and that seemed to go well.  Anything else that we should test before closing this ticket?

**Comment by kltm** [comment]
No--with the production loads back to normal, I think it's done. Great!
