### ISSUE TITLE
PAINT GAF for TAIR contains 447 broken lines with column 1+2 missing

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#638]
lines that are not TAIR or UniProt:

`curl -s -L  ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_tair.gaf.gz | gzip -dc |  egrep -v '^(TAIR|UniProt)'`

col1+2 missing from ~500:

```
                At2g28815               GO:0005762      PMID:21873635   IBA     PANTHER:PTN000259457|UniProtKB:Q9NX20|SGD:S000000134    C       60S ribosomal protein L16-like, mitochondrial   UniProtKB:Q84WZ8|PTN000259517   protein taxon:3702      2017-02-28      GO_Central              
                At1g11303               GO:0006468      PMID:21873635   IBA     PANTHER:PTN001563910|UniProtKB:Q8L710|TAIR:locus:2116525|TAIR:locus:2200151|TAIR:locus:2197729  P       G-type lectin S-receptor-like serine/threonine-protein kinase At1g11303 UniProtKB:Q9SXB5|PTN001232076   protein taxon:3702      2017-02-28      GO_Central              
                ATG3            GO:0044804      PMID:21873635   IBA     PANTHER:PTN000305308|SGD:S000005290     P       Autophagy-related protein 3     UniProtKB:Q0WWQ1|PTN002656712   protein taxon:3702      2017-02-28      GO_Central              
```

@dougli1sqrd - any idea why we don't pick this up? We should filter these!

@huaiyumi - do you know what is causing these?

**Comment by dougli1sqrd** [comment]
How long have these been broken? We wouldn't necessarily know as the pipeline hasn't been functioning very well recently. And likely we do filter them if it's missing a first column. Cause you're pulling that from the submission, yeah?

**Comment by huaiyumi** [comment]
In the past, these rows have a database name (Araport) that is not one of those in the GO database cross reference list. We tried to fix it. Obviously we didn't handle it correctly. We will fix it.
