### ISSUE TITLE
Sporadic SSL issues with OpenJDK while loading Ontologies via HTTPS

### ISSUE THREAD

**Issue by hdietze** [geneontology/go-site#65]
In the TermGenie and Amigo loads, there have been problems loading PATO hosted on Github.

One problem seems to be an SSL implementation issue in the OpenJDK (seen on 7u45):

```
Could not download IRI: http://purl.obolibrary.org/obo/pato.owl
javax.net.ssl.SSLException: bad record MAC
```

The official JDK bug is here:
https://bugs.openjdk.java.net/browse/JDK-8030806

A longer discussion of the underlying issue is here (for rubygems): 
https://github.com/rubygems/rubygems.org/issues/615

The general consensus is that is hard to debug because of the sporadic nature and most-likely is the missing SSLv2 implementation (SSLv2 should not be used anyway, only SSLv3 should).

The proposed workaround is adding a flag to the Java command to force a fix behavior:
`-Dcom.sun.net.ssl.rsaPreMasterSecretFix=true`

Also upgrading the JDK implementation version (e.g. from 7u45 to 7u75) seems to fix/minimize it for some.

**Comment by kltm** [comment]
@stuartmiyasato This might affect you at some point (weird failures, etc.). You might want to keep an eye out, but is seems like re-running may well work as it is a sporadic issue.

**Comment by stuartmiyasato** [comment]
Thanks @kltm .  We are running 7u79 on the loading server so hopefully we won't run into this issue.

**Comment by kltm** [comment]
I think we can say this has been generally solved with the completion of the new pipeline...and not having seen this for years.
