### ISSUE TITLE
GAF validation exclusions should be passed on to other make targets

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#651]
Traditionally, we have excluded a couple datasets from GAF validation. These are `goa_uniprot_all` `goa_uniprot_gcrp` `goa_pdb`. 

What happened in the most recent jenkins failure is that the `validate.py` call that parses the source gaf files, produces gpad, gpi, and ttl is told to exclude the above mentioned datasets. 

The mistake is that when we parse the yaml metadata files, we don't take the exclusions into account. So we produce a makefile target called `target/groups/goa/goa_pdb-owltools-check.txt` but the prerequisites for that were not made in the previous `validate.py` step.

So the solution is to exclude these also from the makefile targets.

Now, we do have an issue with goa_uniprot_all. With this, we *don't* want `validate.py` to run it, but we do want to keep all the goa_unirprot_all targets, as we do process them, just differently. We don't process the others at all though. So we'll need to exclude them completely. This should be a mostly straightforward Makefile change. 

For testing purposes, we could add `goa_pdb` to the goa.yaml in the iteration branch. This would replicate this situation, and would ensure that it's skipped correctly.

**Comment by kltm** [comment]
Thank you for the analysis and adding to the `iteration` branch.
Are there any other "edge" cases that you can think of that we should proactively add to the `iteration` branch? AmiGO is almost two months behind at this point and I'm getting a little worried.

**Comment by dougli1sqrd** [comment]
Apologies. I'm not sure. I can meditate on that, and look at the old make maker.

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/pull/652
