### ISSUE TITLE
PAINT is propagating chloroplast annotations to mouse

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#660]
```
$ curl -s -L ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_mgi.gaf.gz | gzip -dc | grep GO:0009507
MGI     MGI:107384      Dnm1            GO:0009507      PMID:21873635   IBA     PANTHER:PTN001696340|UniProtKB:Q84N64   C       Dynamin-1       UniProtKB:P39053|PTN000170280   protein taxon:10090       2017-02-28      GO_Central      
MGI     MGI:109547      Dnm2            GO:0009507      PMID:21873635   IBA     PANTHER:PTN001696340|UniProtKB:Q84N64   C       Dynamin-2       UniProtKB:P39054|PTN000170186   protein taxon:10090       2017-02-28      GO_Central      
MGI     MGI:1341299     Dnm3            GO:0009507      PMID:21873635   IBA     PANTHER:PTN001696340|UniProtKB:Q84N64   C       Dynamin-3       UniProtKB:Q8BZ98|PTN000170221   protein taxon:10090       2017-02-28      GO_Central  
```

**Comment by cmungall** [comment]
also for chicken, human

**Comment by pgaudet** [comment]
1) For PAINT, taxon check failures should strip the annotation lines. We won't be able to be up to date 
manually. 

2) This is really weird. Again it's not in the current PAINT file. See attached screenshot
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/4782928/40496522-3e030e9c-5f7a-11e8-8d34-e591fc2fc9be.png">




(3) Why are there 2 PTN IDs in two separate columns ? 


Thanks, Pascale
@huaiyumi

**Comment by selewis** [comment]
I did speak with @ktlm & Eric about the taxon web service (which is no more
and is what PAINT relied upon for automatic checks). Basically these are no
longer being carried out by PAINT because of the web service going away.
Eric needs to reimplement - for PAINT, for Huaiyu's dumps, and for the
pipeline itself. These aren't being carried out at all at the moment
anywhere.

-S

**Comment by cmungall** [comment]
@pgaudet 

> This is really weird. Again it's not in the current PAINT file. See attached screenshot

You mean not in the current PAINT database? In that case it looks like it may be an issue in transferring from the database to the files on FTP. You can run the command I gave about and see the choloroplast annotations just now

@huaiyumi / @mugitty - we **must** have all code that is part of this dataflow be in github. Can you do this?

> (3) Why are there 2 PTN IDs in two separate columns

not sure I see this but I don't use PAINT - maybe file a separate bug in the PAINT tracker?

**Comment by pgaudet** [comment]
>>  (3) Why are there 2 PTN IDs in two separate columns
> not sure I see this but I don't use PAINT - maybe file a separate bug in the PAINT tracker?

The question was WRT AmiGO, see screenshot at top. But here it is again: 
MGI     MGI:107384      Dnm1            GO:0009507      PMID:21873635   IBA     **PANTHER:PTN001696340**|UniProtKB:Q84N64   C       Dynamin-1       UniProtKB:P39053|**PTN000170280**

Thanks, Pascale

**Comment by selewis** [comment]
As regards point #3. As I said earlier I"m betting this is because we're
somehow still picking up older PAINT annotations and the family #changed
from one PANTHER build to the next.

**Comment by pgaudet** [comment]
@selewis @cmungall Isn't this odd ? @dougli1sqrd told me yesterday that his check to remove IBA annotations NOT coming from PAINT ran for the last release. 

I guess that's not the case ?

**Comment by cmungall** [comment]
I think this was a miscommunication. It did not run on the last release

**Comment by pgaudet** [comment]
Fixed - @marcfeuermann recurated the family.
