### ISSUE TITLE
paint yaml file has url that doesn't resolve

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-site#663]
I was hunting around the GO website looking for the PAINT files without success.  @huaiyumi 
pointed me to this file:

https://github.com/geneontology/go-site/blob/master/metadata/datasets/paint.yaml

Here's the TAIR stanza:

>    id: paint_tair.gaf
>    label: "paint_tair gaf file"
>    description: "gaf file for paint_tair from PAINT"
>    url: http://geneontology.org/gene-associations/gene_association.paint_tair.gaf.gz
>    type: gaf
>    dataset: paint_tair
>    submitter: paint
>    compression: gzip
>    source: ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_tair.gaf.gz
>    entity_type:
>    status: active
>    species_code: Atal
>    taxa:
>     - NCBITaxon:3702
> merges_into: tair

We had been pulling PAINT annotations from here:
http://geneontology.org/gene-associations/submission/paint/pre-submission/
------------------

We can switch to this url but it doesn't resolve:

http://geneontology.org/gene-associations/gene_association.paint_tair.gaf.gz

(@cmungall - should it? If so, why doesn't it?)

though 

ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_tair.gaf.gz

does resolve.

----------------
Perhaps this affects more than just TAIR's link?

**Comment by cmungall** [comment]
Hi @tberardini 

You can pull from the 'source' URL. We are also discussing having groups get PAINT and other injected annotations from the main GOC release files.

Some docs, not perfect, apologies:

http://wiki.geneontology.org/index.php/Release_Pipeline

**Comment by tberardini** [comment]
Thanks @cmungall .  Kimberly pointed me to the Release_Pipeline page but there was no info on the PAINT files. It would be great to include that information.

We will update our PAINT annotations from the source URL at the Panther FTP site.   I'm not sure when the PAINT project transitioned from putting these types of files into the GO svn to only putting them in the Panther FTP.  Was there an announcement that I missed?

**Comment by cmungall** [comment]
Apologies @tberardini we discussed at GOC meeting, and I thought on an annotation call but we should have emailed go-discuss

You can see my slides from the meeting here:

https://docs.google.com/presentation/d/1Q-KVvjQBnNIDfZ4R8crphnMDrMQk0Dca9XYn9BecV4I/edit

@vanaukenk @pgaudet shall we send out an email?

**Comment by vanaukenk** [comment]
@cmungall 
I was going to propose that we present the new pipeline again on the next annotation call but that is not until June 12th (another two weeks), so if you think an email to go-discuss would help, we can certainly do that, as well.

**Comment by tberardini** [comment]
I think both venues for announcement would be good.  With the email, there's a trail that can be followed back to to documentation.  The annotation call will allow for more explanation.

**Comment by pgaudet** [comment]
Hi @cmungall 

My understanding is that PAINT annotations are *not* available separately anymore. I edited the https://github.com/geneontology/go-site/blob/master/metadata/datasets/paint.yaml to reflect this. 

**Please approve the pull request** (or edit as appropriate). 

Thanks, Pasccale

**Comment by tberardini** [comment]
> My understanding is that PAINT annotations are not available separately anymore. 

Wait, what?   Since when? This change was probably covered at the GO meeting but has not been disseminated by email to the larger group.  Also good fodder for the next annotation call, I think @vanaukenk and @pgaudet are on that.

**Comment by cmungall** [comment]
That's not correct, apologies if there has been any miscommunication.

The PAINT files are still available (they have to be, the GO Central pipeline consumes them). You can find the location for the PAINT files in the source field here: https://github.com/geneontology/go-site/blob/master/metadata/datasets/paint.yaml

If TAIR is already consuming from the location here, don't worry, your pipeline has not broken.

What we *do* need to do is to discuss simplification of the overall dataflow. Some people grab PAINT files hot off the press from the PAINT database at the above URLs. Some people get a slightly regurgitated version after it goes through protein2go.

To simplify, the recommendation that came up at the GO meeting that we will discuss further on the annotation call is for groups to uniformly consume non-native annotations from GO Central.

**Comment by cmungall** [comment]
> I was going to propose that we present the new pipeline again on the next annotation call but that is not until June 12th (another two weeks), so if you think an email to go-discuss would help, we can certainly do that, as well.

I will be on holiday June 12

**Comment by pgaudet** [comment]
This seems to be done.
