### ISSUE TITLE
Links from PanTree to AmiGO broken

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#664]
_From @ValWood on May 25, 2018 19:0_

http://www.pantree.org/node/annotationNode.jsp?id=PTN000042666

gives

Not Found
The requested URL /cgi-bin/amigo/term_details was not found on this server.

_Copied from original issue: geneontology/go-annotation#1996_

**Comment by kltm** [comment]
_From @pgaudet on May 27, 2018 19:30_

@kltm or @cmungall Did the links change ? If that's the case, PanTree is probably not the only site with bad links (dictybase seems to have the same problem). 
 
 @mugitty can you please have a look? 

Thanks, Pascale

**Comment by kltm** [comment]
@mugitty Does the PanTree site have a tracker we can submit issues to?

**Comment by kltm** [comment]
The modern URL form is: http://amigo.geneontology.org/amigo/term/GO:0004674

**Comment by kltm** [comment]
Also see: https://github.com/geneontology/amigo/issues/502

**Comment by mugitty** [comment]
I can update the links on PanTree, however, there are other sites with broken links as well.

**Comment by selewis** [comment]
Question still remains @mugitty

Is there a tracker for PanTree?

If yes, where is it?
If no, would you please set one up.

**Comment by pgaudet** [comment]
@mugitty Can you please update the PanTree links ? 

@suzialeksander We should think of where to document this.

**Comment by mugitty** [comment]
Fixed.  I have created https://github.com/pantherdb/PanTree for tracking issues in PanTree
