### ISSUE TITLE
GO Rules Review/Update

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#670]
Overriding as super:

1. Review status of the rules: (checked = reviewed)
2. if something needs to be done, a ticket is created and added to the project GO QC/QA/Rules 1.1 Release (2018-10, Fall GOC)
3. Check current GO rules against previous implementation #712 
4. Make reports prettier 

- [ ] 0000001: See https://github.com/geneontology/go-site/issues/715
- [x] 0000002  
- [x] 0000003
- [x] 0000004
- [x] 0000005
- [x] 0000006
- [x] 0000007
- [x] 0000008
- [x] 0000009
- [x] 0000010
- [x] 0000011
- [x] 0000013
- [x] 0000014
- [x] 0000015
- [x] 0000016
- [x] 0000017
- [x] 0000018
- [x] 0000019
- [x] 0000020
- [x] 0000021
- [x] 0000022
- [x] 0000023
- [x] 0000024
- [x] 0000025
- [x] 0000026
- [x] 0000027
- [x] 0000028
- [x] 0000029
- [x] 0000030
- [x] 0000031

**** original

Using this google document https://docs.google.com/document/d/1bVX8_Mf5OIFoVT_efawIvYDHBzNG-61hVZBfFLdOSqY/edit?usp=sharing as a guide, let's update the written GO Rules in metadata/rules/ in go-site to reflect some of the changes in the document. 

Let's also create more tickets as necessary, and place them in https://github.com/orgs/geneontology/projects/20

This particular ticket is primarily about editing the rules to conform better to the things in the google doc. 

Lastly, I've added a new field, `type`. Go Rules will be divided into a few types:
- `filter`: This rule applies to individual lines in a GAF, and will throw out the line on a failure of the rule.
- `repair`: This rule applies also to individual lines in a GAF, and will attempt to map a rule failure into compliance.
- `report`: This can apply individually or collectively as a SPARQL query. 

Any failure of a rule for any type should always report the failure.

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/tree/gorule_update-670

This is the branch I'm working in. If anyone makes GO RULE changes as per the doc above, let's put it here.

**Comment by dougli1sqrd** [comment]
Pascale says that for rule 26: If IBA annotations were made a `contributor` that is not GO_Central, that is a "real" error in the annotation. (Rather than just wanting to get rid of paint annotations in mod files)

**Comment by dougli1sqrd** [comment]
Should we say this is done?

**Comment by pgaudet** [comment]
OK added tickets for everything - I think.
