### ISSUE TITLE
Update GPAD specifications

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#674]
Update GPAD specifications to use identifiers for relations in place of term labels.  This would hold for the Qualifier column as well as Annotation Extensions.
Proposal wrt GAF and GPAD: keep both; increment in sync.  Issues to consider: relations, evidence codes

**Comment by tonysawfordebi** [comment]
I thought that the decision was taken to freeze GAF as it is now, and only to update GPAD?

**Comment by pgaudet** [comment]
humm could be - but I thought this was a problem for people consuming GAF. I just copied what's in the GOC minutes. I'll add this to the managers discussion for clarification. Thanks for pointing that out!

**Comment by ukemi** [comment]
We also need to keep in mind that if this happens, it is a new format for GPAD that is different from the existing specs. Therefore it can't just happen without advanced notice.

**Comment by tonysawfordebi** [comment]
Indeed, @ukemi, and it would be a non-trivial amount of work on our side too, but I think that it's the right thing to do.

**Comment by pgaudet** [comment]
Current documentation is here: 
http://wiki.geneontology.org/index.php/Final_GPAD_and_GPI_file_format
https://geneontology.github.io/docs/gene-product-association-data-gpad-format/

**Comment by pgaudet** [comment]
Suggest from @tonysawfordebi from the Montreal 10-2018 GOC meeting: 
Extend GPAD header (any annotation set generated by any group) to include PURL for GO ontology information (or snapshot/release DOI), last ‘good’ version of the ontology that was in use when annotations were made

**Comment by kltm** [comment]
I have some questions around the exact nature of "GO version URI":

Is this intended to be an optional use-if-there field, or something that is more important?

Right now, unless somebody creates their own URI and storage, GO currently only provides the possibility of versioned ontologies for "full" releases. Snapshot releases cannot currently be referenced permanently in any meaningful way, which puts up an immediate practical barrier (although there are obviously ways to engineer around that).

Also, what to do when there are multiple ontologies involved in a file/set? Unless part of the definition of the format it to lock it to one, if we are using GPAD as an interchange format, there will be a lot of cases where information from multiple upstreams that used different ontologies to be in one file.

**Comment by kltm** [comment]
This ticket is the new spec, now finalized.
