### ISSUE TITLE
404 on release.geneontology.org

### ISSUE THREAD

**Issue by lpalbou** [geneontology/go-site#677]
The only links that work on release.geneontology.org are those starting with 2018*. 

2017* links return a 404, same thing for annotations / metadata / ontology / products / reports. These last 5 folders should probably be symlinks to the last release anyway ?

The 404 links should be either resolved or removed as this is a public production address.

**Comment by kltm** [comment]
All data there before march will be removed, resolving this.
We have punted until this week for final discussion.

**Comment by kltm** [comment]
@cmungall

**Comment by pgaudet** [comment]
Aren't these our public files ? If that's the case I would say this is blocking. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@kltm I thought these (and earlier ones) would be available. Did I misunderstand ? Or will that be done later ? 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet We'll eventually back-populate with the contents of archive.geneontology.org, although the data layout, etc. will naturally not match. That is still to do and meshes with some topics that we didn't get to.
For now, while "correct-ish", items pre-March are possibly in various states of production for runs that occurred during pipeline development--there is likely nothing wrong with the available data itself, but things like lack of indices, incomplete data types, alternate file layouts, and other issues mean that we want to purge back to about March.
That said, we are trying to remember if there is any reason not to proceed with the final deletion of these files as the action would be irrevocable. Once we go ahead, the changes will take only a few minutes.

**Comment by kltm** [comment]
Talked with @cmungall ; moving forward with the removal.

**Comment by kltm** [comment]
Manual removal of directories, manual update of index.html, invalidation of index.

**Comment by pgaudet** [comment]
Great ! Thanks
