### ISSUE TITLE
gorule-0000008 (no annotations should be made to high level terms) should be a soft check

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#679]
Hello, 

Working on the documentation of GO rules, I realized that GO_Rule_0000008 ("No annotations should be made to uninformative high level terms") is now a hard check, ~which is relatively new~

I suggest we change this back to being a report (soft check), because we ~are~may be loosing a lot of annotations. 

@vanaukenk Can you bring that up at the next annotation call to find out what the different group want to do ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Is it possible to get a report of whether genes annotated to a do_not_annotate term are *also* annotated to a more granular term ? 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
This is implemented already. Pascale says close.
