### ISSUE TITLE
wormbase annotations use WormBase and WB

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#685]
_From @ValWood on June 14, 2018 8:12_

I thought this was fixed before, but  when looking at EXP colocalizes_with:

![colocalizes_with](https://user-images.githubusercontent.com/7359272/41399776-1c2b6956-6fb3-11e8-834b-e08d61a882d1.jpg)

_Copied from original issue: geneontology/amigo#510_

**Comment by kltm** [comment]
_From @ValWood on June 14, 2018 8:13_

@vanaukenk  just so you know

**Comment by kltm** [comment]
_From @vanaukenk on June 14, 2018 13:54_

@ValWood 
What term are you looking at?
We only have WB in our source file, so I'm wondering if these are annotations from WB that were made to other species?

**Comment by kltm** [comment]
_From @ValWood on June 14, 2018 14:20_

I did  cellular_component, filtered on qualifier contributes_to, filtered on experimental evidence codes.

v

**Comment by vanaukenk** [comment]
Please also see:
https://github.com/geneontology/go-site/issues/512

**Comment by pgaudet** [comment]
Should we close as redundant with https://github.com/geneontology/go-site/issues/512?

**Comment by kltm** [comment]
Dupe to #512
