### ISSUE TITLE
Generate external2go as part of main ontology pipeline

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#688]
Currently we have a standalone job

https://build.berkeleybop.org/view/GO/job/Update%20external2go

That pushes to the top-level directory external2go in svn

This page
http://www.geneontology.org/page/download-mappings

points to this via URLs like http://geneontology.org/external2go/prints2go

We need to:

 - generate this as part of the ontology release workflow; this will place things into $OBO/go/external2go
 - change docs to point here
 - push to svn to sync

**Comment by cmungall** [comment]
Note that a subset of these are sourced from the go-edit file, and are auto-generated from here

Others are sourced in svn and are manually updated by @tonysawfordebi and others:
http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/external2go/

**Comment by ukemi** [comment]
Wouldn't it be best if we had these synch with the rest of the releases and had them in their own directories in the snapshot and release products?

**Comment by cmungall** [comment]
That's the plan

**Comment by tonysawfordebi** [comment]
@cmungall In the dim & distant past I put entries for the various external2go files that we submit in https://github.com/geneontology/go-site/blob/master/metadata/datasets/goa.yaml - assuming that that's all OK, I can turn off the SVN submission that we do as part of the four-weekly GOA release whenever you like.

**Comment by suzialeksander** [comment]
Is this the right place to ask about outdated files? 
http://geneontology.org/external2go/tigrfams2go : Dated 2008/08/11
but, ftp://ftp.jcvi.org/pub/data/TIGRFAMs/ lists a 14.0 release from 9/17/14- still old but closer... I don't know how the mappings are constructed so not sure if this newer version matters.

**Comment by kltm** [comment]
http://test.geneontology.io/external2go/tigrfams2go goes to
http://snapshot.geneontology.org/ontology/external2go/tigrfams2go , which is blank.
However, we have others: http://snapshot.geneontology.org/ontology/external2go
It looks like the tiger mappings are just not being generated?

**Comment by cmungall** [comment]
Assign to Eric he known the go-ontology Makefile

**Comment by suzialeksander** [comment]
No idea if this is related, but accessing the Rfam mapping here:
http://geneontology.org/external2go/rfam2go

the mapping has no header (date, etc).

(Likely doesn't matter, but I access this through https://test.geneontology.io/docs/download-mappings/ and I'm assuming it will change soon)

**Comment by alexsign** [comment]
I'm not sure it's the right place, but following has a lot of file missing.
http://snapshot.geneontology.org/ontology/external2go/
I got multiple emails about  
http://www.geneontology.org/external2go/uniprotkb_kw2go
is missing, but many other links from 
http://geneontology.org/docs/download-mappings/
are not working.

**Comment by cmungall** [comment]
For now we will hardcode the paths in https://github.com/geneontology/go-site/blob/master/metadata/datasets/goa.yaml

in the Makefile:

https://github.com/geneontology/go-ontology/blob/456915821627e32bc8593df79b6d35f1d4d6bc3b/src/ontology/Makefile#L423-L424

**Comment by cmungall** [comment]
I did interpro2go here: https://github.com/geneontology/go-ontology/pull/16914

@dougli1sqrd can add the others

Later we will properly ingest, and slurp into go-basic, where they can be exported with the owltools command

**Comment by kltm** [comment]
Noting user expression of this issue here: https://github.com/geneontology/helpdesk/issues/178

**Comment by kltm** [comment]
Temporary fix in for snapshot (then release), now being tested. 
Closure of this ticket still hinges on switching this over to reading from the metadata files instead of the current hard-coding.

**Comment by kltm** [comment]
Note that some of these currently fall through the cracks here #996

**Comment by cmungall** [comment]
Note ticket was github-moved: https://github.com/geneontology/go-ontology/issues/16989

**Comment by pgaudet** [comment]
If it has been moved, should we close this ticket ?

**Comment by cmungall** [comment]
This is now done.
