### ISSUE TITLE
facebook v twitter

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-site#690]
Hi Suzi

I don't have your new email address, please could you send it to me. Also please could you let me know whether the GOC twitter and facebook accounts should be used for the same thing or if there is a difference between them.
We always put our quarterly newsletters on GOC twitter and as a news item, but we wondered if we should also include this as a facebook announcement too.

Thanks

Ruth

@suzialeksander @rachhuntley @BarbaraCzub

**Comment by suzialeksander** [comment]
Hi Ruth,


In case this gets redirected with a Github address, my email is suzia@stanford.edu.  I saw the newsletter is already on Twitter, it can definitely go on FB- anything to get that account active! I can do it or you can, I don't know who put the newsletter on Twitter but it wasn't me.


Thanks!

Suzi


________________________________

**Comment by suzialeksander** [comment]
For the record, yes, Twitter and FB should have overlapping information.

**Comment by RLovering** [comment]
thanks Suzi
