### ISSUE TITLE
Can we get more information about proposed gorule-0000009.md

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#700]
All it says right now is title: "Annotation Intersection Alerts"

@ValWood  What is this expected to do ?

**Comment by ValWood** [comment]
This is the matrix rules.

There are a set of rules for the intersections which have been checked and should be zero.

It should be a soft-check. People will either remove or let me know and I'll fix the rule.

I have forgotten where the rules live.... I can look into this next week. I don't think this rule has ever been active?

@cmungall  @kltm  sorry I will resurrect the manuscript too as soon as  2 others are finished...
Do you remember where the rules are?

Val

**Comment by kltm** [comment]
To catch up people on the matrix rules, the Biocuration 2017 presentation: http://bit.ly/go-report-int-slides
The report lives here: http://bit.ly/go-report-int (needs to be kicked)
The rules for the report here: https://github.com/geneontology/shared-annotation-check

**Comment by cmungall** [comment]
Just so there is no ambiguity

The code for the matrix checks are here: https://github.com/geneontology/shared-annotation-check (curators do not need to go here)

I believe Val's question was where to go for the complete set of GO rules. These live in github in the go-site repo under metadata, here: https://github.com/geneontology/go-site/tree/master/metadata/rules

**Comment by kltm** [comment]
@cmungall But the matrix rules themselves are at https://github.com/geneontology/shared-annotation-check/blob/master/rules.txt ; isn't this a rule for "implementing" the matrix rules?

**Comment by pgaudet** [comment]
Are the reports generated by this script available somewhere ?

**Comment by kltm** [comment]
https://github.com/geneontology/go-site/issues/700#issuecomment-404257783

**Comment by ValWood** [comment]
https://github.com/geneontology/shared-annotation-check
very cool! I hadn't seen that.

Maybe I can just take out the rules with lots of violations and we begin with the ones with only a few (I can quickly do all of the  obvious "zero" rules).  

Then I can add the big ones in slowly. Don't want to scare people....

**Comment by ValWood** [comment]
I mena this one:
https://s3.amazonaws.com/go-reports/index.html

**Comment by kltm** [comment]
@ValWood It's been a while, but this was part of the package we put together for Biocuration a couple of years ag0 :) This still needs to be "ported" to the new pipeline (https://github.com/geneontology/pipeline/issues/21), but should be easy work.

**Comment by ValWood** [comment]
I'm sure I never saw this page though!
This will come back onto my radar in a couple of months...

**Comment by kltm** [comment]
I've ported it; it should have a new home here from tomorrow: http://snapshot.geneontology.org/reports/shared-annotation-check.html

**Comment by dougli1sqrd** [comment]
Talking with Seth, this is being run now every day http://snapshot.geneontology.org/reports/shared-annotation-check.html. 

I will update the Rule that it's implemented and the report is at the above link.

**Comment by dougli1sqrd** [comment]
Updated here: https://github.com/geneontology/go-site/pull/744

**Comment by pgaudet** [comment]
Is this a rule ? This is just a report that may lead to constraints and annotation review tickets, isn't it ?

**Comment by ValWood** [comment]
Well they are 'annotation rules' but at the moment they are soft checks. I think eventually many (ideally most) will be hard checks....

**Comment by dougli1sqrd** [comment]
@pgaudet Is the update to gorule 9 satisfactory, given the conversation?

**Comment by pgaudet** [comment]
Sure. It's only in snapshot, and not in current and releases ?

**Comment by kltm** [comment]
All reports appear in all pipeline runs, including `release` (and `current`, which is a copy of the latest `release`). 
The rules describe both things we wish and things we have, as a method of documentation and tracking progress towards our goals. Implementations and hardness/softness will change through time, as well as how something is implemented and reported. In this case, the intersection check and report predates the current pipeline reports. In the end, we hope to have all reports centralized, but for now, for some use cases, there may be some outliers.

**Comment by ValWood** [comment]
So where do I create and edit  the intersection rules?
Is it a YAml file? I can't remember...

**Comment by kltm** [comment]
@ValWood 
https://github.com/geneontology/shared-annotation-check
https://github.com/geneontology/shared-annotation-check/blob/master/rules.txt
