### ISSUE TITLE
Disable old jenkins reports and add a note in the header for each pointing to the wiki.

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#702]
http://build.berkeleybop.org/view/GAF/

(Maybe other parts of the jenkins site needs to be archived/deprecated - but I am most concerned about the GAF part).

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet I think we'd just off these and make sure the documentation is up to date.
Large portions of https://build.berkeleybop.org will be blinked off when the time comes. That said, I'm not sure anybody is really going to be going in there for file/job updates.

**Comment by pgaudet** [comment]
Hi @kltm 
Apologies - what do you mean 'off these'? I guess close, but concretely, how will that be done? 

Any site that exists, people may end up there, so if it's deprecated it would be best to indicate it. 

Thanks, Pascale

**Comment by kltm** [comment]
"Off" as in remove from the server and internet completely. This can be done as soon as the thumbs up is given to the new reports.
tagging @cmungall

**Comment by dougli1sqrd** [comment]
Will we need to move Jim's Sparql -> GPAD to the actual pipeline in order to shut this down properly?

**Comment by pgaudet** [comment]
@kltm you wrote: 
>  I'm not sure anybody is really going to be going in there for file/job updates.

Many people still go there (http://build.berkeleybop.org/view/GAF/)

Can this be done soon ? It really adds to the confusion.

**Comment by kltm** [comment]
Talked with @cmungall ; will do a manual run-through.

**Comment by kltm** [comment]
All disabled with warning text.
