### ISSUE TITLE
Annotation files on GO-website - are they pointing to the correct releases? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#703]
Links on this page: http://geneontology.org/page/download-go-annotations
Go to, for eg: http://geneontology.org/gene-associations/goa_human.gaf.gz

Shouldn't they go to 
http://current.geneontology.org/annotations/index.html
(for example: http://current.geneontology.org/annotations/goa_human.gaf.gz) ? 

Thanks, 

Pascale and @ukemi 

@kltm @cmungall

**Comment by kltm** [comment]
Dupe of #491 (and #492 )
