### ISSUE TITLE
New rule needed in eco-usage-constraints.yaml for ECO:0001242

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-site#705]
(See also https://github.com/evidenceontology/evidenceontology/issues/170)

We are seeing annotations in files that we import that use ECO:0001242 (phage display evidence used in manual assertion), and which supply a with/from.

Our parser is currently flagging these annotations, saying that a with/from is not permitted. When I investigated, I found that it was because ECO:0001242 is a subclass of both ECO:0000353 (IPI, with/from required) **and** ECO:0000314 (IDA, with/from prohibited).

I think that a new rule is required in eco-usage-constraints.yaml that will apply to ECO:0001242 and its descendants, in order to resolve this ambiguity.

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/issues/908
