### ISSUE TITLE
IEAs more than 1 year old should be filtered out

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#710]
GORULE# 29

This used to be implemented but isn't anymore. We need to implement it again.

**Comment by dougli1sqrd** [comment]
It also does should be a "filter" type rule, not repair

**Comment by kltm** [comment]
tagging @cmungall as well

**Comment by dougli1sqrd** [comment]
Above PR is ready for review

**Comment by pgaudet** [comment]
Waiting for next ontobio release to be live. 

Date ?

**Comment by pgaudet** [comment]
Example file with old IEAs= gramene

**Comment by pgaudet** [comment]
I need to test and close.

**Comment by dougli1sqrd** [comment]
@pgaudet does show for you that this ticket is done? http://release.geneontology.org/2018-09-05/reports/gramene_oryza-report.html

**Comment by pgaudet** [comment]
yes, thanks !
