### ISSUE TITLE
Ensure that ontobio / GAF parser output cites GO rules

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#711]
Currently, there are some outputs and fixes that are implemented by the ontobio GAF parser / reporting that are not properly cited to a GO rule. 

Closing this issue would mean that output and reported changes mapped to a GO rule.

**Comment by dougli1sqrd** [comment]
https://github.com/biolink/ontobio/pull/215

**Comment by dougli1sqrd** [comment]
Above PR is ready to be reviewed
