### ISSUE TITLE
Check current GO rules against previous implementation

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#712]
Looking at the "Mike" script, there are some rules that may be useful that are not currently implemented.

http://geneontology.org/page/annotation-quality-control
http://geneontology.org/page/annotation-quality-control-checks

Go through the latter and see what can be salvaged.
This ticket is to be closed once the above has been reviewed.

**Comment by pgaudet** [comment]
http://geneontology.org/page/annotation-quality-control-checks

    Implemented
        GO_AR:0000001 Basic GAF checks
        GO_AR:0000002 No 'NOT' annotations to 'protein binding ; GO:0005515'
        GO_AR:0000003 Annotations to 'binding ; GO:0005488' and 'protein binding ; GO:0005515' should be made with IPI and an interactor in the 'with' field
        GO_AR:0000006 IEP usage is restricted to terms from the Biological Process ontology
        GO_AR:0000019 Generic Reasoner Validation Check
    Approved
        GO_AR:0000004 Reciprocal annotations for 'protein binding ; GO:0005515'
        GO_AR:0000005 No ISS or ISS-related annotations to 'protein binding ; GO:0005515'
        GO_AR:0000016 IC annotations require a With/From GO ID
        GO_AR:0000017 IDA annotations must not have a With/From entry
        GO_AR:0000018 IPI annotations require a With/From entry
        GO_AR:0000020 Automatic repair of annotations to merged or obsoleted terms
        GO_AR:0000007 IPI should not be used with catalytic activity molecular function terms
        GO_AR:0000008 No annotations should be made to uninformative high level terms
    Proposed
        GO_AR:0000009 Annotation Intersection Alerts
        GO_AR:0000010 PubMed reference formatting must be correct
        GO_AR:0000011 ND annotations to root nodes only
        GO_AR:0000013 Taxon-appropriate annotation check
        GO_AR:0000014 Valid GO term ID
        GO_AR:0000015 Dual species taxon check

**Comment by pgaudet** [comment]
@vanaukenk @ukemi 
We should review these on Wed to make sure they are still what we want.

**Comment by ukemi** [comment]
I suggest we triage: ones we certainly want to keep, ones we want to certainly discard and ones we want to reconsider based on GO-CAM modeling.

**Comment by vanaukenk** [comment]
Yes, let's discuss on Wednesday.
I think we should keep GO-CAM models in mind for reviewing most all of them, actually, and if needed, create a model to check and/or illustrate the implementation.

**Comment by dougli1sqrd** [comment]
Has this been appropriately reviewed? 

So says @kltm 
> Go through the latter and see what can be salvaged.
> This ticket is to be closed once the above has been reviewed.

**Comment by dougli1sqrd** [comment]
Maybe we should merge this with #670; @pgaudet can you make sure there is no missing information?

**Comment by pgaudet** [comment]
We have everything in  #670. 

Thanks!
