### ISSUE TITLE
ISBN link is broken because openisbn.com domain has not been renewed (AmiGO)

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#713]
_From @kltm on July 27, 2018 18:24_

_From @franzcalvo on July 27, 2018 18:21_

on the page for:
coreceptor-mediated virion attachment to host cell
http://amigo.geneontology.org/amigo/term/GO:0046814

the link: Source: ISBN:0879694971 
is broken because the openisbn.com domain has not been renewed

_Copied from original issue: geneontology/helpdesk#149_

_Copied from original issue: geneontology/amigo#520_

**Comment by kltm** [comment]
This seems to work, and probably more stable:
https://catalog.loc.gov/vwebv/search?searchArg=0781702534&searchCode=CMD&searchType=1&limitTo=none&fromYear=&toYear=&limitTo=LOCA%3Dall&limitTo=PLAC%3Dall&limitTo=TYPE%3Dall&limitTo=LANG%3Dall&recCount=25

**Comment by kltm** [comment]
This should clear on AmiGO when the new data goes out on the 1st or 2nd.

**Comment by pgaudet** [comment]
Fixed
