### ISSUE TITLE
Check 'basic GAF checks' against Stanford implementation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#715]
According to the old documentation, the checks for GO_AR:0000001 were: 

The following basic checks ensure that submitted gene association files conform to the GAF spec, and come from the original GAF check script.

- Each line of the GAF file is checked for the correct number of columns, the cardinality of the columns, leading or trailing whitespace
- Col 1 and all DB abbreviations must be in _GO.xrf_abbs_ 
-- now in yaml
-  All GO IDs must be extant in current ontology
--  replaced by GORULE:0000014
- Qualifier, evidence, aspect and DB object columns must be within the list of allowed values
- DB:Reference, Taxon and GO ID columns are checked for minimal form
- Date must be in YYYYMMDD format
-  All IEAs over a year old are removed
-- replaced by GORULE:0000029; **not currently implemented**
- Taxa with a 'representative' group (e.g. MGI for Mus musculus, FlyBase for Drosophila) must be submitted by that group only -> is this right ?  For example I think this is not true anymore for PAINT

**Comment by cmungall** [comment]
I would not represent details of the GAF syntax in the GO rules. This belongs in the GAF spec. E.g. the fact that GAF stores dates as YYYYMMDD (this was a historic mistake - the internal datamodels we use are all ISO-8601, YYYY-MM-DD)

**Comment by pgaudet** [comment]
Right - we just need to document, so that information is very useful. 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
Ontobio currently does this, except for the last point:

> Taxa with a 'representative' group (e.g. MGI for Mus musculus, FlyBase for Drosophila) must be submitted by that group only -> is this right ? For example I think this is not true anymore for PAINT

@cmungall @kltm does this seem like we can close this?
