### ISSUE TITLE
Convert gorule-0000011 from legacy (owltools) to implemented 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#716]
* ND annotations to root nodes only
* This should be a filter (annotations should be excluded) 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/pull/745

**Comment by dougli1sqrd** [comment]
Oh, this was supposed to be a filter, okay. I can do that too.

**Comment by pgaudet** [comment]
Also, we will remove the existing SQL, reword the rule to exclude the GOREF references, and update the sparql.

**Comment by pgaudet** [comment]
(Note that GORULE_11 used to also make a restriction on the reference allowed, this will be moved to GO_RULE33)

**Comment by pgaudet** [comment]
OK done
