### ISSUE TITLE
PAINT annotations removed  in Panther Version 13.1 (released 2018-02-03) still in PAINT GAFs

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#725]
Hello 

@cmungall @kltm 
I thought the PAINT loading pipeline was fixed, but I find annotations that were removed back in the February release, for eg: rhomboid-related PTHR22936, that includes MGI:104328. 

Can you please check ? And hopefully fix for the next release ? 

Thanks, Pascale

**Comment by kltm** [comment]
Could you clarify the issue that you are seeing with this? Looking at the data load currently in AmiGO
http://amigo.geneontology.org/amigo/search/annotation?fq=panther_family_label:%22rhomboid-related%20pthr22936%22&sfq=document_category:%22annotation%22
We have annotations to it from 20110401 to 20180624, across many evidence codes and contributors. Can you point to which of those annotations should not be available and we can start tracing them back.
Also tagging @dougli1sqrd

**Comment by selewis** [comment]
Hi @kltm  - Look at http://amigo.geneontology.org/amigo/gene_product/MGI:MGI:104328 

There are two annotations to GO:0004252, serine-type endopeptidase (with and without a NOT). One of these is wrong (though I'm not sure which).

@huaiyumi - maybe you can take a look?

**Comment by pgaudet** [comment]
I am talking about IBA annotations from 20170228.

**Comment by kltm** [comment]
@selewis You may want to open a separate ticket for that.

**Comment by kltm** [comment]
@pascale this does not appear to have to do with the pipeline: the annotations (amigo link below) appear in the upstream MGI PAINT data source GAF.
http://amigo.geneontology.org/amigo/search/annotation?q=MGI:MGI:104328&fq=panther_family_label:%22rhomboid-related%20pthr22936%22&fq=taxon_subset_closure_label:%22Mus%20musculus%22&fq=evidence_subset_closure_label:%22biological%20aspect%20of%20ancestor%20evidence%20used%20in%20manual%20assertion%22&sfq=document_category:%22annotation%22

**Comment by pgaudet** [comment]
So that means that the next release will not lead this data and this will be fixed ? 

I'll leave this open so I remember to check. 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
Hey Pascale, so I may be mistaken, but when Seth and I looked at these annotations you found, we found them in PAINT. They were in the PAINT source, that then gets merged with the group GAF, after all files have passed through the parser. So these IBA annotations that you're finding don't come from the MGI GAF, and so should not be filtered. 

If you look at the MGI source file, it has 5,000 or so IBA annotations. After ontobio runs the parser on them, the MGI has IBA annotations. We matched the annotations you found as coming directly from the MGI PAINT source. My understanding is that we only remove IBA annotations from group GAF, not PAINT GAF.

So unless the annotations you mention are incorrect somehow, it seems like these annotations should be here, and not filtered. If there is something wrong with the annotations themselves, that's something to bring up to PAINT and is an upstream data issue.

**Comment by dougli1sqrd** [comment]
Yeah, that's right. These paint annotations come from PAINT, not from MGI.

**Comment by pgaudet** [comment]
> If you look at the MGI source file, it has 5,000 or so IBA annotations. After ontobio runs the parser on them, the MGI has IBA annotations. 
This is not right, is it ? shouldn't these get filtered out ?

**Comment by selewis** [comment]
Pascale is right, what you're saying is confusing. What exactly do you
mean? Is it the following?

There should be NO IBAs coming into the GO repository from MGI or any other
source. The only IBAs showing up in AmiGO should be those from PAINT

For posting back to MGI that GAF file (the one MGI will consume, but not
what is provided from them for EXPs) should be those mouse IBA annotations
added back after they've been harvested from the incoming PAINT GAF (with
all previous IBAs that might have come in from MGI removed).

**Comment by pgaudet** [comment]
OK - offline @dougli1sqrd mentioned the mgi **PAINT** file 
http://release.geneontology.org/2018-07-02/products/annotations/paint_mgi-src.gaf.gz
which *does* have the incorrect annotation. 

This is really weird because according to Pantree there are no more annotations in this tree:
http://www.pantree.org/tree/family.jsp?accession=PTHR22936
See also automated note "2018-02-04: Due to PANTHER library version update from PANTHER12 to PANTHER13.1, PANTHER13.1 family PTHR22936 lost some paint annotations because in PANTHER12 family PTHR22936 some nodes PTN000533168,PTN000533212,PTN001879321 annotated with GO termsGO:0004252,GO:0016485 can not be mapped to PANTHER13.1."

@huaiyumi Why is this data still in the PAINT file generated on 2018-07-02 ? 

Thank you in advance for your response. 

Pascale

**Comment by dougli1sqrd** [comment]
@pgaudet oh yeah I made typo in my long comment. I updated with an edit. Sorry for the confusion there

**Comment by kltm** [comment]
This is an upstream PANTHER/PAINT issue--IBAs are coming into our pipeline from PAINT upstream. 
Note that the five annotation are present in the July upstream data:
```
curl http://release.geneontology.org/2018-07-02/products/annotations/paint_mgi-src.gaf.gz | zgrep "[[:space:]]IBA[[:space:]]" | grep "104328"
```
*and* in the last snapshot (which will become our next release):
curl http://snapshot.geneontology.org/products/annotations/paint_mgi-src.gaf.gz | zgrep "[[:space:]]IBA[[:space:]]" | grep "104328"

These annotations are not coming from the "curator" data stream.

**Comment by ukemi** [comment]
@hdrabkin can you take a look at this thread?

**Comment by kltm** [comment]
For complete clarify, our current source in this case is:
https://github.com/geneontology/go-site/blob/master/metadata/datasets/paint.yaml#L117
And it contains the annotations in question here:
```
curl ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_mgi.gaf.gz | zgrep "[[:space:]]IBA[[:space:]]" | grep "104328"
```

**Comment by pgaudet** [comment]
Right - this is what I am now looking at. In that file 
ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_mgi.gaf.gz

I cannot see MGI:104328 being annotated to GO:0004252 (with or without a NOT). 

@kltm can you confirm that you see that annotation ? 
(I would like to know if the bad file is being parsed or if incorrect data in making its way in the file that the pipeline is producing) 

Thanks a lot for your help. 

Pascale

**Comment by hdrabkin** [comment]
Hi
David asked me to look at this thread and clarify what happens at MGI with PAINT annotations,.
Based on a scheme we made in 2010, “External GAF files into MGI for GO RefGen Project”
We first fetch a file 
This file, as I understand it, is generated for each mod during a new PAINT release.
ftp://ftp.geneontology.org/go/gene-associations/submission/paint/pre-submission/gene_association.paint_mgi.gz
We load that file into MGI, thus our site now has the annotations made to mouse by PAINT annotators.  These get a single reference, GO_REF:0000033, and GO_Central as the provider

These annotations are then output in the GAF and GPAD  we supply to GOC (formaly weekly, now nightly as far as I understand).
We have noticed that this file is NOT being updated; it is over a year old.

Header of file is 
!gaf-version: 2.0
!
! 05/08/2017
!
! 31402 associations from PAINT for mgi
“

**Comment by kltm** [comment]
@pgaudet , please run the command I gave above, it's in there:
```
MGI     MGI:104328      Rhbdf1          GO:0004252      PMID:21873635   IBA     PANTHER:PTN000532910|UniProtKB:Q96CC6   F       Inactive rhomboid protein 1     UniProtKB:Q6PIX5|PTN000532956   protein taxon:10090     2017-02-28      GO_Central              
MGI     MGI:104328      Rhbdf1  NOT     GO:0004252      PMID:21873635   IBA     PANTHER:PTN001117529|PANTHER:PTN000532910       F       Inactive rhomboid protein 1     UniProtKB:Q6PIX5|PTN000532956   protein taxon:10090     2017-02-28      GO_Central              
MGI     MGI:104328      Rhbdf1          GO:0050708      PMID:21873635   IBA     PANTHER:PTN001117529|UniProtKB:Q96CC6   P       Inactive rhomboid protein 1     UniProtKB:Q6PIX5|PTN000532956   protein taxon:10090     2017-02-28      GO_Central              
MGI     MGI:104328      Rhbdf1          GO:0042058      PMID:21873635   IBA     PANTHER:PTN001117529|FB:FBgn0041723|UniProtKB:Q96CC6    P       Inactive rhomboid protein 1     UniProtKB:Q6PIX5|PTN000532956   protein taxon:10090     2017-02-28      GO_Central              
MGI     MGI:104328      Rhbdf1          GO:0005789      PMID:21873635   IBA     PANTHER:PTN001117529|MGI:MGI:2442473|UniProtKB:Q96CC6   C       Inactive rhomboid protein 1     UniProtKB:Q6PIX5|PTN000532956   protein taxon:10090     2017-02-28      GO_Central              

```

**Comment by kltm** [comment]
@hdrabkin That I believe is not correct. I believe the file you list is the old SVN copy of the *output* of our pipeline.
Either way, all MOD inputs are scrubbed of IBAs, so would not complete the circle.

**Comment by hdrabkin** [comment]
This is the info I have been asking for over a year, having Karen as to why the file was not being updated; 
ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_mgi.gaf.gz
IS NOT where we were instructed to fetch the file. We have never been notified of any change. 
I'll bet now if we change this, we will now get the missing MGI annotations(anything post 5/8/2017)

**Comment by kltm** [comment]
@hdrabkin Regarding MGI PAINT
*GO* pipeline *input*: 
`ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_mgi.gaf.gz`
*GO* pipeline *output*, including PAINT data from upstream (what is in AmiGO): 
`http://current.geneontology.org/annotations/mgi.gaf.gz`

**Comment by pgaudet** [comment]
@huaiyumi Can you please check what is happening ?

**Comment by hdrabkin** [comment]
you seem to be bypassing the ability for MGI to get these into our own DB first.???
??????
Doesn't the mgi.gaf.gz also contain what WE submit in our gaf that you fetch daily? In which case of course only have the annotations for PAINT up to 5/8/2017.

**Comment by kltm** [comment]
@hdrabkin I don't think we're bypassing anybody, just merging different data streams. The following policy is in place:
* We grab the upstream MOD GAF, filter out the IBAs, do needful operations
* We grab the upstream MOD PAINT GAF, do needful operations
* We append the latter to the former in the GO final GAF product, which is loaded into AmiGO

**Comment by pgaudet** [comment]
Right @kltm but this is different from what used to happen - and clearly not everyone knows yet :(

**Comment by hdrabkin** [comment]
OR we could get the upstream MOD PAINT gaf and load that

**Comment by cmungall** [comment]
There is too much going on in this thread. Let me try and summarize.

 1. There is problem upstream of the GO Central dataflow. Make a new ticket clearly stating the problem and assigned to the right person
 2. @hdrabkin the GO Central release pipeline is documented to the best of our abilities here: http://wiki.geneontology.org/index.php/Release_Pipeline - if you need extra clarifications open a new ticket with the question. You might want to review the slides I presented in the GOC meeting in NYC in particular slide 10 https://docs.google.com/presentation/d/1Q-KVvjQBnNIDfZ4R8crphnMDrMQk0Dca9XYn9BecV4I/edit#slide=id.g397af94a16_0_60 where I described how PAINT annotations are injected at GO Central

**Comment by pgaudet** [comment]
@huaiyumi tells me that this is a bug. I will leave this open and check that offending annotation once the bug has been fixed, new PAINT GAFs generated and uptaken by GOC. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Corrected in ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_mouse.gaf.gz on Aug 7, 2018

   

MGI   MGI:104328 Rhbdf1 NOT GO:0004252 PMID:21873635 IBA   PANTHER:PTN001117529\|PANTHER:PTN000532910 F Inactive rhomboid protein 1   UniProtKB:Q6PIX5\|PTN000532956 protein taxon:10090 2017-02-28 GO_Central
--
MGI MGI:104328 Rhbdf1   GO:0050708 PMID:21873635 IBA PANTHER:PTN001117529\|UniProtKB:Q96CC6 P Inactive   rhomboid protein 1 UniProtKB:Q6PIX5\|PTN000532956 protein taxon:10090   2017-02-28 GO_Central
MGI MGI:104328 Rhbdf1   GO:0042058 PMID:21873635 IBA   PANTHER:PTN001117529\|FB:FBgn0041723\|UniProtKB:Q96CC6 P Inactive rhomboid   protein 1 UniProtKB:Q6PIX5\|PTN000532956 protein taxon:10090 2017-02-28   GO_Central
MGI MGI:104328 Rhbdf1   GO:0005789 PMID:21873635 IBA   PANTHER:PTN001117529\|MGI:MGI:2442473\|FB:FBgn0041723\|UniProtKB:Q96CC6 C   Inactive rhomboid protein 1 UniProtKB:Q6PIX5\|PTN000532956 protein taxon:10090   2017-02-28 GO_Central



Please keep open until the correction trickles through in AmiGO. 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet Could you give a simple test to look for here and we can dupe it onto the AmiGO ticket--there is nothing to keep open here if it has been fixed upstream.

**Comment by pgaudet** [comment]
The test would be: 
This should exists: MGI:104328 + NOT GO:0004252 + IBA
This should NOT exist: MGI:104328 +  GO:0004252 + IBA

Pascale

**Comment by kltm** [comment]
Should be good upstream now, expression duped onto https://github.com/geneontology/amigo/issues/522 .
