### ISSUE TITLE
OWLTools taxon constraint reports contain unexpected results (and gorule-0000013.md)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#734]
Hello, 

GO_AR:0000013 /GORULE:0000013 triggers some warnings in the reports, see for eg:
http://release.geneontology.org/2018-07-02/reports/rgd-report.html

However this is incorrect, see for ex line 381653 

GO_AR:0000013 Warning Could not retrieve a class for taxonCls: NCBITaxon: UniProtKB M0R6B6 Ube2w **GO:0061631** PMID:21873635 IBA FB:FBgn0000173|FB:FBgn0011217|FB:FBgn0026316|FB:FBgn0035601|FB:FBgn0264848|MGI:MGI:104632|MGI:MGI:107411|MGI:MGI:107412|MGI:MGI:109240|MGI:MGI:1913839|MGI:MGI:1914049|MGI:MGI:1917343|MGI:MGI:1917870|MGI:MGI:1934835|MGI:MGI:2384911|MGI:MGI:2388672|PANTHER:PTN002514495|PomBase:SPAC11E3.04c|PomBase:SPBC119.02|PomBase:SPCC1259.15c|PomBase:SPCC338.05c|UniProtKB:A1L167|UniProtKB:O00762|UniProtKB:P51668|UniProtKB:P51965|UniProtKB:P61077|UniProtKB:P61085|UniProtKB:P62837|UniProtKB:P68036|UniProtKB:Q16763|UniProtKB:Q8N2K1|UniProtKB:Q96LR5|UniProtKB:Q9NPD8|UniProtKB:Q9Y2X8|UniProtKB:Q9Y385|WB:WBGene00006713 F Ubiquitin-conjugating enzyme E2 W UniProtKB:M0R6B6|PTN002784003 protein NCBITaxon: 20180314 GO_Central 

**GO:0061631** has no taxon constraints associated with it. 

This rule should be implemented correctly. 

Thanks, Pascale

**Comment by kltm** [comment]
link to owltools check in reports http://release.geneontology.org/2018-07-02/reports/rgd-report.html#otc

**Comment by kltm** [comment]
@pascale It appeazrs not to be an issue in snapshots (and next release), possible a taxon constraint was removed?
http://snapshot.geneontology.org/reports/rgd-report.html

**Comment by pgaudet** [comment]
According to the QuickGO change log, there were never any taxon constraint removed: 
https://www.ebi.ac.uk/QuickGO/term/GO:0061631

(here I checked that taxon constraint changes do get documented in the QuickGO change log: https://www.ebi.ac.uk/QuickGO/term/GO:0019012)

So can we please leave this open until we *see* that it's resolved. (Maybe this ticket is not in the right place but its not resolved). 

Thanks, Pascale

**Comment by pgaudet** [comment]
@kltm I find it slightly odd that the RGD snapshot report has 0 errors for GO_AR:0000013 (or GORULE:0000013).

**Comment by cmungall** [comment]
This is the problem

This is not a taxon violation. It is misleading reporting from owltools. See this line:

https://github.com/owlcollab/owltools/blob/41e1f585d7a8135081c3f2e56c4aa6590901227b/OWLTools-Annotation/src/main/java/owltools/gaf/rules/AnnotationTaxonRule.java#L75

owltools is reporting that it does not know what the taxon of the gene product is. This may because the information is missing from the GAF or there may be another cause. We should investigate and improve the reporting, but regardless, this is not reporting a taxon violation.

**Comment by cmungall** [comment]
the upstream problem was with PAINT providing blank taxon IDs:

```
$ curl -L -s http://release.geneontology.org/2018-07-02/products/annotations/paint_rgd-src.gaf.gz | gzip -dc | grep M0R6B6 
UniProtKB       M0R6B6  Ube2w           GO:0043161      PMID:21873635   IBA     PANTHER:PTN000630458|MGI:MGI:1914049    P       Ubiquitin-conjugating enzyme E2 W       UniProtKB:M0R6B6|PTN002784003  protein taxon:  2017-02-28      GO_Central      
UniProtKB       M0R6B6  Ube2w           GO:0061631      PMID:21873635   IBA     PANTHER:PTN002514495|FB:FBgn0026316|UniProtKB:O00762|FB:FBgn0011217|MGI:MGI:1913839|UniProtKB:P68036|UniProtKB:Q9NPD8|UniProtKB:A1L167|MGI:MGI:109240|MGI:MGI:1917343|MGI:MGI:1934835|MGI:MGI:107412|PomBase:SPCC338.05c|MGI:MGI:107411|MGI:MGI:1917870|UniProtKB:Q9Y385|MGI:MGI:104632|UniProtKB:Q96LR5|MGI:MGI:1914049|FB:FBgn0035601|UniProtKB:P51668|UniProtKB:Q9Y2X8|PomBase:SPBC119.02|PomBase:SPAC11E3.04c|FB:FBgn0000173|UniProtKB:P62837|FB:FBgn0264848|PomBase:SPCC1259.15c|MGI:MGI:2388672|UniProtKB:P61085|UniProtKB:Q8N2K1|WB:WBGene00006713|UniProtKB:P51965|UniProtKB:Q16763|MGI:MGI:2384911|UniProtKB:P61077 F       Ubiquitin-conjugating enzyme E2 W       UniProtKB:M0R6B6|PTN002784003 protein  taxon:  2018-03-14      GO_Central      
UniProtKB       M0R6B6  Ube2w           GO:0005634      PMID:21873635   IBA     PANTHER:PTN000630458|MGI:MGI:1914049    C       Ubiquitin-conjugating enzyme E2 W       UniProtKB:M0R6B6|PTN002784003  protein taxon:  2017-02-28      GO_Central 
```

action items - possibly new tickets

 - PAINT ticket if this issue remains in paint_rgd
 - ontobio should filter blank taxa rather than passing them on to owltools
 - owltools should not produce confusing messages

**Comment by kltm** [comment]
@cmungall Just for clarification, the third item there is a non-issue if the first two are met? We can create an ontobio ticket and a PAINT ticket to close this out?

**Comment by dustine32** [comment]
@cmungall I remember fixing the "taxon:blank" issue in the GAF generation script sometime around early July. The latest gene_association.paint_rgd.gaf that we submit has taxon:10116 for M0R6B6 lines.

**Comment by dustine32** [comment]
Didn't find a ticket for the taxon fix but I did find the [commit](https://github.com/pantherdb/fullgo_paint_update/commit/b6c9e33f0cd76fdbfc844e58729704f556d2a5e0).

**Comment by cmungall** [comment]
Status:

Jim and @dougli1sqrd are integrating taxon constraints into ontobio thus unifying reporting. This will render this ticket irrelevant. We can close then or now

**Comment by pgaudet** [comment]
The problem here was no data in the taxon column. Is this being checked anywhere?

**Comment by pgaudet** [comment]
Yes  say @cmungall and @dougli1sqrd
