### ISSUE TITLE
Problem with reports ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#735]
Hello, 
In the report: http://release.geneontology.org/2018-07-02/reports/rgd-report.html

We have  this error: _'Violates GO Rule: obj:'GO:0000011' "GORULE:0000026: IBA evidence codes should be filtered from main MOD gaf sources" RGD 1305397 Rbsn GO:0000011 PAINT_REF:13510|RGD:1600115 IBA PANTHER:PTN001004537 P rabenosyn, RAB effector gene taxon:10116 20180328 GO_Central'_ 

There are two problems: 
1. GORULE11  should be 'ND annotations to root nodes only' 
2. This seems like the parser is not doing what it's supposed to be doing ! 

Can you please have a look ? 

Thanks, Pascale

**Comment by kltm** [comment]
Actually referring to rule 26.
