### ISSUE TITLE
GORULE:0000014 and GORULE:0000020 are essentially the same.

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#736]
GORULE:0000014 should be deprecated and folded into GORULE:0000020. 20 is a repair rule that says to repair an obsolete class if possible and 14 is a repair rule that says that obsolete classes are not allowed. 

Let's deprecate 14 in favor of 20. 

@cmungall currently in ontobio we do not filter deprecated classes. Is this behavior correct? We should reflect this in the rule.

**Comment by pgaudet** [comment]
As long as the error report is clear (whether the repaired occurred or whether the data was filtered out) this is OK for me.

**Comment by pgaudet** [comment]
We also need to add that 
- Obsolete terms can have a 'replace by' tag or not. 
-- Terms with a 'replaced by' are **repaired**
-- Terms with no 'replaced by' are **filtered**.

**Comment by pgaudet** [comment]
Hi @dougli1sqrd 
The current documentation of the rule says its implemented as a HARD FILTER but that's not the case, see 

http://release.geneontology.org/2018-08-09/reports/wb-report.html

Please fix the rule. 
Pascale

**Comment by pgaudet** [comment]
OK @dougli1sqrd and I agree to merge these two rules.

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/pull/795
We merged these during the meeting. This ticket seems done. @pgaudet, can you close this ticket if you are in agreement?
