### ISSUE TITLE
Fix implementation of GORULE:0000027

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#739]
GORULE:0000027 states: "Each identifier in GAF is valid"

* Col 1 and all DB abbreviations must be in db-xrefs.yaml (see below)
* All GO IDs must be extant in current ontology
* The format of the identifier is checked (for eg number of digits, etc) (but not its actual value)
But this is not how it's implemented : we don't check the db-xrefs.

IDs must also be checked for **validity** (or the description of the rule be edited) 

@cmungall

**Comment by dougli1sqrd** [comment]
A term being obsolete is different I think than an ID that just doesn't exist in the ontology. Like, GO:9999999 I don't think exists as a term. This is what that sentence means, as far as I can tell.

**Comment by dougli1sqrd** [comment]
https://github.com/biolink/ontobio/pull/250
This at least checks that ID prefixes exist in the db xref yaml, and that the contributor is in groups.yaml. This is a pretty good improvement from before, and is a good point to be at for now. This still doesn't check the id part against what is expected in dbxref (regex, digit counting, etc).

**Comment by pgaudet** [comment]
The rule is not only checking the prefix; it's also checking special characters  (see #843); I am not sure this is useful (maybe?)

If we want to leave it like that we need to explain other checks that occur for this rule (ie edit the gorule-0000027.md file). 


Thanks, Pascale

**Comment by dougli1sqrd** [comment]
That's correct. We know some things about IDs that (with the exception of DOIs) that they should not have certain characters. I think it's definitely useful to check for bad characters. If you think the rule needs to be changed to specify that we are checking for bad characters, then we can create a separate ticket and PR for that specifically I think.
