### ISSUE TITLE
GORULE:0000023 'Materialize annotations for inter-branch links in the GO' is not a rule

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#741]
GORULE:0000023  Materialize annotations for inter-branch links in the GO
This is very interesting - however it should go in other documentation, possibly the pipeline documentation ? where we document our products. 
People need to know that this data in being generated, how, and how to consume it. 

2 actions: 
1. Move this to documentation (Pascale) 
2. Deprecate this as a rule (Eric)

**Comment by pgaudet** [comment]
@cmungall Is the text that is there OK to start the documentation ? Or please provide some text.

**Comment by cmungall** [comment]
This is a rule. We can add a field that distinguishes constraint rules from generative rules.
