### ISSUE TITLE
Procure and roll out frontend helpdesk widget for non-GitHub users

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#750]
As the current goal in our adventure from SF.net, through two JIRAs and Drupal, to now directly to GitHub, the closure of this ticket is having a general purpose drop-in widget for handling user queries via email, and pop-up forms, backed or connected through GitHub.
We are currently finishing arrangements with Tender. Others may be used in the future as a drop-in replacement.

**Comment by pgaudet** [comment]
Great ! Thanks

**Comment by lpalbou** [comment]
@kltm any update on Tender ?

**Comment by kltm** [comment]
No progress as I am buried on other fronts. Top of queue when head gets above water.

**Comment by pgaudet** [comment]
I think this can close?
