### ISSUE TITLE
Incorrect link in PAINT yaml file

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#753]
Hi @cmungall 

In the PAIN yaml file (https://github.com/geneontology/go-site/blob/master/metadata/datasets/paint.yaml)  there are link such as http://geneontology.org/gene-associations/submission/gene_association.paint_cgd.gz

that go nowhere. What are they supposed to represent? I'm asking you because you seem to have added that link, see 
https://github.com/geneontology/go-site/commit/c4a49420f264c0ce2ac5dc6217be874a43909fa3#diff-b70bd813aa0f4e3e4ff6c7d86e5dbb5a

and @huaiyumi said he only provided the ftp link. 

I am happy to remove the links if they are obsolete. 

Thanks, Pascale

**Comment by cmungall** [comment]
This is a problem with all, not just PAINT. historic.

We should just eliminate `url`

**Comment by kltm** [comment]
Talking with @cmungall , we'll keep `url` for the time being, updating it to reflect current downloads that we're making available.

**Comment by kltm** [comment]
Now duplicated with #804
