### ISSUE TITLE
GORULE:??? Check for contradictory ND annotation at the top when there actually are annotations for a gp

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#755]
_From @selewis on August 8, 2018 17:47_

See "Automatic deletion of ND-evidenced annotations" 
https://github.com/geneontology/go-annotation/issues/2045 

Should be impossible to say that a GP has annotations, but at the same time say there is No Data.

Raise an alert, and exclude the ND annotation

_Copied from original issue: geneontology/pipeline#52_

**Comment by pgaudet** [comment]
Duplicate of https://github.com/geneontology/go-site/issues/775
