### ISSUE TITLE
Travis timing out again

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#760]
Also, AmiGO isn't accessible. 

Thanks

**Comment by kltm** [comment]
@pgaudet An AmiGO ticket needs to go in the amigo tracker--these are not related, ticket location means it's seen by different people, and will not be solved in the same repo.

**Comment by kltm** [comment]
@pgaudet Which Travis checks are timing out?--these are repo-specific.

**Comment by pgaudet** [comment]
Hi sorry

The ontology checks. I should have put this in the ontology repo.

Thanks, Pascale

**Comment by kltm** [comment]
dupe of #16232
