### ISSUE TITLE
gorule-0000011 ND annotations: Decide on new language for GO_REF requirement

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#761]
GORULE 11 currently says that annotations that use ND as evidence must also use GOREF:0000015 in the reference column. 

In the discussion of the PR, @pgaudet brought up some questions of if that's the that reference is the only one that should work. She suggests relaxing that saying: 

> GO_REF:0000015 also has External accession(s): AspGD_REF:ASPL0000111607, CGD_REF:CAL0125086, dictyBase_REF:2, dictyBase_REF:9851, FB:FBrf0159398, MGI:MGI:2156816, RGD:1598407, SGD_REF:S000069584, TAIR:Communication:1345790, ZFIN:ZDB-PUB-031118-1, GO_REF:nd

As written, the rule does not say this. @cmungall, can you weigh in the conversation, and we can come to a decision?

The output of this ticket is a final decision for the wording/specifics for what violates the rule. You can assign me when this is finalized. We can make Pull Requests against this ticket that implement the decision reached in the discussion. When the PR(s) is merged, this ticket can be closed.

Referencing https://github.com/geneontology/go-site/pull/745#issuecomment-410643725

**Comment by pgaudet** [comment]
@cmungall This means that the file 
http://www.geneontology.org/cgi-bin/references.cgi is out of date? This is what is stated: 

> GO_REF:0000015 also has External accession(s): AspGD_REF:ASPL0000111607, CGD_REF:CAL0125086, dictyBase_REF:2, dictyBase_REF:9851, FB:FBrf0159398, MGI:MGI:2156816, RGD:1598407, SGD_REF:S000069584, TAIR:Communication:1345790, ZFIN:ZDB-PUB-031118-1, GO_REF:nd

We need to give groups notification that this is not allowed anymore.

**Comment by pgaudet** [comment]
Where is the new version of http://www.geneontology.org/cgi-bin/references.cgi  on go-site ?

**Comment by dougli1sqrd** [comment]
@cmungall what counts as an equivalent ID for a reference? In the triple store, There’s nothing in the triple store about `<http://purl.obolibrary.org/obo/go/references/0000015>`. It's only an ID, and as such we have no way of using the triple store to obtain "alternate IDs".

**Comment by dougli1sqrd** [comment]
Closing, as this will be covered in gorule-0000043 in defining proper ECO/GOREF mapping. These mappings will occur in the gorefs directory of go-site. Ontobio currently looks at this for any violations. We have a ticket to fill out these mappings: https://github.com/geneontology/go-site/issues/1177
