### ISSUE TITLE
Out of date jenkins files to be removed

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#762]
Hello, 

Following up on #578 

@cmungall @kltm 
I am not sure how Val accessed this file (http://build.berkeleybop.org/view/GAF/job/gaf-check-pombase/lastSuccessfulBuild/artifact/gene_association.pombase.inf.gaf/*view*/); it dates form June, so it doesn't seem to be generated anymore. Can we remove these files and put a redirect message ? 

Thanks, Pascale

**Comment by kltm** [comment]
Dupe of #702
