### ISSUE TITLE
Change TAIR gene ID format in db-xrefs.yaml to match PAINT with values

### ISSUE THREAD

**Issue by dustine32** [geneontology/go-site#765]
Related to @tonysawfordebi 's error reporting [here](https://github.com/geneontology/go-annotation/issues/2044#issuecomment-411663480), which thinks TAIR ID's in with/from columns of IBA annotations are not using correct format. Ex: TAIR:locus:2117758. They seem to use the locus-based identifiers for genes as stated [here](https://www.arabidopsis.org/portals/nomenclature/guidelines.jsp#locus). I couldn't find any annotation results from Amigo by searching "TAIR:gene*" (currently the format for gene in db-xrefs.yaml) but I could for "TAIR:locus*".

I'm proposing that we update the `entity_type: gene` properties to match those in `entity_type: locus`:
```
- type_name: gene
  type_id: SO:0000704
  id_syntax: locus:[0-9]{7}
  url_syntax: http://arabidopsis.org/servlets/TairObject?accession=[example_id]
  example_id: TAIR:locus:2146653
  example_url: http://arabidopsis.org/servlets/TairObject?accession=locus:2146653
```

Tagging @thomaspd @huaiyumi since I discussed this with them. I'll also put in a PR with the changes.

**Comment by dustine32** [comment]
Also, tagging this issue: https://github.com/pantherdb/fullgo_paint_update/issues/6

**Comment by kltm** [comment]
https://github.com/geneontology/go-site/pull/766#issuecomment-413052864

**Comment by kltm** [comment]
Noting https://github.com/geneontology/go-site/issues/659

**Comment by kltm** [comment]
I'm worried that this looks like a pass at https://github.com/geneontology/go-site/issues/659, but conflating locus IDs with genes.

**Comment by dustine32** [comment]
Yeah, I saw https://github.com/geneontology/go-site/issues/659 too. I can email TAIR helpdesk to confirm the `locus:####` format is how they mint all of their IDs. Or is email too square?

**Comment by dustine32** [comment]
Me too! Emailed...

**Comment by kltm** [comment]
Talking with @cmungall , it may be best to attack this in the eco constraints file (as you identified) with
```yaml
entity_type: *primary_transcript
```

**Comment by dustine32** [comment]
@kltm Cool! I'll update the eco-usage-constraints.yaml then let you know when the PR's ready to review. Thanks!

**Comment by tberardini** [comment]
See my comment in #659 please.

**Comment by pgaudet** [comment]
@tberardini @dustine32 Is this fixed ?

**Comment by tberardini** [comment]
I've given my input, hope that was sufficient.

**Comment by dustine32** [comment]
@pgaudet Closing since this was fixed when we updated the metadata yaml files to allow `TAIR:locus:` style IDs.
