### ISSUE TITLE
Issues with GOC inference file (i) incorrect aspect reported

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#767]
~PomBase	SPBC13E7.10c	brf1		GO:0045945	PMID:12682361	IC	GO:0000995	F	transcription factor TFIIIB complex subunit Brf1	SPBC30D10.20	protein	taxon:4896	20170901	GOC-OWL	part_of(GO:0045945)
GO:0045945 positive regulation of transcription by RNA polymerase III
is a BIOLOGICAL PROCESS  TERM ASPECT IS REPORTED AS "F"~

annotation no longer exists in file below

**Comment by pgaudet** [comment]
Which file are you looking at ?

**Comment by pgaudet** [comment]
@ValWood GO:0045945 is in the extension - the annotated term, GO:0000995, *is* a MF; isn't it ?

**Comment by ValWood** [comment]
PomBase	SPAC14C4.08	mug5	contributes_to	GO:0032118	PMID:25736293	IC	GO:0106006	F	dynactin complex subunit Mug5		protein	taxon:4896	20170718	GOC-OWL	part_of(GO:0032118)

GO:0032118 is A BIOLOGICAL PROCESS TERM
horsetail-astral microtubule organization (GO:0032118)

**Comment by ValWood** [comment]
This annotation

PomBase	SPBC13E7.10c	brf1		GO:0045945	PMID:12682361	IC	GO:0000995	F	transcription factor TFIIIB complex subunit Brf1	SPBC30D10.20	protein	taxon:4896	20170901	GOC-OWL	part_of(GO:0045945)

Colum 5 is 
GO:0045945

(I haven't even got to extensions yet......)

**Comment by ValWood** [comment]
this file
http://snapshot.geneontology.org/products/annotations/pombase-prediction.gaf

**Comment by ValWood** [comment]
Note that all of these have GOC_OWL in the assigned by field rather than just GOC.
The GOC ones have the apsect reported correctly.

**Comment by pgaudet** [comment]
OK get it - I see the same: GO:0045945 (positive regulation of transcription by RNA polymerase III) is labeled as a F but it isnt. 

@cmungall @kltm Is the a problem with the script that generates these ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Yay!

**Comment by kltm** [comment]
@cmungall I'm not particular familiar with the prediction generation here; this is owltools?

**Comment by cmungall** [comment]
Yes, owltools


## incorrect aspect

The incorrect aspect issue was reported here: https://github.com/owlcollab/owltools/issues/237

The ticket was not closed, but I believed it was fixed by HyeongSik with this PR, which was merged: https://github.com/owlcollab/owltools/pull/239

However, it seems that he only implemented this for the basic annotation propagator, not for the annotation deepening.

Action: I can fix this, how high a priority is this for you?

Ultimately this code will be rewritten

## GOC-OWL vs GOC

This was agreed on with @tonysawfordebi a number of years ago. It was required so that these could be separated from the F->P propagations. Similar to how PAINT has GO_Central. It's not ideal but these decisions have accumulated over the years to make up for the complex dataflow of GO annotations with a limited format.

This is documented in the corresponding rule:

https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000025.md

## Explanation of inference

> I think GO:0000995 is in the "with" field of what the original annotation was inferred from. I'm not sure right now...

This is correct. I have updated the docs for https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000025.md to clarify this.

So this is your inferred line:

PomBase	SPBC13E7.10c	brf1	GO:0045945	PMID:12682361	IC	GO:0000995	F	transcription factor TFIIIB complex subunit Brf1	SPBC30D10.20	protein	taxon:4896	20170901	GOC-OWL part_of(GO:0045945)

This is the source line:

PomBase SPBC13E7.10c    brf1            GO:0000995      PMID:12682361   IMP             F       transcription factor TFIIIB complex subunit Brf1        SPBC30D10.20    protein taxon:4896    20170901 PomBase part_of(GO:0045945)     

i.e the annotation was that brf1 is involved in "GO:0000995 ! transcription factor activity, core RNA polymerase III binding" that is part of "positive regulation of transcription from RNA polymerase III promoter"

From this it can be inferred that brf1 is itself involved in "GO:0045945 ! positive regulation of transcription from RNA polymerase III promoter"

(now you already had an annotation to this, but this isn't guaranteed)

I agree this is confusing. We are working with a file format that was not designed for providing chains of evidence. There is information loss.

How can we do this better for our users, so that the provenance of annotations are completely clear?

How can we make it easier for GOC members?

**Comment by pgaudet** [comment]
> How can we do this better for our users, so that the provenance of annotations are completely clear?

Perhaps adding an internal GO_REF describing the method ? 
Pascale

**Comment by ValWood** [comment]
- I still don't fully understand the difference between the two sources, but I'm happy that they are different, and that the annotation is correct based on ontology links. The only action here was to correct the aspect. For us this is not urgent if it needs to be rolled in with other work. It just annoys me ;), and it might be an issue for downstream tools that the aspect does not match the term. 

- I still think the extension is odd, and I don't see why it is required. Here, once the aspect is corrected) you are saying
GO:0045945  positive regulation of transcription by RNA polymerase III
part_of GO:0045945  positive regulation of transcription by RNA polymerase III
That statement does not make sense to me. I don't think you need to propagate the extension do you?

- Ideally duplicate annotations would not be generated, but we filter them anyway, so not a problem for PomBase. I still believe _strongly_ that we should not provide redundant annotation generated by pipelines  (direct or to parents) if a manual annotation exists. The inferences are not required, the support is almost always circular, but they do not add anything useful for the end user.  This step would reduce the number of annotations for all MODs by around ~>50%  and really help in global annotation consumption. But this is an ongoing moan for another place.

- I don't think this particular relationship in the ontology is correct. The general transcription factors are required for transcription to occur. They are part of the process of transcription. I will open a ticket about this on the ontology tracker.
Once fixed, this particular annotation will disappear. So everyone, please note that if you cannot see this particular annotation it does not mean that the problem has gone away. I can find another example ....

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/16267
for the ontology issue

**Comment by ValWood** [comment]
I agree that the internal GO_REF would be sufficient to describe the difference in the methods.

**Comment by pgaudet** [comment]
But @ValWood Aren't there use cases for having all predictions ? For eg: 
https://gotrack.msl.ubc.ca/terms.xhtml?query=GO%3A2000463

**Comment by cmungall** [comment]
Propagation of extensions: you are correct, in this case it is clearly redundant.

It's not always redundant.

Say we have P and occurs_in some 'primary lysosome', and only 'vacuolar P' pre-composed, the extension still carries extra information.

Nevertheless we should add something for the trivial case where the extension matches the inferred GO term directly.

**Comment by ValWood** [comment]
> Propagation of extensions: you are correct, in this case it is clearly redundant.

Doesn't it depend on relationship type? If the relation is part_of it would always be redundant wouldn't it? (because the part_of relation  you are instantiating is the thing in the extension); other relations would be OK because they are to different ontologies/aspects/objects.

**Comment by cmungall** [comment]
> If the relation is part_of it would always be redundant wouldn't it

Not necessarily. For as long as we have the pre-composed "P involved in W" terms in the ontology (let's not get into a discussion as to whether that's good or bad here), it is possible to infer a more specific GO ID with a non-redundant extension.

E.g. pre-composed: "wnt signaling involved in heart development"

annotation "wnt signaling" + part_of(myocardium development)

can be replaced by

annotation "wnt signaling involved in heart development" + part_of(myocardium development)

I can't deny that this is ugly but (1) the GO term in isolation is more informative in a strict ontological sense (2) the extension is formally non-redundant.

**Comment by ValWood** [comment]
> But @ValWood Aren't there use cases for having all predictions ? For eg:
https://gotrack.msl.ubc.ca/terms.xhtml?query=GO%3A2000463

I don't know, what is the usecase for having more redundent annotation.

Take for eample dcp1. 
4 additional annotations are generated by IBA:
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPBC3B9.21
all are already experimetnally annotated in pombe. For two one of the evidences in from pombe.
Our users would  get a bit annoyed if we added more information from characterised  proteins in other species saying the same thing.....They don't need this information becasue they already know it from experiemnts in pombe. They would not think this was adding more support, they just see it as clutter.

From our user survey when we compacted our GO presentation view further (we already filter away redundant a non experimental data)

![pi_survey](https://user-images.githubusercontent.com/7359272/44223554-d61ddd00-a17f-11e8-81c1-c671d184b063.jpg)

In general end users want the most concise data presented, they don't want to see more data which does not add more information. I don't believe that this increases confidence if you already have good experimental data.

In quickgo the situation is worse
http://amigo.geneontology.org/amigo/gene_product/PomBase:SPBC3B9.21
because  ~10  inferred annotations that PomBase already filtered away.

To me, the inference piplines should be used to fill annotation gaps, not to  provide redundant data on gene pages and in the GO database. This seems to  align with what our users want.... Part of our purpose as curators  is to *reduce* the amount of information to sift through, not to add to it...

**Comment by cmungall** [comment]
Agree 100%. Original idea was to do this in a more modular way - rather than building in redundancy filtering rules to the inference components, the inference components are liberal allowing redundancy filtering to happen downstream... which it isn't at the moment.

**Comment by ValWood** [comment]
Some individual comments on changes to reduce redundent data presentation:

“My lab uses PomBase on a daily basis and .... improve what was already an excellent and essen.al resource for my lab...The new version is better mainly because it seems very easy to find the data you are looking for” -Sir Paul Nurse, Director, Francis Crick Institute

“It becomes easier to check known/published results of genes of interest”
-Takashi Toda, Hiroshima University

“[S]treamlined for easier access. less time searching the page, more time doing research!”
-James Moseley, Dartmouth Medical School

“The new site is becoming more and more comprehensive, with frequent updates. However, it is designed so that large amounts of information can be easily sorted/filtered to extract information I need”
-Anonymous

“I believe this is making it easier for me to determine where to focus future experiments”
-Anonymous

Plus many more comments like this. Generally users want streamlining. Believe me !
I don't want to give our users  information that does not add anything. I'd get hassled.....

**Comment by ValWood** [comment]
> allowing redundancy filtering to happen downstream... which it isn't at the moment.

OK so the eventual  plan is to hide /filter all non-experimental redundant data in user front end views?

**Comment by kltm** [comment]
I see that @cmungall was poking around in the issues, but just to link back to the work on it:
https://github.com/geneontology/amigo/issues/43
If this as a roadmapped feature is sufficient, we can move the conversation over there.

**Comment by ValWood** [comment]
Is this current?

**Comment by ValWood** [comment]
The main issue in this ticket was buried.   Some BP annotations are created with MF aspect.
I will open a new ticket for this but and remove it from this ticket.

**Comment by ValWood** [comment]
the rest of this ticket is me moaning about redundancy, I think.

I'm pointing out that  GO:0032118  is inferred from GO:0106006, but we already made   GO:0032118. This will all be moot when the proposal to filter redundant inferences is implemented.

geneontology/go-site#943
