### ISSUE TITLE
http://geneontology.org/page/download-ontology should link to 'current', not 'snapshot'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#769]
The ontology files that can be downloaded form the website 
http://geneontology.org/page/download-ontology
(the ontology PURLs) currently redirect to snapshot. This needs to be changed, as it is in contradiction with our guidelines. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Note that this means that MODs downloading the ontology from this location will need to change their links. We'll notify them when the change is done.

**Comment by kltm** [comment]
`snapshot` is correct for the PURLs right now; as well, they contain date information.
The citable bundles are still there containing the ontology at a point in time.
Tagging @cmungall so he can discuss this with you in another channel.

**Comment by pgaudet** [comment]
@kltm which channel would that be ? So I dont loose the info ?

**Comment by kltm** [comment]
@pgaudet Your google doc for pipeline questions would probably be the best place to capture this type of thing.
