### ISSUE TITLE
Typo on Evidence code page URL & title

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-site#772]
http://wiki.geneontology.org/index.php/Inferred_from_Hight_Throughput_Mutant_Phenotype_(HMP)

links from http://geneontology.org/page/guide-go-evidence-codes

Do I fix with a redirect or ... ?

**Comment by kltm** [comment]
@suzialeksander Sorry, could you outline what you're seeing versus what you think should be there?

**Comment by suzialeksander** [comment]
Title and URL are "...Hight_Throughput..."
Should be "High", shouldn't it?

**Comment by kltm** [comment]
...totally didn't see that...
Bleh, yes, change everywhere, please.

**Comment by kltm** [comment]
As it's a wiki, there will be at least the redirect in there (as pages can't be destroyed).

**Comment by suzialeksander** [comment]
Great.  I'm on it.

**Comment by pgaudet** [comment]
@kltm 
> as pages can't be destroyed


But they can be deleted ... what's the difference ?

**Comment by suzialeksander** [comment]
I don't have permissions to delete a wiki page, only move it.  But I suppose you can delete it if possible?

**Comment by kltm** [comment]
They can be destroyed in a way, but it is generally discouraged (as it breaks bookmarks and can cause some annoying aftereffects). I would use a redirect here.

**Comment by pgaudet** [comment]
yes, I agree.
