### ISSUE TITLE
Regenerate the readme file

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#774]
Hi @dougli1sqrd 
The readme file is out of date; can you please regenerate ? 
(Is this something *you* need to do? I'd be happy to help.) 

Pascale

**Comment by kltm** [comment]
What README are you referring to here (link)?
That said, I don't think we currently generate any README files for publication.

**Comment by pgaudet** [comment]
Humm. so we do need more documentation ;)

**Comment by pgaudet** [comment]
> What README are you referring to here (link)?

I should have given the link, but I assumed that there was a single README per repo; is this right ? 
(for my information). 

Thanks, Pascale

**Comment by kltm** [comment]
In this case it would be the static file: https://github.com/geneontology/go-site/blob/master/README.md
There can be as many or as few READMEs per directory in a repo as necessary. It happens that GitHub will try and render one of them when visiting a directory in associated code tree.

**Comment by cmungall** [comment]
Yes, every repo should have a README. It need not be comprehensive but it should serve as in index to more in-depth docs as required. go-site is organized into more granular areas like the rules, and these are linked to from the top level README.

**Comment by dougli1sqrd** [comment]
Updated!
