### ISSUE TITLE
New GO RULE: Genes annotated with ND with a given aspect should have no other annotations

### ISSUE THREAD

**Issue by selewis** [geneontology/go-site#775]
Need to ensure that there are no ND annotations for a given aspect if in fact there are annotations available. sparql query to determine the answer, then if there are any annotations contradicting the ND annotation should send a warning to the provider and filter out the ND annotation.

**Comment by kltm** [comment]
Can you clarify this issue's relation to #755 and #701 ?

**Comment by selewis** [comment]
Duplicate with #755 and #701

**Comment by pgaudet** [comment]
In fact these two rules are not redundant at all. 

1. gorule-0000011: only annotations to root terms are allowed with Evidence code ND (I think this is the one that Eric implemented). 

2. new-gorule: for any gene product annotated to a root term, no other annotations should be present for that aspect.

**Comment by dougli1sqrd** [comment]
I think this is completed as of https://github.com/geneontology/go-site/pull/1035

**Comment by vanaukenk** [comment]
@pgaudet - at the Montreal meeting, we discussed that curators did not want ND removed if 'protein binding' annotations were the only other MF annotations that existed for a given GP.
See section on 'ND annotations':
https://docs.google.com/document/d/16KMJRn-Vqf4yRsXAR1KYlwYvPob1tRTQbq2cEs6IJNY/edit#
How does this rule fit in with that?  Thx.

**Comment by pgaudet** [comment]
This rule is a 'report', so people can look at the annotations that fail it, but the annotations should all remain in the files and the data we show in AmiGO.
