### ISSUE TITLE
Manage migration of consortium members to use explicit snapshot PURLs

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#783]
Individual MODs and other GOC consumers of the ontology need a way to access the latest/snapshot in order to provide their annotators with latest terms.

Currently people are consuming PURLs of the form
http://purl.obolibrary.org/obo/go/go.obo

These currently resolve to snapshot. We will switch this to resolve to current. But first we need to make sure GOC consumers switch to URLs of the form:

http://purl.obolibrary.org/obo/go/snapshot/go.obo

@tonysawfordebi I believe you already use the explicit snapshot PURL

**Comment by kltm** [comment]
Now in docs?
