### ISSUE TITLE
Report request - any groups still have SVN as a source for GO data?

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-site#784]
From USC hackathon - are there any groups whose annotation and/or gene product mapping files (e.g. gpi) are still sourced from the SVN directory?

**Comment by kltm** [comment]
aspgd.yaml:   source: http://geneontology.org/gene-associations/submission/gene_association.aspgd.gz
cgd.yaml:   source: http://geneontology.org/gene-associations/submission/gene_association.cgd.gz
ecocyc.yaml:   source: http://geneontology.org/gene-associations/submission/gene_association.ecocyc.gz
fb.yaml:   source: http://geneontology.org/gene-associations/submission/gene_association.fb.gz
genedb.yaml:   source: http://geneontology.org/gene-associations/submission/gene_association.GeneDB_Pfalciparum.gz
gonuts.yaml:   source: http://geneontology.org/gene-associations/submission/gene_association.gonuts.gz
gramene.yaml:   source: http://geneontology.org/gene-associations/submission/gene_association.gramene_oryza.gz
jcvi.yaml:   source: http://geneontology.org/gene-associations/submission/gene_association.jcvi.gz
pamgo.yaml:   source: http://geneontology.org/gene-associations/submission/gene_association.PAMGO_Atumefaciens.gz
pamgo.yaml:   source: http://geneontology.org/gene-associations/submission/gene_association.PAMGO_Ddadantii.gz
pamgo.yaml:   source: http://geneontology.org/gene-associations/submission/gene_association.PAMGO_Mgrisea.gz
pamgo.yaml:   source: http://geneontology.org/gene-associations/submission/gene_association.PAMGO_Oomycetes.gz
pseudocap.yaml:   source: http://geneontology.org/gene-associations/submission/gene_association.pseudocap.gz
reactome.yaml:   source: http://geneontology.org/gene-associations/submission/gene_association.reactome.gz
rgd.yaml:   source: http://geneontology.org/gene-associations/submission/gene_association.rgd.gz
sgd.yaml:   source: http://geneontology.org/gene-associations/submission/gene_association.sgd.gz
sgn.yaml:   source: http://geneontology.org/gene-associations/submission/gene_association.sgn.gz
tair.yaml:   source: http://geneontology.org/gene-associations/submission/gene_association.tair.gz

**Comment by tonysawfordebi** [comment]
We still submit several external2go (and gp2protein) files to SVN - see also https://github.com/geneontology/go-site/issues/688

**Comment by hdrabkin** [comment]
MGI still submits gp2protein, gp2RNA, and gp_unlocalized via SVN

**Comment by kltm** [comment]
Moving work portion to fresh ticket at #997 .
