### ISSUE TITLE
All pipeline reports should have a date

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#785]
All pipeline reports should have a date.

**Comment by pgaudet** [comment]
@dougli1sqrd @kltm 
In fact, all files produced should have a date (the ontology, the annotations) 
Also, the ontology header should indicate whether it is a 'release' or a snapshot (right now snapshots have 'data-version: releases/2018-09-09' (for example). This is misleading. 

Should I create a separate ticket ? 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet Yes, please go ahead and create a separate ticket for any desired files that do not yet have dates.
