### ISSUE TITLE
Define layout of the Downloads page http://current.geneontology.org/products/pages/downloads.html

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#786]
http://current.geneontology.org/products/pages/downloads.html

**Comment by pgaudet** [comment]
For example: 

 |  |  | 
-- | -- | -- | --
Aspergillus Genome Database 		  (aspgd, Aspergillus) | n/a | 633597 | aspgd.gaf (gzip)

- organize by species

**Comment by suzialeksander** [comment]
AGD is gone, so not an issue.

unclear if the action item is to merge files or leave alone, closing this ticket.
