### ISSUE TITLE
Script keeping MeSH URI up to date?

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-site#79]
(Assuming this is now the correct place for this ticket given that the affected file now lives here.)

MeSH base URI in db-xrefs.yaml has the year in it  67a60a84e6c91d868ceb00ca917f2e0b12967ee2

Presumably needs to be updated each year in order to point at latest.  Would be a very simple to script this.  Could be a simple Travis or Jenkins Job.  Happy to write this myself.

(Note this is a general issue for OBO folks making xref to MeSH - not just an issue for GO).

**Comment by kltm** [comment]
Seems like their issue somehow; what about:
http://www.nlm.nih.gov/cgi/mesh/current/MB_cgi?view=expanded&field=uid&term=D017209
(Besides the fact that it's hilariously the 2002 version.)

**Comment by kltm** [comment]
Or, to restate that, when somebody is using that ID, unless the date information is somehow encoded as well, there is no way of knowing what version that are referencing. In that case, I think that you would default to the "current" version rather than assuming a dated version (and we try and get them to fix the current URL).

**Comment by cmungall** [comment]
@dosumis has always been a proponent of citing the exact version when using an xref for provenance, e.g. a wikipedia revision.

I agree... but OTOH use of wikipedia or mesh is often a 'bad smell' for a copy and pasted dictionary style loosely worded milquetoast definition so a version-independent ID is often fine.

Jenkins seems OTT for updating the URL. Calendar reminder?

**Comment by dosumis** [comment]
Added calendar reminder to GO calendar.  Jan 7th repeating yearly.
