### ISSUE TITLE
Implement gorule-0000043: Allowed References for each ECO

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#790]

**Comment by pgaudet** [comment]
@dougli1sqrd 
Can I change the format of the GO_refs to add which evidence codes are allowed ? Would that be a way to provide the information? 

See for ex: 
https://github.com/geneontology/go-site/blob/master/metadata/gorefs/goref-0000037.md

--- 
authors: UniProt-GOA
external_accession: 
  - "SGD_REF:S000148671 "
id: GO_REF:0000039
year: 2011
layout: goref
**+ ADD evidence_codes: ECO:000314, ECO:0002221, etc**
---

Would that work ? 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
I like this idea. I'll make a PR for the reference schema.

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/pull/1033

**Comment by dougli1sqrd** [comment]
@pgaudet your new goref field is now available!

**Comment by pgaudet** [comment]
thanks !

**Comment by dougli1sqrd** [comment]
This is complete. The current effort is here: https://github.com/geneontology/go-site/issues/1177
