### ISSUE TITLE
gorule-0000020 GAF with/from (Column 8) or extension (Column 16) should NOT contain obsolete terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#793]

**Comment by pgaudet** [comment]
Unless gorule-0000027 does that ? 
https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000027.md

Last time I checked it wasn't. Should I extend the description of gorule-0000027 ?

**Comment by pgaudet** [comment]
Still not implemented- ie obsolete GO classes with no replacement are not shown as errors in gorule-0000027, see for eg http://release.geneontology.org/2019-06-09/reports/ecocyc-report.html#gorule-0000020. 

Pascale

**Comment by dougli1sqrd** [comment]
This is a little more involved to do. We will need to figure out how to detect which IDs in which fields should correspond to which special ontologies, from which we could then do this upgrade in any field. 

This could be done as a global check. 

Some refactoring of the ID validation systems in ontobio might have to refactored somewhat to make this viable.

**Comment by sierra-moxon** [comment]
obsoletes in with/from repair: https://github.com/biolink/ontobio/pull/593

**Comment by pgaudet** [comment]
Suggestion to add this to gorule-0000020 
and edit the rule to say that obsoletes are tested in Col 4 (GOID), Col 8 (with/from), and Column 16 (extension)

**Comment by pgaudet** [comment]
To do with #844

**Comment by mugitty** [comment]
@pgaudet, for column 16 (Annotation Extension).  If there is no replacement GO term, should we remove the term and output warning message?

**Comment by mugitty** [comment]
@pgaudet according to http://geneontology.org/docs/go-annotation-file-gaf-format-2.0/#annotation-extension-column-16 (Annotation Extension), cardinality is zero or greater.  Will the fields be separated by pipe '|' similar to 'with' column?

**Comment by pgaudet** [comment]
@sierra-moxon Do you have more work to do on this, or should we re-assign this to @mugitty ?

**Comment by pgaudet** [comment]
I made 2 new tests, for annotation extensions

Need to rerun checks.

**Comment by pgaudet** [comment]
tests are failing correctly on @mugitty 's machine; need to test in a future release
