### ISSUE TITLE
gorule 32 has a bad form, but not caught by the validation step

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#798]
gorule32 passes validation but is in fact in bad form. This causes the pipeline to fail when running the sparta tests. The rule should be fixed in addition to the validate sparta command to fail on this rule when it's just text like this. Fixing the validate command will cause travis to correctly validate rule updates.

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/pull/797

**Comment by kltm** [comment]
@dougli1sqrd @cmungall  Just FYI, let's maybe move away from calling this 'yamldown' and start calling this 'frontmatter'? As this is more-or-less the default parser for jekyll, there already seems to be a bit of an ecosystem around it:
https://github.com/jonbeebe/frontmatter
https://pypi.org/project/python-frontmatter/
