### ISSUE TITLE
Add Gorule: ID prefixes should be repaired from synonyms to canonical forms

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#799]
Gorule-0000027 as stating that database prefix IDs should match what's in db xrefs. We can repair synonyms in cases that it exists in the dbxrefs. Let's upgrade synonyms in IDs when we can and report warnings (or maybe filter) when the ID prefix is not in dbxrefs.

**Comment by pgaudet** [comment]
Please provide an example.

**Comment by dougli1sqrd** [comment]
For example, you can see in the report here: http://release.geneontology.org/2019-03-18/reports/gramene_oryza-report.html#gorule-0000027

`GR_protein Q84Q78 OJ1364E02.5 GO:0000015 GR_REF:8030 IEA InterPro:IPR000941 C Hypothetical protein OJ1364E02.5 LOC_Os03g15950|Os03g0266200 protein taxon:39947 20060831 GR`

Has `GR_protein` in column 1, which is not allowed since it's not in dbxrefs. The message shows all the allowed dbxrefs. Here in the dbxrefs yaml: https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml#L1162 we can see that the form should be all caps: `GR_PROTEIN`. As a synonym though we have listed `GR_protein` (which is what we see in the line). 

This ticket says that we should upgrade db prefixes that appear in synonyms. Does this example make sense?

**Comment by pgaudet** [comment]
I think the example makes sense - except for 
> The message shows all the allowed dbxrefs. 
Do we really want to do that ? Sounds quite wordy. 

Thanks, Pascale

**Comment by cmungall** [comment]
I agree, it is rather wordy. I suggest just reporting the ID and a link to
the db-xrefs file

OR just reporting the complete list once

Otherwise great, thx!

**Comment by dougli1sqrd** [comment]
This is completed and in ontobio from https://github.com/biolink/ontobio/pull/311 and version 1.10.0. This just has to be updated in the go-site makefile but I'll wait for snapshot to clear.

**Comment by dougli1sqrd** [comment]
http://snapshot.geneontology.org/reports/gramene_oryza-report.html#gorule-0000027
We see messages indicating the upgrade:
> WARNING - ID or symbol not present in DB xrefs file: GORULE:0000027: GR_protein is a synonym for the correct ID GR_PROTEIN, and has been updated (GR_protein)

`curl -L http://snapshot.geneontology.org/annotations/gramene_oryza.gaf.gz | gzip -dcf | grep GR_PROTEIN | head`
Produces:
```
GR_PROTEIN	Q9ZTS1	Os06g0508700, LOC_Os06g31210		GO:0000049	GR_REF:8030	RCA	InterPro:IPR002547	F	Probable methionyl-tRNA synthetase	Methionine--tRNA ligase|MetRS	protein	taxon:4530	20060831	GR
GR_PROTEIN	Q06967	GF14F		GO:0000077	GR_REF:2029|PMID:7678761	ISS		P	14-3-3-like protein GF14-F		protein	taxon:4530	20060831	GR
GR_PROTEIN	Q06967	GF14F		GO:0000077	GR_REF:2030|PMID:8405471	ISS		P	14-3-3-like protein GF14-F		protein	taxon:4530	20060831	GR
GR_PROTEIN	Q9ST27	Osnph1b		GO:0000155	GR_REF:8030	RCA	InterPro:IPR000217	F	Nonphototrophic hypocotyl 1b	LOC_Os04g23890|Os04g0304200	protein	taxon:39947	20060831	GR
GR_PROTEIN	Q9ST26	Osnph1a		GO:0000155	GR_REF:8030	RCA	InterPro:IPR000700	F	Nonphototrophic hypocotyl 1a	Os12g0101800|LOC_Os12g01140	protein	taxon:39947	20060831	GR
GR_PROTEIN	Q9FRD1	OSJNBa0013M12.5		GO:0000155	GR_REF:8030	RCA	InterPro:IPR004358	F	Putative pyruvate dehydrogenase kinase	Os03g0370000|LOC_Os03g25400	protein	taxon:39947	20060831	GR
GR_PROTEIN	Q9AUQ0	OSJNBa0058E19.1		GO:0000155	GR_REF:8030	RCA	InterPro:IPR004358	F	Histidine-kinase like protein		protein	taxon:4530	20060831	GR
GR_PROTEIN	Q9ATR2	PDK		GO:0000155	GR_REF:8030	RCA	InterPro:IPR004358	F	Pyruvate dehydrogenase kinase	LOC_Os07g44330|Os07g0637300	protein	taxon:4530	20060831	GR
GR_PROTEIN	Q9SC66	nph1		GO:0000155	GR_REF:8030	RCA	InterPro:IPR000700	F	Non-phototropic hypocotyl NPH1	LOC_Os11g01140|Os11g0102200	protein	taxon:4530	20060831	GR
```
