### ISSUE TITLE
Makefile sparta report port randomization is not working correctly

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#801]
This line
https://github.com/geneontology/go-site/blob/master/pipeline/Makefile#L164
in the pipeline makefile is supposed to randomize the port used for the sparta checks. Apparently it's only picking 10000. This should be fixed to actually randomize the port number.

**Comment by kltm** [comment]
Trivial Makefile to test:
```Makefile
port := $(shell echo $$(( ((RANDOM<<15)|RANDOM) % 64000 + 10000 )) )
all:
        echo $(port)
```

**Comment by kltm** [comment]
Possible fix:
```Makefile
random := $(shell python -c 'from random import randint; print(randint(10000, 6$
all:
        echo $(random)
```
https://stackoverflow.com/questions/36106044/how-to-generate-random-number-in-a-range-in-makefile

**Comment by kltm** [comment]
$RANDOM is a bash-ism, so may not be particularly portable anyways. In this case, unless we extend Make (guile function anybody?), it needs to be grabbed from the outside with something that we know will be there. I'm comfortable with explicit bash (maybe `$(shell env bash -c 'echo $$RANDOM'`), python3 (as we need it elsewhere), etc.

**Comment by dougli1sqrd** [comment]
Huh, it's weird that it didn't work for you, cause when I do the same thing:
```
port := $(shell echo $$(( ((RANDOM<<15)|RANDOM) % 64000 + 10000 )) )

all:
	echo $(port)
```
```
edouglass@Erics-MacBook-Pro-2:~/lbl/geneontology/go-site/pipeline[master *?]$ make all
echo 65427
65427
```

But I understand there are different `make`s for machines, etc. So definitely I can definitely take in your suggesetions

**Comment by kltm** [comment]
This is a bash issue, not a Make one.

**Comment by dougli1sqrd** [comment]
`14:35:43 PY_ENV=mypyenv ./triplestore-rulecheck.sh 19119 target/blazegraph-production.jnl target/sparta-report.json`

In the most recent snapshot. 19119 sure is a random number! I'm calling this done.
