### ISSUE TITLE
new qualifiers should be allowed in GAF

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#802]
@dougli1sqrd 
Protein2GO is exporting these qualifiers, which are producing false errors in the reports (see for eg: http://release.geneontology.org/2018-09-05/reports/dictybase-report.html). 

1561 PARSER ERROR   Unknown qualifier: acts_upstream_of_or_within dictyBase DDB_G0267962 tsuA   acts_upstream_of_or_within GO:0043326 PMID:18708585 IMP P Probable   serine/threonine-protein kinase tsuA tsuA\|DDB_G0267962 protein taxon:44689   20080929 dictyBase

We need to allow these. I think this is a modification to gorule-0000001.md. 

Thanks, Pascale

**Comment by tonysawfordebi** [comment]
@pgaudet Really? It shouldn't be - there was a bug in our GAF export process when the new qualifiers were first introduced which meant that they did appear in some GAFs, but I'm pretty sure we fixed that.

@alexsign Can you verify that the new qualifiers are not finding their way into the GAFs?

**Comment by tonysawfordebi** [comment]
Also, I'm pretty sure that it was agreed at the NY meeting that we wouldn't extend GAF any further, and that the new qualifiers were to be GPAD-only.

**Comment by pgaudet** [comment]
Well they show up in the error reports, see http://release.geneontology.org/2018-09-05/reports/dictybase-report.html

Any idea where they come from ?

**Comment by pgaudet** [comment]
Sorry, it must be this one: 
ftp://ftp.ebi.ac.uk/pub/contrib/goa/dictyBase.gaf.gz (not the GPAD)

**Comment by pgaudet** [comment]
...  and in that file I do see the 'acts_upstream_of_or_within' qualifiers

For eg 
dictyBase	DDB_G0267376	acrA	acts_upstream_of_or_within	GO:0006171	PMID:11566867	IGI	UniProtKB:Q03100	P	Adenylate cyclase, terminal-differentiation specific

**Comment by tonysawfordebi** [comment]
AAAARRRRGGGGGHHHHH!!!!! Found it - there's one (dicty-specific) script that slipped through the net...

I'll fix it.

**Comment by tonysawfordebi** [comment]
Script now fixed, and files being regenerated.

**Comment by pgaudet** [comment]
great ! 
you mean no other species had that problem ??

**Comment by tonysawfordebi** [comment]
Yes - the problem was in a script that we put together specifically for dictyBase (to generate files with dicty IDs in column 2, rather than UniProtKB / RNAcentral ones); the scripts that we use for generating files as part of a GOA release had already been fixed.

**Comment by pgaudet** [comment]
Awesome, thanks !
