### ISSUE TITLE
Ensure mentions of CVS are expunged from main GO website

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#81]
Moved from: https://www.ebi.ac.uk/panda/jira/browse/GO-219

In general we should not be pointing people at CVS; in some cases we may need to refer to it - e.g. it's the only way to access full history. But in general it should be clear that we don't encourage access. In general external users should have no reason for VCS at all, use URLs that can be redirected

**Comment by mcourtot** [comment]
Duplicate #146

**Comment by pgaudet** [comment]
Dealt with in the new website.
