### ISSUE TITLE
 broken links

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#810]
I was looking for some old meeting minutes to reconstruct a timeline for my thesis:

I wanted to access the minutes for  some old meetings:
ftp://ftp.geneontology.org/go/www/GO.meetings.shtml

Can these documents be reinstated?  (they are an important part of the GO archive).

**Comment by kltm** [comment]
That is just a pointer into the legacy SVN (which was exposed on the web).
trunk/www/GO.meetings.shtml

**Comment by kltm** [comment]
This issue was moved to geneontology/go-docs#18
