### ISSUE TITLE
human proteome

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#819]
_From @ValWood on September 23, 2018 7:25_

How do I access the exact human reference proteome  dataset that is currently used by GO?

Is this it?
https://www.ebi.ac.uk/reference_proteomes

@Antonialock  if so we should use this one, as it should align with GO

Thanks,

Val

_Copied from original issue: geneontology/helpdesk#161_

**Comment by kltm** [comment]
_From @ValWood on September 23, 2018 7:28_

Except that it has fragments, and pseudogenes, and it doesn't seem straightforward to access the  HGNC IDs

**Comment by kltm** [comment]
@ValWood 
That's a good question. Honestly, if it's not an upstream or derived file and not accessible via metadata in the GAFs (then available in AmiGO or SPARQL), I'm not sure how you'd get at it.
Can you think of any way of filtering down to the data that you want?

**Comment by kltm** [comment]
_From @Antonialock on September 25, 2018 1:16_

This is the ticket I was referring to in our email exchange Val

**Comment by kltm** [comment]
_From @ValWood on September 25, 2018 5:16_

OK I totally forgot that I opened this ticket. Anyway @Antonialock  we  will proceed with the dataset you are using now.
We'll keep this one open  as I need to know for the GOC discussion
http://wiki.geneontology.org/index.php/2018_Montreal_GOC_Meeting_Agenda
representing complete proteomes


I guess the question is, is this the set of human uniprot accessions that can be submitted?

@selewis 

related ticket
https://github.com/geneontology/go-annotation/issues/2082

**Comment by ValWood** [comment]
closing...it was for
https://royalsocietypublishing.org/doi/10.1098/rsob.180241
