### ISSUE TITLE
Add additional links and tags to go rule report (gorule-report.html)

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#820]
Looking at gorule-report.html, a few visual/workflow improvements came up:

- [x] The y-axis rules should link to the rule .md in GitHub
- [x] The alt/title property for the y-axis should contain the rule description, so users do not need to click
- [x] each cell should contain both the file in question, the rule in question, and possibly the description, so if the user is fully scrolled with both axes away, they can still orient a little

**Comment by pgaudet** [comment]
Nice !
