### ISSUE TITLE
Add PAINT (paint_*) files to go rule report (gorule-report.html)

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#821]
Currently, while the go rule report (gorule-report.html) contains most of the inputs into the pipeline, it does not cover the upstream PAINT files. The paint_* files should be added to the report page for completion.

**Comment by dougli1sqrd** [comment]
http://snapshot.geneontology.org/reports/gorule-report.html
This shows paint.

**Comment by pgaudet** [comment]
Thanks !!! Awesome. 

I was envisioning a single PAINT report - can they be concatenated  into a single file ?
