### ISSUE TITLE
gorule-0000020 report: please display what repair was done

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#826]
GO RULE 20 : Obsolete terms get removed or replaced 

* When the term gets replaced, please display what it got replaced by
* also, please provide term labels for terms (obsolete/ replacements) (optional)

**Comment by pgaudet** [comment]
The way the reporting is done just shows the original line. Need to look into what it would take to implement this. Low priority.

**Comment by dougli1sqrd** [comment]
Pascale says that if the labels are hard, then this does not need to be done.

**Comment by pgaudet** [comment]
Wont do
