### ISSUE TITLE
gorule-0000027 should allow DOIs

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#836]
gorule-0000027 doesn't seem to allow DOIs, see for eg: http://snapshot.geneontology.org/reports/wb-report.html#gorule-0000027

Or is it that the format is incorrect ? 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
https://github.com/biolink/ontobio/pull/256

**Comment by pgaudet** [comment]
Seems fixed. The wormbase file does not have any doi errors anymore.
