### ISSUE TITLE
Add GAF header information to general report

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#837]
Currently, on the general GAF report page for a specific file, there is no header information to help orient readers.
This ticket would be closed on a GAF header pass-through.

**Comment by pgaudet** [comment]
Please also add the original file location.

**Comment by kltm** [comment]
"Original" as in the location of the source file preserved for the pipeline run.
(To remove confusion about the nature of "products", it may be worthwhile to consider a "source" directory.)

**Comment by pgaudet** [comment]
> To remove confusion about the nature of "products", it may be worthwhile to consider a "source" directory.

If possible it would be **very** useful to rename files and directories in there. I know we had said that we don't expect anyone to have to go in there, but as we saw yesterday, until we have other tools, curators need to look at these files. 

Can this be done 'easily'? 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
https://github.com/biolink/ontobio/pull/284

**Comment by dougli1sqrd** [comment]
For now, any naming or renaming won't happen in this ticket. At this point in the pipeline we don't know the future URLs for these files. We would need to come up with a more clever solution for that, and so let's make that a separate ticket if we want to do that.

**Comment by dougli1sqrd** [comment]
http://snapshot.geneontology.org/reports/fb-report.html#rmd

This shows the header from the original source fb file in snapshot.
