### ISSUE TITLE
GORULE:0000027 is incorrectly reporting DOIs 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#843]
DOIs do contain colons, periods and slashes, for eg DOI:10.1007/BF00127499

These are incorrectly reported as errors, see 
http://snapshot.geneontology.org/reports/fb-report.html#gorule-0000027

Thanks, Pascale

**Comment by kltm** [comment]
DOIs are fun!
https://www.crossref.org/blog/dois-and-matching-regular-expressions/

**Comment by dougli1sqrd** [comment]
Yep, that's going to be annoying. We can try the regex, but if we have a lot of DOIs that could get slow. How do we feel about accepting anything that is prefix `DOI` but non empty ID part?

**Comment by pgaudet** [comment]
Can we make it simple and check only the prefix ? (as stated in the rule?)

**Comment by dougli1sqrd** [comment]
This is done already for some time actually.
