### ISSUE TITLE
gorule-0000020 report should be sorted into ERROR, then WARNING

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#844]
gorule-0000020 does 2 things: 

1. Repair obsolete terms with a replaced_by tag, as well as merged terms with their new their primary IDs, anywhere in the file (including GO:ID (Col 5); with/from (Col 8), and annotation extensions (Col 16)
2. Report obsolete terms with no replaced_by tag. 

@dougli1sqrd Should I edit the md file to describe this? 

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
I thought we covered this in this update here: https://github.com/geneontology/go-site/pull/840/files ?

Feel free to make a new PR with the wording you think is more appropriate though.

**Comment by pgaudet** [comment]
OK. 

This rule is both a repair and a filter - can we have two types ?

**Comment by dougli1sqrd** [comment]
In the Great Rules Meetings, we decided that gorule-0000020 should be split apart. gorule-0000020 will say that obsolete terms with an upgradable term will be repaired. The new rule should say that terms without an obsolete upgrade will be filtered.

**Comment by pgaudet** [comment]
to do with #793

**Comment by pgaudet** [comment]
Problem with ontobio build, to be tested once this is resolved.

**Comment by pgaudet** [comment]
Looks OK on snapshot
