### ISSUE TITLE
Almost all GO annotations dropped for Cryptococcus neoformans taxon:214684

### ISSUE THREAD

**Issue by murphyte** [geneontology/go-site#845]
Hi GO -- 
With the latest GO release, the goa_uniprot_all_noiea.gaf.gz file went from 10018 rows for taxon:214684 to only 32. It looks like all 9986 annotations that were dropped were from PAINT and coded as IBA, and are old (nothing from the last year). Is the dropped annotation expected?

Thanks for checking!
-Terence

**Comment by tonysawfordebi** [comment]
I've just looked in our (GOA) database, and we currently have 12,650 annotations from PAINT to proteins from taxon:214684, so that's what I'd expect to see in the next set of files that we release (which is scheduled to happen next week).

**Comment by murphyte** [comment]
Thanks!
Do you have any advice on what we should do when the source GO data has such dramatic changes in content? Should I continue to report such occurrences here?

-Terence

**Comment by kltm** [comment]
@murphyte Thank you for noticing and taking the time to contact us.
For this question specifically, The GO source of IBAs is now PANTHER (https://github.com/geneontology/go-site/tree/master/metadata/rules#gorule0000026). If there is a concern around this, we should loop in more of the annotation group (@pgaudet @vanaukenk ) or move this item over to go-annotation to get more views.

**Comment by kltm** [comment]
@murphyte As far as reporting these things, well, I don't know your schedule, but it's always good from our perspective to know what people are seeing that has not been appropriately communicated to the community. If you have time for letting us know about issues that you're running into, we're happy to triage and check as best we can. Thank you for taking the time.

**Comment by murphyte** [comment]
ok, I'll continue to ping if we see issues. Thanks for the investigation here, and it sounds like our problems will resolve when the new files are out.
