### ISSUE TITLE
Entity Type issues in Annotation Downloads table

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-site#847]
The table that allows users to access annotations (bottom of geneontology.github.io/_docs/download-go-annotations.md, which links to http://current.geneontology.org/products/pages/downloads.html) currently displays "n/a" as the Entity Type, this should be "gene".

Also, the Annotation Downloads table needs to only display genes & proteins- complexes and other types should be in a separate table [@kltm @thomaspd @pgaudet @lpalbou please correct me if I binned these groups incorrectly]

**Comment by suzialeksander** [comment]
Possibly related: 
Should we review the files provided in this table? For example, the most recent annotation in the JCVI file is over 9 years old, and we link to a non-existent site http://cmr.jcvi.org/

**Comment by kltm** [comment]
The data there parrots what is found in the YAML metadata files:
https://github.com/geneontology/go-site/blob/master/metadata/datasets/
These can be updated easily, but I'm not familiar enough to insert the correct values. As well (maybe a different ticket), removing dataset entries for resources no longer needed.

**Comment by cmungall** [comment]
We should review the submissions that get included, but make separate tickets for this

**Comment by suzialeksander** [comment]
> As well (maybe a different ticket), removing dataset entries for resources no longer needed.
Ok, that ticket's made, #982

**Comment by pgaudet** [comment]
@kltm 
- What does n/a mean ? 
- Is there any way to fix the cases correctly (rna -> RNA; goa -> GOA, etc?) 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet 
* usually a variation of "none available" or "not applicable" 
* everything there is derived from the YAML metadata; fixes would be editing the metadata (or creating new metadata)

**Comment by pgaudet** [comment]
@kltm 
>everything there is derived from the YAML metadata; fixes would be editing the metadata (or creating new metadata)
I'll get the information from the groups where it's missing. I suppose there can be more than one value ? 

Thanks, Pascale

**Comment by kltm** [comment]
Labels are typically single-valued fields.

**Comment by pgaudet** [comment]
But in this case a single GAF may contain different types or entities, or is this not allowed ?

**Comment by kltm** [comment]
@pgaudet Apologies, I'm not following--there is a single entry per GAF. The only multi-valued fields are `taxa` and `datasets`.

**Comment by suzialeksander** [comment]
> But in this case a single GAF may contain different types or entities, or is this not allowed ?

@pgaudet  do you mean the DB Object Type? Yes, some of the GAFs contain different values in that column- e.g. the cow RNA GAF has primary_transcript/snRNA/rRNA/lnc_RNA/etc.; I think most of the  other GAFs are all genes (so these would be labelled "gene" not n/a) or all proteins, etc.

**Comment by pgaudet** [comment]
OK, so we could have say 'protein/microRNA' - that would be OK ? 
Is the separator a / ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
I have edited the SGN entity type in the yaml file to 'gene' and I dont see this reflected in the downloads page in snapshot 
http://snapshot.geneontology.org/products/pages/downloads.html

How should I do this ? 

Thanks, Pascale

**Comment by kltm** [comment]
When did you make the edit?

**Comment by suzialeksander** [comment]
Since she's probably offline tonight, I'm going to say 22 hours ago: https://github.com/geneontology/go-site/commit/41ce7e8528fe3738df65bb9641fa2ae49cdcb006

**Comment by suzialeksander** [comment]
For reference, these changes will only pop up when a new release triggers the Downloads page to be re-generated.

Looking at the GAFs, these have multiple entities: 

- TAIR: antisense_RNA, gene_product, lnc_RNA, miRNA, protein, pseudogene, RNA, rRNA, snoRNA, snRNA, transposable_element_gene, tRNA
- WB : gene, protein
- Zfin: protein_coding_gene pseudogene miRNA tRNA protein gene_product
- Dicty: protein snoRNA snRNA gene_product tRNA scRNA RNase_P_RNA RNase_MRP_RNA
- FB: gene_product protein rRNA ncRNA miRNA tRNA snoRNA snRNA
- CGD: gene_product protein
- ~~Ecoli: protein~~
- Pfalc: mRNA tRNA gene_product ncRNA
- Lmajor: mRNA gene_product (note: only 44x gene product)
- Tbrucei: mRNA gene_product snoRNA tRNA
- MGI: protein_coding_gene pseudogene gene_product gene_segment tRNA_gene scRNA_gene lncRNA_gene protein biological region snRNA_gene miRNA_gene ncRNA_gene snoRNA_gene lincRNA_gene sense_intronic_ncRNA_gene gene rRNA_gene RNase_P_RNA_gene telomerase_RNA_gene mRNA sense_overlap_ncRNA_gene RNase_MRP_RNA_gene SRP_RNA_gene
- Pseudo: protein, tmRNA, ncRNA
- RGD: gene, protein
- SGD: protein gene protein_complex snoRNA tRNA ncRNA rRNA snRNA telomerase_RNA 
- ~~Sjap: protein~~
- Pombe: protein, tRNA, gene_product, snoRNA, rRNA, snRNA, protein_coding_gene
- Xenbase: protein, gene

I've specified the Japonicus and E coli entity types.

@pgaudet what do you want to do about the rest that are mixed types?

**Comment by suzialeksander** [comment]
closing as dupe of https://github.com/geneontology/go-site/issues/1018
