### ISSUE TITLE
Add file types to Annotation Downloads table

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-site#848]
For the produced annotation downloads page (http://current.geneontology.org/products/pages/downloads.html), file types should be added as separate columns. (GPI, GAF, GPAD)

[@kltm edited from original]

**Comment by pgaudet** [comment]
Is this done ? 
The extension is there - and there only seem to be GAFs (perhaps less chances of confusion for users than if we had multiple file types?)

**Comment by pgaudet** [comment]
We'll reopen when we add the GPI/GPAD files back.
