### ISSUE TITLE
New Noctua user(s?) and group for CACAO 

### ISSUE THREAD

**Issue by jrr-cpt** [geneontology/go-site#849]
I have filled out the new user form to request access to Noctua. I work with @jimhu-tamu doing GO annotation in the CACAO class. My interest is to expand annotation for phage.

There is not a user group that we fit into in the [metadata](https://github.com/geneontology/go-site/blob/master/metadata/groups.yaml) referred to in the new user form. Can we have EcoliWiki/CACAO added?

**Comment by kltm** [comment]
@jrr-cpt It may take a moment to figure out what to do in this case, I hope you don't mind bearing with us as we sort through it--the hows of training and inclusion of people is still something under debate internally. (Tagging @vanaukenk.) For the use of Noctua for CACAO, we'd likely want to help you setup and maintain a separate instance as the primary GO instance is for vetted curation by internally trained groups and collaborators, or help with the creation of an intermediate client.

If you are interested in learning more about and how to use Noctua, we can also give easier access to the development instance of Noctua at "http://noctua-dev.berkeleybop.org", which may be sufficient for use cases.

**Comment by jrr-cpt** [comment]
I will explore the dev instance as a start. 

I did not mean to imply that we intend to begin having CACAO students use this interface in the near future. Improving the phage annotation base is my primary interest, and I am not associated with any formal GO Consortium groups, just trying to learn from the EcoliWiki/CACAO group. As I learn more about the current methods employed in making useful annotations, I was led to consider whether the models coming out of Noctua are the best for our needs.

**Comment by kltm** [comment]
@jrr-cpt Apologies, this is still under discussion.
To get started, however, no matter what we should at least have your groups' information. Would you mind start by either giving your group information here or starting a PR?

**Comment by jrr-cpt** [comment]
@jimhu-tamu and @sandyl27 are two users in our group. And it turns out that we are in the list as   label: E. coli
id: http://www.bio.tamu.edu
shorthand: E_coli
