### ISSUE TITLE
Migrate and useful scripts or software bits from the SourceForge SVN to GitHub

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#85]
Migrate and useful scripts or software bits from the SourceForge SVN to GitHub.

The current list is:
- go_db_install.pl
- go_db_install_wrapper.pl

**Comment by kltm** [comment]
Anything else?

**Comment by cmungall** [comment]
I think these are the only standalone scripts.

We should still move over go-dev (perhaps splitting go-perl into its own repo). These could remain in my github space rather than in the go org to reflect the fact the GOC no longer supports

**Comment by kltm** [comment]
For things that we still need for the legacy load, that might go fine under its own project just in case it still needs to be modified for some reason (legacy-perl?), or at least to make it easily forkable by people who might care.
For the rest, yes, it's probably best to put it out of the way so that it is accessible, but clearly downgraded.

**Comment by kltm** [comment]
Ugh, there are all sorts of sql/ dependencies everywhere that I didn't remember--the scripts will only half work. (I'd also forgotten what a PITA the MySQL db was to maintain looking at all that stuff.)

Does Tony have a GitHub ID?

**Comment by tonysawfordebi** [comment]
Apart from the dependencies on the various sql scripts, go-db-install.pl also has some hard-wired assumptions about file locations and directory structures. It's not pretty.

**Comment by kltm** [comment]
Hm, it works for me now (https://build.berkeleybop.org/view/GO/job/load-mirror-go-latest/454/). Are there problems that you're still having in there? I haven't tried a full load, only lite...

**Comment by tonysawfordebi** [comment]
Don't know yet... in order to minimise the amount of disruption to my scripts, I tried grabbing the go-site repo using svn rather than git:

svn checkout https://github.com/geneontology/go-site

and it failed with this error:

svn: Failed to add directory 'go-site/trunk/scripts/legacy-sql/migrate/.svn': an unversioned directory of the same name already exists

**Comment by kltm** [comment]
Okay, I think I got all of the old cruft out--the SVN checkout now works for me.

**Comment by tonysawfordebi** [comment]
Excellent! Works for me too now - thanks, Seth.

**Comment by kltm** [comment]
I think this is all done with, yes?
