### ISSUE TITLE
Correction parameter for Enrichment Analysis

### ISSUE THREAD

**Issue by mugitty** [geneontology/go-site#850]
PANTHER Enrichment service is invoked with correction parameter set to 'bonferroni'.  The default is 'FDR'.  Update to not specify the correction parameter or set correction parameter to 'FDR'

**Comment by kltm** [comment]
@cmungall My understanding is that Bonferroni was the desired correction for our users.

**Comment by mugitty** [comment]
Currently, PANTHER uses FISHER with FDR by default

**Comment by lpalbou** [comment]
@mugitty this is now corrected in https://github.com/geneontology/geneontology.github.io/pull/154.
Changes should be deployed in a minute.
