### ISSUE TITLE
NO_MAPPING evidence code appearing in GOA data

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#851]
We noticed that many annotations in GOA have the symbol `NO_MAPPING` as  the evidence code in the gaf. For example, goa_human_complex has ~1000, goa_chicken_complex has ~50, etc.

This looks like (from goa_chicken_complex):
```
ComplexPortal	CPX-960	collagen_ii_chick		GO:0030020	PMID:26059120	NO_MAPPING		F	Collagen type II trimer	Type II collagen|COL1A2 trimer	protein_complex	taxon:9031	20170526	ComplexPortal
```

**Comment by kltm** [comment]
Pinging @tonysawfordebi 
For the time being, these are naturally being filtered.

**Comment by pgaudet** [comment]
@bmeldal

**Comment by tonysawfordebi** [comment]
Those shouldn't be there - clearly something has gone wrong with our GAF-dumping script when it encounters annotations that use ECO codes that don't map to a legacy GO evidence code. We'll fix it.

@alexsign

**Comment by alexsign** [comment]
The GAF files are fixed and uploaded to GOA ftp. Sorry for the inconvenience.

**Comment by kltm** [comment]
No problem! That should get picked up tonight and things should continue on.
