### ISSUE TITLE
Remove reduction allowance in sanity check for goa_chicken_complex

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#854]
Currently there is a data in the incoming goa_chicken_complex source GAF that is being filtered, causing the sanity check to fail seeing a large decrease in file size. See here: https://github.com/geneontology/go-site/issues/851

Once this issue is fixed, let's undo this special case allowance. goa_chicken_complex is mostly well behaved so this is just a temporary measure.

**Comment by pgaudet** [comment]
Was this just a one-off? 
And is this superseded by the new manual check step in the release process ? 

@kltm

**Comment by kltm** [comment]
@pgaudet Let's close and see what happens.
