### ISSUE TITLE
Can't trace source  annotation  GO_AR:0000008

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#861]
I'm stumpled by this one:

31303	GO_AR:0000008	Warning	Do not annotate to: GO:0005622 'intracellular' The term is considered to high level, as marked via the subset tag: gocheck_do_not_annotate PomBase	SPAC24H6.09	gef1	GO:0005622	PMID:24146635	IDA	C	Cdc42 RhoGEF Gef1	protein	taxon:4896	20140225	PomBase	exists_during(GO:0034605)	

This has "PomBase" as assigned_by
But we didn't make this annotation as far as I can see?

If it was from an inference it would have GOC is that correct?

**Comment by mah11** [comment]
We did make that annotation. On Monday, I changed it to cytoplasm (GO:0005737) when I saw that warning (or rather, the equivalent in a local owltools run). I also updated the GAF on Monday, so the better question is "how long does it take for the snapshot reports to be updated after a file update?".

**Comment by ValWood** [comment]
Ah OK, I thought I had a handle on "intracellular" ...
Snapshots are usually daily, but occasionally take longer if there is a problem.
