### ISSUE TITLE
create a table summary of the rules reporting the status

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#866]
Contains rule number, description, status
make it easy to find from the reports

**Comment by ValWood** [comment]
This is what we agreed in Montreal.

A view like this:
https://github.com/geneontology/go-site/tree/master/metadata/rules

but with human readable rule names, and the ability to quickly scan the list  to see if we have any violations (and how many). By  species. I only want to see PomBase. I think others would find this useful.

OK I guess this does it!
http://release.geneontology.org/2019-01-01/reports/paint_pombase-report.html

I guess I was confused because we have only violations for one rule.

@mah

**Comment by ValWood** [comment]
Found 13050 annotations in 13061 lines.
sounds low?

**Comment by ValWood** [comment]
I don't fully understand the contents of this file though....

**Comment by ValWood** [comment]
@kltm I don't have permissions to assign

**Comment by kltm** [comment]
@ValWood You should now have permissions, but we do not yet know where this work is relative to other items and who would perform it.

**Comment by ValWood** [comment]
Assigned to you so it doesn't fall through the cracks. This was an action from Montreal I'm sure. I guess you will assign to the right person...

**Comment by cmungall** [comment]
In an email @ValWood asked for short titles.

Is the action here to

 1. reduce the length of some existing rule names
 2. curate an additional 'short name' field that can be used in summary section of reports?

Here is a random sample:

```
GORULE:0000029 All IEAs over a year old are removed
GORULE:0000030 Deprecated GO_REFs are not allowed
GORULE:0000031 Annotation relations are replaced when not provided by source
GORULE:0000032 Allowed References for each ECO.
GORULE:0000033 Group specific Reference IDs (column 6) will be replaced by corresponding GO_REF (or other public ID) or filtered.
GORULE:0000035 'Colocalizes_with' qualifier not allowed with protein-containing complex (GO:0032991)' and children.
GORULE:0000036 Report annotations that involve gene products where the gene product is annotated to a term 'x' and 'regulation of X' (multiple annotations involved)
```

Some like GORULE:0000032 I think are *too* short, it's not clear what this one 

Some are overly wrong and are recapitulating information that should be in the full description. E.g. if we use the standard GAF/GPAD terminology (e.g. reference ID) then we do not need to say "column 6" (which is file-format specific; the descriptions should be about the *data model*, not the format).

I suggest writing all of these in the active voice, using concise language, following ISO terminology for shall/must/should etc. https://www.iso.org/foreword-supplementary-information.html

E.g. GORULE:0000033 becomes "Remove or replace group-specific references"

**Comment by ValWood** [comment]
Yes! They are difficult to interpret or unnecessarily verbose.

**Comment by dougli1sqrd** [comment]
I created https://github.com/geneontology/go-site/issues/1165 and https://github.com/geneontology/go-site/issues/1164 as a result of the above discussion. I'll close for now, but if there's anything else open this again.
