### ISSUE TITLE
Add ECO contacts in group-contacts.csv

### ISSUE THREAD

**Issue by nsuvarnaiari** [geneontology/go-site#870]
Could you please add Michelle, Suvvi, James and Becky in the group-contacts.csv for ECO group contacts.

Michelle : @mgiglio99
Suvvi : @nsuvarnaiari
James : @jbmunro
Becky : @rctauber

Thanks,
Suvvi

**Comment by pgaudet** [comment]
Done - let me know if it's OK. 
https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

I also invited everyone to be a member of the project, please check your inbox and accept the invitation. 

Thanks, Pascale

**Comment by nsuvarnaiari** [comment]
Hi @pgaudet 

Thanks for adding us in the list. One mention, I did not get any invitation. You may want to check if there is a typo while entering my github handle.

Thanks,
Suvvi

**Comment by pgaudet** [comment]
You were already a member :)
