### ISSUE TITLE
Column 17 (gene product form ID) information being stripped from GAF

### ISSUE THREAD

**Issue by tonysawfordebi** [geneontology/go-site#871]
We've just been informed that the published version of the goa_human_isoform GAF (http://www.geneontology.org/gene-associations/goa_human_isoform.gaf.gz) is missing column 17

The column is definitely present in the source file (ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human_isoform.gaf.gz) so it would appear that something is amiss with the pipeline that fetches and filters the files.

I haven't checked any of the other species-specific isoform GAFs, but I suspect that if one of them is affected in this way, then they all will be.

**Comment by kltm** [comment]
@dougli1sqrd It looks like that information is indeed just being straight stripped out, without the annotation being filtered.

http://snapshot.geneontology.org/annotations/goa_human_isoform.gaf.gz (our product)
vs
ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human_isoform.gaf.gz (upstream)

Any idea? There seems to be no corresponding rule violoation.

**Comment by dougli1sqrd** [comment]
Oh that's super weird. I'll take a look

**Comment by kltm** [comment]
Also note from @cmungall : we are not writing interacting taxon id either

**Comment by dougli1sqrd** [comment]
So I have this: https://github.com/biolink/ontobio/pull/262 Which should fix the column 16 and 17 issues. Regarding the extra taxons, @cmungall at some point we decided to only use the first taxon id. I'm not sure what the fix for the "interacting taxon" is, or what your visions was there.

**Comment by cmungall** [comment]
@dougli1sqrd, there is no vision, just the GAF spec

**Comment by kltm** [comment]
Narrowing this and adding taxon check to new ticket.

**Comment by kltm** [comment]
Checking skyhook output.
Lines like
```
UniProtKB       A0A087WTH5      KCNE1B          GO:0005249      GO_REF:0000002  IEA     InterPro:IPR000369|InterPro:IPR005424   F       Potassium voltage-gated channel subfamily E member 1B   KCNE1B  protein taxon:9606      20181006        InterPro                UniProtKB:A0A087WU88
```
now output as
```
UniProtKB       A0A087WTH5      KCNE1B          GO:0005249      GO_REF:0000002  IEA     InterPro:IPR000369|InterPro:IPR005424   F       Potassium voltage-gated channel subfamily E member 1B   KCNE1B  protein taxon:9606      20181006        InterPro                {'filler': 'UniProtKB:A0A087WU88', 'property': 'isoform'}
```
@cmungall @dougli1sqrd Is the "upgrade" to explicit JSON desired here?

**Comment by tonysawfordebi** [comment]
That's not valid GAF-speak...

**Comment by dougli1sqrd** [comment]
Yeah this isn't right. Sorry about this. I'll see what happened.

**Comment by kltm** [comment]
For this and https://github.com/geneontology/go-site/issues/872, we should have a test where input === emitted output on full-featured GAF lines.

**Comment by dougli1sqrd** [comment]
I understand what happened now. My test from assoc object to annotation in the writer was wrong. My test data was incorrect. But you're right, better round trip tests would be good too.

**Comment by dougli1sqrd** [comment]
https://github.com/biolink/ontobio/pull/263

**Comment by dougli1sqrd** [comment]
Okay go-site (the pipeline) is updated, and we should see fixed results tomorrow afternoon.

**Comment by kltm** [comment]
I've checked in with @dougli1sqrd , there still seems to be issues with this. We'll figure out what failed in the unit tests and then try and get this cleared before the release.

**Comment by kltm** [comment]
It looks like there was an issue with travis, make, and what tests were being run. @dougli1sqrd is on the case.

**Comment by kltm** [comment]
Product now appears to be clear on skyhook for `snapshot`.
