### ISSUE TITLE
PURLs for the ontology need to point to 'current' rather than 'snapshot'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#873]
See http://geneontology.org/page/download-ontology
Can this be done soon ? Since we mention in our documentation that users should not use snapshot. 

Thanks, Pascale

**Comment by lpalbou** [comment]
@cmungall you are the only one (to my knowledge) having access to OBO to change those PURLs. Can you help us ?

**Comment by cmungall** [comment]
Anyone can make a PR: https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/go.yml

**Comment by lpalbou** [comment]
@cmungall https://github.com/OBOFoundry/purl.obolibrary.org/pull/489 

I also changed the last "/" as I think the GO PURL should point to current and not snapshot, please confirm

**Comment by pgaudet** [comment]
Do we want this information public ? I thought we had said no. 

Do we anyway have links to /current? (I can't see them in your changes).

**Comment by lpalbou** [comment]
PURL go.obo are now pointing to current and not snapshot anymore (e.g. 
http://purl.obolibrary.org/obo/go.obo)

However, the snapshot URLs were indeed also added in http://geneontology.org/docs/download-ontology/ . I don't know where the requirement came from ?
