### ISSUE TITLE
Implement gorule-0000015

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#881]
https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000015.md

Annotations to terms that have the biological process term 'GO:0051704 : multi-organism process' or the cellular component term 'GO:0044215 : other organism' as an ancestor should contain two different Taxon IDs.

**Comment by kltm** [comment]
https://github.com/biolink/ontobio/issues/363
