### ISSUE TITLE
Implement gorule-0000007

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#885]
See feedback https://github.com/geneontology/go-annotation/issues/2131
before deciding on the implementation of this rule.

**Comment by pgaudet** [comment]
The rule is 'IPI should not be used with catalytic activity molecular function (GO:00038249) or children terms'

**Comment by cmungall** [comment]
The wording on this is v vague:
https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000007.md

Can we write this more like a specification?

**Comment by cmungall** [comment]
@dougli1sqrd you moved this to "Clearing". However, it's not clear if there is something blocking, and what has been done?

Can you remember to tag issues in commits? E.g. tagging this ticket in commits that address the issue. Also just giving a brief narrative update in tickets like this one is very useful. Thanks!

**Comment by dougli1sqrd** [comment]
Clearing means where waiting for the results to show up in the pipeline run. Looking at latest snapshot, we see that the implementation of gorule 7 is running live now. http://snapshot.geneontology.org/reports/gorule-report.html. This means this can be closed.
