### ISSUE TITLE
Fix gorule-0000039 to look at GO:0032991's (protein-containing complex) descendants

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#895]
Currently, this looks only checks for direct annotations to GO:0032991 protein-containing complex. It needs to look at all children of GO:0032991 and report an error if the 'object type' (GAF column 12) is 'complex'

**Comment by ValWood** [comment]
I don't understand that rule?

**Comment by pgaudet** [comment]
We dont want to allow annotations like: 
ComplexPortal:RNA polymerase II:  GO:RNA polymerase II complex. 

This is already a cross-reference.

**Comment by kltm** [comment]
This can be cleared and closed once the rule is fixed--it currently only looks at direct annotations, not children.

The implementation is likely pretty easy, but just needs to be prioritized. 
@dougli1sqrd @pgaudet

**Comment by pgaudet** [comment]
To find complexes in the GAF: [DB Object Type](http://geneontology.org/docs/go-annotation-file-gaf-format-2.2/#db-object-type-column-12) complex

**Comment by pgaudet** [comment]
This rule is now working, failing tests as expected.
