### ISSUE TITLE
New gorule0000040 Check for valid combination of evidence code and GO term

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#897]
P2GO check 

@tonysawfordebi 

Can you give the specific details of that check (which ECO for which terms? 

Thanks, Pascale

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-site/pull/898

**Comment by tonysawfordebi** [comment]
P2G has three places where it does this check:

- evidence is IEP (ECO:0000270) or HEP (ECO:0007007) and GO term is not a process term
- GO term is one of the three root terms (GO:0005575, GO:0008150, GO:0003674) and evidence is not ND (ECO:0000307)
- evidence is ND and the GO term is not one of the root terms

**Comment by pgaudet** [comment]
> evidence is IEP (ECO:0000270) or HEP (ECO:0007007) and GO term is not a process term
-> gorule-0000006

>  GO term is one of the three root terms (GO:0005575, GO:0008150, GO:0003674) and evidence is not ND (ECO:0000307)
-> gorule-0000011

>  evidence is ND and the GO term is not one of the root terms
-> gorule-0000011

So it looks like we don't need that rule.
