### ISSUE TITLE
Fix download annoations metadata for downloads pages

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/go-site#9]
I would like to modify text at http://beta.geneontology.org/page/download-annotations but I do not currently have permission to edit this page.

**Comment by mcourtot** [comment]
Hi Seth - can you (or Chris) update the links on this page to reflect the new filenames? There have been a few download issues, see http://jira.geneontology.org/browse/GO-1248 and http://jira.geneontology.org/browse/GO-1249

**Comment by cmungall** [comment]
JSON-driven. No need to update the page. Covered here #190

**Comment by suzialeksander** [comment]
No longer use JIRA
