### ISSUE TITLE
email alerts of new tickets posted

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-site#90]
Could we have a similar alert system as we had from SF that tell us if new tickets or new comments on existing tickets have been posted? Makes it easy to keep an eye on posts that might be relevant to one's work and also be helpful for the poster to get community input.

Thanks,
Birgit

**Comment by hdietze** [comment]
I have create a script similar to the SF one. It seems to be working fine and I will run tests over the weekend. If these test run well, the e-mails should be ready early next week.

Known limitation: 
 * Max 100 issues.
   If there are more than 100 search results (i.e. new issues) the github search api makes it very difficult to retrieve them (pagination links are part of the response header, not the json body)

see commits:
 * owlcollab/owltools@6e80dee0c64fbf1776fab56c326e9c7853016999
 * owlcollab/owltools@7919c6e4b71d8901d551a730929b3017f29127ae

Relevant jenkins jobs:
 * https://build.berkeleybop.org/job/go-github-ontology-requests-summary-email/
 * https://build.berkeleybop.org/job/go-github-annotation-tracker-summary-email/

**Comment by hdietze** [comment]
Summary e-mails are now being send to the lists again.

**Comment by bmeldal** [comment]
Thanks, Heiko!
