### ISSUE TITLE
New gorule-0000043 Reference: check for valid combination of evidence code and GO_REF

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#904]
P2GO rule

@tonysawfordebi Can you give the combinations of evidence code and GO_REF?

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-site/pull/905

**Comment by tonysawfordebi** [comment]
The valid combinations that we currently allow in P2G are:

- ND (ECO:0000307): GO_REF:0000015
- ISS (ECO:0000250): GO_REF:0000024
- ISA (ECO:0000247): GO_REF:0000030, GO_REF:0000113
- ISM (ECO:0000255): GO_REF:0000030, GO_REF:0000050
- ISO (ECO:0000266): GO_REF:0000024
- IC (ECO:0000305): GO_REF:0000036, GO_REF:0000057, GO_REF:0000111
- IKR (ECO:0000320): GO_REF:0000047
- IDA (ECO:0000314): GO_REF:0000052, GO_REF:0000054

Note that this is probably not an exhaustive list.

**Comment by pgaudet** [comment]
Thanks @tonysawfordebi 
Where can I look to make that list exhaustive ?

**Comment by alexsign** [comment]
@pgaudet Hi Pascale, can gorule-0000043 be fixed.
https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000043.md 
Right now it says: "Specific forbidden combinations:" which should be "Specific allowed combinations:"
See Tony's post from 9 Nov 2018 on this ticket.

**Comment by pgaudet** [comment]
Done, thanks for pointing that out ! 

Pascale

**Comment by jimhu-tamu** [comment]
@pgaudet can you add allowed ECO for the two Phage CACAO GO_REFs?

From @ivanerill 
> GO_REF:0000100 was created for SEA-PHAGES annotation and was restricted to ISS, ISA, ISO, ISM, IGC and ND GO evidence codes.
> The more recent GO_REF:0000112 was defined for ISS, ISA, ISO, ISM and IGC evidence codes.

**Comment by dougli1sqrd** [comment]
How is this mapping to be interpreted? Is this, GO_REF:x --> ECO:Y, ECO:Y --> GO_REF:X, or GO_REF:X <--> ECO:Y ?

**Comment by dougli1sqrd** [comment]
To clarify, is this a "if and only if" situation, and "If GO_REF then ECO", or "if ECO then GO_REF"?

**Comment by ivanerill** [comment]
This should be a GO_REF-->ECO rule. That is, these ECO terms should be
admissible when using the GO_REF. Not the only way around.

**Comment by dougli1sqrd** [comment]
https://github.com/biolink/ontobio/pull/375
