### ISSUE TITLE
Remove MGI doubling up

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#91]
Lori has produced a report here:

ftp://ftp.informatics.jax.org/pub/reports/

**Comment by cmungall** [comment]
Issue: col6 still has doubling up

> MGI     MGI:1918911     0610005C13Rik           GO:0003674      MGI:MGI:2156816|GO_REF:0000015  ND              F       RIKEN cDNA 0610005C13 gene              gene    taxon:10090     20100209        MGI

**Comment by pgaudet** [comment]
Is this now revolved @kltm @ukemi @balhoff  ?
