### ISSUE TITLE
Implement gorule-0000047: With/from: ChEBI IDs in With/from can only be used with terms that are descendants of GO:0005488 (binding), except for protein binding (GO:0005515) and protein-containing-protein

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#912]
P2GO rule

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-site/pull/913

**Comment by pgaudet** [comment]
@dustine32 or @lpalbou Can you run a query to check if we have cases that fail this proposed rule?

**Comment by kltm** [comment]
This can be done, but requires prioritization, but the implementation should be pretty easy.

**Comment by pgaudet** [comment]
There would be many exceptions here: protein binding, protein-containing complex binding. nucleic acid binding, etc. 

This is too complicated to implement now.
