### ISSUE TITLE
New gorule-0000052: Check whether the combination of gene product and GO term is blacklisted

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#919]
P2GO rule

@tonysawfordebi Can you provide the list ?

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-site/pull/920

**Comment by tonysawfordebi** [comment]
The current blacklist is in the attached spreadsheet.

Note that the contents of the list are dynamic, and are derived from three sources. Here's an edited version of the description of what the blacklist contains, taken from the old version of QuickGO:

There are three categories of entry in the list:

1. Negative associations curated from IEA pipeline review
A list of gene product-to-GO term associations that have been observed as being incorrect from the review of annotations obtained from an IEA pipeline. These associations are often added when a curator has observed that a function/process term is being over-predicted to a group of gene products.
Some electronic annotation sources have a cut-off criterion such that if the annotation is true for a given threshold percentage of the gene products in the set, it is considered relevant for GO mappings to be added to the FULL set. The blacklist endeavours to highlight those gene products that may have been caught out in the 5% to provide users with as correct a set of annotations as possible.

2. Negative associations obtained from NOT-qualified GO annotations (annotation set updated weekly)
These gene product-to-GO term associations have been created when a gene product has been expected to have a particular function, associated process or location, but specific experimental or sequence-based evidence has been curated to demonstrate the contrary. These NOT-qualified GO annotations are obtained from the current GOA annotation set and are updated weekly.

3. Negative associations obtained from UniProt COMMENT_CAUTION entries (annotation set updated weekly)
These protein-to-GO term associations have been created when a 'caution' comment in the UniProt entry indicates that a protein does not have the expected function, process or location. These comments are added manually by UniProt curators after reviewing the sequence or literature.

[annotation_blacklist_2018-11-09.xlsx](https://github.com/geneontology/go-site/files/2565219/annotation_blacklist_2018-11-09.xlsx)

**Comment by pgaudet** [comment]
@cmungall @kltm I'm happy to convert this into whatever format we need, if you want. 
Let me know where the file should be saved.

**Comment by kltm** [comment]
@tonysawfordebi That list is like 10k lines. Is that an accumulation of a lot of "bads" manually curated, or is there an algorithm that is generating it?

**Comment by pgaudet** [comment]
We need to understand exactly is being checked and decide how to implement.

**Comment by pgaudet** [comment]
@dougli1sqrd This was created as gorule-0000051 but I cannot see it.... We need to check together.

**Comment by kltm** [comment]
Talking to @pgaudet and @dougli1sqrd , this is a "blacklist" ticket and needs further discussion, etc. We'll revisit this later on.
