### ISSUE TITLE
New rule: Identify annotations to the function term "mRNA binding involved in post transcriptional gene silencing" (GO:1903231) that lack a corresponding annotation to the process term "gene silencing by miRNA" (GO:0035195) or one of its descendants

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#921]
P2GO rule. 

Do we want to do this ? It seems like this could be handled with P-F links. 

@vanaukenk

**Comment by vanaukenk** [comment]
Might be good to ask @rachhuntley about this one.  

Right now, it doesn't look like there's an F-P link for between two terms in the ontology, so I'd be interested to know more about why this rule was implemented before we decide.

**Comment by ukemi** [comment]
Aren't there post-transcriptional mechanisms to gene silence that aren't miRNA mediated? I thought there were other types of RNA that could mediate this.

**Comment by rachhuntley** [comment]
Yes, siRNA can bind to mRNA to silence it as well (see link below). I'm not sure where this rule originated from, I don't *think* I would have requested it.
If anything, I would suggest a F-P link between the function term and "posttranscriptional gene silencing by RNA" or one of its descendents? I don't know enough about the other PTGS mechanisms to recommend a link to the parent "posttranscriptional gene silencing" - i.e. do all these mechanisms require mRNA binding?

https://www.researchgate.net/publication/282035687_siRNA_Versus_miRNA_as_therapeutics_for_gene_silencing/figures?lo=1

**Comment by tonysawfordebi** [comment]
@rachhuntley This check, and the accompanying P2G report, arose from the conversation we had back in November 2016, in the email thread with the subject "Possible edit to PSICQUIC miRNA interaction type".

**Comment by RLovering** [comment]
Sounds like a very useful check though ;)

**Comment by rachhuntley** [comment]
I think the check is in place, but I guess we never get a report because there aren't any missing BP annotations?

**Comment by tonysawfordebi** [comment]
Yes, exactly that.

**Comment by pgaudet** [comment]
At the QC call we decided not to implement this in the gorules.
