### ISSUE TITLE
Update gorule-0000006 to include HEP

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#927]
"IEP and HEP usage is restricted to terms from the Biological Process ontology"

**Comment by kltm** [comment]
See #925

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-site/pull/925

**Comment by pgaudet** [comment]
#925 is the modification of the description of the rule. We still need to modify the rule.

**Comment by pgaudet** [comment]
Yes, we need to change the implementation of the rule, I changed the title to reflect that. 

Thanks !
