### ISSUE TITLE
gorule-0000046: add clear/implementable description

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/go-site#930]
Would an explanation like this work?
```
Since these gene products are 'self-binding', they interact with themselves, and as such, should also be listed in the 'with/from' column, in addition to being the gene product.

Self-binding terms include GO:0042803 protein homodimerization activity, GO:0051260 protein homooligomerization, and GO:0043621 protein self-association (and their descendants)
```

This adds a lot of information for people like me. Since I know how the GAF works, this puts your biological rule in terms of what is happening in the GAF. I'm not sure if my explanation is actually accurate, but something like this is helpful.

**Comment by pgaudet** [comment]
See https://github.com/geneontology/go-site/pull/933

**Comment by pgaudet** [comment]
@vanaukenk 
Is the decision to keep 
GO:0042802 identical protein binding
and     GO:0043621 protein self-association? 

Thanks, Pascale
