### ISSUE TITLE
New gorule-0000050 ISS annotations and children should not be self-referential

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#934]
New P2GO rule

Annotations to ISS, ISA and ISO should not have the same identifier in the 'gene product column' (column 2) and in the 'with/from' column (column 8).

**Comment by pgaudet** [comment]
This is implemented - @dougli1sqrd can you link the PR ?

**Comment by dougli1sqrd** [comment]
Implemented and rule exists. https://github.com/biolink/ontobio/pull/353
