### ISSUE TITLE
PANTHER files on download site need to have PTN's in the attr.tab file

### ISSUE THREAD

**Issue by selewis** [geneontology/go-site#94]
files in http://data.pantherdb.org/PANTHER10.0/books/ do not have the PTN id and these are essential information that must be included. Both AmiGO and touchup rely on these being present.

**Comment by mugitty** [comment]
Files are available in http://data.pantherdb.org/PAINT_PANTHER10.0

**Comment by selewis** [comment]
Super, thanks
