### ISSUE TITLE
GO rules schema: change rule types

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#945]
Current rule types are: 

RULE TYPE -> behavior
filter -> filter out from the GAF at import, report annotations lines that were filtered in the gorule report
report -> no action on data, report affected annotations lines in the gorule report
repair -> fix data at import, report affected annotations lines in the gorule report

PROPOSED: 
NEW: 
excluded: > filter out from the GAF at import, do not report anything in the report
filter -> filter out from the GAF at import, report annotations lines that were filtered in the gorule report
report -> no action on data, report affected annotations lines in the gorule report
repair -> fix data at import, report affected annotations lines in the gorule report

@kltm @dougli1sqrd @selewis 
Does that work ? If it's OK I can add that to rule 26 (and others as needed) 

Thanks, Pascale

**Comment by pgaudet** [comment]
@dougli1sqrd @kltm @cmungall 

Hello, 

Can we implement this soon? Concretely, I would like GORULE:0000026  *not* to be in the reports, since this makes them very hard to read (see for eg http://snapshot.geneontology.org/reports/dictybase-report.html#rmd). 

If this can be done rapidly, MODs could review their error reports. Otherwise it's very difficult. 


Thanks, Pascale

**Comment by cmungall** [comment]
This was addressed in:
https://github.com/geneontology/go-site/pull/1027

see this line:

https://github.com/geneontology/go-site/commit/5b7f346dd8794a6850471d1231004bfd32a1e66f#diff-022948c3e27b415189bfbc8aa463b5c2R8

We are implementing this via the 'silent' tag.
