### ISSUE TITLE
Change gorule-0000016 to a filter

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-site#955]
We have reviewed annotations to IC with no data in the with/from column. These are mostly from unmaintained sets. We would like to filter these out. 

Annotations are here: 
https://docs.google.com/spreadsheets/d/1sydzUKLMDXexD2vYCumma0VWZsBJZontxDCjAwZ1_hE/edit#gid=0

Thanks, Pascale

@vanaukenk @ValWood @selewis

**Comment by pgaudet** [comment]
Actually, although there are errors in the reports, I can't find any annotations in AmiGO with no data in the 'with' column. 

Is this a filter or a report ? 
@dougli1sqrd

**Comment by dougli1sqrd** [comment]
It looks like these are showing gaf lines that have nothing in the with/from but have IC evidence, unless I'm mistaken:
http://current.geneontology.org/reports/genedb_pfalciparum-report.html#gorule-0000016

Also, just for clarification, I'd like to note that gorule-16 states that it's a failure not just if there's nothing in with/from, but if there isn't a GO term. So it's also a failure if there is something, but it's not a go term.
