### ISSUE TITLE
Take over the geneontology.org root domain (including www)

### ISSUE THREAD

**Issue by selewis** [geneontology/go-site#958]
Aside from the www conf file (which itself was last modified in 2016), nothing has been modified since 2015 so guessing by now a lot of those redirects are not really necessary.  I don't even remember why some were put in place to begin with, although presumably there was a reason!  :-)

Also, aside from the www server, the rest are running on an Apache 2.2 server so yes, they may need to be modified to run under 2.4.  I think that would mostly be access rules -- the (allow,deny) type configs.  Modules would also be an issue.  I don't think we're using anything out of the ordinary, but I didn't include any of the main configs where that would have been defined.  I don't think it will be an issue for you, but let me know if you run into any problems that seem to be related to modules.  (Or anything else, really.)

**Comment by kltm** [comment]
See: https://github.com/geneontology/go-site/issues/789

**Comment by kltm** [comment]
Also note that we'll need to take over the www subdomain in a safe way. Playing with it a little, a subdomain redirect may work better than a server alias (and the related SSL quirks).

**Comment by kltm** [comment]
www test with www-test.geneontology.io

**Comment by kltm** [comment]
To close this:

- [ ] check logging
- [ ] check backups
- [ ] flip DNS
- [ ] final check

**Comment by kltm** [comment]
@stuartmiyasato One more off the list. My backup-fu is weak, but the ansible playbooks work nicely.
