### ISSUE TITLE
Ensure all top level URL paths from old website resolve to content in the new website

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#959]
Note this is distinct from the redirects #957 

The previous system served content driven by svn, from here: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/

top level directories mapped to top level svn folders, e.g

http://www.geneontology.org/external2go/
->
http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/external2go/

We should make sure all top level geneontology.org folders go somewhere or are consciously deprecated. I will make a list but the most complete way would be to grep the logs and take the top level folders accessed

**Comment by kltm** [comment]
@cmungall Thank you for the all the footwork here--we can start the with the proxy and work out from there fresh on a test URL.

**Comment by kltm** [comment]
Starting to add things to this list on test.geneontology.io
(note: I am @kltm, not "KTLM")

**Comment by kltm** [comment]
Test URLs for *ontology*:
http://test.geneontology.io
http://test.geneontology.io/external2go
http://test.geneontology.io/external2go/ec2go
http://test.geneontology.io/ontology/go.obo

**Comment by cmungall** [comment]
Not sure whether we need a new ticket for this but obviously we need to redirect /page/ to /docs/

E.g. current URL
http://geneontology.org/page/download-go-annotations

Dead:
https://geneontology.github.io/page/download-go-annotations

Should go here:
https://geneontology.github.io/docs/download-go-annotations

**Comment by lpalbou** [comment]
Hi Chris, whenever the other redirects are ready, I can implement those redirects with the GH plugins (we discussed this before); should take no more than a few hours as I have the list of original most visited URLs from google analytics. If the other redirects are ready, I could do that tomorrow.

**Comment by lpalbou** [comment]
@cmungall done for the 80 most visited links: https://github.com/geneontology/geneontology.github.io/pull/109

**Comment by kltm** [comment]
@cmungall http://geneontology.org/gp_unlocalized does not seem to exist

**Comment by kltm** [comment]
Talking to @cmungall http://geneontology.org/gp_unlocalized and http://geneontology.org/gpad-gpi unneeded/unmapped for now. /gp2protein and /gp2rna will be skipped for now and re-added to the pipeline if needed (as they change and would require storage).

I added /go-cam, but that may need to be adjusted a bit to work with the proxy.

For the rest, there should not be testable rewrites in place.

**Comment by kltm** [comment]
@cmungall Please close at your satisfaction.

**Comment by kltm** [comment]
@lpalbou Could you point me towards the discussion mentioned here: https://github.com/geneontology/go-site/issues/959#issuecomment-447920695 ? I'm not remember with my brain parts real good at the moment...

**Comment by lpalbou** [comment]
@kltm I was answering this https://github.com/geneontology/go-site/issues/959#issuecomment-447850342. It is also referring issue https://github.com/geneontology/go-site/issues/789 (`set up http / forwarding @kltm @lpalbou mixture of apache and gh pages`) and at least another issue where we discuss the redirect-from plugin to use with GH pages
