### ISSUE TITLE
Where is the list of annotator providers?

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/go-site#96]
Apparently a list of "annotation providers" once lived here http://www.geneontology.org/cgi-bin/xrefs.cgi but this page sends a 404 now. Do we know where it moved?

**Comment by kltm** [comment]
I'm guessing here:
http://amigo.geneontology.org/xrefs

**Comment by cmungall** [comment]
Correct. Source here: https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

**Comment by cmungall** [comment]
Note. This will all be much clearer once 2.3 is out the door, see https://github.com/geneontology/amigo/issues/199

**Comment by monicacecilia** [comment]
Thanks!
