### ISSUE TITLE
Organisms in drop-down for enrichment tool is not the same as list of organisms supported for enrichment by PANTHER

### ISSUE THREAD

**Issue by mugitty** [geneontology/go-site#963]
List of supported organisms for enrichment has been updated on pantherdb.org. Enrichment form  on landing page has to be updated to reflect the change.

**Comment by kltm** [comment]
Could you add a full list of codes to this ticket?
As well, I assume that the list is backwards compatible for the time being?

**Comment by pgaudet** [comment]
@mugitty Can you please reply ?

**Comment by lpalbou** [comment]
Done here: https://github.com/geneontology/geneontology.github.io/pull/148
