### ISSUE TITLE
Move OBO format definitions to new docs site, ensure path is in place

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#964]
Copy contents of http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/www/formats/ to new gh site

Serve from http://(www.)geneontology.org/formats/

Originally from https://github.com/geneontology/go-site/issues/959#issuecomment-446971679

**Comment by pgaudet** [comment]
@kltm Can you check whether this has been done ?

**Comment by pgaudet** [comment]
See also https://github.com/geneontology/geneontology.github.io/issues/142

**Comment by kltm** [comment]
Tested and deployed with pair https://github.com/geneontology/operations/commit/aae9b921ea2ba692147518137923e71dd2ee06c7
