### ISSUE TITLE
Species name Trypansoma brucei in enrichment tool has TRYB2 in the name

### ISSUE THREAD

**Issue by huaiyumi** [geneontology/go-site#966]
In the drop-down menu, the species name Trypansoma brucei has TRYB2 in front the name. This may cause the PANTHER site not recognizing the species and throw an "invalid species" error when people use the tool in GO.

**Comment by kltm** [comment]
Is this different than #963 ?

**Comment by huaiyumi** [comment]
@kltm Yes.

**Comment by mugitty** [comment]
pantherdb.org has a web service to return the list of supported organisms (http://www.pantherdb.org/webservices/garuda/search.jsp?type=organism).  This list should be used to generate the items in the drop down menu.

**Comment by lpalbou** [comment]
Done here https://github.com/geneontology/geneontology.github.io/pull/148
