### ISSUE TITLE
PAINT and EcoCyc are using different gene product IDs

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#969]
RecA in E coli is represented twice:

http://amigo.geneontology.org/amigo/gene_product/EcoGene:EG10823
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:P0A7G6

These are all to UniProtKB:
http://release.geneontology.org/2018-12-01/products/annotations/ecocyc-src.gaf.gz

All to EcoGene (except Ins genes)
http://release.geneontology.org/2018-12-01/products/annotations/paint_ecocyc-src.gaf.gz

It would seem more conventional for ecocyc to provide gene IDs, but if they are providing UniProtKB as primary then PAINT should follow

Can't seem to assign at the moment, this should go to @dustine32, also cc-ing @jimhu-tamu

**Comment by jimhu-tamu** [comment]
We will look at this, as it looks like the filters we run on the gaf must need some debugging. But note: EcoCyc downloads the UniProt-goa files and translates the annotations to refer to EcoCyc protein IDs. Then they add annotation made in EcoCyc, also using EcoCyc IDs. We get that from them, add anything from EcoliWiki, and translate back to UniProt IDs. There should not be any EcoGene IDs in the file (and I don't see any in either the gaf or the gp2p we submitted). So I don't know where that is coming from.

The translation back to UniProt was done because @thomaspd and @selewis  told me years ago that the EcoCyc IDs would not work with PAINT.

**Comment by cmungall** [comment]
I don't know the background of why EcoCyc IDs wouldn't work, I'll leave it to you and Dustin to coordinate on IDs.

aside for Jim; when checking your most recent GAF I noticed there is one line that includes a space at the beginning of col1:

```
$ curl -L -s http://release.geneontology.org/2018-12-01/products/annotations/ecocyc-src.gaf.gz | gzip -dc | grep -v ^UniProtKB
 UniProtKB      P0A776  rppH            GO:0050779      PMID:18202662   IMP             P                       gene    taxon:83333     20081017    EcoliWiki
```

**Comment by dustine32** [comment]
I also don't know off the top of my head why EcoCyc IDs wouldn't work with PAINT. From PAINT's perspective, it would import the GAFs using the EcoCyc ID and map it to the Panther (long) ID, which also contains the UniProt ID (`ECOLI|EcoGene=EG10823|UniProtKB=P0A7G6` for this example) anyway. 

These annotations could then be used as evidence for the PAINT annotations that are then applied to these Panther IDs to create IBAs. @huaiyumi Do I have anything wrong here or anything I'm not considering?

The other solution for the problem in this ticket is, I believe we can control whether to output the EcoCyc ID or the UniProt in the PAINT GAFs. So we could probably switch if needed, though that may add confusion when attempting to track changes in our GAFs.

**Comment by cmungall** [comment]
Any update on this?

**Comment by cmungall** [comment]
Not only are our annotations split:

http://amigo.geneontology.org/amigo/gene_product/UniProtKB:P0A6T5 - 9 annotations
http://amigo.geneontology.org/amigo/gene_product/EcoGene:EG11375 - 5 annotations

we are missing some; compare:

30 annotations:
https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=P0A6T5

@dustine32 and @kltm let's find a few minutes this week to sort this out

**Comment by dustine32** [comment]
Sure @cmungall @kltm I can try to zoom/skype with you on this. Recall I'm still currently on PST so hopefully not at 2AM my time. Just let me know a good time.

**Comment by dustine32** [comment]
I still feel like an easy solution would be to write an exception in the [PAINT IBA generation script](https://github.com/pantherdb/fullgo_paint_update/blob/7872aa5954675c6839906930867820cd11139d78/scripts/createGAF.pl#L214-L215) to output the UniProt rather than MOD identifier if `EcoGene` is in the Panther long ID? I think it'll be fine (i.e. they'll map back to Panther long IDs) when PAINT cycles these IBA annotations back in from the GO release GAFs.

Does this make sense? Might wanna pull in @huaiyumi to see what he thinks of switching this.

**Comment by cmungall** [comment]
I think we may need @jimhu-tamu as well so maybe best when we're all in the rough same time zone again..

**Comment by cmungall** [comment]
@dustine32 you should go ahead and use UniProtKB as the primary IDs for E coli

Can you also coordinate with @jimhu-tamu on helping him fix the E coli exports?

It looks like the E coli wiki pages are complete:

http://ecoliwiki.net/colipedia/index.php/folE:Gene_Product(s)

E.g. this has the annotation to tetrahydrofolate biosynthetic process from HAMAP and InterPro

However, this is not in the submission file (which is still svn):

`$ curl -L -s http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.ecocyc.gz | gzip -dc | grep folE`

**Comment by jimhu-tamu** [comment]
I’m lurking on this conversation. Just way behind in my todos.

**Comment by huaiyumi** [comment]
@jimhu-tamu I am OK to switch as long as you are OK with it. I thought the reason we use EcoGene ID for GAF was upon your request, and also to be consistent with the rest of the 12 MODs genomes. Since we already switch to UniProt for the human GAF, it is really not a big deal for us.

**Comment by cmungall** [comment]
alternatively ecoli could export gene IDs to their GAF

Either way, we are going to need to fix the issue that the ecoli GAF is missing annotations (regardless of IDs).

@jimhu-tamu - we are going to need the help of someone technical on your side of things. If you are snowed under is there a way we can help?

**Comment by cmungall** [comment]
Ecocyc.yaml issues moved here: #1142

**Comment by cmungall** [comment]
Note this seems to have been fixed upstream:

```
$ curl -L -s https://ecoliwiki.org/gaf/gene_association.ecocyc.gz | gzip -dc | grep -v ^UniProtKB
[no output]
```

not yet percolated to release:

```
curl -L -s http://current.geneontology.org/annotations/ecocyc.gaf.gz | gzip -dc | grep -v ^UniProtKB
```

when it does we can finally close this. Thanks for fixing this @jimhu-tamu, or whoever did this!

This should never have happened in the first place. TODO:

 - [ ] add GO RULE to prevent mix of gene and uniprot IDs in col2

**Comment by kltm** [comment]
Note, currently:
```
sjcarbon@moiraine:/tmp$:) curl -L -s http://current.geneontology.org/annotations/ecocyc.gaf.gz | gzip -dc | grep -v ^UniProtKB | grep -v ^! | wc
      0       0       0
```
