### ISSUE TITLE
GAF and GPAD mentions on website

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-site#97]
http://geneontology.org/page/contributing-go

Modify "- Human & Model Organism Databases: Your research group should follow the steps outlined on the guide to Submitting GO Annotations. This involves the preparation and submission of a GAF2.0 formatted file that complies with the specifications of the GOC." to mention GPAD. (and other occurrences)

**Comment by kltm** [comment]
specific ping to @cmungall

**Comment by mcourtot** [comment]
Done. Pointed to the general file formats page instead - http://geneontology.org/page/go-annotation-file-formats to cover future cases as well.
