### ISSUE TITLE
Content of 'gocheck_do_not_annotate' in release different from geneontology.org

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-site#972]
Hi,

The content of the 'gocheck_do_not_annotate' subset is different depending on where you look.

For example, checking for GO:0005622 'intracellular', I can see it in the subset on current and snapshot:

http://current.geneontology.org/ontology/subsets/gocheck_do_not_annotate.obo

http://snapshot.geneontology.org/ontology/subsets/gocheck_do_not_annotate.obo

but do not see it in the subset on geneontology.org

http://geneontology.org/ontology/subsets/gocheck_do_not_annotate.obo

This came up as I was looking at the InterPro2GO mappings and finding some mappings to terms in the gocheck_do_not_annotate subset and was wondering why they might not have been flagged as I thought 'gocheck_do_not_annotate' held for any pipeline, even InterPro2GO.

**Comment by cmungall** [comment]
@kltm and I will check later today

**Comment by cmungall** [comment]
We'll fill you in tomorrow, but basically this will be fixed with the new release of the website when we switch geneontology.org to the new site.

**Comment by pgaudet** [comment]
This seems to be fixed.
