### ISSUE TITLE
Add evidence metadata for Google

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-site#975]
If I google "Gene ontology evidence codes" 

this page,
http://www.candidagenome.org/cgi-bin/GO/goEvidence.pl

gets  prominence in a "box" at the top. How can that be. It ust be configurable somehow?

**Comment by kltm** [comment]
In this case, I do not currently see the box you mention myself. My results for the Google search contain no box and has that site as number five (after the usual more obvious locations).
Looking at the page, I see no obvious metadata that google is pulling.

Could you possible add a screenshot of what your seeing?

Also see:
https://github.com/geneontology/amigo/issues/534

**Comment by ValWood** [comment]
![evidence codes](https://user-images.githubusercontent.com/7359272/51144474-0c53ab80-1849-11e9-9622-57a2f015b108.jpg)

**Comment by ValWood** [comment]
Good point. The GO evidence page is a list linking to the wiki....

**Comment by ValWood** [comment]
you can close if you like, I was curious...
