### ISSUE TITLE
Check that all URLs work and are consistent on new website

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#978]
To close this issue, we would want positive results that:

- [x] all core URLs still work
- [x] URLs checked via spidering are consistent and make sense
- [ ] trim out URLs that we don't want public; e.g. api.geneontology.cloud and possibly golr*.geneontology.(org|io)

**Comment by kltm** [comment]
Since we have done so much remapping, etc., as part of this, it would probably be good practice to add a custom 404 page contains a search element #977

**Comment by lpalbou** [comment]
@kltm closing this as all core URLs are working, we now have the 404 search page and the other URLs are part of a larger efforts (true GO/BioLink API + GOlr indexing)
