### ISSUE TITLE
Process to edit website

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-site#98]
Is there a sanctioned way to edit the pages? Should I get write access and just go ahead, or is there a staging area, or should I send requests on this github?

**Comment by monicacecilia** [comment]
Hi Melanie, directions on how to edit the pages can be found at http://wiki.geneontology.org/index.php/Editing_GO_Site

Have at it! :dancer: 

There is not a staging area. You make the change, you submit and it is immediately updated. In general, if you have questions regarding content updates, please ask @kltm (Seth) and/or I and we will do our best to help you sort it out.
