### ISSUE TITLE
Remove Annotation Downloads dataset for Dog, complex (is blank)

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-site#982]
Spawned off of #847:

Need to review the Annotation Downloads (bottom of geneontology.github.io/_docs/download-go-annotations.md, which links to http://current.geneontology.org/products/pages/downloads.html) and remove unneeded entries

**Comment by suzialeksander** [comment]
Related, review slims- the SGD slim is in the archived as well as the current slims pages.

**Comment by pgaudet** [comment]
> Related, review slims- the SGD slim is in the archived as well as the current slims pages.

@suzialeksander the one in the Archived is the file from 2003. We can delete it - up to SGD. I would say it's old enough to delete.

**Comment by pgaudet** [comment]
@suzialeksander Which entries as unneeded ?

**Comment by suzialeksander** [comment]
@pgaudet  This is up for discussion as to what users need, but for example, Dog has a whopping 0 complex annotations.  Cow has 8 complex, is that useful either?

**Comment by suzialeksander** [comment]
looks like this GAF is still blank, 4 years later, so not much fluctuation in file size

**Comment by suzialeksander** [comment]
done, new smallest annotation set on that page is 1356 lines (sol)
