### ISSUE TITLE
Check linkouts for IntAct

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-site#99]
Follow linkout from here
http://amigo2.berkeleybop.org/amigo/gene_product/IntAct:EBI-767678

Ambiguous:
http://www.ebi.ac.uk/intact/pages/interactions/interactions.xhtml?query=EBI-767678

Should actually link here:
http://www.ebi.ac.uk/intact/complex/details/EBI-767678

**Comment by kltm** [comment]
metadata may actually be correct here, with the resolution problem upstream; the real link in amigo and db-xrefs.yaml is:
http://www.ebi.ac.uk/intact/search/do/search?searchString=EBI-767678

**Comment by cmungall** [comment]
that's metadata isn't it? so fixing in db-xrefs.yaml should fix this

**Comment by kltm** [comment]
Or (maybe) resolution at their end, that's all--it looks like they may have multiple entity types that are solved at a single URL?

**Comment by cmungall** [comment]
`s@http://www.ebi.ac.uk/intact/search/do/search?searchString=@http://www.ebi.ac.uk/intact/complex/details/@` in db-xrefs.yaml

**Comment by pgaudet** [comment]
@kltm Is this still valid ?

**Comment by kltm** [comment]
Link out above goes to a real thing. Let's called it fixed.
