### ISSUE TITLE
Migrate away from legacy GO SVN for annotation file sources

### ISSUE THREAD

**Issue by kltm** [geneontology/go-site#997]
The following resources still use the GO SVN as the deposit and pickup point for their annotations. We would like to migrate these resources away. Preferably from a URL of their own choosing (and support), but we could support something if necessary, TBD. The primary goal is to suspend the use of the GO SVN for anything but historical purposes.

- [x] aspgd.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.aspgd.gz
- [x] cgd.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.cgd.gz
- [x] ecocyc.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.ecocyc.gz
- [x] genedb.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.GeneDB_Pfalciparum.gz
- [x] gonuts.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.gonuts.gz
- [x] gramene.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.gramene_oryza.gz
- [x] jcvi.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.jcvi.gz
- [ ] pamgo.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.PAMGO_Atumefaciens.gz
- [ ] pamgo.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.PAMGO_Ddadantii.gz
- [x] pamgo.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.PAMGO_Mgrisea.gz
- [ ] pamgo.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.PAMGO_Oomycetes.gz
- [x] pseudocap.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.pseudocap.gz
- [x] reactome.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.reactome.gz
- [x] sgn.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.sgn.gz
- [x] tair.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.tair.gz

This is an action based on the initial work of https://github.com/geneontology/go-site/issues/784 .

**Comment by suzialeksander** [comment]
Related to/partial overlap of https://github.com/geneontology/go-site/issues/409

**Comment by pgaudet** [comment]
As far I know, 
- [ ] genedb.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.GeneDB_Pfalciparum.gz
- [ ] jcvi.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.jcvi.gz
- [ ] pamgo.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.PAMGO_Atumefaciens.gz
- [ ] pamgo.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.PAMGO_Ddadantii.gz
- [ ] pamgo.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.PAMGO_Mgrisea.gz
- [ ] pamgo.yaml:   source: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/gene_association.PAMGO_Oomycetes.gz

Is loaded via Protein2GO/GOA pipeline
@alexsign Is this right ? 

If that's the case, these should be somehow wrapped into the GOA yaml file? Is that the procedure ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@vanaukenk Already contacted TAIR and Reactome 
Reactome's next release (March 2019) should not be useing SVN anymore.

**Comment by pgaudet** [comment]
Pseudocap0s source file information has been updated
https://github.com/geneontology/go-site/blob/master/metadata/datasets/pseudocap.yaml

**Comment by alexsign** [comment]
@pgaudet  We don't use SVN to get files. Most of the data is downloaded from following FTP.
ftp://ftp.geneontology.org/pub/go/gene-associations/submission/
I do still submit some files to SVN during our public release, but I was waiting for green light to stop it. The GOA yaml file should contain everything needed for consortium to download files posted on the EBI FTP site.

**Comment by cmungall** [comment]
Hi @alexsign - you should only be using URLs sanctioned in the datasets yamls

**Comment by cmungall** [comment]
@pgaudet if UniProt-GOA is the source for these then the entries in the yaml can be retired. Note that there will be no explicit download for these

**Comment by pgaudet** [comment]
@cmungall I think this is what we need to do, since the groups do not maintain the data anymore. OK ? 

@alexsign I assume you document somewhere all the sources that you load ? (apologies if I have asked before).

**Comment by alexsign** [comment]
@pgaudet I posted all our sources in XLS file before, but without information where I downloading files from. Data coming from various locations, but iI can collect this info if needed. 

@cmungall I still in a process of reviewing some part of my inheritance from Tony. I agree completely to use info from the datasets yaml files is the best way get consistence. I don't know why not everything is migrated to it yet. However, I will review it in the future and make changes. Since everything is in goa.yaml now, do I have to still submit files via SVN?

**Comment by pgaudet** [comment]
>  I posted all our sources in XLS file before,

Right ! Sorry

 > do I have to still submit files via SVN
No

**Comment by vanaukenk** [comment]
Contacted @marekskrzypek about AspGD and CGD files.

**Comment by vanaukenk** [comment]
AspGD and CGD file source locations are now updated in the respective yaml files.

**Comment by pgaudet** [comment]
@kltm CGD and AspGD are producing their own files. These should NOT be loaded via the GOA (uniprot all? ) data. 

Let me know if this should be a separate ticket. 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet CGD and AspGD are already their own resources with their own upstreams; I'm not sure how you are tying them to goa. If there is an issue, make a ticket.

**Comment by pgaudet** [comment]
PAMGO: Emailed contact on this page: http://depts.washington.edu/agro/

**Comment by lpalbou** [comment]
FYI, the SVN still gets updated frequently:

<img width="1000" alt="Screen Shot 2020-07-28 at 11 37 10 AM" src="https://user-images.githubusercontent.com/24249870/88707165-b9f27c80-d0c6-11ea-936d-a15b627f37fb.png">

rgd, cgd and (less importantly) jenkins are still submitting data.

**Comment by pgaudet** [comment]
In any case, this is not where we get the data from according to the yaml. 

I suppose when we retire the SVN that will not be relevant anymore ? Or do you want them to already stop submitting there ?

**Comment by pgaudet** [comment]
I think this can be closed ?

**Comment by kltm** [comment]
There is no more SVN appearing in our metadata and pamgo--long gone--were the only things unchecked above in the original entry:
```
sjcarbon@moiraine:~/local/src/git/go-site/metadata/datasets[master]$:) grep -i SVN *
sjcarbon@moiraine:~/local/src/git/go-site/metadata/datasets[master]$:( 
```

`\(^_^)/`
